knative/docs

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-PKS.md
Knative Serving release was moved to its own directory in knative/serving#1654.
> Update Knative Serving GCS bucket

- serving/samples/source-to-url-go/README.md
Wrong domain is shown in the example. Updated to use the default domain name.
> Fix a domain typo

- eventing/README.md
Hello, I fix duplicate phrase causing following error:
```
⟩ kubectl apply -f kubectl apply -f https://storage.googleapis.com/knative-releases/eventing/latest/release.yaml
error: Unexpected args: [apply]
See 'kubectl apply -h' for help and examples.
```
> fix duplicate phrase `kubectl apply -f`

- build/README.md
- build/installing-build-component.md
- install/Knative-with-GKE.md
Fixes #246 
Added stand alone "add build component to existing installation"
Added mention of install in README.md (which is linked to from knative/build code repo)
Added build component option in knative/install GKE instructions
> Add build component instructions throughout

- serving/samples/thumbnailer-go/README.md
> Edits to Thumbnailer sample

- build/builds.md
There are two "of the" in the sentence, should be only one.
> Fix syntax error in builds.md

- install/getting-started-knative-app.md
Simplify the getting started example by setting environment
variables rather than asking the user to remember IP addresses
and host urls.
> Update getting started doc to use env vars

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
Fixes #286
* Update install instructions to use files from the Serving 0.1.0 release instead of latest
> Update install instructions to use release 0.1.0 files

- build/creating-builds.md
Converted copied/moved content from the knative/build/README.md into a formal task in the docs to cover the steps in detail for deploying, running, and testing a Build.
Build component install instructions are here: https://github.com/knative/docs/pull/265
> New task in docs/build based on content moved from knative/build

- serving/samples/source-to-url-go/README.md
Fixes #252
update the instructions to show using a service account in the build to link the secret in properly.
> fix source-to-url-go sample to use secret

- eventing/samples/k8s-events/serviceaccount.yaml
This may require double check / confirmation, but my cluster did not have a `viewer` role. It did have a `view` role though, which once used allowed me to run a Flow
> Update role reference in sample

- serving/outbound-network-access.md
* Remove a trailing space in the command that caused copy & paste to fail
> Remove space from command

- community/CONTRIBUTING.md
- community/ROLES.md
- community/WORKING-GROUPS.md
* Make it clear everywhere we mention team drive that [knative-users](https://groups.google.com/forum/#!forum/knative-users) provides immediate access to team drive docs.
> Add knative-users as as access option for Team Drive

- install/Knative-with-OpenShift.md
- install/README.md
- install/scripts/knative-with-openshift.sh
This PR adds instructions and a script for testing out Knative on OpenShift using `oc cluster up`.
Thanks to @bbrowning for a big assist with this.
> Add instructions for OpenShift

- community/REVIEWING.md
Now that our Prow instance is public, links to test results work out-of-the-box.
> Remove instructions for checking Prow logs from Google Cloud Console

- install/getting-started-knative-app.md
Adds back manual options for figuring out the host URL and IP address, since all users should know how to see that information without having to export it into a variable.
* 
* 
*
> Updating app deployment guide

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
* https://github.com/knative/docs/pull/318 changed the GKE install instructions; this syncs up the other install guides.
* Note: the Minikube and OpenShift instructions include a "lite" version of the install, and I'm not sure: 
A. If the lite version installs both serving and build and
B. if it installs both, whether or not there's a build-only "lite" install file. So, I left those two versions 
alone for the moment.
> Sync install instructions with GKE version

- serving/installing-logging-metrics-traces.md
* I found that I didn't know the starting point to run the command to add monitoring components, given it referenced relative file locations.  By specifying the starting point as the root of the serving repository, it is clear to readers.
> Clarifies working directory to run command

- eventing/samples/k8s-events/function.yaml
Fix a typo in the path so that ko can be used to deploy the sample.
> Fix a typo in the path so that ko can be used to deploy the sample.

- Gopkg.lock
- Gopkg.toml
- hack/update-deps.sh
- test/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
* shared scripts from test-infra live in //vendor/github.com/knative/test-infra/scripts;
* created `//hack/update-deps.sh` to properly update deps, including test-infra;
* all bash scripts were updated to use the vendored scripts;
Part of knative/test-infra#30.
> Vendor the test-infra scripts

- serving/samples/source-to-url-go/README.md
Fixes #341 
*  Remove step 5 in the source-to-url deployment sample, as far as I can tell simply removing it does not lose any guidance
> remove redundant step in source-to-url deployment

- serving/using-external-dns.md
Update ExternalDNS setup doc to require Cloud DNS scope when creating a cluster.
See https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/gke.md#set-up-your-environment.
> Update ExternalDNS setup doc to require Cloud DNS scope when creating a cluster

- community/WORKING-GROUPS.md
The Contributor WG meeting was accidentally deleted. Creating a new meeting generated a new UID.
Also included some text indicating when the meeting was.
> Fix WG calendar link after original meeting was deleted.

- community/WORKING-GROUPS.md
I copied the URL into my browser in an incognito window, and it appears to work, but please double-check.
> Really fix URL to the WG meeting

- serving/samples/helloworld-go/helloworld.go
#290
Removes the `flag` package import and flag parsing as it is noted that this is done elsewhere.
> Remove flag package import

- eventing/samples/github-events/README.md
- serving/samples/gitwebhook-go/README.md
- serving/samples/knative-routing-go/README.md
- serving/samples/traffic-splitting/README.md
Fixes #292
Replace the remaining/missed shorthand `kubectl` `-o` flags with `--output`
Related PR #372
> cleanup remaining kubectl shorthand -o flags

- serving/installing-logging-metrics-traces.md
By reading the docs, I can't tell where are these config/monitoring stuff.
So I'm adding sub-steps to (a) clone repo + cd + checkout to the release tag,
then (b) apply them.
Please /cc someone who knows about this stuff to verify.
> telemetry: document sd/prom manifest locations

- serving/samples/helloworld-python/README.md
- serving/samples/helloworld-python/app.py
According to the runtime contract, the service should connect to the PORT env var, not just use 8080.
https://github.com/knative/serving/blob/master/docs/runtime-contract.md#process
> Make Python example use the PORT env var instead of 8080

- community/WORKING-GROUPS.md
The current link is invalid due to calendar event cancellation happened before. 
Updated the link pointing to valid knative team meeting calendar.
> update calendar link for productivity wg

- community/README.md
Fixes #428
*  Change the Slack link in the community page to show the Slack Guidelines page that contains the invite.
> Change slack link to slack guidelines

- eventing/samples/k8s-events/README.md
- install/getting-started-knative-app.md
- serving/samples/gitwebhook-go/README.md
- serving/samples/helloworld-csharp/README.md
- serving/samples/helloworld-elixir/README.md
- serving/samples/helloworld-go/README.md
- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-java/README.md
- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-php/README.md
- serving/samples/helloworld-python/README.md
- serving/samples/helloworld-ruby/README.md
- serving/samples/helloworld-rust/README.md
- serving/samples/source-to-url-go/README.md
Fixes #379 
* Revert the use of short-name `ksvc` since it isn't supported in the 0.1.1 release which is what the installation instructions are currently using.
> Revert ksvc changes

- serving/samples/helloworld-csharp/README.md
- serving/samples/helloworld-csharp/Startup.cs
- serving/samples/helloworld-go/README.md
- serving/samples/helloworld-go/helloworld.go
- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-haskell/app/Main.hs
- serving/samples/helloworld-java/README.md
- serving/samples/helloworld-java/src/main/java/com/example/helloworld/HelloworldApplication.java
- serving/samples/helloworld-nodejs/Dockerfile
- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-nodejs/app.js
- serving/samples/helloworld-nodejs/package.json
- serving/samples/helloworld-php/README.md
- serving/samples/helloworld-php/index.php
- serving/samples/helloworld-python/README.md
- serving/samples/helloworld-python/app.py
- serving/samples/helloworld-ruby/README.md
- serving/samples/helloworld-ruby/app.rb
- serving/samples/helloworld-rust/README.md
- serving/samples/helloworld-rust/src/main.rs
When no env var is provided (for example because the developer only has deployed the code without using the `service.yaml`), instead of displaying "Hello World: NOT SPECIFIED", display the more friendly message "Hello Word".
This means that when the `TARGET` env var is set, instead of displaying "Hello World: <TARGET>", the samples will display "Hello <TARGET>", which seems totally OK.
All sample changes have been tested.
> Make samples less scary when no env var is provided

- install/Knative-with-OpenShift.md
- install/scripts/knative-with-openshift.sh
- serving/accessing-logs.md
- serving/installing-logging-metrics-traces.md
- serving/samples/telemetry-go/README.md
- serving/setting-up-a-logging-plugin.md
The namespace is `knative-monitoring` instead of `monitoring`
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Fix knative-monitoring namespace and accessing-logs URL

- serving/samples/autoscale-go/test/test.go
The test program doesn't close the http response Body causing the connection to
not be released and the creation of new connections until the exhaustion of the
process file descriptors.
This patch closes the response body (actually a defer also if not really needed but useful if in future the body will be read)
> Close response body in autoscale-go sample test program

- serving/samples/helloworld-clojure/README.md
- serving/samples/helloworld-clojure/src/helloworld/core.clj
- serving/samples/helloworld-csharp/README.md
- serving/samples/helloworld-go/README.md
- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-java/README.md
- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-php/README.md
- serving/samples/helloworld-python/README.md
- serving/samples/helloworld-ruby/README.md
- serving/samples/helloworld-rust/README.md
* Apply the unscary change (#443) to the helloworld-clojure sample.
* Update all the helloworld-* README.md files with the unscary message.
> Make the Clojure greeting unscary.

- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-nodejs/app.js
Works towards #456 and makes a minor README update follow-up to #443
* Replace use of `var` with `const`
* Add exclamation mark back to the message!
* Note that the default behavior if no $TARGET variable is set will be 'Hello World'
> serving/helloworld-nodejs: Respect the PORT env var

- serving/samples/helloworld-php/Dockerfile
- serving/samples/helloworld-php/README.md
- serving/samples/helloworld-php/index.php
Work towards #456
Tested locally with success.
* [Do not indent code after opening PHP tag or have a closing PHP tag](https://stackoverflow.com/questions/14989525/indent-after-opening-php-tag).
* Note that the default behavior if no $TARGET variable is set will be 'Hello World'
> serving/helloworld-php: Respect the PORT env var

- serving/samples/helloworld-csharp/Program.cs
- serving/samples/helloworld-csharp/README.md
Work towards #456
Tested locally with success
* Note that the default behavior if no $TARGET variable is set will be 'Hello World'
> serving/helloworld-csharp: respect the port env var

- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-haskell/app/Main.hs
Work towards #456
Tested locally with success
* Note that the default behavior if no $TARGET variable is set will be 'Hello World'
> serving/helloworld-haskell: respect the port env var

- serving/samples/helloworld-go/README.md
- serving/samples/helloworld-go/helloworld.go
Works towards #456 and makes a minor README update follow-up to #443
* Log as fatal the result of http.ListenAndServe throwing an error per [common practice](https://golang.org/pkg/net/http/#ListenAndServe)
* Note that the default behavior if no $TARGET variable is set will be Hello World
> serving/helloworld-go: Respect the PORT env var

- install/Knative-with-any-k8s.md
This cleans up some example text for the Knative install on any k8s documentation.
> Clean up formatting on with-any-k8s steps

- serving/samples/helloworld-dart/README.md
- serving/samples/helloworld-dart/service.yaml
Fix Dart service.yaml (indentation) and indicate that local dart is only needed for local development.
* Fix indentation in `service.yaml` (discovered via `kubectl apply -f <(sed 's/{username}/evankanderson/' service.yaml)`
* Indicate that local dart steps are only needed if you want to run locally as opposed to simply using Docker/Knative
> Fix Dart sample

- install/Knative-with-OpenShift.md
- install/scripts/knative-with-openshift.sh
- serving/accessing-logs.md
- serving/installing-logging-metrics-traces.md
- serving/samples/telemetry-go/README.md
- serving/setting-up-a-logging-plugin.md
knative-monitoring does not work in serving 0.1.x
#437
> Reverting the namespace rename knative-monitoring

- eventing/samples/k8s-events/README.md
- install/Knative-with-OpenShift.md
- install/scripts/knative-with-openshift.sh
- serving/debugging-application-issues.md
- serving/samples/autoscale-go/README.md
- serving/samples/telemetry-go/README.md
- serving/samples/telemetry-go/telemetrysample.go
Renames the `monitoring` namespace to `knative-monitoring` to reflect the changes in https://github.com/knative/serving/pull/1851. 
Some files have not been updated, see comments in #407.
cc @RichieEscarez
> Update references to monitoring namespace (#407)

- serving/samples/helloworld-nodejs/README.md
* Fixed `docker` to `Dockerfile` for highlighting in markdown code fence
Instead of doing
```docker
We should do:
```Dockerfile
to get syntax highlighting on github.
> docker -> Dockerfile for syntax highlighting

- eventing/samples/k8s-events/README.md
- install/getting-started-knative-app.md
- serving/samples/blue-green-deployment.md
- serving/samples/gitwebhook-go/README.md
- serving/samples/helloworld-clojure/README.md
- serving/samples/helloworld-csharp/README.md
- serving/samples/helloworld-dart/README.md
- serving/samples/helloworld-elixir/README.md
- serving/samples/helloworld-go/README.md
- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-java/README.md
- serving/samples/helloworld-kotlin/README.md
- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-php/README.md
- serving/samples/helloworld-python/README.md
- serving/samples/helloworld-ruby/README.md
- serving/samples/helloworld-rust/README.md
- serving/samples/knative-routing-go/README.md
- serving/samples/source-to-url-go/README.md
- serving/setting-up-a-logging-plugin.md
- serving/using-an-ssl-cert.md
- serving/using-cert-manager-on-gcp.md
Fixes #481 
* Replace long knative service "services.serving.knative.dev" with "ksvc
* Pick off and fix new or overwritten references to kubectl CLI short flags (#292). Instead use long name flags:
* --filename
* --namespace
* --output
Note: Avoided changing the CLI short flags in the [Minishift](https://github.com/knative/docs/blob/master/install/Knative-with-Minishift.md) and [OpenShift](https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md) install guides since I have no familiarity with those "oc" commands.
> Use the ksvc shortname for services

- serving/samples/source-to-url-go/README.md
- serving/samples/source-to-url-go/service.yaml
Add TypeMeta and wrap the existing field in `spec:` so that Build is used through the new dynamically linked style.
> Update the serving + build sample to use the new style.

- eventing/README.md
* link has extra .yaml in the end, remove it.
* 
*
> Remove extra.yaml from a link to release-with-gcppubsub.yaml

- eventing/samples/kubernetes-event-source/README.md
Installation of Eventing Sources is a prerequisite, no need to have it in the instructions (and it's b0rk3d). Also remove the in-memory-provisioner, it's installed by default.
* Remove "Deploy Event Source" section because it's in prerequisites.
* Remove instructions for installing an in memory provisioner, it's installed as part of eventing
> Remove redundant (and errorneous) installation of eventing-sources

- eventing/samples/kubernetes-event-source/README.md
* Make setting up Knative Serving a prerequisite in kubernetes events sample instead of a line item.
> Make serving a prerequisite rather than a surprise later on

- eventing/samples/kubernetes-event-source/README.md
Now user doesn't need to fill in the actual pod name.
/cc @vaikas-google
> Kubernetes event source sample: get message dumper logs by label selector

- community/TECH-OVERSIGHT-COMMITTEE.md
- community/WORKING-GROUPS.md
Updates several TOC meeting details which were TODO even though we've been having TOC meetings for the last 2 months.
Updates and standardizes the Working Groups format for meetings, pointing all WGs except build and eventing to link to the shared public calendar. (Will need Jason Hall to update the Build WG, and will re-create the eventing meeting since Morgan Hallmon is out on leave.)
> Update calendar information for TOC and Working Groups.

- eventing/samples/gcp-pubsub-source/README.md
Fixes #529
* Removes passing `-n default` to the `ko` command as this doesn't do anything.
> Don't pass -n default to `ko`

- eventing/samples/gcp-pubsub-source/README.md
- eventing/samples/gcp-pubsub-source/channel.yaml
- eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
- eventing/samples/gcp-pubsub-source/subscriber.yaml
* Rewrites the PubSub sample to be able to be run using the GCP CLI (`gcloud only` after project creation).
* Updates eventing instructions based on #558
* Flattened one level of nesting.
* Added opinions about how to use the system, rather than options. It's a sample, not reference documentation.
* Couldn't get around to removing `ko`, though I have a public image published at gcr.io/argent-gke/message_dumper-147eae4dc6ef877ac915642c58dec291:latest
* Inlined some of the interesting yaml. I didn't inline the `subscriber.yaml` because it still needs to be de-`ko`-ed.
> Update pubsub sample

- install/Knative-with-OpenShift.md
Update istio-sidecar-injector configmap after Istio is ready in order to let knative activator and autoscaler pods running properly, setting Istio sidecar injector priviledged to true.
Fixes CrashLoopBackOff issue for knative activator and autoscaler pods
Fixes #417 
* Add section to update istio-sidecar-injector configmap to set Istio sidecar injector priviledged to true
> Update OpenShift instructions to set Istio sidecar injector priviledged to true

- serving/samples/helloworld-kotlin/Dockerfile
- serving/samples/helloworld-kotlin/README.md
Addresses #497 for Kotlin.
Tested with $TARGET and $PORT.
Filed #515 as that issue remains consistent with existing master branch as well as these changes.
Note this moves the Kotlin Dockerfile to a multi-stage build in line with the other JVM languages.
> serving/samples/helloworld-kotlin: simplify and standardize Dockerfile

- serving/accessing-logs.md
Fixes #573
Change the namespace to knative-monitoring from
just monitoring
> Correct Namespace in Kabana UI link

- install/Knative-with-IKS.md
Version 1.10.3 is not available anymore in IKS. Having a fixed
version will become stale eventually. The default version is
now >1.10 but that may change, so ask installers to select an
appropriate version based on the minimum requirement.
Fixes #562
* Add instructions on how to discover available k8s version
* Replace fixed k8s version with variable
*
> Discover the K8S version for IKS deployment

- serving/samples/build-private-repo-go/README.md
This is a follow up action for https://github.com/knative/docs/pull/571
/cc @vdemeester
> Use golang:alpine instead of golang for example Dockerfile.

- eventing/samples/kubernetes-event-source/README.md
- eventing/samples/kubernetes-event-source/subscription.yaml
Addresses #541
* Use a public docker image for the messagedumper so ko is not required for the k8s events sample.
* 
*
> use public image instead of requiring ko

- eventing/README.md
Removed kubectl command to create namespace "knative-sources" from section that covers setting up of GCP pubsub source as installation of eventing core sources already creates the namespace
#567 
Removed the create namespace kubectl command that is not required from the README.md
> Removed the unnecessary create namespace command under section for setting up GCP pubsub source

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/dummy.go
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
Old images cleanup is no longer part of e2e test, this functionality will be moved to a separate job runs periodically.
*This part is done in knative/test-infra, updating dependencies in this repo to include this update.
Link to the issue in test-infra: knative/test-infra#276
> Remove images deletion step from e2e test / Update test-infra

- serving/samples/helloworld-nodejs/README.md
**WARNING:** I didn't actually test this. **Consider this a bug report** with a suggestion, more than a fully tested patch.
Please, check that I didn't missing something, it's plausible that missed something obvious.
-----
We specify `TARGET='Node.js Sample v1'` in `service.yaml`, so it would be surprising if this isn't printed in the response.
> Node.js serving sample README.md has inconsistent response example

- eventing/README.md
We need to keep the releases up to date in these docs
-
-
-
> move eventing to 0.2.1 release

- eventing/README.md
- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-PKS.md
A few things I noticed while going through the install procedure.
- Use the istio release artifact in serving (https://github.com/knative/serving/releases/download/v0.2.2/istio.yaml) to install Istio instead of a direct link to the file in the repo.
- Same as above for build-only.
- Install serving v0.2.2 instead of v0.2.1.
- Point users to the top-level install instructions from the eventing readme.
> Update kubectl apply URLs to use release artifacts

- eventing/README.md
- install/Knative-with-GKE.md
Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
> Format markdown

- serving/samples/autoscale-go/Dockerfile
- serving/samples/autoscale-go/README.md
- serving/samples/autoscale-go/service.yaml
This patch simplifies the autoscaling tutorial by eliminating steps to:
- go-get the repo
- set a $REPO
- enable GCR API
- show how to authenticate to GCR via docker client
- push image
- update service.yaml
Instead we just do:
- deploy service.yaml that has a pre-built public image
I just published this image to `gcr.io/knative-samples/autoscale-go:0.1` and I
have eliminated excessive Dockerfile instructions that cause the entire docs/
repo to be sent to docker-engine as part of the "docker build".
Verified manually that it works. 👍 
Fixes #633.
> samples/autoscale-go: simplify instructions

- serving/samples/gitwebhook-go/service.yaml
Change the image name to match the instructions in README.
> Update service.yaml in the gitwebhook sample

- install/Knative-with-Docker-for-Mac.md
- install/README.md
> Add Docker for Mac setup instructions.

- serving/samples/telemetry-go/README.md
Fixes #652 
- Fix an error in the command to forward the Prometheus server to local machine
> Fix an error in README of serving/sample/telemetry-go

- community/WORKING-GROUPS.md
Points the Eventing Working Group calendar to the general working group meeting calendar where the Eventing Working Group meetings are scheduled.
-
-
-
> Update the link to the Eventing Working Group calendar.

- serving/samples/blue-green-deployment.md
Fixes #628
Provide access to source so users can learn more about how it works.
> Add link to source code

- build/README.md
- build/builder-contract.md
Fixes #625 
Make it clear that a *builder* is a type of container image and is not a formal object in Knative.
>  Use lowercase 'b' for builders

- serving/installing-logging-metrics-traces.md
Looks like these were lost and missed during a merge conflict.
Fixes #407
> Update old monitoring namespaces

- eventing/samples/gcp-pubsub-source/README.md
- eventing/samples/gcp-pubsub-source/subscriber.yaml
Helps with #548 and #541.
- Update the GCP PubSub sample.  
1. Add the second secret, erroneously removed in #559.
1. Make the examples easier to apply by using `sed` to replace the required placeholder.
1. Remove the dependency on `ko` by using the released image from https://github.com/knative/eventing-sources/tree/v0.2.1.
1. Replace `kail` with `kubectl logs`.
1. Tolerate `gcppubsub-source-key` already existing.
> Update the GCP PubSub sample

- install/Knative-with-Minikube.md
* Added `--disk-size=30g` since it was breaking
* Removed `--bootstrapper=kubeadm` because it is default
> Fix knative minikube installation doc

- serving/samples/autoscale-go/README.md
- serving/samples/autoscale-go/service.yaml
- Add annotations to autoscale-go sample to demonstrate CPU-based autoscaling, setting custom targets and scale bounds.
- Use `hey` for load generation instead of custom tool.
- Link to Kubecon demo of autoscaler customization.
> Add annotations to autoscale-go sample.

- install/Knative-with-Docker-for-Mac.md
+ Use knative v0.2.2 like on minikube
+ Fix the instructions to install knative serving
Signed-off-by: David Gageot <david@gageot.net>
Fixes #696
> Improve Docker for Mac installation guide

- serving/samples/helloworld-php/Dockerfile
- serving/samples/helloworld-php/README.md
Fixes #695
- Use the development php.ini shipped in the image but not "activated"
- Add comment pointing out the use of the production configuration
- Add comment linking to the documentation on the image README
> serving/samples/helloworld-php: use development php.ini

- eventing/sources/generator/main.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
> golang format tools

- README.md
- community/WORKING-GROUPS.md
- eventing/sources/README.md
- serving/samples/autoscale-go/README.md
We've been having issues with prettier.io on one of the autoscaling markdown files, so I manually fixed that file so that it wouldn't trigger the issue and ran prettier.io over the repo using the normal @mattmoor-sockpuppet command.
> Manually run prettier.io

- install/Knative-with-ICP.md
- install/README.md
Fixes #557
- Add the a new file install/Knative-with-ICP.md
- Update the install/README.md
> Update doc for knative deploy on IBMCloudPrivate

- hack/gen-api-reference-docs.sh
- hack/reference-docs-gen-config.json
- reference/README.md
- reference/build.md
- reference/eventing/eventing-sources.md
- reference/eventing/eventing.md
- reference/gen-api-reference-docs.sh
- reference/knative-refdocs-gen-config.json
- reference/serving.md
Generated with https://github.com/ahmetb/gen-crd-api-reference-docs and
this patch includes the script to self-serve this process. I hope to improve
this stuff in the future, for now it works fine.
Fixes #636.
> api-reference: Add API reference docs

- install/Knative-with-IKS.md
Fixes #540
If people are ok with this change I'll make similar modifications to the other
instruction files too.
> Tweaks docs to create Istio CRDs first

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-Minishift.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
Continuation of #717 - get the rest of the install docs
> Tweaks docs to create Istio CRDs first - part 2

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
- install/README.md
* Re-organize install guides by what kind of install they perform.
* Add link to new custom install guide
* Putting a HOLD on this for now, since this can't be merged in until #542 is merged.
Fixes: #295
> Organizing install guides; adding link to Custom Install guide.

- install/Knative-with-GKE.md
Fixes #N/A
- Correct wrong slash used to separate commands
- Correct extraneous `--filename` flag
> Fix syntax of Knative install command

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
* Updates installs in most guides to 0.3.0 release. 
* Doesn't update guides that were using the release-lite.yamls to install Knative, since those release versions don't exist in 0.3.0. Created #740 to track this.
Some install commands had an extra --filename flag and were using incorrect slashes, same as #736 ; also fixes that issue
> Update installs to 3.0 releases; fixing error in some install commands

- serving/samples/helloworld-go/helloworld.go
This is a 30 line trivial hello world, a 15 line license header adds unnecessary complexity.
Many other samples do not include a license header.
The license is already captured at the root of the repository.
> Remove license header for Go sample

- serving/samples/helloworld-nodejs/app.js
This is a 15 line trivial hello world, a 15 line license header adds unnecessary complexity.
Many other samples do not include a license header.
The license is already captured at the root of the repository.
> Remove license header for Node.js sample

- serving/outbound-network-access.md
Fixes #758 
- Use same env variables as in the install document.
-
-
> use consistent env variables from install section

- serving/samples/helloworld-go/Dockerfile
- serving/samples/helloworld-go/README.md
Mainly for consistency with other samples.
> Add link to image in Dockerhub

- eventing/sources/README.md
- eventing/sources/sources.yaml
This was found by the dead link checker (https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_docs/715/pull-knative-docs-build-tests/1085239101386395648/) and should fix that test failure.
- Update GCPPubSubSource link to its new location
> GCPPubSubSource moved to contrib

- install/Knative-custom-install.md
- install/Knative-with-AKS.md
- install/Knative-with-Docker-for-Mac.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-OpenShift.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
- use kube version 1.11
- the recommended version of knative was bumped to v0.3.0 - we need to adjust the kube version as well
> Bump required kube version to 1.11 to align with v0.3.0 release

- serving/README.md
- serving/cluster-local-route.md
- Update instructions to show how to make a Route/KService visible only inside a cluster.
> Instruction to make a Route/KService visible only inside cluster.

- build/auth.md
Fixes #385 
Explains parameters like `build.knative.dev/git-0` under each example. This could be explained _somewhat_ more in the comments in the examples themselves instead of below the example, as this does. If we think that approach would be preferable, I'm happy to update this.
> Fixes #385

- eventing/README.md
- eventing/default-channels.md
[**Rendered**](https://github.com/grantr/docs/blob/default-channels/eventing/default-channels.md)
Features described were added in https://github.com/knative/eventing/pull/580.
Fixes https://github.com/knative/eventing/issues/632.
- Add `default-channels.md` to eventing docs and link to it from `eventing/README.md`.
/cc @evankanderson 
for general documentation review
@Harwayne 
for accuracy review
> Document default channels for users and operators

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-ICP.md
- install/Knative-with-IKS.md
- install/Knative-with-PKS.md
- serving/installing-logging-metrics-traces.md
Previously, the comprehensive install guides had users check for pods in the knative-monitoring namespace, but didn't actually direct users to install monitoring. This fixes that.
Also rewrites monitoring install page to no longer reference outdated install bundles that no longer exist in v0.3
Also a rewrite of the ICP guide to be more consistent with existing install guides. (Will conflict with the other open PR that touches the ICP page, but I think these edits are the correct way to go for that guide. Depending on which PR goes in first, I'll resolve conflicts appropriately to keep the version in this PR.)
> Updates monitoring in installs; rewrite of ICP install

- eventing/samples/gcp-pubsub-source/subscriber.yaml
Hi,
it looks like that with the last commit the `image` was deleted accidentally. This simple fix should make the sample working again.
> Add missing image tag for v0.3

- eventing/samples/cronjob-source/README.md
- eventing/samples/cronjob-source/service.yaml
Use real message_dumper image instead of ko image path.
Fixes #813 
Used `ko` image path in the spec however the installation command in README.rd was "kubectl apply ..."
-  Use a real message_dumper image instead of `ko` image path, so that user can try out the samples without `ko`.
> Fix cronjob sample bug

- eventing/README.md
Correct the `serviceAccountName` description for the `GitHubSource` and fix a missing space.
> Correct spec documentation for GitHubSource

- doc-releases.md
Cutting the long overdue 0.2.x version of the knative/docs repo (into a maintenance branch).
> Cut v0.2 branch + add v0.2.x tag

- eventing/samples/gcp-pubsub-source/README.md
- eventing/samples/gcp-pubsub-source/knative-source.json
The file name must've changed in the new release in eventing-sources repo.
Making change to accommodate.
> eventing/samples/gcp-pubsub-source: fix filename

- build/auth.md
- build/build-templates.md
- build/builder-contract.md
- build/builds.md
- build/creating-builds.md
- build/installing-build-component.md
- build/personas.md
- eventing/debugging/README.md
> Add front matter to Build files

- serving/samples/helloworld-nodejs/README.md
- serving/samples/helloworld-nodejs/package.json
Since this is a Hello World, I do not think we need the `homepage`, `bugs` and `repository` attributes of package.json, but instead I suggest to keep it short in order to show the actual simplicity of the sample
> Simplify Node.js package.json

- eventing/samples/gcp-pubsub-source/README.md
See the line I changed, when I paste it to my zsh terminal, it thinks the
closing double-quote is missing. Turns out the `!"` is a special sequence in zsh
so it's better not to end a sample command like this.
Source: https://unix.stackexchange.com/questions/497328/zsh-thinks-unterminated-quote-if-preceded-by-exclamation-mark/497335#497335
> eventing/samples/pubsub: fix copy paste issue

- eventing/README.md
Fixes #600
Assuming this is intended behavior,  I wanted to clarify the --sink argument for a ContainerSource a bit after getting tripped up a bit on it myself, where the argument must be exactly "--sink"
> Argument must be "--sink" exactly for the sink to be filled in for ContainerSource

- serving/samples/helloworld-scala/README.md
Noticed a typo at the very end of the README, this fixes that.
> Addressing a kubectl typo in helloworld-scala README

- install/Knative-with-Minishift.md
Fixes #(844)
- fixed the dead link in the installation file  [Knative-with-Minishift.md](https://github.com/knative/docs/blob/master/install/Knative-with-Minishift.md#install-knative-serving)
> Fixed the dead link

- eventing/samples/writing-a-source/README.md
because it was a temporary prototype and is now currently written in go with kubebuilder.
-
-
-
> removing mention of gitlab source being python

- eventing/samples/cronjob-source/README.md
User just run a sample of knative-eventing. The [kail](https://github.com/boz/kail) isn't necessary to install.  We can use `kubectl logs` to instead.
Use `kubectl logs` instead of `kail` to verify the message in Cron Job Source example.
> Use kubectl logs instead of kail to verify the message

- serving/accessing-metrics.md
- serving/gke-assigning-static-ip-address.md
- serving/setting-up-custom-ingress-gateway.md
This change updates the metrics, logging, and ingress documentation with
information from documents in the Knative Serving repository. This is an
effort to centralize our user documentation in a single place.
This should allow us to remove the following files from Knative Serving
as they now contain either duplicative or out-dated information.
* https://github.com/knative/serving/blob/master/docs/telemetry.md
*
https://github.com/knative/serving/blob/master/docs/setting-up-custom-ingress-gateway.md
*
https://github.com/knative/serving/blob/master/docs/setting-up-ingress-static-ip.md
> Update metrics and ingress gateway documentation

- serving/samples/rest-api-go/README.md
- serving/samples/rest-api-go/sample.yaml
This change updates the sample to use a Knative Service instead of a
Route and Configuration directly.
It also updates the instructions to:
* Add links to relevant external documentation
* Clarify steps and actions occuring in each step
* Use label selectors for querying child resources
* Require Knative 0.3 to simplify instructions
> Update Serving Rest API example

- serving/samples/grpc-ping-go/Dockerfile
- serving/samples/grpc-ping-go/README.md
- serving/samples/grpc-ping-go/client/client.go
- serving/samples/grpc-ping-go/sample.yaml
User a Service instead of Route/Configuration
Specify the port with `name: h2c`
Build the client into the docker image (due to Go build tags)
User DockerHub, drop perl
Other cosmetic tweaks
> Fix up the GRPC sample in preparation for 0.4

- install/Knative-custom-install.md
- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gloo.md
- install/Knative-with-Minikube.md
- install/Knative-with-OpenShift.md
- install/README.md
[Gloo, the Envoy-based Kubernetes Ingress / API Gateway](https://gloo.solo.io/) can now [serve as a clusteringress controller for knative-serving](https://gloo.solo.io/getting_started/kubernetes/gloo_with_knative/). 
- Add an alternate installation option for OpenShift, Minishift, Minikube to use `glooctl` to install Knative without Istio, using Gloo as the Gateway controller instead.
> Add gloo to docs

- install/Knative-with-Minikube.md
Fixes #(882)
- The `istio-crds.yaml` should be apply before the `istio.yaml`.
> Correct Istio install steps for minikube (#882)

- install/Knative-custom-install.md
- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-ICP.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-Minishift.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
0.4 isn't cut yet but I'd like to send this PR out to get feedback first to be ready when it is.
/hold
(until 0.4.0 is cut)
> Add commands to clean up `knative-ingressgateway` before upgrade from 0.3.x to 0.4

- serving/README.md
- serving/deploying-with-private-registry.md
Fixes #819
- As per our discussion in issue #819, I've created a new doc called: "Deploying to Knative using a Private Registry"
- This doc uses IBM Container Registry as the example
> Deploy using private registry

- install/Knative-custom-install.md
- install/Knative-with-AKS.md
- install/Knative-with-Docker-for-Mac.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-ICP.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-Minishift.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
v0.4 release has been cut for all components; updating install files to match.
Adds information about clusterrole.yaml, which is now necessary if using the Build and Serving components together.
> Updating install docs to v0.4

- eventing/README.md
Fixes N/A (Follow up https://github.com/knative/docs/pull/915)
- Install v0.4.0 release of eventing and eventing-sources instead of v0.3.0.
> Update eventing install for v0.4.0

- install/Knative-with-Gardener.md
- Fix issue with markdown syntax in `install/knative-with-gardener.md`
> knative with gardener: fix markdown syntax

- serving/samples/helloworld-python/Dockerfile
- Use gunicorn to serve hello world app instead of built-in Flask debug server (benefits: production-ready out of the box; drawbacks: more complex example, debug mode disabled for security reasons)
- In order to use $PORT properly in the CMD, switch to using shell syntax
- In order to ensure signals are received properly by gunicorn and not intercepted by the shell, use 'exec'
> Update Dockerfile to use gunicorn w/ multithread

- serving/samples/telemetry-go/prometheus-test.yaml
- serving/using-external-dns-on-gcp.md
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>
Since RBAC went into GA in 1.8, switching to use rbac v1 in yaml files in docs repo.
> Switching to rbac v1

- install/Knative-with-GKE.md
Eventing release was failing for me due to missing `ClusterChannelProvisioner`
```
unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
```
Adding `https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml` fixes this
-
-
-
> Add in-memory-channel to enable eventing release

- community/README.md
Fixes #193 
- Add the links of Build and Eventing to "How can I help"
> Add Build and Eventing to "How can I help" (#193)

- build/auth.md
If there are multiple YAML files for kubectl, all files should be
specified by -f option.
> Correct the command for build auth.

- serving/samples/helloworld-nodejs/Dockerfile
By specifying the package.json separately from the wildcard argument, we get a more specific error. In general there is no error if missing `package-lock.json`, but missing `package.json`:
```
COPY failed: no source files were specified
```
```
COPY failed: stat /var/lib/docker/tmp/docker-builder239774917/package.json: no such file or directory
```
> serving/samples/helloworld-nodejs: specifically require package.json

- serving/samples/source-to-url-go/README.md
- serving/samples/source-to-url-go/service.yaml
Users trying out the source-to-url sample might experience Kaniko build pod time-outs in slow network conditions. This is hard to troubleshoot as Kaniko offers no pull progress logs. The existence of a timeout and setting should thus be made explicit for new users to avoid getting stuck at this point.
- note in doc
- timeout parameter explicit in yaml
> Add note on build pod timeout in Serving source-to-url sample

- serving/samples/source-to-url-go/README.md
Lined up `timeout` key correctly
> Fix syntax error in yaml

- eventing/README.md
- eventing/samples/github-source/README.md
- eventing/samples/github-source/github-source.yaml
This commit introduces extra documentation to support the new
functionality on githubsource where you can optionally specify
the baseURL of the github api server - thus enabling the existing
githubsource to be used against both public github and github
enterprise.  
New function added under https://github.com/knative/eventing-sources/pull/219
- Update sample code to highlight new optional githubAPIURL spec value
- Update main doc to highlight new optional githubAPIURL spec value
> Doc changes to githubsource for specifying API URL

- serving/samples/grpc-ping-go/client/client.go
I was trying to connect to my grpc service at a custom domain like
`grpc-ping.default.IP.IP.IP.IP.xip.io` while omitting -server_host_override
and it resulted in bug https://github.com/knative/serving/issues/3307 which
took several days to figure out there was a default value for this flag.
Removing the default value as nobody's really owning grpc.knative.dev or
setting it as the custom domain in this sample.
> samples/grpc-ping-go: don't provide default -server_host_override

- install/Knative-with-Minikube.md
Due to a bug in CoreDNS that is fixed only in a version that ships
on MiniKube when installing Kubernetes v1.12 or newer. See
https://github.com/coredns/coredns/issues/2038
Fixes knative/serving#3067
- Change MiniKube installation to require 1.12 cluster.
> Change MiniKube installation to require 1.12 cluster.

- install/Knative-with-OpenShift.md
curl doesn't seem to work on github release pages anymore
> update Knative-with-OpenShift from 3.10 to 3.11 (and minor clean up)

- .github/ISSUE_TEMPLATE/docs-feature-request.md
- .github/ISSUE_TEMPLATE/new-changing-functionality-in-knative.md
- We needed a template specifically for user's feature requests; we only had one for bugs and one for upcoming changes to Knative
> Update issue templates -- separate feature request from new/changing functionality

- eventing/samples/cronjob-source/README.md
Updates the documentation for cronjob-source sample to show latest output.
Fixes #1005 
- Output has changed due to the adoption of  cloudevents.io by eventing.
- It shows some of the headers received by the message dumper as part of cloudevents spec.
> Update Eventing cronjob-source for Cloudevents

- hack/gen-api-reference-docs.sh
The API docs generation script can now be called with non-hardcoded commit/tag
refs.
KNATIVE_SERVING_COMMIT=v0.4.0 \
KNATIVE_BUILD_COMMIT=v0.4.0 \
KNATIVE_EVENTING_COMMIT=v0.2.1 \
KNATIVE_EVENTING_SOURCES_COMMIT=v0.2.1 ./gen-api-reference-docs.sh
This should ease docs releases a tiny bit.
> hack: configurable repo refs for api docs gen

- hack/gen-api-reference-docs.sh
Adding an EXIT trap to cleanup the /tmp directories containing
1. cloned knative repos (can be huge, especially going forward)
2. `gen-crd-api-reference-docs` tool's repo + built binary
Fixes #1000.
/assign @richieescarez
> hack: update ref docs gen script to cleanup tmp dirs

- docs/reference/README.md
- hack/gen-api-reference-docs.sh
add "how to build knative api docs" steps while its front of mind
also included copy of changes/improvements to script from #998 and #1001
/cc @ahmetb
> ref tool steps + script

- docs/serving/setting-up-a-logging-plugin.md
- fix serving directory path in setting-up-a-logging-plugin.md
> fix serving directory path

- docs/reference/build.md
- docs/reference/eventing/eventing-sources.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Built an 0.4 version of the API docs using the 0.4.0 releases of knative components:
KNATIVE_BUILD_COMMIT=v0.4.0 \
KNATIVE_EVENTING_COMMIT=v0.4.0 \
KNATIVE_EVENTING_SOURCES_COMMIT=v0.4.0 \
KNATIVE_SERVING_COMMIT=v0.4.0 \
./gen-api-reference-docs.sh
> build version of API docs for 0.4

- docs/concepts/resources.md
`ko` has a new home at https://github.com/google/ko
> Point to new ko repo

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
People need to delete this one Eventing resource before they can apply
the yaml for the upgrade. W/o this they'll see an error like this:
```
The StatefulSet "controller-manager" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
Once people are ok with this text I'll then apply it to the other md files.
> Minor change to our upgrade docs

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
People need to delete this one Eventing resource before they can apply
the yaml for the upgrade. W/o this they'll see an error like this:
```
The StatefulSet "controller-manager" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
> Minor change to our upgrade docs (#1059)

- docs/install/Knative-with-GKE.md
Add newlines between the two descriptions and commands, otherwise they get jammed together and it's unreadable.
- Add newlines between description and the actual example command line.
-
-
> add newlines between label namespace and command

- test/e2e/flag.go
`emitmetrics` flag is supplied in continuous run, handle this flag to make continuous run pass
> allow emit-metrics flag to fix continuous run

- docs/build/auth.md
Since v0.4.0 release, knative/build supports additional secrets for
docker registries : `kubernetes.io/dockerconfigjson` and
`kubernetes/dockercfg`.
See knative/build#536 and knative/build#545 :angel: 
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Update build/auth documentation to document kubernetes.io/* secrets

- docs/eventing/README.md
Fixes gaps in documentation introduced by https://github.com/knative/eventing-sources/pull/264
- added KafkaSource details using the same template as existing sources to https://github.com/knative/docs/tree/master/docs/eventing#sources
> Add KafkaSource information and link to example

- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/iot-core/README.md
- docs/eventing/samples/kubernetes-event-source/README.md
- cronjob-source: cleanup event source, service
- iot-core: cleanup gcpubsub, channel, gcpubsub-source and subscription
- kubernetes-event-source: cleanup channel, service account, k8s event, and subscription
> Add resource cleanup instructions for several event-source examples

- docs/serving/samples/hello-world/rest-api-go/sample-template.yaml
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/traffic-splitting/README.md
- docs/serving/samples/traffic-splitting/release_sample.yaml
- docs/serving/samples/traffic-splitting/split_sample.yaml
- docs/serving/samples/traffic-splitting/updated_sample.yaml
Update traffic splitting example to use Release mode (#964)
* Update traffic splitting example to use Release mode
This change updates the traffic splitting example to use release mode
introducing the concepts of the mode in three steps. This change also
simplifies running the commands and removes the need to mutate files on
disk to run through the example.
* Use envsubst instead of perl. Simplify image path
* Use long names for arguments
* Update diff statement
* Add envsubst install instructions
-
-
-
> Resolving bad merge in v0.3, with cherry-pick 

- docs/serving/samples/hello-world/rest-api-go/sample-template.yaml
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/traffic-splitting/README.md
Update traffic splitting example to use Release mode (#964)
* Update traffic splitting example to use Release mode
This change updates the traffic splitting example to use release mode
introducing the concepts of the mode in three steps. This change also
simplifies running the commands and removes the need to mutate files on
disk to run through the example.
* Use envsubst instead of perl. Simplify image path
* Use long names for arguments
* Update diff statement
* Add envsubst install instructions
> Resolving bad merge in v0.4, with cherry-pick

- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/gcp-pubsub-source/channel.yaml
- docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
- docs/eventing/samples/gcp-pubsub-source/trigger.yaml
Part of #1021
- Switches the sample from using `Channel` to use `Broker`.
> Update the GcpPubSubSource example to use Broker, rather than Channel.

- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/channel.yaml
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/serviceaccount.yaml
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
Part of #1021 
- Switches the sample from using `Channel` to use `Broker`.
> Update the kubernetes-event-source example to use Broker, rather than Channel.

- docs/install/check-install-version.md
Relates to [Issue #1119](https://github.com/knative/docs/issues/1119)
Fixes #(1119 )
- 'verion' typo fix
- removed unnecessary article 'a' in line 33
> Fix 'verion' mispelling in check-install-version

- contributing/STEERING-COMMITTEE.md
Google nominated, and the steering committee approved, the nomination of Ryan Gregg (github.com/rgregg) to fill Google's allotted and vacant seat.
> Add Ryan Gregg to the Knative Steering Committee page

- docs/serving/samples/blue-green-deployment.md
This updates the blue green sample to use the new URL field instead of
asking the user to query a fixed URL.
Fixes #1078
> Update sample to use the new URL field

- docs/build/installing-build-component.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/installing-logging-metrics-traces.md
Fixes #994 
- Release name changed for one of the [eventing-sources resources
](https://github.com/knative/eventing-sources/releases) https://github.com/knative/eventing-sources/releases/download/v0.4.0/release.yaml --> https://github.com/knative/eventing-sources/releases/download/v0.5.0/eventing-sources.yaml
- /releases/download/v0.4.0/ --> /releases/download/v0.5.0/
> v0.4 -> v0.5

- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/cronjob-source/service.yaml
- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/gcp-pubsub-source/trigger.yaml
- docs/eventing/samples/github-source/README.md
- docs/eventing/samples/github-source/service.yaml
- docs/eventing/samples/iot-core/README.md
- docs/eventing/samples/iot-core/trigger.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
> message_dumper to event_display

- docs/reference/build.md
- docs/reference/eventing/eventing-sources.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
v0.5.0 API docs, generated from the `v0.5.0` component release numbers:
```
KNATIVE_BUILD_COMMIT=v0.5.0 \
KNATIVE_EVENTING_COMMIT=v0.5.0 \
KNATIVE_EVENTING_SOURCES_COMMIT=v0.5.0 \
KNATIVE_SERVING_COMMIT=v0.5.0 \
./gen-api-reference-docs.sh
```
Fixes #1139
> API docs for v0.5.0 release

- docs/install/Knative-with-Minishift.md
Adds missing chaining in bash command resulting in invalid command error: Unexpected args: [oc apply oc apply]
No Issue created
- Fix bash syntax in docs/install/Knative-with-Minishift.md snipped on line 231
> Fix bash syntax error

- docs/install/Knative-custom-install.md
Some of the resource install links were broken; updating to the correct resources and adding links to the Apache Kafka and Camel sources.
> Fix broken resource links

- docs/serving/samples/knative-routing-go/routing.yaml
- Replace `knative-ingressgateway` service with `istio-ingressgateway` service as it is the newest ingress service used in Knative 0.3 and above.
> Replace knative-ingressgateway service with istio-ingressgateway service

- docs/install/Knative-with-Minishift.md
- Enabling admissions-webhook can be done with an add-on.
- Replacing `kubectl` commands by `oc`
> Update installation documentation with Minishift

- community/samples/serving/helloworld-dart/README.md
Replace pubspec field `private` with `publish_to`.  
See 52f464f.
[ref](https://www.dartlang.org/tools/pub/pubspec#publish_to)
> fix README for community Dart sample

- contributing/STEERING-COMMITTEE.md
Red Hat nominated, and the steering committee approved, the nomination of Paul Morie (github.com/pmorie) to fill Red Hat's allotted and vacant seat.
> Add Paul Morie from Red Hat to the Knative Steering Committee

- docs/build/auth.md
- docs/eventing/debugging/README.md
- docs/eventing/samples/cronjob-source/README.md
Fix some spelling mistakes of docs：
- precendence -> precedence
- reconcilation -> reconciliation
- destiantion -> destination
- Similarily -> Similarly
> Fix some spelling mistakes of docs

- community/samples/serving/helloworld-vertx/README.md
Signed-off-by: xichengliudui <1693291525@qq.com>
-
-
-
> Fix typo Knatve -> Knative

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/README.md
Fixes #1190  and #1194 
- Updates install guides to first install only the labeled sections of the install files, to avoid race conditions and unpredictable install errors as described in #1036 
- Updates Minikube install to include all components, not just Serving
> Add label install to guides, update Minikube

- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- Remove `--save` from `npm install` script.
See https://stackoverflow.com/a/19578808
> docs: Remove `--save` from `npm install`

- contributing/DOCS-CONTRIBUTING.md
Make it clear that you need to sign the CLA even for docs
plus reduce duplicate mention of style guide to just a link
> add missing mention of cla

- docs/serving/samples/buildpack-app-dotnet/sample.yaml
- docs/serving/samples/buildpack-function-nodejs/sample.yaml
according the buildpacks build-templates name in cnb.yaml updated to 'buildpacks-cnb', the build-template name in buildpacks sample.yaml should update to 'buildpacks-cnb' as well
sample.yaml
-
-
-
> update sample.yaml to fix the build-template name to buildpacks-cnb

- docs/eventing/README.md
I believe it say the producers and consumers are independent, since producers and sources are kind of the same thing.
> Fix a typo in Eventing doc

- community/samples/README.md
- community/samples/_index.md
- docs/build/README.md
- docs/build/samples.md
- docs/concepts/_index.md
- docs/eventing/debugging/_index.md
- docs/eventing/samples/_index.md
- docs/samples.md
- docs/serving/samples/README.md
- docs/serving/samples/_index.md
Add crossing link for all samples, create a main code samples page, and add some consistency:
- Add "Code samples" landing pages:
- "all code samples" at top level in nav (new)
- community (edit)
- serving (edit)
- build (new)
- eventing (edit)
- Ensure "Code samples" shows toward the bottom of each section in the nav tree
- Shallow pass at consistent use of "code sample" (vs sample app)
Issue: #1213
> links and landing pages for all samples

- contributing/README.md
- Fix the links that go to issues labelled "help wanted", current links are querying for labels named "community/help wanted"
> README: fix broken links to "help wanted" label

- docs/eventing/samples/iot-core/README.md
\``` is missed in the markdown code block.
> Fix an error in README.md

- community/samples/serving/helloworld-vertx/README.md
- contributing/DOCS-CONTRIBUTING.md
Fix some minor problems while reading.
Some spelling mistakes:
- youself -> yourself
- seperately -> separately
> Fix some spelling mistakes of doc

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
In 0.6 we will stop shipping Istio yamls, as we are not in the business of
redistributing Istio (incl. supporting these yamls).  In preparation for that,
this change makes a few changes:
1. Update things to point to the 0.5.2 release
1. Point to our in-tree Istio files (which is what we were attaching)
1. For GKE, direct users to the Istio addon instead.
1. For GKE, add a pointer to CR-GKE (if folks wanted hosted).
This is a half-measure to avoid things breaking.  We need a page that points
folks to the Istio docs, and calls out any specialized instructions for
what Knative needs.
Fixes: https://github.com/knative/serving/issues/3670
> Remove references to Istio yamls attached to releases.

- docs/serving/samples/autoscale-go/autoscale.go
We wanted to use the autoscaler-go sample to do some load testing. However many load testing services require the target to return a specific string to verify that they should be load tested (vs. a DDoS attack).
This update uses the **VALIDATION** env-var to define the string that should be returned from a URL that includes that token, and appears to be a common format for validating a URL from these types of sites.
This PR also fixes that the sample listens only on port 8080, which is not the desired experience in the container runtime contract.
> Add validation token support to autoscaler-go

- docs/serving/samples/traffic-splitting/README.md
Update the command in README to correctly extract latest_hostname from target Knative Service json output.
- pick the right k service ("stock-service-example")
- look up with right field ("name")
> Fix command line to extract LATEST_HOSTNAME

- docs/serving/samples/traffic-splitting/README.md
When upgrade ksvc from `runLatest` to `release` should use `kubectl replace` rather than `kubectl apply`, or you will get exception: "expected exactly one, got both: runLatest, release"
> Correct traffic splitting in release-0.5

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
Update vendor: knative/test-infra.
- fix for retrying different GCP regions when e2e test failed due to stock out
- Istio install from GKE Addon
> Update test-infra: some fixes

- docs/eventing/samples/gcp-pubsub-source/README.md
This fixes #1264 issue in master.
Do we want to fix the release-0.5 as well ?
> address wrong manifest in gcppubsub sample

- docs/install/Knative-custom-install.md
- docs/serving/installing-logging-metrics-traces.md
- Documentation changes to accompany serving PR https://github.com/knative/serving/pull/3938
- Jaeger operator is changed from being embedded (and managed by Knative) to being a dependency that needs to be pre-installed
> Update docs to define jaeger-operator as a dependency

- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-Minikube.md
Fixes https://github.com/knative/serving/issues/4057
- Change the configuration of cluster from allocating 4 CPUs to 6 CPUs for local Kubernetes
> Change the configuration for local Kube cluster in Minikube and Docker desktop

- docs/install/Knative-with-IKS.md
cluster-addon-enable knative -y $CLUSTER_NAME
or 
cluster-addon-enable knative $CLUSTER_NAME -y
works but the currently documented
cluster-addon-enable -y knative $CLUSTER_NAME
doesn't.
Note: If this creates a CLA warning, it's because
I made the PR from the GitHub web editor.
> IKS: move addon enable -y flag to the end

- docs/serving/samples/autoscale-go/README.md
Fixes #1300
- Instruction is added for Minikube and docker desktop to get the IP address for autoscaling
- A reference link is added for other platforms
> Add the instruction on how to get IP_ADDRESS for autoscaling for other Kube environments

- docs/README.md
The main readme redirects to github the first time we read about the _Components_
This change redirects to our own docs and then adds pointers to github issues for contributors.
> redirect to docs instead of github

- docs/build/README.md
- docs/build/builds.md
This PR corrects the build example which defines two build steps with the previous version only one step will be executed (this is actually an bug in knative build, I will create another issue in the according repo).
> Correct syntax of build example

- docs/eventing/broker-trigger.md
Mostly a copy of https://github.com/knative/eventing/blob/e4637d3d854c06ebce7041a08a2191e17003ce66/docs/broker/README.mdgithub.com/knative/eventing/docs/broker/README.md, but
with a new intro and without the `Implementation` section.
All of these words were written by @Harwayne. This was originally more targeted to contributors, so it probably needs some massaging to be useful to users.
Fixes #1023 
/label cherrypick-0.5
> Add Broker/Trigger docs from eventing repo

- docs/install/check-install-version.md
- Add section about the new Knative Serving release version label (v0.4.0+), while
keeping the old way in a different section.
- Add an Eventing section. The Eventing components have the release
version label, but it's set to "devel" in 0.6.0, so we can't use it this time :(
> Update check install version docs

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-OpenShift.md
- Eventing now uses standard Kubernetes Services, so it should be compatible
with both Gloo and Istio.
> Remove note about Gloo incompatibility with Eventing

- docs/build/installing-build-component.md
- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/iot-core/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/installing-logging-metrics-traces.md
Now that 0.6 has been released, we can update all the install links to `v0.6.0`.
> Update release versions to 0.6

- docs/install/installing-istio.md
Fixes #1338
- Add a step to create istio-system namespace
- Update the command of installing istio-lean.yaml according to the newest [download-istio.sh](https://github.com/knative/serving/blob/master/third_party/istio-1.1.3/download-istio.sh#L68)
> Fix the broken Istio installation command

- docs/install/getting-started-knative-app.md
Fixes #1298
Adds a note that points to the guide to configure a custom domain
> add reference to custom DNS config

- docs/serving/samples/hello-world/helloworld-go/README.md
issue: None 
- Fix samples path when `git clone && cd`
> Fix samples path

- docs/serving/samples/telemetry-go/Dockerfile
Cannot build the image follow the doc: 
https://github.com/knative/docs/tree/master/docs/serving/samples/telemetry-go
will hit $GOPATH exception, it's caused by a incorrect path in the Dockfile
> Correct the path in the Dockerfile

- docs/eventing/broker-trigger.md
Fixes
It should be `ServiceAccount` instead of `User` for broker `RoleBinding` subject.
-
-
-
> Fix broker rolebinding for master

- docs/install/README.md
Removed a dead link on "Picking the Right Solution" which was going to a 404 page. Based off feedback from #1382 for which link to use.
Fixes #1382 
- Replace link for "Picking the Right Solution" with  https://kubernetes.io/docs/setup/ so that it does not go to a 404 page anymore
> Update README.md to remove dead link

- docs/install/installing-istio.md
> Fix bad href

- docs/eventing/broker-trigger.md
Fixes 
Broker `RoleBinding` subject should use `ServiceAccount` instead of `User`
-
-
-
> Fix broker rolebinding for 0.6.0

- docs/serving/samples/hello-world/helloworld-csharp/.dockerignore
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/.dockerignore
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/.dockerignore
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/.dockerignore
- docs/serving/samples/hello-world/helloworld-python/README.md
1. If someone runs a local build in these samples, it will generate files that will make their way into the container. Once there, these files can interfere with the build.
2. Files unrelated to the application itself such as the `Dockerfile` or `README.md` can excessively reset the layer cache.
- Add a new `.dockerignore` for serving samples subject to (1), with language-specific exclusions of generated files. This includes: Python, C#, PHP, Nodejs
- Add Dockerfile and README.md for (2)
- Include a new step in the README after the Dockerfile is set up to note creating the .dockerignore.
> service/samples: add .dockerignore to samples with local build disruption risk

- docs/README.md
- docs/serving/README.md
- docs/serving/autoscaling.md
- docs/serving/configuring-the-autoscaler.md
Fixes #1362 
- added autoscaling.md
- updated links
> Added autoscaling docs and scale-to-zero details

- docs/serving/samples/grpc-ping-go/README.md
Fixes #1381
- Based on the syntax in sample.yaml, it should be version 0.6 or later.
- The command "docker push" uses a wrong tag name for the image. This PR corrects it.
> Fix the wrong information in grpc example

- docs/serving/configuring-the-autoscaler.md
Fixes #1405 
- removes H1 that wasn't required at the start of the configuring-the-autoscaler.md doc
> removed unnecessary H1 from autoscaling docs

- docs/serving/tag-resolution.md
Our controller does resolution of tags to digests, which has been a
source of confusion. This documents the fact that we do it, why we do
it, and how to configure the controller to work around common issues.
> Document serving tag resolution

- docs/install/Knative-with-GKE.md
- Istio install instructions are in `install` now, not `serving`.
> Fix istio link

- docs/README.md
- docs/eventing/broker-trigger.md
- docs/install/getting-started-knative-app.md
- docs/install/installing-istio.md
- docs/serving/README.md
- docs/serving/configuring-the-autoscaler.md
- docs/serving/samples/grpc-ping-go/README.md
- docs/serving/samples/hello-world/helloworld-csharp/.dockerignore
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/.dockerignore
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/.dockerignore
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/.dockerignore
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/tag-resolution.md
PRs:
#1408 
#1398 
#1392 
#1380 
#1363 
#1357 
#1355 
#1327
#1260
> Cherry pick changes from master into 0.6

- test/e2e/sampleapptestbase.go
This PR fixes e2e test error by using url instead of domain for finding domain URL. This PR unblocks PR from being merged in docs, but will makes e2e tests diverge from instructions. subsequent update is needed from #1438
> Fix e2e test breakage by using url instead of domain

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
Two changes
* eventing-sources is now eventing-contrib (touched the file, so updated those references)
* the kafka source is relocating: https://github.com/knative/eventing-contrib/pull/426 
/cc @evankanderson
> Moving kafka src and contrib

- docs/serving/samples/knative-routing-go/README.md
Fixes #1384
- Fixes the typo in the command to get the gateway ip.
- Adds the information regarding using existing domain name.
- Adds the information on how to use dockerhub.
- Adds the information on different domain templates.
> Improve the documents for the knative routing example

- docs/install/installing-istio.md
Fixes #https://github.com/knative/serving/issues/4225
- Update Istio version from 1.1.3 to 1.1.7
> Update the Istio version from 1.1.3 to 1.1.7

- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-clojure/service.yaml
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-dart/service.yaml
- community/samples/serving/helloworld-elixir/README.md
- community/samples/serving/helloworld-elixir/service.yaml
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-haskell/service.yaml
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-rust/service.yaml
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-swift/service.yaml
- community/samples/serving/helloworld-vertx/README.md
- community/samples/serving/helloworld-vertx/service.yaml
Replace the use of `runLatest` with `template`.
/label cherrypick-0.6
Fixes #1330
> Update community samples to use v1beta1 APIs

- docs/install/Knative-with-GKE.md
> Fixing a path to the istio installation docs

- docs/install/installing-istio.md
Since `istio-lean` should not be used for production deployment, this PR sets the Istio pilot memory request to 128Mi from 2Gi ...
-
-
-
> Set pilot memory request lower for lean install

- docs/serving/setting-up-a-logging-plugin.md
Replace fluentd sidecar by fluentd daemon set since it was changed in https://github.com/knative/serving/pull/4156.
> Update logging plugin docs

- docs/install/Knative-custom-install.md
It's not a source, it's a sample Sink. And since it's just a sample
Sink we shouldn't include it in the docs as something people should install
as part of a default install process for core Knative.
> Don't show event-display as a source

- docs/serving/samples/blue-green-deployment.md
- Changes use of `name` to `tag` to follow the new API instead of the deprecated API.
> Update to use `tag` instead of `name` in traffic

- docs/eventing/broker-trigger.md
These were added to the automatic setup in https://github.com/knative/eventing/pull/1426. They're not required for the Broker to work, but they enable observability features like consolidated logging, metrics, and tracing.
- Document additional RoleBindings to be created when manually preparing a namespace for a Broker.
/cc @Fredy-Z
> Add new RoleBindings to broker manual setup

- docs/serving/samples/grpc-ping-go/README.md
Was trying to run through the Prerequisite commands and noticed that the `cd` command had the incorrect path.
```
❯ git clone -b "release-0.6" https://github.com/knative/docs knative-docs
cd knative-docs/serving/samples/grpc-ping-go
Cloning into 'knative-docs'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 10590 (delta 9), reused 12 (delta 5), pack-reused 10563
Receiving objects: 100% (10590/10590), 25.08 MiB | 14.92 MiB/s, done.
Resolving deltas: 100% (6409/6409), done.
cd: no such file or directory: knative-docs/serving/samples/grpc-ping-go
```
This PR updates that command to the correct path.
> Update path in prerequisites command for grpc example

- README.md
Fixes #1498
- `Edit this page` instead of `Edit ths page`
-' let' instead of 'lets'
> Correct minor typo in README.md 

- docs/eventing/broker-trigger.md
As part of fix for https://github.com/knative/eventing/issues/1395.
This change needs to be merged after https://github.com/knative/eventing-contrib/pull/469
/hold
> Fix the broker trigger demo in release-0.6 docs

- docs/install/Knative-with-GKE.md
- docs/serving/samples/blue-green-deployment.md
- docs/serving/samples/grpc-ping-go/README.md
Original PRs:
#1404 
#1453 
#1493
> Cherry-pick batch release-0.6 --> master

- docs/serving/knative-kubernetes-services.md
that are running on a kubernetes cluster after installing knative 0.6.0.
- Describes the running knative services and deployments.
> Add documentation for the different knative services and deployments

- docs/eventing/samples/container-source/README.md
- docs/eventing/samples/container-source/heartbeats-source.yaml
Fixes https://github.com/knative/eventing/issues/1348
https://github.com/knative/eventing/pull/1321 introduces `PodTemplateSpec` to `ContainerSourceSpec`. This feature will be out in 0.7.x. Updating documentation to reflect the `template` field.
> Update container source documentation with `template` field

- docs/serving/using-a-tls-cert.md
Updating kubernetes secret creation instruction to correctly show which file should hold which data, ie. certificate on `cert.pem` and private key on `cert.pk`.
-
-
-
> Update order of files in example

- docs/serving/samples/gitwebhook-go/README.md
Fixes #1312
- Replace service.yaml with the correct contents
- Add the requirement for a public domain name for the service
> Replace service.yaml with the correct contents

- docs/serving/using-cert-manager-on-gcp.md
The current documentation only has httpsRedirect set on the https endpoint itself. In order for the ingress to redirect all traffic to use https, the tls section with httpsRedirect: true needs to be on the http section as well.
> Update cert manager on GCP example to upgrade to http by default

- docs/install/README.md
- docs/serving/using-a-tls-cert.md
Cherry-pick batch
Included PRs:
#1501 
#1511
> Cherrypick release-0.6 --> master

- docs/eventing/samples/container-source/README.md
- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/iot-core/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/installing-logging-metrics-traces.md
- docs/serving/samples/autoscale-go/README.md
- docs/serving/samples/gitwebhook-go/README.md
- docs/serving/samples/grpc-ping-go/README.md
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-scala/README.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/secrets-go/README.md
- Updates locations for install resources and `git clone` commands to the 0.7 release. 
- Removes references to clusterrole.yaml, since that is not necessary with Build being spun out to Tekton Pipelines
> Install updates -- v0.7.0

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
Eventing sources: https://github.com/knative/eventing-contrib/releases/download/v0.7.0/eventing-sources.yaml has been removed in lieu of all individual releases of the contrib projects.
> There is no longer a eventing-sources release.

- docs/eventing/debugging/README.md
- docs/reference/README.md
- docs/reference/eventing/eventing-contrib-api.md
- hack/gen-api-reference-docs.sh
updating a few terms and file names to better align with the change from "knative eventing sources" to 
"eventing resources that conform to Knative Eventing"
> Clarify "event sources" NOT "Knative eventing sources"

- doc-releases.md
Convert list to a link to the GitHub release page where all versions are listed (and avoid future maintenance)
> Update list of releases 

- doc-releases.md
Update list of available releases to instead use GitHub releases page
> change list to releases landing page

- docs/serving/README.md
- Changed
"resource maps a network endpoint to a one or more revisions"
to 
"resource maps a network endpoint to one or more revisions"
> Fix a small grammatical error

- hack/gen-api-reference-docs.sh
This updates to a recent version of gen-crd-api-reference-docs and allows
customizing the -api-dir option so that the docs for theeventing-contrib repo
can be generated.
Fixes #1528.
> gen-api-reference-docs: fixes for eventing-contrib

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
Remove the `kubectl get pods` command for eventing-sources, which doesn't exist anymore.
I was alerted to this issue by #1546 , but that PR only fixed one of the affected files and wasn't against the master branch, so I opened this PR for simplicity's sake. Thanks to @meteatamel !
> Remove kubectl get pods commands for eventing sources

- hack/gen-api-reference-docs.sh
This bumps the `gen-crd-api-reference-docs` to v0.1.5 which has two notable
fixes impacting Knative:
1. Prevent types in same apiGroup but different apiVersion (e.g v1beta1 vs
v1alpha1) from grouped together.
2. De-duplicate the apiGroups list when types belonging to that api group come
from different Go packages.
Fixes #1559.
/assign @richieescarez
> reference: fix api grouping in reference docs

- docs/eventing/broker-trigger.md
Upgrading the curl example in Broker's manual event emit example as the CloudEvents v0.1 format and no longer works, v0.2 does.
Tested with Knative Eventing 0.6
> Fixing Broker manual event emit curl example

- docs/build/README.md
Fixes #1457 
- Removes the reference and lead up to a defunct code sample. 
-
-
> Removes references to a invalid sample file. Fixes #1457.

- docs/install/README.md
Eventing did not require Istio anymore from v0.6.
> Remove Istio requirement for Eventing

- docs/reference/build.md
- docs/reference/eventing/eventing-contrib-resources.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Updated version of 07 API using revised API build script (#1559)
> 07 api from new version of script

- docs/_index.md
All main menu configuration now lives in the sites default config.toml
https://github.com/knative/website/pull/61
> Remove "Documentation" main menu config

- docs/install/Knative-with-OpenShift.md
- corrects directory so images are rendered
> Updating image path for OpenShift install docs

- docs/serving/configuring-the-autoscaler.md
Small change to fix typos in the ConfigMap example
> Additional space is required in the yaml example

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Minikube.md
- docs/install/README.md
Ambassador recently released an update that gives it the ability to create routes based off of Knative `ClusterIngress` resources. 
This PR adds Ambassador to the list of envoy-based solutions for install Knative.
> Add Documentation for Install Knative with Ambassador

- docs/eventing/sequence.md
- Fix the incorrect markdown link syntax.
-
-
> fix incorrect link format

- docs/serving/samples/grpc-ping-go/README.md
This PR adds a fix to the gRPC Go README which had a broken command in it.
> gRPC Go example fix

- docs/eventing/samples/apache-camel-source/README.md
- Update version for doc
- Brief explanation on running a Camel source
>  Document usage of Camel K in sources

- docs/eventing/broker-trigger.md
Fixes: https://github.com/knative/eventing/issues/1504
- Add a note about removing of annotation on a namespace does not delete broker.
> removing annotation does not remove broker

- docs/serving/spec/knative-api-specification-1.0.md
Adding a Markdown formatted version of the approved Knative API
Specification to the repository. Once this is checked in it will replace
the Google Doc found here:
https://docs.google.com/document/d/1UHT3W61tbX1qnEPA0qtoNUACki0d8FkXJ10JHOQu9uU/edit#
Fixes https://github.com/knative/serving/issues/4517
Related https://github.com/knative/serving/issues/4227
> Add Knative API Specification

- docs/eventing/channels/README.md
- docs/eventing/channels/_index.md
- docs/eventing/channels/channels-crds.md
- docs/eventing/channels/channels.yaml
- docs/eventing/channels/generator/ReadmeTemplate.gomd
- docs/eventing/channels/generator/main.go
- Fix the "default-channels" topic (the channels directory requires the _index.md file)
- Prevent nested markdown processing
- Move auto gen table into separate topic (prevents past issue of double rendering = displays hidden html comments)
- Add fix from #1486 (add missing Channels CRDs and qualify CCPs)
> fix default-channels rendering and prevent nested shortcodes

- docs/smoketest.md
- smoketest.md
two hidden yet published pages that can be used to verify that known site pain points haven't broken
the smoketest.md file at root allows for local testing and /docs/smoketest.md gets copied into that versions build (for v0.8 and forward)
related:
https://github.com/knative/website/pull/71
https://github.com/knative/website/pull/63
https://github.com/knative/website/pull/74
Replaces #1643 
Staged previews:
https://prstaging--knative-v1.netlify.com/docs/smoketest/
> Create smoke test pages (for testing site elements)

- docs/install/Knative-with-Ambassador.md
Ambassador requires Knative be installed in the cluster before it can run. The current ordering causes Ambassador to fail to start
Signed-off-by: nbkrause <krausenoah@gmail.com>
- Reorder the install steps so Ambassador is installed after Knative
-
-
> Fix the order that Knative is installed in.

- docs/install/Knative-with-ICP.md
Fixes https://github.com/knative/docs/issues/1655
Delete the content of `knative build` in `docs/install/Knative-with-ICP.md`
> Delete knative build in the doc for 0.8 version

- docs/eventing/debugging/README.md
- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/iot-core/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/installing-logging-metrics-traces.md
- docs/serving/using-auto-tls.md
Update all install commands to use the `version` shortcode (https://github.com/knative/website/pull/71) so that version numbers are automatically added (defaults to 0.lastest-release.0).
Future install commands will be unnecessary unless manually add a patch release version number, in which case you can append `patch=#.#.#` to the `version` shortcode (where #.#.# are any integers - details in https://github.com/knative/website/pull/71)
**Staged preview: https://prstaging--knative-v1.netlify.com/docs/install/**
> v0.8 - Convert all install cmds to dynamically use version (at site build time)

- community/samples/serving/helloworld-java-quarkus/README.md
- docs/eventing/samples/container-source/README.md
- docs/serving/samples/autoscale-go/README.md
- docs/serving/samples/gitwebhook-go/README.md
- docs/serving/samples/grpc-ping-go/README.md
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-java-spark/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-scala/README.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/secrets-go/README.md
Update all `git clone` commands to use the `branch` shortcode (https://github.com/knative/website/pull/74) so that branch names are automatically added at site build time. (this makes the need for future command updates unnecessary)
**Staged preview: https://prstaging--knative-v1.netlify.com/docs/serving/samples/**
> v0.8 - convert git clone cmds to use dynamic variables

- docs/reference/eventing/eventing-contrib-resources.md
- docs/reference/eventing/eventing.md
- hack/gen-api-reference-docs.sh
- hack/reference-docs-gen-config.json
```
cd hack
KNATIVE_EVENTING_COMMIT=v0.8.0 KNATIVE_EVENTING_RESOURCES_COMMIT=v0.8.0 KNATIVE_SERVING_COMMIT=v0.8.0 ./gen-api-reference-docs.sh
```
Per [knative/serving release notes](https://github.com/knative/serving/releases) bumped k8s api version up to 1.14
KNOWN ISSUE: https://github.com/knative/docs/issues/1661
> v0.8 API ref docs and updated build scripts

- docs/serving/samples/rest-api-go/README.md
Knative Build has been deprecated.
Related: https://github.com/knative/docs/pull/1656
> remove mention of Knative Build as an option

- docs/install/Knative-with-GKE.md
Double-backslash breaks copy and pasted instructions for install.
> Fix line continuation

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/using-auto-tls.md
fixes: #1614 
the cert-manager controller is no longer installed by default
Related UX issue: https://github.com/knative/serving/issues/4120
> remove cert-manager from serving install

- docs/serving/samples/knative-routing-go/routing.yaml
When having TLS termination in a Gateway, this example stops working because the gateway doesn't know what to do with HTTP traffic on port 443. Fixing the port to 80 solved this for me.
- Added port number to routing example
> Add port number to route example

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-any-k8s.md
- Replace eventing.yaml with release.yaml in the install instructions to have a fully working system with InMemoryChannel installed.
> Replace eventing.yaml with release.yaml in the install instructions

- docs/serving/configuring-the-autoscaler.md
We definitely need more data there and document with more examples.
But this is for another PR.
/assign @samodell @RichieEscarez
> Add/fix some documentation for the autoscaler configuration.

- docs/eventing/samples/container-source/README.md
Fixes #1725 
```
-ko publish github.com/knative/eventing-contrib/cmd/heartbeats
+ko publish knative.dev/eventing-contrib/cmd/heartbeats
```
> [container source] Fix the docs to point to correct 'ko publish' command

- docs/serving/knative-kubernetes-services.md
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/rest-api-go/sample-template.yaml
directory confusion missing readinessProbe config
readinessProbe requires timeoutSeconds and failureThreshold are required
Fixes #1731
-
-
-
> directory confusion missing readinessProbe config

- docs/serving/samples/secrets-go/README.md
Fixes #1744
- Change `GOOGLE_APPLICATION_DEFAULT` to `GOOGLE_APPLICATION_CREDENTIALS` as per the GCP documentation https://cloud.google.com/docs/authentication/getting-started
> Secrets use GOOGLE_APPLICATION_CREDENTIALS as key

- OWNERS_ALIASES
I would like to have approval permission to help triage Serving API
related samples and PRs (docs/serving).
/cc @mattmoor @samodell
-
-
-
> Add dgerd to eng-approvers

- docs/install/Knative-with-Gloo.md
- docs/install/README.md
- docs/serving/using-auto-tls.md
* update gloo install guide for 0.18.x
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* fix comments, gloo supports tls
* move blocks
* Update docs/install/README.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: RichieEscarez <rescarez@google.com>
* Update docs/install/Knative-with-Gloo.md
Co-Authored-By: …
> release-0.8 cherrypick: update gloo install guide for knative serving 0.8.0 (#1691)

- docs/eventing/README.md
Currently, the Eventing README states that Eventing requires Istio 1.0 or greater. Eventing 0.7 and greater have been tested to wrok with Gloo >=v0.18.16 
- Update the Eventing README to mention Eventing support offered by Gloo
> update note on eventing dependency

- docs/serving/knative-kubernetes-services.md
Please refer to https://knative.dev/docs/serving/knative-kubernetes-services/ in ` 3. To view the deployments in your cluster, use the following command`. It has a broken format.
- Remove extra spaces to correct format
> Remove extra spaces to correct format

- docs/eventing/README.md
Fixes https://github.com/knative/docs/issues/1780
- kafka source link is broken so change to another location
> Fix broken kafka source link

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
Fixes #1771
- Fixes broken links for AWS SQS, GCP PubSub, and GitHub in Eventing Sources.
- The problem was that the files were moved out of eventing-contrib/contrib to eventing-contrib/
- The gcppubsub directory isn't in the [eventing-contrib master branch](https://github.com/knative/eventing-contrib/tree/master), so I had to hardcode in the `release-0.8` branch into the URL. I expect this is not ideal, but I'm not sure what would be better.
> fix event sources broken links because of migration

- docs/install/Knative-custom-install.md
- docs/reference/eventing/eventing.md
related to https://github.com/knative/eventing/pull/1882
- Use the term source.
- Use the new kafka release file.
> Use the term source.

- docs/serving/samples/hello-world/helloworld-go/Dockerfile
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-go/go.mod
- test/sampleapp/config.yaml
First step toward #1686 
- Upgrades from go 1.12 to go 1.13
- Upgrades to use go modules
- Pins alpine image to 3.10
- Tweaks working directory to /app
- Rename binary in container from `helloworld` to `server`
- Use `go mod download` to facilitate a layer cache of go deps.
- Use `-mod=readonly` flag on builds for strictness of container builds
- Some minor style changes around syntax and comments
> serving/samples: update helloworld-go to go:1.13 and go modules

- docs/eventing/README.md
Currently, the Eventing README states that Eventing requires Istio 1.0 or greater. Eventing 0.7 and greater have been tested to wrok with Gloo >=v0.18.16 
- Update the Eventing README to mention Eventing support offered by Gloo
> Note: This change has already been merged to `master` in #1795
> update note on eventing dependency (0.8.0 release) 

- docs/serving/using-a-custom-domain.md
The current documentation is confusing because it does not show the contents of the default configmap: https://github.com/knative/serving/blob/master/config/config-domain.yaml
The default configmap has an additional `_example` key in front of the domain.
- Use default configmap in custom-domain documentation
> Make updating custom-domain configmap clearer

- docs/serving/samples/knative-routing-go/README.md
Fix a wrong indentation at knative routing go sample documentation.
> fix a wrong indentation at knative routing go sample docs

- docs/serving/samples/traffic-splitting/README.md
- The path is wrong, since doc let user enter `cd $GOPATH/src/github.com/knative/docs` firstly, then the correct path should be `docs/serving/samples/traffic-splitting` rather than `serving/samples/traffic-splitting`
- The attribute should be `tag`, not `name`
> Correct path and attributes

- docs/serving/configuring-the-autoscaler.md
- This patch moves `autoscaling.knative.dev/{minScale,maxScale}` to `spec.template.metadata.annotations`, where is correct settings.
You can refer to https://github.com/knative/serving/blob/master/docs/scaling/README.md as well.
> Move scale bounds settings to annotation field

- docs/serving/getting-started-knative-app.md
Fixes Markdown formatting. Without this fix, the "Take note of the..." sentence and the following sentence are rendered as code.
> remove erroneous extra backtick

- docs/serving/getting-started-knative-app.md
- Fix invalid markdown format in Getting Started with App Deployment.
Please refer to the code block in under the `The command will return something similar to this:` in
https://knative.dev/docs/serving/getting-started-knative-app/#interacting-with-your-app The format is broken because of extra "`".
> Fix invalid format in Getting Started with App Deployment

- docs/install/Knative-with-Gloo.md
/assign @tcnghia 
/assign @ilackarms 
This is a precursor to cleaning up all of the `curl -H 'Host: ...'` stuff in samples, which is very Istio specific.
> Document xip.io with Gloo.

- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-elixir/README.md
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-java-micronaut/README.md
- community/samples/serving/helloworld-java-quarkus/README.md
- community/samples/serving/helloworld-r/README.md
- community/samples/serving/helloworld-rserver/README.md
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-vertx/README.md
- docs/eventing/samples/container-source/README.md
- docs/serving/getting-started-knative-app.md
- docs/serving/samples/autoscale-go/README.md
- docs/serving/samples/blue-green-deployment.md
- docs/serving/samples/grpc-ping-go/README.md
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-java-spark/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-scala/README.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/rest-api-go/README.md
- docs/serving/samples/secrets-go/README.md
- docs/serving/samples/telemetry-go/README.md
This builds on these changes to allow us to drop the manual gateway resolution from our samples:
https://github.com/knative/docs/pull/1839
https://github.com/knative/docs/pull/1840
https://github.com/knative/docs/pull/1841
The expectation is that samples are run in an environment with DNS suitably configured, even if
that is simply `xip.io` for development.
> Drop the manual gateway resolution from samples.

- docs/eventing/samples/kafka/README.md
- docs/eventing/samples/kafka/_index.md
- docs/eventing/samples/kafka/channel/000-ksvc.yaml
- docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kafka/channel/030-trigger.yaml
- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-display.yaml
- docs/eventing/samples/kafka/source/event-source.yaml
- docs/eventing/samples/kafka/source/kafka-topic.yaml
Adding Apache Kafka docs and samples for the `KafkaChannel` and the `KafkaSource`
@RichieEscarez @samodell @joaedwar 
This PR is based on top of https://github.com/knative/eventing-contrib/pull/548  which moves the _existing_ source-example here.
In addition to that I also add a channel based example
> Apache kafka

- docs/eventing/samples/kafka/README.md
- docs/eventing/samples/kafka/_index.md
- docs/eventing/samples/kafka/channel/000-ksvc.yaml
- docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kafka/channel/030-trigger.yaml
- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-display.yaml
- docs/eventing/samples/kafka/source/event-source.yaml
- docs/eventing/samples/kafka/source/kafka-topic.yaml
https://github.com/knative/docs/issues/1865
- Cherry-picked kafka docs to 0.9
```
(base) aslom@m docs (release-0.9) $ git cherry-pick 69b071c47d359c3cebc070c2887af62d9924d591
[release-0.9 8dbd3bd] Apache kafka (#1712)
Author: Matthias Wessendorf <mwessend@redhat.com>
Date: Fri Oct 4 22:17:07 2019 +0200
11 files changed, 573 insertions(+)
create mode 100644 docs/eventing/samples/kafka/README.md
create mode 100644 docs/eventing/samples/kafka/_index.md
create mode 100644 docs/eventing/samples/kafka/channel/000-ksvc.yaml
create mode 100644 docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
create mode 100644 docs/eventing/samples/kafka/channel/020-k8s-events.yaml
create mode 100644 docs/eventing/samples/kafka/channel/030-trigger.yaml
create mode 100644 …
```
> Cherry-picked kafka docs to 0.9

- docs/install/installing-istio.md
We used to recommend deploying only a single instance of Envoy per ingress Gateway because we had no visibility on when they would be ready. This is not true anymore since we probe them now.
Also, set the max to 2 to show it is possible.
A user got confused and asked about it in this [issue](https://github.com/knative/serving/issues/5766).
> Remove comment about limitation that doesn't exist anymore

- docs/install/Knative-with-Gardener.md
The use of `knative-ingressgateway` is deprecated in Knative v0.3.x.
Use `istio-ingressgateway` instead, since `knative-ingressgateway`
will be removed in Knative v0.4.
> Use istio-ingressgateway in docs

- docs/install/Knative-custom-install.md
Fixes  https://github.com/knative/eventing/issues/2024
- change incorrect filename from in-memory-channel-crd.yaml to in-memory-channel.yaml
-
-
> fix incorrect link in-memory-channel-crd.yaml => in-memory-channel.yaml

- docs/eventing/getting-started.md
FIxes https://github.com/knative/eventing/issues/2026
- Remove references to in-memory-channel-* pods and do not talk about provisioner.
> remove references to in-memory-channel-*

- docs/serving/samples/hello-world/helloworld-java-spark/README.md
> Eallred google patch 1

- docs/eventing/samples/container-source/README.md
- docs/eventing/samples/container-source/heartbeats-source.yaml
- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/github-source/README.md
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-source.yaml
- docs/eventing/samples/kafka/source/kafka-topic.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
@nachocano  I update some docs, including CloudEvent 0.3 and updating some other forgotten "version bumps"
> Version updates and CE update

- docs/serving/configuring-the-autoscaler.md
The original autoscale example misses annotations
Fixes #1900
-
-
-
> Add annotatios in autoscale example

- docs/serving/samples/hello-world/helloworld-go/Dockerfile
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-go/helloworld.go
- docs/serving/samples/hello-world/helloworld-shell/Dockerfile
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/hello-world/helloworld-shell/go.mod
- docs/serving/samples/hello-world/helloworld-shell/invoke.go
- test/sampleapp/config.yaml
This is another step towards #1686
- Minor clarity and log output improvements to helloworld-go
- Update the go pieces of helloworld-shell to align with helloworld-go
* I tested these changes locally.
* I do not anticipate any platform-specific impacts from these changes.
> helloworld: go clarity tweaks and go modules for shell

- docs/eventing/debugging/example.yaml
Fix the Subscription's apiVersion in eventing debugging example.yaml file.
According to the api register in `https://github.com/knative/eventing/tree/master/pkg/apis/messaging`. 
The Subscription Kind should be in `messaging.knative.dev/v1alpha1`, while the original file is `eventing.knative.dev/v1alpha1`.
If apply the original file, the error happened `error: unable to recognize "example.yaml": no matches for kind "Subscription" in version "eventing.knative.dev/v1alpha1"`
This update fix this bug.
Fixes #1913 
- Change the apiVersion of Subscription Kind into `messaging.knative.dev/v1alpha1` in example.yaml line 43 https://github.com/knative/docs/blob/release-0.9/docs/eventing/debugging/example.yaml#L43.
> Fix the Subscription's apiVersion in debugging.

- docs/serving/configuring-the-autoscaler.md
Using `autoscaling.knative.dev/metric: concurrency`
made no sense to me so I'm doing a quick PR.
An example of this can be found at https://medium.com/@mchmarny_google/https-medium-com-p-knative-autoscaling-love-story-e32a27b7855
but let's not try to send people to external links to find how to do this.
> Use cpu metric for CPU-based autoscaling sample

- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
> Fixing links

- docs/reference/eventing/eventing-contrib.md
New API docs build for eventing-contrib.
`KNATIVE_EVENTING_CONTRIB_COMMIT=v0.10.0 ./gen-api-reference-docs.sh`
Serving and Eventing are still blocked by #1661
> update eventing-contrib api for v0.10

- docs/build/README.md
- docs/build/_index.md
removing this unnecessary folder and redirect for the deprecated build content
(also see dependent https://github.com/knative/website/pull/99)
> remove build folder for good

- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/gcp-pubsub-source/event-display.yaml
- docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
- docs/eventing/samples/gcp-pubsub-source/trigger.yaml
- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
Fixes https://github.com/knative/docs/issues/1814
Fixes https://github.com/knative/docs/issues/1905
Fixes https://github.com/knative/docs/issues/1843
Fixes https://github.com/knative/docs/issues/1262
Fixes https://github.com/knative/docs/issues/1885
Helps with https://github.com/knative/docs/issues/1750
- Updating PubSub source example to use newer knative-gcp stuff. 
- We should later on revisit whether this documentation should lie here or somewhere else. For now, given that this is published in the knative.dev website, I've decided to put it here.
- Fix old links in others places. Regenerated files...
> Fixing PubSub source example

- test/presubmit-link-check.sh
Run markdown_build_tests directly to:
* fix readonly var warning
* skip unnecessary tests
/cc @RichieEscarez
> Fix presubmit-link-check.sh

- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-java-micronaut/README.md
- community/samples/serving/helloworld-java-quarkus/README.md
- community/samples/serving/helloworld-r/README.md
- community/samples/serving/helloworld-rserver/README.md
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-vertx/README.md
- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-java-spark/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/secrets-go/README.md
While going through the sample docs I noticed a small typo that I then noticed had propagated to other READMEs as well. 
- change `the with URL` to `with the URL`
> fix small typo in sample READMEs

- docs/serving/spec/knative-api-specification-1.0.md
Fixes #1960
- Add field imagePullSecrets to serving docs
> Add field imagePullSecrets

- docs/README.md
- docs/serving/configuring-autoscaling.md
- Renamed section to make it more general for Autoscaling docs
- Added details for BYO autoscaler (using PodAutoscaler custom resource)
Fixes issue #1892
> Renamed autoscaling section, added details for PodAutoscaler custom resource

- docs/eventing/README.md
- docs/eventing/samples/parallel/README.md
- docs/eventing/samples/parallel/multiple-branches/README.md
- docs/eventing/samples/parallel/multiple-branches/cron-source.yaml
- docs/eventing/samples/parallel/multiple-branches/parallel.yaml
- docs/eventing/samples/parallel/mutual-exclusivity/README.md
- docs/eventing/samples/parallel/mutual-exclusivity/cron-source.yaml
- docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/cron-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/steps.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/cron-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/steps.yaml
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/cron-source.yaml
- docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
- docs/eventing/samples/sequence/sequence-terminal/steps.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/cron-source.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
Fixes #1977
- Update examples for sequence/parallel to use flows.knative.dev instead of messaging.knative.dev
- Add a pointer and a blurp about sequence/parallel to main Eventing Readme for easier discoverability.
- update cronjobsource specs to reflect new Sink format (v1.destination duck).
> Issue 1977

- docs/serving/configuring-autoscaling.md
Fixes #1980 
- where it makes sense, changed 'reconciler' to 'controller'
- added links for reconciler and controller docs to introduction paragraphs
> Updated docs for reconciler / controllers in autoscaling

- docs/install/check-install-version.md
1. Change to a command that returns just the release version
2. Move current methods of querying to the top of the page
3. Combine old methods into a single section
* Describe old steps rather than walk through as we expect very few
people to be running these older versions.
> Cleanup Knative install versions page

- docs/reference/eventing/eventing.md
- docs/reference/serving.md
fixes #1962
Added the dynamic variables in these temp files while the "API ref docs tool" is still not working but forgot that these reference files are "ignored" (to avoid build errors with the HTML thats normally here when the "API ref docs tool" is working.)
> fix links to repos in temp API refdocs files

- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-csharp/service.yaml
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-go/service.yaml
- docs/serving/samples/hello-world/helloworld-java-spark/README.md
- docs/serving/samples/hello-world/helloworld-java-spark/service.yaml
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/service.yaml
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/service.yaml
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/service.yaml
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-php/service.yaml
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-python/service.yaml
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-ruby/service.yaml
- docs/serving/samples/hello-world/helloworld-scala/README.md
- docs/serving/samples/hello-world/helloworld-scala/helloworld-scala.yaml
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/hello-world/helloworld-shell/service.yaml
Remove the namespace definition from the service.yaml in each of the helloworld-*
samples.
Specifying the namespace in service.yaml expects there to exist a namespace with
the specified name, in this case 'default'.  When namespace is unspecified, the
service.yaml will default to using the namespace specified in the default $KUBECONFIG.
> Remove namespace definition from hello-world service.yaml

- docs/serving/services/creating-services.md
- Added _Creating Knative Services_ section
@RichieEscarez this should replace some of the work previously done in #1972 - I think there was some confusion about that PR because the scope wasn't necessarily supposed to be creating a service so much as collecting all the information about services and organizing it.
This new section should be inline with the plans in the nav doc though, I will address the other sections related to services (e.g. cluster local) in subsequent PRs so that I can keep the scope smaller and avoid confusion.
> Added 'Creating Knative Services' section

- test/presubmit-link-check.sh
This will allow cherry-picks to the release-0.10 branch to benefit from the link checker job.
/cc @RichieEscarez
> [release-0.10] Cherry-pick presubmit link checker tool

- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-source.yaml
- updates for 0.10 for kafka doc
-
-
> updates for kafka based on 0.10.x release

- docs/eventing/debugging/README.md
- docs/eventing/samples/parallel/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-MicroK8s.md
- docs/install/Knative-with-any-k8s.md
- docs/install/check-install-version.md
- docs/serving/debugging-application-issues.md
- docs/serving/services/_index.md
- docs/serving/services/creating-services.md
- docs/serving/using-a-custom-domain.md
- docs/serving/using-auto-tls.md
- docs/serving/using-cert-manager-on-gcp.md
> Removing old versions from docs

- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/heartbeats-source.yaml
- docs/eventing/samples/sinkbinding/service.yaml
- docs/eventing/samples/sinkbinding/sinkbinding.yaml
This is largely derived from the ContainerSource docs, but
using SinkBinding and a CronJob.
/hold
This needs the following related PRs to land:
- https://github.com/knative/pkg/pull/915
- https://github.com/knative/eventing/pull/2234
- https://github.com/knative/eventing-contrib/pull/766
> Add a SinkBinding sample.

- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
- Updating PubSub example due to change in Destination
> Updating PubSub example due to change in Destination

- docs/install/installing-istio.md
Fixes https://github.com/knative/serving/issues/6118
Update documentation to reflect the fact that
- 1.2.x has been dropped: https://github.com/knative/serving/pull/6110
- 1.3.5 is the new recommended version: https://github.com/knative/serving/pull/6021
> Update default Istio version to 1.3.5

- docs/install/Knative-custom-install.md
* Reduce verbosity
* Remove reference to closed issues
* Remove reference to Knative Serving 0.3 upgrades
* Use bash variable syntax in code snippets
> Update Custom Knative Installation page

- docs/install/README.md
I don't remember exactly when this became true, but Eventing hasn't required Istio for several releases.
- Remove sentence asserting that eventing requires Istio
/cc @rgregg
> Eventing doesn't require Istio

- docs/samples.md
KnFun is a complete example of three functions used to demonstrate serverless and Knative and its client: kn.
- adds a link to KnFun example
> added knfun as external code

- docs/serving/README.md
the resource url is out of date.
> update service resource spec url

- docs/eventing/event-delivery.md
Fixes #1952
- add event delivery section
> initial delivery options doc

- docs/serving/deploying/private-registry.md
The IBM version of how to use a private registry were deleted when Knative build was deprecated.
This is a new non-host specific task about how to create a secret and use it to access a private container registry.
> How to use a private registry

- hack/gen-api-reference-docs.sh
The API reference docs were failing to generate because they didn't
account for the change from github.com/knative/serving to
knative.dev/serving and similar for the eventing and eventing-contrib
repos.
> Adjust API reference docs scripts for knative.dev

- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/event-display.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/steps.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/event-display.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/steps.yaml
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/steps.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
- I moved the example code from vaikas/transformer to knative/eventing-contrib, so update docs
- Use the newly released artifact from knative/eventing-contrib releases
- Update event-display container to use shorter vanity name.
> update examples to use new image locations

- docs/eventing/channels/README.md
- docs/eventing/event-registry.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
- Change deprecated sourceAndType Trigger examples to use attributes
- Fix one broken link.
-
> update samples to not use deprecated fields in triggers

- docs/eventing/getting-started.md
Fixes #2023 
- Update wording to reflect what's actually happening during install (the guide doesn't actually need to install Eventing sources; the install is just split into two steps so that the CRDs are installed first and then everything else is installed on the second pass)
- Update formatting to add whitespace and use automatic numbering
> Fix wording to address bug #2023 plus small formatting updates

- docs/install/installing-istio.md
The docs uses default template (`install/kubernetes/helm/istio/values.yaml`) which enables mtls by
default on Istio-1.4+. It causes some problem like https://github.com/knative/serving/issues/6254.
So, this patch sets `global.mtls.auto` to `false` for istio-lean and
clsuter-local-gateway installation.
Fixes https://github.com/knative/serving/issues/6254
cc @ahmetb @tcnghia
> Set global.mtls.auto to false for istio-lean and clsuter-local-gateway

- test/presubmit-tests.sh
Issues #66 and #67 are now closed.
> Remove outdated TODOs

- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/installing-istio.md
In other news, I was able to install Istio + Knative using Docker-for-Mac within a fairly small footprint. I think the actual size is closer to 2GB of RAM, but I left it at 6GB to have a margin for error.
- Reduce resource requirements for Docker-for-Mac
- Don't suggest that Docker-for-Mac use the cloud provider's Istio.
- Don't use a NodePort with Docker-for-Mac, because it's not needed.
- Istio was referred to as "Gloo" at one point.
> Update and simplify a few install docs

- docs/install/Knative-with-Ambassador.md
Fixes https://github.com/datawire/ambassador/issues/1871
This commit installs Ambassador using ambassador-rbac.yaml instead
of ambassador-knative.yaml which will be deprecated soon.
ambassador-rbac.yaml contains the latest Ambassador install
manifests which have sufficient RBAC to update ingress resources
when required. ambassador-knative.yaml does not have these
permissions and hence Ambassador panics for anyone who follows
the instructions.
> Fix Ambassador install instructions to avoid panic

- docs/install/Knative-with-Gloo.md
It seems that the `glooctl` changed and doesn't require prefixing the command with `--`.
> call version with using '--'

- docs/serving/samples/telemetry-go/README.md
The README.md mentioned `ksvc`, there is no `ksvc` in this sample, should check `Route`
> correct the README.md of docs/serving/samples/telemetry-go

- docs/eventing/samples/github-source/README.md
Fixes #2092 
- In the Github source example, add a step that installs the Github Source CRD.
-
-
> Add a step for installing github source

- docs/eventing/debugging/example.yaml
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
Pending on https://github.com/knative/eventing/pull/2368
Related to https://github.com/knative/eventing/issues/1500
- ApiServerSource is moving the ApiGroup it lives in: `sources.eventing.knative.dev` becomes `sources.knative.dev`.
> Use the new api group for ApiServerSource.

- docs/eventing/getting-started.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
Fixes https://github.com/knative/eventing/issues/1987
Eventing PR: https://github.com/knative/eventing/pull/2382
-
-
-
> Rename eventing release artifacts release.yaml => eventing.yaml

- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
The original image path is not work, will make the `Revision` failed and raise `container missing` error.
> Correct image path in sample of "kubernetes-event-source"

- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/sinkbinding.yaml
Pending on https://github.com/knative/eventing/pull/2369
Related to https://github.com/knative/eventing/issues/1500
- SinkBinding is moving the ApiGroup it lives in: `sources.eventing.knative.dev` becomes `sources.knative.dev`.
> Use the new api group for SinkBinding.

- docs/install/Knative-with-Gloo.md
- Update shell `glooctl install knative`, the previous one only install
knative-serving.
- Update outdated url.
> Update knative install using Gloo

- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
The doc should not go with a specific version, they should use LATEST release.
/cc @abrennan89
> Updating to LATEST for Kafka Channel/Source

- docs/install/README.md
- docs/install/knative-with-kourier.md
- Adds a new installation guide for Knative with Kourier
Related to: https://github.com/knative/serving/issues/5982
> Kourier Installation guide for Knative Serving

- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
- docs/install/README.md
- docs/install/knative-with-kourier.md
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/using-auto-tls.md
Cherry-pick batch for January 23rd. (From this point on, cherry-picks will be done in a batch weekly on Thursday.)
Adding cla: yes label because all these commits were previously submitted to master.
> Release 0.12

- docs/eventing/samples/kafka/channel/000-ksvc.yaml
- docs/eventing/samples/kafka/channel/README.md
Fixes #2134 
- Set numPartitions and replicationFactor in the default Channel template spec. 
- Use a newer version of Event Display. The one in the instructions fails to decode the incoming message.
-
> fix default template so it works, use event display that works

- community/samples/README.md
Fixes #2131
- create new `kn` client section in community samples
- add [knfun](https://github.com/maximilien/knfun) to the community samples
> added github.com/maximilien/knfun as a Knative client demo sample

- docs/install/Knative-with-Contour.md
The edit command requires a type, in this case `configmap`.
> Fix missing type in edit command

- docs/eventing/samples/kafka/source/event-display.yaml
Fixes #2147 
- Update the event-display yaml to correct format, update container image.
-
-
> fix the service yaml, update image

- docs/install/Knative-with-Gloo.md
This has been deprecated in favor of tekton pipelines, and is no longer installed with gloo. See https://github.com/solo-io/gloo/blob/master/docs/content/cli/glooctl_install_knative.md.
> Remove mention of Knative Build in Gloo docs

- docs/install/Knative-with-any-k8s.md
This attempts to consolidate our install instructions into a single source of truth.
/assign @samodell 
Networking bits: cc @ilackarms @tcnghia @concaf @bbrowning 
Eventing bits: cc @vaikas @lionelvillard 
General: @rgregg @duglin @pmorie 
This depends on: https://github.com/knative/website/pull/124
This links to the WIP: https://github.com/knative/docs/pull/2150
/hold
As this needs a number of eyeballs on it...
For those who haven't been following along the tabs saga, here's roughly how it looks in hugo locally:
> An update to the install instructions that make use of tabbing.

- docs/install/install-kn.md
As this is today, things don't look very good:
> Fix the CLI installation headings

- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- the `README` talk about the Broker, but the yaml used `ksvc`, which is wrong
> The yaml was not matching the text in the README

- docs/eventing/samples/container-source/README.md
- docs/eventing/samples/container-source/heartbeats-source.yaml
- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/cronjob-source/cronjob-source.yaml
Most examples are already using the Destination API syntax, like:
```yaml
...
sink:
ref:
apiVersion: serving.knative.dev/v1
kind: Service
name: event-display
```
but some examples did actually lack those :disappointed:  
This PR fixes this.... 
as well as using `apiVersion: serving.knative.dev/v1` instead of `apiVersion: serving.knative.dev/v1alpha1`  this
> Using Destination API on source examples

- docs/install/knative-with-any-k8s.md
See also: https://github.com/knative/eventing/pull/2519
/assign @vaikas
> Reflect the separation of the Channel-based Broker.

- docs/eventing/samples/github-source/README.md
- docs/eventing/samples/github-source/github-source.yaml
See https://github.com/knative/eventing-contrib/issues/894
/assing @nachocano 
I've updated the apiGroup for the GH source in the sample doc
> The github source was moved to sources.knative.dev APIgroup

- docs/install/Knative-with-Contour.md
- Add missing configmap command
- `kubectl edit --namespace knative-serving config-network` to `kubectl edit --namespace knative-serving configmap/config-network`
> (bug-fix): Add missing configmap command

- docs/install/knative-with-any-k8s.md
usage of Apache for Caamel-K and kafka, to reflect better the offical names/trademarks (Apache Kafka != Kafka)
> Apache Camel-K/Kafka usage, instead of just Camel/Kafka

- docs/eventing/event-delivery.md
- docs/reference/serving.md
- docs/serving/configuring-autoscaling.md
- docs/serving/samples/telemetry-go/telemetrysample.go
liinks to godoc seem to be deprecated.
See
> Pkg.go.dev is a new destination for Go discovery & docs. Check it out at pkg.go.dev/knative.dev/pkg/apis/duck/v1 and share your feedback.
warning on their site 
/assing @mattmoor 
/assign @samodell
> Godoc seem seems to go away

- docs/concepts/resources.md
knctl doesn't seem to be developed anymore (latest serving dependency: 0.2.1, latest commit: May 2019).
I think its fair to remove it from this page to not mislead potential users
(or at least don't call it 'under active development')
@cppforlife I hope this is ok for you. You did an awesome job to kick off the idea for a Knative client and you paved the way to `kn`. However, I think it would be a bit confusing for people if we give them the choice between `kn` and `knctl`. Please let me know if I'm wrong and you are planning to continue to work on `knctl`.
Thanks !
In general I question the value of the overall page is can be removed completely IMO.
> chore(resources): Remove link to knctl

- docs/eventing/getting-started.md
- docs/install/knative-with-any-k8s.md
- docs/serving/installing-logging-metrics-traces.md
I'm introducing this here: https://github.com/knative/website/pull/129 with the intention of enabling us to make the Pre-release pages show nightly builds, which are hosted completely differently.
/hold
Until the website PR merges.
> This adopts the "artifact" shortcode.

- docs/install/knative-with-any-k8s.md
based on changes from #2193 - let's get that in first!
/assign @mattmoor 
A couple of thoughts....  
Should we separate this into three different aspects? 
* Broker enablement (well, atm there is just one, but we could show the install of a custom one, w/o the labeling?
* Full dedicated section on Sources _and_ one that covers channels.
Currently we mix all in one, but as soon we have more content there, it might be better to separate things!  Happy to help on that.
> Apache Kafka channel install

- docs/eventing/samples/kafka/source/README.md
- The `KafkaSource` does use 1.0 compliant events since a while. Updating the doc to reflect proper usage of `source`, `subject` and `datacontenttype` attributes.
> Updating to CloudEvent 1.0 compliant events

- docs/eventing/samples/sinkbinding/README.md
- Document the addition of CloudEvents Overrides from SinkBinding.
Related to https://github.com/knative/eventing/pull/2481
> Update docs to talk about CloudEvents Overrides

- docs/install/knative-with-any-k8s.md
I noticed that the link for serving code examples is actually linking to the eventing examples page. Have changed it to reflect the correct link.
> Updated serving code examples link

- docs/install/knative-with-any-k8s.md
In the docs it currently says "You can find a number of sample on how to get started with Knative Eventing here." 
This is confusing as it talks about both a link to samples and getting started (which are two different pages). Also, the existing link is to the general Knative Eventing overview. I have tried to make it more explicit.
> Update Knative Eventing sample link

- docs/eventing/README.md
- docs/eventing/getting-started.md
- docs/eventing/samples/kubernetes-event-source/README.md
- Consistent use of API Server Source instead of Kubernetes Events Source
- Add warning about Minikube
> improving eventing doc (?)

- .github/pull-request-template.md
Fixes old, confusing instructions that tell users to open PRs against the release branches
- Removes guidance about contributing directly to release branches
- Adds more prompting to describe what the PR does and why
> Update template to avoid branch confusion

- docs/install/knative-with-any-k8s.md
Fixes https://github.com/knative/eventing-contrib/issues/895
Helps with https://github.com/knative/docs/issues/2153
- Adding PubSub channel to new installation docs
- @matzew do you know how {{< artifact repo="knative-gcp" file="cloud-run-events.yaml" >}} gets replaced? It will probably point somewhere else...
> Adding PubSub Channel

- docs/serving/samples/blue-green-deployment.md
This patch adds note for 0% of traffic for old revision.
Current non-routeable makes a few confusion like:
* Until when users should keep setting 0% traffic.
* With 0% traffic setting, the revision is not garbage collected.
Hence, this patch adds the note.
> Add note for 0% of traffic for obsolete revision

- docs/install/knative-with-any-k8s.md
- Removing google="org", as it's an invalid link. With google org the link ends up being: https://storage.googleapis.com/google-nightly/knative-gcp/latest/cloud-run-events.yaml, which doesn't exist. 
- The correct link is https://storage.googleapis.com/knative-nightly/knative-gcp/latest/cloud-run-events.yaml
/assign @samodell
> Fixing Google links

- docs/serving/README.md
- docs/serving/cluster-local-route.md
- docs/serving/using-subroutes.md
Add documentation detailing how subroutes are used.
Add documentation detailing how to set visibility of a route via k8s service.
This is documentation relevant to knative starting at v0.8.
I'm looking for guidance on how to make it better if anyone has improvement tips.
> Add documentation for subroutes and k8s service visibility tagging

- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/cronjob-source/service.yaml
Fixes #2145 
I changed image from gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display to gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display.
> Updated image reference for cron job source example.

- docs/eventing/samples/kafka/source/README.md
- Added documentation for `KafkaSource` new label introduced by https://github.com/knative/eventing-contrib/pull/860
> key deserializer doc for kafka source

- docs/eventing/samples/cloud-audit-logs-source/README.md
- docs/eventing/samples/cloud-pubsub-source/README.md
- docs/eventing/samples/cloud-scheduler-source/README.md
- docs/eventing/samples/cloud-storage-source/README.md
- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- docs/install/knative-with-any-k8s.md
- deleted duplicate cloud scheduler and cloud storage source
-
-
> deleted duplicate cloud scheduler and cloud storage source

- docs/client/connecting-kn-to-your-cluster.md
- docs/reference/client/README.md
- docs/reference/client/_index.md
Fixes #2046 
Added details about `kubeconfig` file requirements and links to docs for different platforms.
> Added section for connecting  to a cluster

- docs/install/install-kn.md
Fixes #2114 
- Updates in line with Sam's comments on PR #2045 
- Removed Go section since this is relevant for developers only
> Follow up updates to CLI install doc

- docs/knative-offerings.md
Migration of the [guide](https://knative.dev/docs/install/knative-with-gardener/) for installing knative on [Gardener](https://gardener.cloud) in response to the [notification](https://groups.google.com/forum/#!msg/knative-dev/3tZRnacsIQI/lLUF8ao7BAAJ) for repurposing the installation guide
Fixes the offerings section after migration of the guide to a Gardener-hosted location.
- Add a bullet with a link to the new location of the guide in the knative-offerings section
> Add Gardener to vendors list

- docs/eventing/broker-trigger.md
- docs/eventing/channel-based-broker.md
- docs/eventing/channels/default-channels.md
Addresses #2248 
- Update documents for Broker / Trigger for v1beta1.
- Add a more detailed section for Channel Based Broker and split out the installation from usage.
-
> Update docs to v1beta1 + add more details about channel based broker

- docs/install/any-kubernetes-cluster.md
Related: https://github.com/knative/docs/issues/2265
/assign @ellenevans @RichieEscarez
> Rename Monitoring bundle to Observability plugin.

- docs/eventing/samples/ping-source/README.md
- docs/eventing/samples/ping-source/ping-source.yaml
- docs/eventing/samples/ping-source/service.yaml
Dependent on https://github.com/knative/eventing/pull/2427
Document the renamed instructions for PingSource. Formally called CronJobSource.
> Make documentation for PingSource.

- docs/install/any-kubernetes-cluster.md
I must have missed this because the MD link checked is dying here: https://github.com/knative/serving/pull/7167
> Add a minishift redirect

- OWNERS_ALIASES
- docs/eventing/channels/OWNERS
- docs/eventing/sources/OWNERS
We noticed in https://github.com/knative/docs/pull/2285 that most eventing leads don't have eng approver on the eventing content areas.
I'm open to whatever approver layout makes sense to the most people, but here's a stab at it. This PR adds owner aliases for eventing WG leads, sources WG leads, and channels WG leads with these approver bits:
- Eventing WG leads approve docs/eventing
- Sources WG leads approve docs/eventing/sources
- Delivery (Channels) WG leads approve docs/eventing/channels
/cc @evankanderson
> Add leads of eventing WGs as area eng approvers

- docs/eventing/migration/README.md
- docs/eventing/migration/_index.md
- docs/eventing/migration/ping.md
- docs/eventing/migration/sinkbinding.md
- adding migrations for `PingSource`
- adding migration for `SinkBinding`
> Source migrations

- docs/eventing/broker-trigger.md
- docs/eventing/samples/ping-source/README.md
- docs/eventing/samples/ping-source/ping-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/ping-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml
- update doc to use `v1alpha2` of PingSource
> Updates on the PingSource

- docs/serving/deploying/private-registry.md
Fixes #2141 
- Added "docker-registry" to the secret creation based on K8s docs and the recommendation of the user
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
> Updated secret creation for private registries

- docs/install/README.md
- docs/install/knative-with-operators.md
Fixes #2260
The outline of this page can be found here: https://github.com/houshengbo/docs/blob/add-doc-operator/docs/install/knative-with-operators.md
- This PR adds the instruction on how to install and uninstall knative with operators.
> Add instruction in how to install Knative with Knative operators

- docs/install/README.md
- docs/install/knative-with-operators.md
Cherry-pick of 38dd475d66f712a9ed8f638ea6fa95af430f4122
* Add instruction in how to install Knative with Knative operators
* Fix the operators's doc based on comments
* Modify the docs of Operators to outline better
* Fixes the typos
> Add instruction in how to install Knative with Knative operators (#2261)

- docs/eventing/channel-based-broker.md
Removing pipe from KafkaChannel spec due to the following error on broker initialization:
- Failed to reconcile trigger channel: json: cannot unmarshal string into Go struct field Channelable.spec of type v1alpha1.ChannelableSpec
Which prevents the broker to initialize.
> Removing pipe from KafkaChannel spec

- docs/install/knative-with-operators.md
- Remove the additional title for operator installation guide.
- Correct the link to the `ko`.
> Remove the additional title for install knative using operators

- docs/serving/samples/cloudevents/cloudevents-go/Dockerfile
- docs/serving/samples/cloudevents/cloudevents-go/README.md
Looking for advice on this one. Should the go mod init and test go in the Dockerfile so the end user doesn't have to run it? This issue prob causes problems when trying to ko apply. I got an error using ko apply further down, but wasn't sure if it was due to the image not building. 
Also looking for help on wording if it could be worded in a better way. 
Fixes #2101 
- Added information about using go mod init to create the go.mod and go. sum files. Otherwise the docker build fails since it expects mod/sum files.
> Added go mod init so that docker can build

- docs/eventing/accessing-traces.md
- docs/eventing/broker-trigger.md
- docs/eventing/channel-based-broker.md
- docs/eventing/channels/_index.md
- docs/eventing/debugging/README.md
- docs/eventing/event-delivery.md
- docs/eventing/event-registry.md
- docs/eventing/samples/_index.md
- docs/eventing/sources/README.md
- Reorder eventing sections
| Old | New |
|---|---|
| Getting Started | Getting Started |
| Channels | Broker and Trigger |
| Eventing sources | Event registry |
| Broker and Trigger | Channel Based Broker |
| Channel Based Broker | Eventing sources |
| Flows | Eventing Flows |
| Migration | Migration |
| Event Delivery | Eventing channels |
| Event Registry | Event delivery |
| Accessing CloudEvent Traces | Debugging |
| Code samples | Accessing CloudEvent traces |
| Debugging | Code samples |
- Remove double-header on "Channel Based Broker"
/assign @vaikas @grantr
> Reorder eventing sections

- docs/install/any-kubernetes-cluster.md
Fixes #2314 
- Update broker configmap example to the new format.
-
-
> fix the broker configmap example

- docs/eventing/samples/kubernetes-event-source/README.md
- docs/install/any-kubernetes-cluster.md
Stepping through the installation guide, I ran into a mild pain point using Minikube and Gloo and/or Istio at the DNS stage. The Magic DNS solution couldn't be used, and the Real DNS method seems perhaps a little heavy-handed - creating DNS entries for what may be dynamically assigned IP addresses - for just getting a Hello, Word application running to see if a cluster is configured correctly.
Judging from issues raised and questions asked online, others were also caught up on this stage, so I suggest the following addition to reduce friction post-installation.
- The addition of another tab in the DNS section that explains how to use curl to specify the application when connecting to the external IP or CNAME. The rationale being most of the sample applications suggest using curl to …
> Remove DNS pain point for new users

- docs/eventing/broker-trigger.md
Fixes indentation of Service YAML in Documentation
File had incorrect indentation, which now has been corrected.
> Fixed indentation of Service YAML in Documentation

- docs/serving/samples/secrets-go/README.md
Fixes issues with old paths for samples. It's knative/docs/serving now.
- Adds docs/ to a path to fix a sample code example
> Updated secret sample path

- docs/serving/samples/autoscale-go/README.md
Fixes an invalid link and removes a Further Reading section.
- Removed further reading from autoscale-go sample as the link doesn't work - https://github.com/knative/serving/blob/master/docs/scaling/DEVELOPMENT.md <-- There doesn't look to be a scaling development.md file for serving in the repository. 
I'm wondering if this should instead point to:
https://github.com/knative/serving/blob/master/docs/scaling/SYSTEM.md
If we want to point to SYSTEM.md I can make the update in the PR, otherwise we probably want to remove the further reading section.
> Removed broken link in autoscale go sample

- docs/eventing/migration/ping.md
- docs/eventing/sources/README.md
- docs/eventing/sources/generator/main.go
- docs/eventing/sources/sources.yaml
> Cherry-pick #2296

- docs/reference/README.md
Should be https://github.com/knative/community/blob/master/docs/DOCS-CONTRIBUTING.md
-
-
-
> Updated link to contributor doc because broken

- docs/serving/debugging-application-issues.md
- docs/serving/samples/knative-routing-go/routing.yaml
- docs/serving/using-external-dns-on-gcp.md
Remote references to obsolete knative-ingressgateway
Fixes #1872
-  Remote references to obsolete knative-ingressgateway
-
-
> Remote references to obsolete knative-ingressgateway.

- docs/serving/using-auto-tls.md
* Update install link for gloo and contour.
* Update ClusterIssuer install link.
JUnit test error in `docs/serving/using-auto-tls.md`. Because of outdated  markdown link.
> Markdown link in using-auto-tls.md is outdated

- docs/eventing/README.md
Fixes #2337 
Fixed links on the sequence and parallel pages.
> Fixed links for Sequence and Parallel flows pages.

- docs/serving/accessing-traces.md
Hi there 👋 
As a user, I scanned the documentation and went directly to Zipkin instructions (`kubectl proxy`). It took me a while to figure out I needed to change the ConfigMap to enable the tracing backend.
This PR adds a more intuitive and explicit code block when describing the process to enable tracing.
> Add more explicit instruction block about enabling tracing

- docs/install/upgrade-installation.md
Fixes older links referencing version v0.10.0 and v0.11.0
- Changing older links so users can copy/paste the latest major release. This puts the links in line with the same version that shows up in the install docs. 
- Changed the eventing file from release.yaml to eventing.yaml since the release doesn't include a release.yaml. The eventing.yaml file had the same description as release.yaml in newer versions.
> Updated upgrade links to v0.13.0

- docs/serving/samples/hello-world/helloworld-python/Dockerfile
- docs/serving/samples/hello-world/helloworld-python/README.md
Based on the current entrypoint configuration, the gunicorn arbiter process has a set timeout. If for any reason this timeout is reached, error logs indicating a `[CRITICAL] WORKER TIMEOUT` are produced.
In practice, this timeout is not an essential part of server resource management and creates and is only an opportunity for distractions in the logs.
Per https://github.com/benoitc/gunicorn/issues/2291, gunicorn supports setting an unlimited timeout with `--timeout 0`.
- Add `--timeout 0` to Python container entrypoint.
> helloworld-python: Prevent "[CRITICAL] WORKER TIMEOUT" error log

- docs/serving/using-cert-manager-on-gcp.md
- Changed examples to show certificates and issuers using the latest cert manager version
> update cert manager version for using on gcp

- docs/install/installing-istio.md
Part of https://github.com/knative/serving/issues/7568
This patch updates Istio version to 1.4.6 which is tested CI and
stable version.
/cc @tcnghia
> Update Istio version to 1.4.6

- docs/eventing/samples/kafka/source/README.md
Fixes readability and matches serving docs where you will clone the docs first so that you are aware of where the files are. 
- add doc clone
- update paths
There is some additional cleanup that might be needed since this file doesn't actually exist now - strimzi-topic.yaml. If needed I can take the yaml from the docs and add it as a file in the sample/source folder. 
Also, not sure if we want to move the clone further up. I added it where you start applying files.
> Added clone of docs to steps and updated paths

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- Switch the status of TriggerMesh external sources to "supported" since we now offer support.
> Switch support status for triggermesh external sources

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- docs/install/any-kubernetes-cluster.md
Add the install/sample links to the Knative installation instructions.
> This documents the VMware sources for Knative.

- docs/install/any-kubernetes-cluster.md
This is blocked on net-kourier actually having a successful nightly, which should be unblocked by: https://github.com/knative/net-kourier/pull/31
> Switch net-kourier to use the artifact shortcode.

- docs/install/knative-with-operators.md
- docs/install/operator/configuring-eventing-cr.md
- docs/install/operator/configuring-serving-cr.md
Fixes #2277
The page of configuring serving CR: https://github.com/houshengbo/docs/blob/operator-cr-configuration/docs/install/operator/configuring-serving-cr.md
The page of configuring eventing CR: https://github.com/houshengbo/docs/blob/operator-cr-configuration/docs/install/operator/configuring-eventing-cr.md
- This PR adds the the documentation on how to configure Knative by configuring the operator CRs.
> Add the instructions on how to configure the operator CRs

- docs/eventing/getting-started.md
- docs/eventing/samples/helloworld/helloworld-go/README.md
Fixes #2389
- Update references to event-display image
> Update references to event-display image

- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Generated API reference docs for v0.14.0 release
-
-
-
> Updated APIs for v0.14.0 release

- community/meetup/README.md
- community/meetup/_index.md
Hi there 👋
This PR adds the Meetup page, as discussed with @evankanderson and María Cruz.
Two things I'd like to discuss:
1. Could we have a separated Google Calendar for the Knative Community Meetings? I believe that people would like to stay tuned for the events with a calendar, but the Knative one has a loooot of events, cluttering anyone's calendar 😅 
2. I wasn't able to build the page locally for testing and I didn't find the instructions anywhere :( could someone help me out?
Cheers ✨
> Add Meetup page

- docs/eventing/README.md
- docs/eventing/samples/gitlab-source/README.md
- docs/eventing/sources/sources.yaml
- docs/reference/eventing/eventing-contrib.md
Documentation for recently introduced [Gitlabsource](https://github.com/knative/eventing-contrib/tree/master/gitlab)
**NOTE:** Gitlabsource has not yet been released, so the installation section looks a bit ugly:
https://github.com/tzununbekov/docs/blob/6b2c0d53e7b102fcafaed15ba63fd169727eef00/docs/eventing/samples/gitlab-source/README.md#install-gitlab-event-source
> Gitlabsource documentation

- docs/install/installing-istio.md
Fixes: #2380
- Update istio version.
> Update istio version for install istio-knative-extras.yaml

- docs/reference/serving.md
- docs/serving/spec/knative-api-specification-1.0.md
**Background:**
A new field has been added as part of the [PR](https://github.com/knative/serving/pull/7373) which is ContainerStatus to the revision status
- Updated new field `ContainerStatus` to  [reference/serving.md](https://github.com/knative/docs/blob/master/docs/reference/serving.md) and [spec/knative-api-specification-1.0.md](https://github.com/knative/docs/blob/master/docs/serving/spec/knative-api-specification-1.0.md)
> Update Docs to include new field ContainerStatus to the revision status

- docs/serving/using-a-custom-domain-per-service.md
Adds an alternative method to fix [Serving #1185](https://github.com/knative/serving/issues/1185) and #1964.
- Adds an alternative documentation to create custom Service FQDN.
> Document alternative process to setup a custom hostname for a Service

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
Fixes docs links in Sources page; see https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_docs/2377/pull-knative-docs-markdown-link-check/1255562718677569538 for an example of the failing link check.
/assign @sebgoa @mpetason
> Update triggermesh docs links after repo move

- community/samples/README.md
I'll need to update this again when https://github.com/knative/docs/pull/2387 lands.
Fixes Markdown_Link error in community/samples https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_docs/2396/pull-knative-docs-markdown-link-check/1253615911399591937
- Points to the rendered page on knative.dev; this will be moving back into the docs repo soon-ish, and I'll need to figure out how to hande it then, probably by changing the website build to not canonicalize https://github.com/... links.
> Update link to point to website contributing guidelines for now.

- docs/serving/samples/autoscale-go/README.md
Fixes an issue with a previously merged PR - https://github.com/knative/docs/pull/2334
- Updated default from 100 to 70 based on the default in the configs
- Updated link to a static file instead of based on Master
> Updated link and default target from 100 to 70

- docs/serving/configuring-autoscaling.md
Fixes #2436 
- Adds the default tabs on configuring-autoscaling documentation
> Add default tabs on configuring-autoscaling documentation

- community/samples/serving/helloworld-deno/Dockerfile
Bump to 1.0 major release of Deno
Related PR: https://github.com/knative/docs/pull/2444
https://hub.docker.com/layers/hayd/alpine-deno/1.0.0-rc2/images/sha256-afabec0749e708106934b1929283653cebc529ec44c74d7b836139e601697e92?context=explore
> feat: bump deno to 1.0

- community/samples/serving/helloworld-deno/Dockerfile
- community/samples/serving/helloworld-deno/README.md
- community/samples/serving/helloworld-deno/deps.ts
- community/samples/serving/helloworld-deno/main.ts
This PR fixes some issues with upgrading the `helloworld-deno` sample to `deno@1.0.0-rc2`.
Related #2444 #2456
@averikitsch https://github.com/knative/docs/pull/2456#issuecomment-627676819
Tested locally and on Cloud Run:
https://hellodeno-q7vieseilq-uc.a.run.app
Sorry for the multiple PRs!
> Update Deno Syntax to New 1.0 Syntax, 

- docs/eventing/broker/channel-based-broker.md
- adding `brokerClass` to match the doc for the MTChannelBasedBroker
-
-
> Adding missing broker class

- community/samples/serving/helloworld-deno/README.md
- community/samples/serving/helloworld-deno/deps.ts
Fixes #2466.
Deno std lib version broke last night. See issue for details.
Tested locally.
R: @averikitsch
> fix: revert hello-deno std lib to pre 1.0, see denoland/deno#5267

- docs/install/any-kubernetes-cluster.md
- The config for the brokers did not provide content for the referenced sample ConfigMap objects. I've added those for completeness
/assign @mattmoor
> Adding sample config map configs for the two brokers

- docs/eventing/samples/helloworld/helloworld-go/README.md
Fixes broken links caught by markdown-checker caused by moving `broker-trigger.md` to `broker/README.md` in #2449
> Fix links after #2449

- docs/eventing/samples/container-source/service.yaml
- docs/eventing/samples/gitlab-source/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- fix event_display image name
-
-
> fix event_display image name

- OWNERS_ALIASES
- blog/OWNERS
Allow Maria Cruz to approve and manage blog posts.
- Adds Maria Cruz (community manager from Google) to OWNERS
> Allow Maria Cruz to manage Knative blog

- docs/serving/configuring-autoscaling.md
Add docs for the new CM flag for last pod retention period.
/assign @abrennan89 @markusthoemmes
> Add the documentation to the new scale-to-zero-pod-retention-period flag

- docs/install/any-kubernetes-cluster.md
Currently we already set up net-certmanager repo. We will use YAML generated from there to install serving certmanager repo.
> Install serving certmanager component from net-certmanager repo

- docs/install/upgrade-installation.md
Addresses #https://github.com/knative/eventing/issues/3095
-
-
-
> add blurp to eventing storage version migration

- docs/eventing/getting-started.md
When going through the [Getting Started with Eventing](https://knative.dev/docs/eventing/getting-started/) documentation, the `kubectl get pods -n knative-eventing` output to confirm a successful installation of eventing doesn't include associated pods for brokers. This pull request updates the output a user should expect to see when going through the install process of Knative Eventing. 
- Change output from `kubectl get pods -n knative-eventing` to include additional expected pods
> Update Eventing Install Verification Output to Include Broker Pods

- docs/install/knative-with-operators.md
- docs/install/operator/configuring-eventing-cr.md
- This PR changes all the references to knative-sandbox into knative for operator, as knative operator has been moved into knative directory.
> Change the knative-sandbox into knative

- docs/eventing/samples/writing-event-source-easy-way/Dockerfile
- docs/eventing/samples/writing-event-source-easy-way/README.md
- docs/eventing/samples/writing-event-source-easy-way/_index.md
- docs/eventing/samples/writing-event-source-easy-way/index.js
- docs/eventing/samples/writing-event-source-easy-way/package.json
- Add a tutorial for writing an event source easy way
- Tutorial is done with Javascript
- Some references are pointing at personal repos/images as they're not published yet or they're not part of Knative GH org yet
> Add tutorial for writing an event source - easy way

- docs/eventing/getting-started.md
- Fix the `kubectl` output alignment from listing deployments for event consumers
- Update `DESIRED` column header to `READY`
- Change `a` to `an` in `You have sshed into the Pod, and can now make an HTTP request`
> Correct Output Alignment, Column Name, and Minor Typo in Eventing Getting Started

- CONTRIBUTING.md
- README.md
- new-page-template.md
The docs contribution information used to be mixed with the general community information, and was moved to https://github.com/knative/community when that was split out.
With the Hugo build, there's no reason for the contributing docs not to live in the docs repo.
Fixes #1917 #2322 
- Move docs from https://github.com/knative/community to this repo
> Update contributing docs

- community/samples/README.md
Adds a link to the interactive Katakoda sample created by Swapnil Bawaskar
(@sbawaska) to the community samples. This lets people try out Knative without
needing to install anything on their local machine.
> Add link to Katakoda sample to community samples.

- docs/eventing/samples/writing-receive-adapter-source/01-theory.md
- docs/eventing/samples/writing-receive-adapter-source/02-lifecycle-and-types.md
- docs/eventing/samples/writing-receive-adapter-source/03-controller.md
- docs/eventing/samples/writing-receive-adapter-source/04-reconciler.md
- docs/eventing/samples/writing-receive-adapter-source/05-receive-adapter.md
- docs/eventing/samples/writing-receive-adapter-source/06-yaml.md
- docs/eventing/samples/writing-receive-adapter-source/07-eventing-contrib.md
- docs/eventing/samples/writing-receive-adapter-source/README.md
- Validate the sample source guide
- Fix the references, file names, etc.
- Adaptions for SinkBinding changes https://github.com/knative/sample-source/pull/40
- Create a separate page for instructions on how to make the source part of `eventing-contrib`
> Update sample source guide

- docs/eventing/samples/writing-event-source-easy-way/Dockerfile
- docs/eventing/samples/writing-event-source-easy-way/README.md
- Addressing @evankanderson 's comments in https://github.com/knative/docs/pull/2494
> Minor fixes in easy event source tutorial

- docs/serving/configuring-autoscaling.md
This can be configured via annotation now as well.
So document that as well.
/assign @abrennan89 @markusthoemmes
> Add the per-revision annotation key

- docs/eventing/samples/kafka/source/README.md
Using "gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display: produces "unknown encoding error" in this Example.  
Switching to image @ gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display resolves these issues for me.
See: https://github.com/knative/docs/issues/2145
- image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
- (instead of) image: gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display
-
> event_display image seems wrong.  produces "unknown encoding" error.

- docs/eventing/samples/writing-event-source-easy-way/README.md
- docs/eventing/samples/writing-event-source-easy-way/index.js
- docs/eventing/samples/writing-event-source-easy-way/package.json
- Migrate the tutorial to use Javascript SDK v2
- Needs Javascript SDK 2.0.1 (not released) because of https://github.com/cloudevents/sdk-javascript/issues/191, thus references a commit
> Migrate "easy event source" tutorial to Cloudevents javascript sdk v2

- docs/serving/samples/hello-world/helloworld-python/Dockerfile
- docs/serving/samples/hello-world/helloworld-python/README.md
Using pythonunbuffered so that  print() statements and log messages will immediately appear in the logs.
Otherwise, you have to use sys.stdout.flush() to print log messages, which is seen as buggy and confusing by our users. 
For example: https://stackoverflow.com/questions/60828641/simplest-way-to-perform-logging-from-google-cloud-run
> Python Unbuffered

- docs/serving/getting-started-knative-app.md
This PR add the usage splits up the walkthrough for the first service into two sections: How to create with YAML and kubectl and how to create a service with kn.
The PR is best reviewed by looking at the file as a whole.
PR replacing #2514 that I have messed up.
> chore: Add `kn` usage to Getting Started guide

- docs/eventing/broker/README.md
- docs/eventing/debugging/example.yaml
- docs/eventing/samples/apache-camel-source/display_resources.yaml
- docs/eventing/samples/container-source/heartbeats-source.yaml
- docs/eventing/samples/github-source/service.yaml
- docs/eventing/samples/iot-core/trigger.yaml
- docs/eventing/samples/kafka/binding/README.md
- docs/eventing/samples/kafka/binding/event-display.yaml
- docs/eventing/samples/kafka/channel/000-ksvc.yaml
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-display.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/heartbeats-source.yaml
- docs/eventing/samples/sinkbinding/service.yaml
- docs/eventing/samples/writing-receive-adapter-source/06-yaml.md
Fixes #2487 
- Updates a bunch of docker image links to remove specific version pins and point to the current location that images are published to.
> Fix docker images to point to released event_display binary

- docs/serving/samples/knative-routing-go/sample.yaml
- docs/serving/samples/rest-api-go/sample.yaml
- docs/serving/samples/traffic-splitting/release_sample.yaml
- docs/serving/samples/traffic-splitting/split_sample.yaml
- docs/serving/samples/traffic-splitting/updated_sample.yaml
- Fixes broken serving examples.
Since knative/serving#4731, `periodSeconds` also requires `failureThreshold` and `timeoutSeconds` to be set. The best is simply not to set it, otherwise our examples fail with
`admission webhook "resource.webhook.serving.knative.dev" denied the request: mutation failed: expected 1 <= 0 <= 2147483647: spec.template.spec.containers[0].readinessProbe.failureThreshold, spec.template.spec.containers[0].readinessProbe.timeoutSeconds`
Ref:
knative/serving#4780
knative/serving#5732
> Remove periodSeconds from examples

- docs/eventing/samples/kubernetes-event-source/README.md
The file docs/eventing/samples/kubernetes-event-source/README.md points to a link in the Kubernetes docs for release 1.17 and that file no longer exists. I've updated that link to match the URL for the 1.18 release of Kubernetes (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#event-v1-core)
> [DOCS] Fix broken link in event source sample

- docs/install/any-kubernetes-cluster.md
Adds Kong as another option for networking layer.
> add Kong Ingress Controller as a supported network layer

- docs/eventing/README.md
- docs/eventing/debugging/README.md
- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
- docs/serving/deploying/private-registry.md
- docs/serving/spec/knative-api-specification-1.0.md
- hack/reference-docs-gen-config.json
Fixes #2562 
Mechanical replacements to point to k8s resources at v1.18 version.
```
for i in `grep -l -R generated/kubernetes-api * | grep -v 1.18`; do sed -i '' 's@generated/kubernetes-api/v1.[^/]*/@generated/kubernetes-api/v1.18/@' $i; done
```
-
-
-
> change all previous versions to generated/kubernetes-api/v1.18

- docs/eventing/README.md
- docs/eventing/broker/README.md
- docs/eventing/debugging/README.md
- docs/eventing/debugging/example.yaml
- docs/eventing/event-registry.md
- docs/eventing/flows/sequence.md
- docs/eventing/samples/apache-camel-source/display_resources.yaml
- docs/eventing/samples/apache-camel-source/source_http_poller.yaml
- docs/eventing/samples/apache-camel-source/source_mqtt.yaml
- docs/eventing/samples/apache-camel-source/source_telegram.yaml
- docs/eventing/samples/apache-camel-source/source_timer.yaml
- docs/eventing/samples/helloworld/helloworld-go/README.md
- docs/eventing/samples/iot-core/gcp-pubsub-source.yaml
- docs/eventing/samples/iot-core/trigger.yaml
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kafka/channel/030-trigger.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Fixes #2545 
- Change v1alpha1 to v1beta1 for flows, messaing and eventing api groups.
-
-
> v1alpha1 -> v1beta1

- docs/serving/setting-up-custom-ingress-gateway.md
This patch updates [Setting up custom ingress gateway](https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/) section.
It changeed to:
- use istio operator example for custom gateway deploy. (Note, `istioctl` cannot install standalone ingress gateway.)
- update config in `config-istio` to `+gateway.knative-serving.knative-ingress-gateway`.
> Update "Setting up custom ingress gateway" section

- docs/eventing/samples/github-source/README.md
Fixes #2578
- The github event source version was still v0.12.* so I updated it to
v0.15.0
> Updated eventing github sample to v0.15.0

- docs/eventing/getting-started.md
update broker url so demo works for later knative eventing version
- Update broker url to match the format of the broker url in v0.15.
> Update broker url in getting-started.md

- docs/install/any-kubernetes-cluster.md
Current doc explains that default-domain does not work on AWS as it
does not expose External IP. But it exposes Extenal Host and supported
it by https://github.com/knative/serving/pull/7518.
Hence, this patch removes AWS from Caveat.
/cc @mattmoor @evankanderson
> Remove AWS from unsupported default-domain in Caveat

- docs/install/installing-istio.md
This patch removes "Verifying your Istio install" section from
Installing Istio for Knative.
When we install istio by `istioctl manifest apply` command, the
command verifies the installation and we can determine the
installation success or failure by the command result.
Hence we don't need this section anymore.
/cc @ZhiminXiang @tcnghia
> Remove "Verifying your Istio install" from section Installing Istio for Knative

- docs/serving/using-auto-tls.md
This patch fixes obsoleted manifest path.
Fixes https://github.com/knative/serving/issues/8335
/cc @ZhiminXiang @abrennan89
> Fix invalid manifest link in auto TLS

- docs/install/installing-istio.md
This patch removes "Configuring DNS" section from Installing Istio for Knative.
It needs to install Knative Serving, so it is not correct to explain
it in Istio which is pre-req.
Also, the configuration is instructed in knative installation.
https://knative.dev/docs/install/any-kubernetes-cluster/
> 4. Configure DNS
`Magic DNS (xip.io)`
Fixes https://github.com/knative/docs/issues/2343
> Remove "Configuring DNS" from Installing Istio for Knative

- docs/eventing/getting-started.md
- docs/eventing/samples/helloworld/helloworld-go/README.md
- docs/eventing/samples/helloworld/helloworld-go/helloworld.go
I saw some references to CloudEvents 0.3 and wanted to clean those up.
- Use CloudEvents 1.0 in Eventing Getting Started guide.
- Use CloudEvents 1.0 in Eventing hello world sample.
- Add comment about ID generation in Eventing hello world sample (thanks @n3wscott)
The only remaining reference to 0.3 that I can find is in the GitLabSource sample. That source still uses 0.3 (tracked in https://github.com/knative/eventing-contrib/issues/1325).
> CloudEvents 1.0

- docs/serving/using-auto-tls.md
Auto TLS verification used the `autoscale-go` sample, but it was moved in https://github.com/knative/docs/pull/2439, and not updated here.
- Didn't find any. I came from the documentation's "*View / Edit this page*" link
- Update the link to the deployment template for verifying auto-tls is correctly configured
> Template for verifying AutoTLS was moved

- docs/install/operator/configuring-eventing-cr.md
- docs/install/operator/configuring-serving-cr.md
- This PR added the instruction on how to config ConfigMaps with eventing CR.
> Add the instruction on how to configure ConfigMaps with eventing CR

- docs/eventing/broker/README.md
- docs/eventing/broker/mt-channel-based-broker.md
- docs/eventing/channels/default-channels.md
- docs/eventing/event-registry.md
- docs/eventing/samples/helloworld/helloworld-go/README.md
- docs/eventing/samples/helloworld/helloworld-go/sample-app.yaml
- docs/eventing/samples/iot-core/gcp-pubsub-source.yaml
- docs/eventing/samples/iot-core/trigger.yaml
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kafka/channel/030-trigger.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
Addresses: #2609 
- Change examples and docs from v1beta1 to v1 for eventing components (Broker/Trigger)
-
-
> change v1beta1 => v1 for eventing components

- docs/install/operator/configuring-eventing-cr.md
- The section of configuring KnativeEventing CR has several typos regarding the CR name and namespace.
> Change the CR name from KnativeServing into KnativeEventing

- docs/serving/istio-authorization.md
This patch adds doc on how to use Istio Authorization with Knative.
As described in https://github.com/knative/docs/issues/2569, the sample configuration of Authorizationpolicy is helpful for our users.
Part of https://github.com/knative/docs/issues/2569
> Add doc on how to use Istio Authorization with Knative and Istio mesh mode

- docs/install/knative-with-operators.md
The istio installation install cluster-local-gateway without any extra steps.
This patch removes the line "to use cluster local gateway".
> Update operator installation doc

- docs/serving/config-ha.md
This reflects https://github.com/knative/serving/pull/8513 as well as some other changes that landed prior.
> Update the HA component list.

- docs/eventing/README.md
- docs/eventing/broker/mt-channel-based-broker.md
- docs/eventing/channels/default-channels.md
- docs/eventing/debugging/README.md
- docs/eventing/debugging/example.yaml
- docs/eventing/event-delivery.md
- docs/eventing/event-registry.md
- docs/eventing/flows/sequence.md
- docs/eventing/samples/apache-camel-source/display_resources.yaml
- docs/eventing/samples/apache-camel-source/source_http_poller.yaml
- docs/eventing/samples/apache-camel-source/source_mqtt.yaml
- docs/eventing/samples/apache-camel-source/source_telegram.yaml
- docs/eventing/samples/apache-camel-source/source_timer.yaml
- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/parallel/multiple-branches/README.md
- docs/eventing/samples/parallel/multiple-branches/parallel.yaml
- docs/eventing/samples/parallel/mutual-exclusivity/README.md
- docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
- docs/eventing/samples/sinkbinding/README.md
- Change messaging resources to v1 from v1beta1.
-
-
> messaging v1beta1->v1

- docs/eventing/broker/README.md
- docs/eventing/broker/defaults-br-config.md
- docs/eventing/broker/mt-channel-based-broker.md
By default some of the magic of Broker / Trigger creation is moved to a separately installed component:
https://github.com/knative/eventing/pull/3459
https://github.com/knative/eventing/issues/3138
This PR adds examples that do not rely on this magic. Also adds more examples and documents on how
to configure the Broker defaults.
Follow up is to document the sugar controller, which is tracked here:
https://github.com/knative/docs/issues/2641
- Remove the injection based examples
- Add a separate doc for configuring the broker defaults, provide an example of that
- Clean up the MT broker documents and examples.
> clean up the broker docs, separate broker defaults

- docs/eventing/getting-started.md
We currently have two sets of installation instructions for Eventing. This PR removes the section in getting started and simply points to the main install instructions.
- Remove parallel installation instructions for eventing. Point to shared instructions instead.
-
-
> remove parallel installation instructions

- docs/install/install-kn.md
* Make `install kn with Go` more detailed.
* Give example on how to run kn using container.
Fixes #https://github.com/knative/client/issues/648
> Improve "Installing the Knative CLI"

- community/meetup/README.md
Add 2020-05-14 – Knative Community Meetup #2!
@macruzbar could u take a look? ✨
> Add 2020-05-14 – Knative Community Meetup #2

- blog/articles/set-up-a-local-knative-environment-up-in-no-time-flat.md
- blog/articles/set-up-a-local-knative-environment-with-kind.md
Adding a new blog post that walks through the set up of a Kubernetes cluster using `KinD`, the deployment of Knative (`v0.15`), and running your first app on top of it.
> [BLOG] Set up a local Knative environment up in no time flat

- docs/eventing/broker/mt-channel-based-broker.md
- docs/eventing/channels/default-channels.md
- docs/eventing/samples/kafka/channel/README.md
- docs/install/operator/configuring-eventing-cr.md
Fixes https://github.com/knative/eventing-contrib/issues/1355
- Use v1beta1 of KafkaChannel in docs
-
-
> Update KafkaChannel examples to use v1beta1

- docs/eventing/broker/README.md
- docs/eventing/broker/_index.md
- docs/eventing/triggers/README.md
- docs/eventing/triggers/_index.md
Partially fixes # 2554 
- Split broker and trigger docs into their own sections at top level.
> Split out trigger and broker docs

- docs/install/upgrade-installation.md
- This PR changed the doc of eventing, as yaml files have been renamed.
- This PR is based on https://github.com/knative/eventing/pull/3536.
> Fix the doc for eventing as yaml files are renamed

- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/sinkbinding.yaml
Fixes https://github.com/knative/docs/issues/2663
Helps with https://github.com/knative/eventing/issues/3544
- Updating example to use v1beta1
> Update SinkBinding example to v1beta1

- docs/serving/autoscaling/concurrency.md
As of https://github.com/knative/serving/pull/8263 the activator no longer has this behaviour when in the path, and instead does nice round-robin load balancing, so this warning is no longer needed \o/.
/assign @markusthoemmes
> Remove warning about activator load balancing behaviour

- docs/serving/feature-flags.md
Issue https://github.com/knative/docs/issues/2684
- Fix the name of the dry-run feature flag. `/` isn't a legal character for flags.
> Fix dry-run flag name

- docs/eventing/broker/README.md
- docs/eventing/broker/config-br-defaults.md
- Changed Broker defaulting title from `defaults-br-config` to `Default config (config-br-defaults)`.
- Clarified `brokerClass` and `spec.config` defaulting.
- Slack discussion: https://knative.slack.com/archives/C9JP909F0/p1594653309428800
> Rename Broker defaults-br-config and clarify Broker defaulting

- docs/eventing/debugging/README.md
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
Fixes #2687 
Helps with knative/eventing#3611
- Updating ApiServerSource example to use v1beta1
-
-
> updating ApiServerSource example to use v1beta1

- docs/install/operator/configuring-serving-cr.md
Based on #2613
- This PR updated the link to the local cluster gateway configuration for istio.
> Update the local cluster gateway link

- docs/serving/config-ha.md
`enabledComponents` is now defunct and this is enabled by default at HEAD.
This talks about `--disable-ha` to disable leader election, and focuses on the need to scale up deployments.
Fixes: https://github.com/knative/docs/issues/2661
> Simplify the HA documentation.
