- serving/installing-logging-metrics-traces.md
- serving/samples/telemetry-go/telemetrysample.go
- serving/setting-up-a-logging-plugin.md
> Fixes to monitoring component installation instructions

- community/README.md
> Typo fix - contriubtions -> contributions

- install/Knative-with-any-k8s.md
- install/README.md
* This is the install instructions without "how to set up k8s". (Copied from PKS, just for the record)
> Add any-k8s instructions, thanks to jbeda for the suggestion.

- serving/samples/README.md
> Fixed Source to URL link

- serving/samples/rest-api-go/README.md
Clean PR for Rest-API
cc: @labadav
> update Rest-API sample

- serving/samples/blue-green-deployment.md
> Fix typo in comment

- build/README.md
> Fix wrong URL in build README.md

- serving/samples/autoscale-go/README.md
sample.yaml -> service.yaml
* 
* 
*
> fix wrong file name in the example

- serving/samples/autoscale-go/README.md
sample.yaml -> service.yaml
* 
* 
*
> fix typo in filename

- serving/samples/README.md
> Fix Typo in link

- serving/samples/helloworld-java/README.md
fixed typo in Hello World Spring Boot sample
> fixed typo in Hello World Spring Boot sample

- install/Knative-with-GKE.md
> Correct Markdown link error

- community/WORKING-GROUPS.md
https://github.com/knative/docs/issues/144
> Update Scaling working group Hangout link

- install/README.md
> Add PKS to choosing a cluster paragraph

- community/WORKING-GROUPS.md
This is a continuation of https://github.com/knative/docs/pull/220 with merge conflicts fixed while Mustafa is out.
cc @mdemirhan @tcnghia
> Split serving into two separate work groups: observability and networking.

- install/Knative-with-GKE.md
> Updates to clarify install instructions

- install/Knative-with-OpenShift.md
Corrects a couple minor typos in OpenShift instructions.
> Correct typos in OpenShift instructions

- install/Knative-with-AKS.md
Changing what seems like a typo in the documentation, which would likely trip others.
* 
* 
*
> Making a change to default azure location to reflect the correct Azure

- serving/samples/thumbnailer-go/README.md
Fixes #306
I had to apply the sample.yaml to actually get this to build and deploy and be able to serve the application. I have added the kubectl cmd at the end of the current code block.
Happy to amend any thing.
> Add applying the knative route and config

- serving/samples/thumbnailer-go/README.md
> Correct name of .yaml file

- community/WORKING-GROUPS.md
/assign mattmoor
Apparently using Hangouts Meet instead of Old Hangouts will solve some of the problems we experienced in today's meeting. 🤞
> Update Build WG meeting information

- serving/samples/helloworld-haskell/.gitignore
- serving/samples/helloworld-haskell/Dockerfile
- serving/samples/helloworld-haskell/README.md
- serving/samples/helloworld-haskell/app/Main.hs
- serving/samples/helloworld-haskell/package.yaml
- serving/samples/helloworld-haskell/service.yaml
- serving/samples/helloworld-haskell/stack.yaml
* Use stack as the build tool
* Use scotty as a web framework
* Use docker multi-stage build to create a smaller runtime image
> Add a helloworld sample for haskell

- community/WORKING-GROUPS.md
Fixes #(343)
added productivity wg description
> add productivity wg

- eventing/samples/event-flow/README.md
- eventing/samples/github-events/README.md
- eventing/samples/k8s-events/README.md
Fixes #351
* Updates the README for each eventing sample to run commands relative to the samples directory
> Run eventing samples from the samples home directory

- build/builds.md
Fixes https://github.com/knative/build/pull/315
* Add build timeout documentation and example
> Add documentation for build timeout

- install/getting-started-knative-app.md
* Fixes a couple of typos in the documentation
> fix typos in getting-started-knative-app.md

- install/Knative-with-any-k8s.md
Fixes #369 
* Mention MutatingAdmissionWebhook is required for serving in "Knative-with-any-k8s.md" doc
> Mention MutatingAdmissionWebhook is required for serving

- build/build-templates.md
> Build Templates Missing comma

- community/WORKING-GROUPS.md
> Update build WG calendar link

- serving/samples/build-private-repo-go/manifest.yaml
- serving/samples/buildpack-app-dotnet/sample.yaml
- serving/samples/buildpack-function-nodejs/sample.yaml
- serving/samples/source-to-url-go/README.md
- serving/samples/source-to-url-go/service.yaml
- serving/samples/thumbnailer-go/sample.yaml
Resolves #390 
* Remove yaml anchor references from docs
> Remove &image yaml anchors

- serving/installing-logging-metrics-traces.md
remove -prod from command so it points to a valid directory
> Fix directory name

- serving/installing-logging-metrics-traces.md
fix list of pods when installing stackdriver monitoring
> Remove incorrect kibana and elasticsearch pods

- community/CONTRIBUTING.md
Partially fixes https://github.com/knative/test-infra/issues/150
* Add a small note on gubernator to community/CONTRIBUTING.md
> Add note to community/CONTRIBUTING.md about gubernator

- community/WORKING-GROUPS.md
* Create Documentation Working Group
> Add Documentation working group

- serving/samples/autoscale-go/README.md
* Update autoscale-go serving sample with ContainerConcurrency changes (#1917).
> Update autoscale-go serving sample with ContainerConcurrency changes

- serving/outbound-network-access.md
> Updating Container Engine to new name

- community/WORKING-GROUPS.md
> Moving documentation WG to Tuesdays

- community/WORKING-GROUPS.md
Update Observability WG meeting information & fix Slack channel links for all WGs
> Update Observability WG meeting information & fix Slack channel links for all WGs

- eventing/samples/k8s-events/README.md
- eventing/samples/k8s-events/function.yaml
Fixes #418 
* Changed github.com url for image to docker.io/{username}
* Added -.... to name of feed to indicate user needs to edit the command to include full feed name
> minor edits to examples

- serving/samples/README.md
- serving/samples/helloworld-clojure/.gitignore
- serving/samples/helloworld-clojure/Dockerfile
- serving/samples/helloworld-clojure/README.md
- serving/samples/helloworld-clojure/project.clj
- serving/samples/helloworld-clojure/service.yaml
- serving/samples/helloworld-clojure/src/hello_world/core.clj
- serving/samples/helloworld-clojure/src/helloworld/core.clj
* Adds a serving sample `helloworld-clojure`.
> Clojure helloworld serving sample

- install/Knative-with-PKS.md
* add note clarifying the need to check "Enable Privileged Containers" and "Disable DenyEscalatingExec" in Ops Manager before creating cluster
> Update PKS docs clarifying the need to enable privileged containers

- serving/samples/helloworld-clojure/README.md
- serving/samples/helloworld-clojure/src/helloworld/core.clj
* Update the helloworld-clojure sample to serve on the PORT environment variable.
> Clojure helloworld serve on $PORT

- serving/samples/helloworld-go/README.md
Fixes #482 
* remove `flag` import
> README.md: imported and not used: "flag"

- serving/accessing-metrics.md
* Update accessing-metrics.md with knative-monitoring namespace.
> Update accessing-metrics.md with knative-metrics namespace.

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
- serving/installing-logging-metrics-traces.md
Update docs to refer to Istio 1.0.2
Updates #479
> Update docs to refer to Istio 1.0.2

- serving/samples/helloworld-java/Dockerfile
- serving/samples/helloworld-java/README.md
- serving/samples/helloworld-java/src/main/java/com/example/helloworld/HelloworldApplication.java
- serving/samples/helloworld-ruby/README.md
Fixes #456
Fixed formatting in ReadMe and made Dockerfile more concise
> Update Hello world - Java 

- .gitignore
> Ignore GoLand files.

- eventing/samples/kubernetes-event-source/README.md
> updating wrong file name

- eventing/README.md
remove extra `.yaml` extension in manifest
> one too many .yaml extension

- install/Knative-with-AKS.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
- serving/installing-logging-metrics-traces.md
* Update installation instructions to refer to v0.2.1 instead of v0.2.0
@mattmoor
> Change install instructions to use v0.2.1 instead of v0.2.0

- eventing/samples/gcp-pubsub-source/subscriber.yaml
This matches the iot-core sample field names.
/assign @evankanderson @vaikas-google
> This fixes some field renaming.

- eventing/samples/gcp-pubsub-source/README.md
/assign @vaikas-google @evankanderson 
From friction log: https://github.com/knative/docs/issues/548
> Drop the namespace argument to `ko`.

- serving/samples/helloworld-csharp/Dockerfile
- serving/samples/helloworld-csharp/README.md
Addresses #497 for C#.
Locally tested with $PORT and $TARGET.
> serving/samples/helloworld-csharp: simplify and standardize Dockerfile

- serving/samples/helloworld-php/Dockerfile
- serving/samples/helloworld-php/README.md
> serving/samples/helloworld-php: simplify and standardize Dockerfile

- serving/samples/helloworld-python/Dockerfile
- serving/samples/helloworld-python/README.md
> serving/samples/helloworld-python: simplify and standardize Dockerfile

- serving/samples/helloworld-go/Dockerfile
- serving/samples/helloworld-go/README.md
> serving/samples/helloworld-go: simplify and standardize Dockerfile

- serving/samples/helloworld-nodejs/Dockerfile
- serving/samples/helloworld-nodejs/README.md
> serving/samples/helloworld-nodejs: simplify and standardize Dockerfile

- install/getting-started-knative-app.md
fix a broken command which was not properly using the set env var.
> Fix getting started

- serving/samples/helloworld-clojure/Dockerfile
- serving/samples/helloworld-clojure/README.md
> serving/samples/helloworld-clojure: simplify and standardize Dockerfile

- community/WORKING-GROUPS.md
To avoid confusion with Knative Events (like a conference) and Knative Eventing
/assign @evankanderson
> Events work group -> Eventing

- serving/samples/helloworld-ruby/Gemfile
- serving/samples/helloworld-ruby/Gemfile.lock
> Require rack 2.0.6

- serving/samples/helloworld-rust/Dockerfile
- serving/samples/helloworld-rust/README.md
> serving/samples/helloworld-rust: simplify and standardize Dockerfile

- serving/samples/helloworld-haskell/Dockerfile
- serving/samples/helloworld-haskell/README.md
> serving/samples/helloworld-haskell: simplify and standardize Dockerfile

- serving/samples/helloworld-java/Dockerfile
- serving/samples/helloworld-java/README.md
Addresses #497 for Java.
Tested with $TARGET and $PORT, found $PORT support does not work. (That's a separate issue, as nothing in this change should affect PORT behavior.)
> serving/samples/helloworld-java: simplify and standardize Dockerfile

- serving/samples/helloworld-dart/Dockerfile
- serving/samples/helloworld-dart/README.md
> serving/samples/helloworld-dart: simplify and standardize Dockerfile

- serving/samples/helloworld-ruby/Dockerfile
- serving/samples/helloworld-ruby/README.md
- serving/samples/helloworld-rust/Dockerfile
- serving/samples/helloworld-rust/README.md
> Docker hello ruby

- install/Knative-with-any-k8s.md
Just document update to use latest serving release.
> Updated k8s doc use latest serving release.

- install/getting-started-knative-app.md
- serving/samples/helloworld-go/README.md
> Add notes for how to debug `curl`.

- serving/setting-up-a-logging-plugin.md
> Replace Bazel commands with ko

- README.md
Fixes https://github.com/knative/docs/issues/581
> Fixed broken link for eventing.

- serving/samples/helloworld-nodejs/service.yaml
* Dockerfile needs to match ReadMe and be consistent with other Helloworld samples
* 
*
> update Helloworld-Nodejs Dockerfile

- serving/samples/helloworld-go/README.md
> Updated helloworld-go by clarifying the `IP_ADDRESS` address.

- eventing/README.md
Fixes #595 
* fix spelling mistake
> Updating misspelling of their

- serving/samples/grpc-ping-go/grpc-ping.go
Produced via: `github.com/client9/misspell`
> Fix spelling errors

- OWNERS
> Adding Caroline to the repo owners file

- serving/samples/autoscale-go/README.md
> Fix spelling error

- serving/outbound-network-access.md
* This is connected to #639
Fixes #(639)
- Adds in details of IP scope for PKS cluster running on GCP
-
-
> Add PKS information to configuring outbound access setup

- build/auth.md
> Fixed the path in example that shows how to copy private key from id_rsa file

- community/WORKING-GROUPS.md
- serving/outbound-network-access.md
- serving/samples/autoscale-go/README.md
- serving/using-external-dns-on-gcp.md
Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
> Format markdown

- .github/ISSUE_TEMPLATE/bug-in-existing-docs.md
- .github/ISSUE_TEMPLATE/feature-request----new-or-updated-documentation.md
> Update issue templates

- eventing/samples/github-source/README.md
- serving/samples/autoscale-go/README.md
Removes duplicate words
Signed-off-by: GuessWhoSamFoo <sfoohei@gmail.com>
> Remove repeated words

- serving/samples/helloworld-haskell/README.md
The code was deleted in https://github.com/knative/docs/commit/41462c69e1879aba14ad91a6f2d10ffe6668051f
> Restore code in the helloworld-haskell README

- OWNERS
- OWNERS_ALIASES
> Creating OWNERS_ALIASES

- OWNERS
- OWNERS_ALIASES
> Updates to OWNERS so Prow will uses ALIASES for autoassignments

- CONTRIBUTING.md
- community/CONTRIBUTING.md
- community/DOCS-CONTRIBUTING.md
- community/WORKING-GROUPS.md
> Adds more info for Docs contributors

- install/Knative-custom-install.md
Fixing a line where an edit started but didnt finish (looks to have stopped mid way).
> Fixing odd sentence

- install/getting-started-knative-app.md
Fixes typo in README
asssigned -> assigned
> Fixed typo

- build/README.md
> fix(README): "repository" -> "registry"

- build/README.md
- align CRD formatting with other links
> fix(README): tiny cosmetic formatting fix

- install/README.md
Update [install landing](https://github.com/knative/docs/blob/master/install/README.md) to include link to the Google codelab
> Add custom install and Knative codelab links

- install/Knative-with-OpenShift.md
> Adding missing scc binding for istio on openshift

- eventing/README.md
Addresses #760 
- Add a note in eventing/README.md install about configuring outbound network access.
-
-
> Note about outbound access

- Gopkg.lock
- README.md
- test/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
Fixes #750.
* disable markdown linting
* ignore localhost links when checking for dead links in markdown files
> Update presubmit tests

- serving/installing-logging-metrics-traces.md
Fixes #657
Original PR is at: https://github.com/knative/docs/pull/613 - I closed the original one due to conflicts and updated that with 0.3.0 changes.
> Update installation instructions for logs, metrics and traces

- test/presubmit-tests.sh
> Disable markdown link checks

- install/Knative-custom-install.md
> Update custom install for v.0.3

- install/README.md
/cc @samodell @RichieEscarez 
-
-
-
> Adding IBM Cloud Private install to index.

- serving/gke-assigning-static-ip-address.md
- serving/samples/knative-routing-go/README.md
- serving/samples/knative-routing-go/routing.yaml
- serving/using-an-ssl-cert.md
- serving/using-cert-manager-on-gcp.md
- Update SSL and IP address docs to work with istio-ingressgateway.
/assign @mchmarny
> Update SSL and IP address docs to work with istio-ingressgateway.

- eventing/README.md
Update release links to v0.3.0
- Point to latest release (0.2.1 => 0.3.0)
-
-
> update version to v0.3.0

- install/Knative-custom-install.md
Addresses @RichieEscarez 's comments from PR #771
> Tweaks to custom install for v0.3

- serving/samples/helloworld-dart/bin/server.dart
- add default port for dart app
> add default port for dart app

- serving/setting-up-a-logging-plugin.md
Update the stale file `setting-up-a-logging-plugin.md`.
> Update instructions for setting up a logging plugin

- doc-releases.md
and provide some indication that the website is coming
> add v0.1 release branch

- eventing/samples/cronjob-source/README.md
> eventing/samples/cronjob-source: fix broken cmd

- install/Knative-custom-install.md
- install/Knative-with-AKS.md
- install/Knative-with-Docker-for-Mac.md
- install/Knative-with-GKE.md
- install/Knative-with-Gardener.md
- install/Knative-with-ICP.md
- install/Knative-with-IKS.md
- install/Knative-with-Minikube.md
- install/Knative-with-Minishift.md
- install/Knative-with-OpenShift.md
- install/Knative-with-PKS.md
- install/Knative-with-any-k8s.md
- install/check-install-version.md
- install/getting-started-knative-app.md
Fixes #728 
Richie -- I decided to try putting all the install guides at the same weight; can you verify that that will just put them in alphabetical order?
> Adding frontmatter to /install/

- serving/accessing-logs.md
- serving/accessing-metrics.md
- serving/accessing-traces.md
- serving/cluster-local-route.md
- serving/debugging-application-issues.md
- serving/debugging-performance-issues.md
- serving/gke-assigning-static-ip-address.md
- serving/installing-logging-metrics-traces.md
- serving/outbound-network-access.md
- serving/setting-up-a-logging-plugin.md
- serving/using-a-custom-domain.md
- serving/using-an-ssl-cert.md
- serving/using-cert-manager-on-gcp.md
- serving/using-external-dns-on-gcp.md
Fixes #730 (except for serving/fluentd/README.md)
> Adds front matter to Serving

- serving/fluentd/README.md
- serving/fluentd/_index.md
> site: Hugo files for Fluentd folder

- eventing/README.md
- eventing/_index.md
- eventing/debugging/README.md
- eventing/debugging/_index.md
- eventing/samples/_index.md
- eventing/samples/cronjob-source/README.md
- eventing/samples/cronjob-source/_index.md
- eventing/samples/gcp-pubsub-source/README.md
- eventing/samples/gcp-pubsub-source/_index.md
- eventing/samples/github-source/README.md
- eventing/samples/github-source/_index.md
- eventing/samples/iot-core/README.md
- eventing/samples/iot-core/_index.md
- eventing/samples/kubernetes-event-source/README.md
- eventing/samples/kubernetes-event-source/_index.md
- eventing/samples/writing-a-source/01-bootstrap.md
- eventing/samples/writing-a-source/02-define-source.md
- eventing/samples/writing-a-source/03-reconcile-sources.md
- eventing/samples/writing-a-source/04-publish-to-cluster.md
- eventing/samples/writing-a-source/README.md
- eventing/samples/writing-a-source/_index.md
- eventing/sources/README.md
- eventing/sources/_index.md
- eventing/sources/generator/ReadmeTemplate.gomd
Fixes #727
Tried to add samples as regular docs (not sure how it will render)
> site: add _index.md build files and front matter

- reference/_index.md
- reference/build-api.md
- reference/eventing/_index.md
- reference/eventing/eventing-sources-api.md
- reference/serving-api.md
add files to pick up autogen API files
> site: hugo build files for autogen refdocs

- community/_index.md
- community/samples/README.md
- community/samples/_index.md
- contributing/CODE-OF-CONDUCT.md
- contributing/CONTRIBUTING.md
- contributing/DOCS-CONTRIBUTING.md
- contributing/README.md
- contributing/REVIEWING.md
- contributing/ROLES.md
- contributing/SLACK-GUIDELINES.md
- contributing/STEERING-COMMITTEE.md
- contributing/TECH-OVERSIGHT-COMMITTEE.md
- contributing/VALUES.md
- contributing/WORKING-GROUP-PROCESSES.md
- contributing/WORKING-GROUPS.md
- contributing/_index.md
Add Community and Contributing content: add _index.md files and front matter
Fixes #726
> site: add community and contributing

- docs/eventing/channels/README.md
- docs/eventing/channels/_index.md
- docs/eventing/channels/default-channels.md
- docs/eventing/channels/generator/ReadmeTemplate.gomd
- docs/eventing/debugging/_index.md
- docs/eventing/samples/_index.md
merge in and add Hugo build and front matter to recent changes from master
> site: add PR#851 - channels

- contributing/CODE-OF-CONDUCT.md
- contributing/CONTRIBUTING.md
- contributing/DOCS-CONTRIBUTING.md
- contributing/README.md
- contributing/REVIEWING.md
- contributing/ROLES.md
- contributing/SLACK-GUIDELINES.md
- contributing/STEERING-COMMITTEE.md
- contributing/TECH-OVERSIGHT-COMMITTEE.md
- contributing/VALUES.md
- contributing/WORKING-GROUP-PROCESSES.md
- contributing/WORKING-GROUPS.md
- contributing/_index.md
> site: fix links in community

- install/Knative-with-Minishift.md
> Correct spelling of privileged

- eventing/samples/gcp-pubsub-source/README.md
> Updated document for gcp pubsub.

- eventing/samples/github-source/README.md
There is no need to use full path as the README and YAML files
are in the same directory.
> Correct the file path of github source.

- eventing/samples/iot-core/README.md
> Correct the file path for iot example.

- serving/accessing-metrics.md
- serving/setting-up-custom-ingress-gateway.md
The previous PR has already been merged. This one addresses outstanding
comments on pull request #802.
> Address comments from #802

- eventing/sources/README.md
- eventing/sources/sources.yaml
Adding new sources with support from triggermesh
I re-run the generator which seemed to have changed some other formatting in the README.
> Add knative lambda sources from triggermesh

- serving/setting-up-custom-ingress-gateway.md
- Just some simple grammar and typography tweaks
> Tweak grammar in Custom Ingress Gateway guide

- install/Knative-with-OpenShift.md
#923 
- Using a valid url for knative yaml resources file
Sending this PR for early feedback - I got this error while going through the Openshift docs.
> using correct link in openshift install docs

- build/installing-build-component.md
Fixes N/A
- Replace invalid manifest URL with the latest manifest URL.
> Fix invalid manifest URL to insatll build

- docs/install/Knative-with-Gloo.md
Moves the Gloo guide to the correct spot; adds front matter.
> Adding frontmatter to Gloo guide

- serving/samples/source-to-url-go/README.md
- fix the indentation error of the code block, which causes a strange view while reading.
> fix the alignment bugs

- serving/samples/helloworld-scala/project/plugins.sbt
n/a
- use latest version of [sbt-native-packager]
> sbt-native-packager 1.3.17

- docs/serving/README.md
- docs/serving/deploying-with-private-registry.md
>  adding frontmatter; cherry-picking commit into 0.3

- community/ROLES.md
Add a note in Approvers section saying that one path to get the reviews is adding yourself to reviewers section in the OWNERS file.
> Add a note about using reviewers section to get PRs assigned to you

- serving/samples/helloworld-go/Dockerfile
Better to put ptag so we're not flying in the air.
/cc  @grayside
> helloworld-go: add go image tag

- docs/serving/gke-assigning-static-ip-address.md
- Add spacing around code snippets in order to fix Markdown rendering issues when they are displayed in a list on the website: https://www.knative.dev/docs/serving/gke-assigning-static-ip-address/
> Add spacing around code snippets to fix rendering issues

- serving/installing-logging-metrics-traces.md
> Fix wrong Stackdriver logging config path

- install/scripts/knative-with-openshift.sh
> make install/scripts/knative-with-openshift.sh +x and -e

- serving/installing-logging-metrics-traces.md
To reflect version v0.4.0 we need to update file version on this file.
> Update the monitoring file version

- docs/reference/README.md
adding edits from PR #1008 
(prow was faster than the UI (merge 42s after accidental lgtm)
> Incorporate edits from #1008

- docs/serving/samples/hello-world/helloworld-python/Dockerfile
- docs/serving/samples/hello-world/helloworld-python/README.md
Python currently tracks latest, to minimize potential for progression rot, let's track Python 3.7.
/cc @averikitsch
> serving/samples/hello-world: pin python to 3.7

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
Background info in #968  and work tracking for upcoming fix to install commands in #1036
> Add note about retrying install commands on failure

- doc-releases.md
- Add release-0.4 to repo list of available doc versions
- Add link to knative.dev
- Suggest site for users and repo for contributors
> update list of released versions

- docs/build/builds.md
Markdown shows if used in hugo frontmatter - removed code tags
> remove markdown from frontmatter

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
- vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
- vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
> update deps: update knative/test-infra to latest

- docs/concepts/resources.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
Cherry-pick for:
#1046 
#1051 
#1053
> Cherry-pick commits into v0.4

- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/hello-world/helloworld-shell/_index.md
add Hugo required _index.md and frontmatter to sample to render content in website
> add website files for shell sample

- docs/serving/samples/hello-world/helloworld-csharp/README.md
- docs/serving/samples/hello-world/helloworld-csharp/Startup.cs
- docs/serving/samples/hello-world/helloworld-go/README.md
- docs/serving/samples/hello-world/helloworld-java/README.md
- docs/serving/samples/hello-world/helloworld-java/src/main/java/com/example/helloworld/HelloworldApplication.java
- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/src/main/kotlin/com/example/hello/Main.kt
- docs/serving/samples/hello-world/helloworld-nodejs/Dockerfile
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-php/index.php
- docs/serving/samples/hello-world/helloworld-python/README.md
- docs/serving/samples/hello-world/helloworld-ruby/README.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/samples/hello-world/helloworld-shell/script.sh
- docs/serving/samples/hello-world/helloworld-shell/service.yaml
- test/e2e/config.yaml
Consolidating helloworld sample apps output, so that they are using the same pattern, also makes sure README.md files are consistent with source code
> Consolidate helloworld sample apps output and make sure instruction consistent with source code

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
as per title.
steps:
* updated yaml
* run the generator, and check in the MD file changes 
/cc @evankanderson @dubee
> Adding Apache Kafka source ref.

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- fix small typo Quele => Queue
-
> fix typo Quele -> Queue

- docs/eventing/sources/README.md
- docs/eventing/sources/generator/ReadmeTemplate.gomd
- docs/eventing/sources/sources.yaml
- Add a link to proof of concept FTP/SFTP source.
-
-
> add a link to ftp source

- docs/eventing/README.md
Related to
- https://github.com/knative/eventing-sources/pull/188
- https://github.com/knative/docs/pull/1104
- https://github.com/knative/docs/pull/1107
- Added details for CamelSource to https://github.com/knative/docs/tree/master/docs/eventing#sources and included link to example.
> Added details for Camel Source and link to example

- docs/install/Knative-with-GKE.md
> #fixitfriday website rendering for GKE install

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
I've updated the `yaml` and run the generator.
> Update sources to include Apache Camel

- docs/build/installing-build-component.md
the code block formating got smooshed into the paragraph above
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> build: code block was smooshed

- docs/install/Knative-with-GKE.md
> Conflict message removed.

- .github/pull-request-template.md
- Gives info about what branch to open your PR against.
- Explains cherry-picking process
> Update PR template with branch info

- docs/reference/serving.md
Update generated documentation to commit 0be6e87 in
preparation for cutting 0.5.
Related #1078
> Updated generated documentation for serving

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
- Updates  the test-infra dependency in vendor
> Update dep for test-infra

- docs/serving/samples/autoscale-go/README.md
https://github.com/knative/docs/issues/1088
Fixes small error in `export IP_ADDRESS` step which causes an error later on in the sample.
> fix export IP Address step

- docs/eventing/samples/gcp-pubsub-source/README.md
Fixes #891 
Remove reference to `Subscriber` section which was previously removed, and rephrase the reference a bit.
> #fixit remove ref to subscriber

- community/samples/serving/helloworld-dart/.gitignore
- community/samples/serving/helloworld-dart/bin/server.dart
- community/samples/serving/helloworld-dart/pubspec.lock
- community/samples/serving/helloworld-dart/pubspec.yaml
- Format server file
- Fix bug when running server without a port specified
- Update dependencies
- Small tweaks to pubspec file
> Update community Dart sample

- docs/install/README.md
> link Install to openshift-cloud-functions/knative-operators

- docs/_index.md
Other half of fix in knative/website PR: https://github.com/knative/website/pull/28
Staged: https://websiteinfra2--knative-v1.netlify.com/
> add 'Documentation' to main menu

- docs/install/Knative-custom-install.md
> Cherry-pick: Fix broken resource links (#1163)

- community/samples/serving/helloworld-dart/.gitignore
- community/samples/serving/helloworld-dart/bin/server.dart
- community/samples/serving/helloworld-dart/pubspec.lock
- community/samples/serving/helloworld-dart/pubspec.yaml
- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- docs/install/Knative-with-Minishift.md
- docs/install/README.md
Cherry-pick #981 #982 #1058 #1153
> Release 0.5

- blog/_index.md
- blog/articles/_index.md
- blog/articles/knative-v0-3-autoscaling-a-love-story.html
- blog/events/_index.md
- blog/releases/_index.md
Fix the date and reordered the blogs
Related: https://github.com/knative/website/pull/33/
> More fixes to blogs

- contributing/WORKING-GROUPS.md
Fixes #1175 
- Change slack links from knative.slack.com to slack.knative.dev
-
-
> knative.slack.com -> slack.knative.dev

- docs/install/Knative-with-IKS.md
> Mention IKS's one-click install process

- docs/install/Knative-with-Minishift.md
- docs/install/getting-started-knative-app.md
- docs/serving/samples/blue-green-deployment.md
- docs/serving/samples/build-private-repo-go/README.md
In the process of reading, I try to fix these spelling mistakes.
> Fix some spelling mistakes in docs

- contributing/DOCS-CONTRIBUTING.md
- doc-releases.md
Add docs PR details:
- docs
- code samples
- branches
- cherry picks
+ add 0.5 release to the list of releases page
> Update docs contributor guidelines

- docs/build/auth.md
- docs/eventing/debugging/README.md
- docs/eventing/samples/cronjob-source/README.md
Cherrrypick: fix some spelling mistakes of docs (#1188)
> Cherrrypick: fix some spelling mistakes of docs (#1188)

- docs/install/Knative-with-Minishift.md
- docs/install/getting-started-knative-app.md
- docs/serving/samples/blue-green-deployment.md
- docs/serving/samples/build-private-repo-go/README.md
Cherrypick: fix some spelling mistakes in docs (#1200)
> Cherrypick: fix some spelling mistakes in docs (#1200)

- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-clojure/_index.md
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-dart/_index.md
- community/samples/serving/helloworld-elixir/README.md
- community/samples/serving/helloworld-elixir/_index.md
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-haskell/_index.md
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-rust/_index.md
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-swift/_index.md
- community/samples/serving/helloworld-vertx/README.md
- community/samples/serving/helloworld-vertx/_index.md
create new _index.md files for each community sample and move all titles into frontmatter
issue: #1213
> add _index.md files for community samples

- community/samples/README.md
- community/samples/_index.md
- docs/build/README.md
- docs/build/samples.md
- docs/concepts/_index.md
- docs/eventing/debugging/_index.md
- docs/eventing/samples/_index.md
- docs/samples.md
- docs/serving/samples/README.md
- docs/serving/samples/_index.md
Cherry-pick PR #1218
cc/ @rgregg
> cherry-pick #1218 - add samples landing pages

- docs/build/samples.md
fix the link to the all samples page
> fix broken link

- docs/eventing/README.md
> Cherry-pick: Fix a typo in Eventing doc (#1221)

- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-php/index.php
Render the "\n" newline character as a newline.
> serving/samples/helloworld-php: render newline

- docs/eventing/samples/cronjob-source/cronjob-source.yaml
@mattmoor  the service is call `event-display`
> fix broken demo

- docs/serving/samples/hello-world/helloworld-java-spark/Dockerfile
- docs/serving/samples/hello-world/helloworld-java-spark/src/main/java/com/example/helloworld/HelloWorldApplication.java
Fixes #1204 
Removed the PORT environment variable from Docker file and Java Code.
> Removing the PORT environment variable from Docker file and Java code.

- docs/eventing/samples/apache-camel-source/README.md
- docs/eventing/samples/apache-camel-source/_index.md
- docs/eventing/samples/apache-camel-source/display_resources.yaml
- docs/eventing/samples/apache-camel-source/dumper_resources.yaml
- docs/eventing/samples/apache-camel-source/source_telegram.yaml
- docs/eventing/samples/apache-camel-source/source_timer.yaml
This adds some examples of CamelSources with instructions on how to run them.
> Add example about using CamelSource

- README.md
As discussed in the Docs wg meeting, here is a proposed change to the README.
Nothing earth shattering but a bit more dev friendly instead of just bouncing folks to go to the website.
Also added support and code of conduct paragraphs. Even though this is available in the contributing guidelines I always like to see them upfront.
> improve readme to be a bit more friendly

- docs/eventing/README.md
Followup to https://github.com/knative/eventing-sources/pull/351
- Mention the KafkaSource net attribute in the eventing README
> eventing/README: add KafkaSource net attribute

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Major change:
- Install Istio via GKE Addon instead of from the one published by knative/serving, as serving has stopped publishing it
> [RELEASE-0.5]update test-infra to make presubmit test succeed

- community/samples/serving/helloworld-vertx/README.md
- docs/README.md
- docs/eventing/samples/cronjob-source/cronjob-source.yaml
- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-Minishift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-php/index.php
- docs/serving/samples/traffic-splitting/README.md
From PRs:
#1196 
#1206 
#1224 
#1242 
#1243 
#1258 
#1273 
#1277
> Cherry-pick batch

- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/_index.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/serviceaccount.yaml
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
- docs/eventing/sources/README.md
Fixes https://github.com/knative/docs/issues/1301
Migrate the sample to do the same thing but use the `ApiServerSource`.
> Update KubernetesEventSource to use ApiServerSource

- docs/serving/samples/buildpack-app-dotnet/README.md
- docs/serving/samples/grpc-ping-go/README.md
- docs/serving/samples/telemetry-go/Dockerfile
Fixes https://github.com/knative/docs/issues/1294
-
-
-
> Fix telemetry Dockerfile and typo

- community/samples/serving/helloworld-clojure/Dockerfile
- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-dart/Dockerfile
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-elixir/Dockerfile
- community/samples/serving/helloworld-elixir/README.md
- community/samples/serving/helloworld-haskell/Dockerfile
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-rust/Dockerfile
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-vertx/Dockerfile
- community/samples/serving/helloworld-vertx/README.md
- docs/install/Knative-with-Gloo.md
- docs/serving/samples/hello-world/helloworld-java-spark/README.md
- docs/serving/samples/secrets-go/Dockerfile
- docs/serving/samples/secrets-go/README.md
Fixes remaining part of #1204 
Removed the ENV PORT environment variable from all Docker files.
> Removed ENV PORT from all Docker files

- docs/serving/deploying-with-private-registry.md
> Remove repeat content

- docs/serving/installing-istio.md
https://github.com/knative/docs/issues/1244
A new doc about installing custom Istio.
More context: we will not ship Istio with Knative in Knative 0.6 and after. Therefore, we need a doc for users to install custom Istio for the use with Knative
> Doc about installing Istio from official source

- docs/eventing/samples/container-source/README.md
- docs/eventing/samples/container-source/_index.md
- docs/eventing/samples/container-source/heartbeats-source.yaml
- docs/eventing/samples/container-source/service.yaml
- docs/eventing/samples/writing-a-source/README.md
Fixes https://github.com/knative/eventing-sources/issues/31 partially
- Add a sample for ContainerSource event source
> Add sample for ContainerSource event source

- docs/serving/samples/blue-green-deployment.md
Fixes #1316 
Since ~0.5 revision names are not `00001` and subsequent increment. There have a generated name.
Thus the blue green sample, which is our second guide in the landing page is Broken.
this PR fixes that by adding a `kubectl command` to get the revision names.
> Use proper revision names in blue green sample

- docs/eventing/samples/container-source/README.md
- docs/serving/samples/autoscale-go/README.md
> add -b branch and fix codeblocks

- docs/install/Knative-custom-install.md
- Remove warning about Gloo/eventing incompatibility.
- Update table of eventing and eventing-sources components in custom install instructions.
> Update custom install docs for eventing

- docs/serving/using-auto-tls.md
There is a small formatting error that makes the page look weird
> Fix formatting on auto tls

- docs/eventing/README.md
Goes with https://github.com/knative/eventing-sources/pull/407
- Mention new `spec.net.tls` attributes
> eventing/README: add new KafkaSource net.tls attributes

- docs/eventing/broker-trigger.md
- Copy the updates from knative/eventing#1241.
> Copy the updates from knative/eventing#1241.

- community/samples/serving/_index.md
- community/samples/serving/helloworld-java-micronaut/_index.md
- community/samples/serving/helloworld-java-quarkus/_index.md
add missing _index.md file
and fix Java short titles
> Fix community samples sub menu

- OWNERS_ALIASES
- test/OWNERS
Part of knative/test-infra#579
> Use OWNERS_ALIASES for productivity approvers/reviewers

- docs/serving/samples/rest-api-go/README.md
Fixes #1369
- Add some explanations on how to look up stock tickers for non-financial experts
> Add some explanations on valid stock tickers

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
Part of #https://github.com/knative/test-infra/issues/829
update test-infra in vendor
> update test-infra in vendor

- docs/serving/samples/hello-world/helloworld-java-spring/README.md
* Fix first shell block
* Fix numbering by applying the correct indentation to text in all steps
> Fix markdown

- docs/build/README.md
> typo in build readme

- docs/install/installing-istio.md
Following the documentation produces:
Error from server (NotFound): error when creating "istio.yaml": namespaces "istio-system" not found
Create instead the istio-system namespace before the actual installation steps start, using the same method as in the current master.
> Fix the broken Istio installation command

- docs/README.md
no issue
- remove an unnecessary comma on the doc
> remove an unnecessary comma

- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Minikube.md
- docs/install/README.md
- docs/serving/setting-up-a-logging-plugin.md
- docs/serving/using-auto-tls.md
pr #1418
pr #1397
pr #1360
pr #1356
pr #1351
> cherrypick changes from release-0.6 to master

- Gopkg.lock
- vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
- vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
- vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
- vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
- vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
- vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
- vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
- vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
- vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
- vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
e2e tests installing serving failed for wrong yaml path, this was fixed in test-infra. Bring the change in to fix e2e build
> update test-infra: fix build breaks

- docs/eventing/README.md
fixes https://github.com/knative/eventing-contrib/issues/453
> clarify when to send direct to broker

- docs/eventing/broker-trigger.md
As part of fix for https://github.com/knative/eventing/issues/1395.
/cc @samodell
> update BrokerTrigger.md for master branch:

- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-clojure/service.yaml
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-dart/service.yaml
- community/samples/serving/helloworld-elixir/README.md
- community/samples/serving/helloworld-elixir/service.yaml
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-haskell/service.yaml
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-rust/service.yaml
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-swift/service.yaml
- community/samples/serving/helloworld-vertx/README.md
- community/samples/serving/helloworld-vertx/service.yaml
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-Minikube.md
- docs/install/installing-istio.md
Original PRs:
#1412 
#1416 
#1430 
#1477
> Cherry-pick batch master --> 0.6

- docs/eventing/samples/kubernetes-event-source/README.md
…instructions.
Signed-off-by: Katherine Jackson <katjackson@google.com>
Fixes #1473 
- Added the contents of the yaml files referenced in the doc so that it is consistent with other docs in the set and so that users do not have to search for the files in the repo.
-
-
> Added yaml contents to doc. Fixes issue 1473

- docs/install/README.md
Fixes #1510
- Link to openshift-knative/docs repo
> Updated link for Knative Install on OpenShift via Operator

- docs/serving/configuring-the-autoscaler.md
Fixes #1331 
- added config details for minScale
- added config details for maxScale
> Initial additions for minScale and maxScale annotations

- docs/_index.md
> add new 07 docs branch as default 

- docs/_index.md
This should be merged only when the release-0.7 branch has been created and the main menu config has been reconfigured there.
> Remove main menu config from 0.6

- Gopkg.lock
- vendor/github.com/knative/test-infra/scripts/README.md
- vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
- vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Bringing changes that fixes `0.7.x` serving release yaml not exist error
/cc @mattmoor
> [RELEASE-0.7]Update test-infra

- docs/install/Knative-with-OpenShift.md
Fixes #1550
- Updated image for installation procedure
> Update Image for Install Knative on OpenShift

- docs/install/Knative-with-OpenShift.md
- broken link in doc, changes point to correct page
> Fix broken link in Install Knative doc

- docs/serving/samples/hello-world/helloworld-java-spring/README.md
Fixes #1506
- Edited so only code is in code block 
- Corrected numbering
>  Formatting for Hello World Java Spring Procedure

- docs/eventing/samples/sequence/_index.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/_index.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/_index.md
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/_index.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/_index.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/reference/README.md
- docs/reference/build.md
- docs/reference/eventing/eventing-contrib-api.md
- docs/reference/eventing/eventing-contrib-resources.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
- docs/serving/knative-kubernetes-services.md
Cherry-pick batch
Includes PRs:
#1536  
#1543 
#1557 
#1558
> Cherry-pick batch master --> release-0.7

- docs/install/Knative-with-Minikube.md
Use current Istio version in Minikube install guide
> Use current Istio version in Minikube install guide

- docs/serving/accessing-logs.md
- docs/serving/installing-logging-metrics-traces.md
> Update logs metrics

- docs/reference/build.md
- docs/reference/eventing/eventing-contrib-resources.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Updated version of 07 API using revised API build script (#1559)
> 07 api from new version of script

- blog/_index.md
- community/_index.md
- contributing/_index.md
All main menu configuration now lives in the sites default config.toml
https://github.com/knative/website/pull/61
> Remove all other main menu configuration out of the files

- docs/install/Knative-with-OpenShift.md
- correct image path so that images render
> Update Knative on OpenShift with images on Knative.dev

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Minikube.md
- docs/install/README.md
* Add instructions for installing Knative with Ambassador
Signed-off-by: nbkrause <krausenoah@gmail.com>
* Update style
Signed-off-by: nbkrause <krausenoah@gmail.com>
* typo fixes
* Update and alphabetize installation options
Signed-off-by: nbkrause <krausenoah@gmail.com>
* Fix title
Signed-off-by: nbkrause <krausenoah@gmail.com>
* Link to Knative-Ambassador docs
Fixes #issue-number https://github.com/knative/docs/pull/1594
- Cherry-pick of https://github.com/knative/docs/pull/1594
-
-
> Add Documentation for Install Knative with Ambassador (#1594)

- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- The bug: https://github.com/knative/eventing/issues/1421 has been fixed, remove the comments saying it doesn't.
- add section showing the resulting output.
-
> sequence with broker works, update docs

- docs/serving/samples/hello-world/helloworld-python/README.md
correct a link in this document.
- knative-docs/serving/samples/hello-world/helloworld-python --> knative-docs/docs/serving/samples/hello-world/helloworld-python
> Update a website in README.md

- docs/install/Knative-with-Docker-for-Mac.md
> Change version for istio and knative serving in docker for mac

- docs/install/Knative-with-any-k8s.md
This line is too long for most monitors.
> line too long

- docs/eventing/README.md
- Points to new samples that were moved in https://github.com/knative/eventing-contrib/pull/426
> Update Broken Kafka Sample Link

- docs/install/getting-started-knative-app.md
Fixes #1484 
- Break up some of the larger code blocks so it is clear what is a command and what is a return value
-
-
> Some formatting changes to address #1484.

- docs/eventing/samples/apache-camel-source/source_camel_k.yaml
corrects broken link
Fixes #
- Fixes link in README for Camel sources
-
-
> Create source_camel_k.yaml in samples directory

- docs/serving/cluster-local-route.md
- Rewrite the cluster-local route topic to be more descriptive and share more about why you would do it and the options available for how.
-
-
> Rewrite the cluster-local route topic

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- fix broken links to various eventing sources.
> fix broken links.

- docs/serving/samples/hello-world/helloworld-php/Dockerfile
- docs/serving/samples/hello-world/helloworld-php/README.md
The current main PHP version is 7.3.
- Update Dockerfile to pull from php:7.3-apache instead of php:7.2-apache
> serving/samples: update helloworld-php to php 7.3

- community/samples/_index.md
- docs/_index.md
- docs/build/_index.md
- docs/eventing/_index.md
- docs/eventing/samples/writing-a-source/_index.md
- docs/install/_index.md
- docs/serving/_index.md
- docs/serving/samples/_index.md
Details in dependent change: https://github.com/knative/website/pull/66
> revert to README.md to prevent index/_index conflict

- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Fix some error, details please check the commit, thanks
- yaml format
- Duplicate name of `Trigger`
> Correct some error in "knative/docs/docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md"

- docs/eventing/choice.md
- docs/eventing/samples/choice/README.md
- docs/eventing/samples/choice/_index.md
- docs/eventing/samples/choice/multiple-cases/README.md
- docs/eventing/samples/choice/multiple-cases/_index.md
- docs/eventing/samples/choice/multiple-cases/choice.yaml
- docs/eventing/samples/choice/multiple-cases/cron-source.yaml
- docs/eventing/samples/choice/multiple-cases/event-display.yaml
- docs/eventing/samples/choice/multiple-cases/filters.yaml
- docs/eventing/samples/choice/multiple-cases/transformers.yaml
- docs/eventing/samples/choice/mutual-exclusivity/README.md
- docs/eventing/samples/choice/mutual-exclusivity/_index.md
- docs/eventing/samples/choice/mutual-exclusivity/choice.yaml
- docs/eventing/samples/choice/mutual-exclusivity/cron-source.yaml
- docs/eventing/samples/choice/mutual-exclusivity/event-display.yaml
- docs/eventing/samples/choice/mutual-exclusivity/switcher.yaml
- docs/eventing/samples/choice/mutual-exclusivity/transformers.yaml
Fixes #1623 
- Add documentation for the new Choice CRD
- Add multiple case sample
- Add mutual exclusivity sample
> choice documentation and samples

- docs/build/samples.md
- docs/install/Knative-custom-install.md
- docs/install/installing-istio.md
- docs/serving/README.md
- docs/serving/debugging-performance-issues.md
- docs/serving/fluentd-requirements.md
- docs/serving/samples/hello-world/helloworld-shell/README.md
- docs/serving/using-a-tls-cert.md
> Sam fixes some links

- docs/eventing/choice.md
- docs/eventing/samples/choice/multiple-cases/README.md
- docs/eventing/samples/choice/mutual-exclusivity/README.md
- docs/eventing/samples/choice/mutual-exclusivity/_index.md
- Choice: minor clarification and fix some typos
> Choice: minor clarification and fix some typos

- community/samples/serving/helloworld-r/.dockerignore
- community/samples/serving/helloworld-r/Dockerfile
- community/samples/serving/helloworld-r/HelloWorld.R
- community/samples/serving/helloworld-r/README.md
- community/samples/serving/helloworld-r/app.py
- community/samples/serving/helloworld-r/service.yaml
> Hello World Sample for R

- docs/eventing/README.md
add whitespace (to prevent odd rendering with Hugo shortcode `readfile`)
> fix https://knative.dev/development/eventing/

- docs/serving/samples/blue-green-deployment.md
> Change initail to initial.

- docs/install/Knative-custom-install.md
kafka is only in eventing-contrib now
> remove broken links

- docs/serving/knative-kubernetes-services.md
> Spelling fix

- docs/build/samples.md
- Fixing typo
- Improved language for better understanding
> Updating samples.md

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-any-k8s.md
- Cherry pick: Replace eventing.yaml with release.yaml in the install instructions to have a fully working system. (#1701)
> Cherry pick of #1701 into release-0.8

- docs/serving/samples/grpc-ping-go/client/client.go
> Enable SSL in client of grpc-ping-go sample.

- docs/README.md
- docs/build/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-Gloo.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-OpenShift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/README.md
- docs/install/installing-istio.md
- docs/serving/getting-started-knative-app.md
- docs/serving/samples/blue-green-deployment.md
Fix the redirect and also hardcode the new path in other files.
> fix redirect and revise hardcoded urls

- docs/README.md
- docs/build/README.md
- docs/eventing/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-Gloo.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-OpenShift.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/README.md
- docs/install/installing-istio.md
- docs/serving/getting-started-knative-app.md
- docs/serving/samples/blue-green-deployment.md
> Fix 404 in v0.8

- blog/articles/ko-fast-kubernetes-microservice-development-in-go.html
- blog/releases/announcing-knative-v0-5-release.html
this area of the site was missed in the last cycle
> fix broken images and links in blog

- docs/serving/setting-up-custom-ingress-gateway.md
There is no configmap named config-ingressgateway, it is named config-istio.
> Update configmap name to config-istio

- docs/install/Knative-with-Gloo.md
- docs/install/README.md
- docs/serving/using-auto-tls.md
Fixes #1690
- Update docs for Gloo installation & basic getting started
> update gloo install guide for knative serving 0.8.0

- docs/serving/getting-started-knative-app.md
- This commit fixes doc formatting which led to text being included in a shell blob.
> Fix doc formatting

- docs/samples.md
- Added a link to a more realistic sample using Knative eventing and serving.
-
-
> Adding Image processing sample to the list of external sample code

- docs/serving/samples/blue-green-deployment.md
Updated blue-green deployment sample with Knative 0.8 instructions
Fixes #1489
> Blue-green deployment update for 0.8

- docs/serving/getting-started-knative-app.md
- Add alternative shell command to delete a `kservice`.
> [DOC] Add alternative shell command to delete knative service 

- docs/serving/custom-metrics-API.md
- docs/serving/using-custom-metrics-API.md
Fixes #1519 
- Added details about checking for existing custom-metrics API and deleting an existing implementation if needed.
- new `using-custom-metrics-API.md` file.
> Added new section for custom-metrics API details

- docs/serving/accessing-traces.md
- update the accessing-traces instructions with instructions for config-tracing.yaml
> update with config instructions

- docs/serving/spec/knative-api-specification-1.0.md
RevisionSpec and RevisionMetadata links were broken.
-
-
-
> Fix broken links in API Spec

- docs/reference/eventing/eventing.md
- docs/reference/serving.md
> no markdown in the HTML

- docs/reference/eventing/eventing.md
- docs/reference/serving.md
> cherry-pick #1807

- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/index.js
- docs/serving/samples/hello-world/helloworld-python/Dockerfile
- test/sampleapp/config.go
- test/sampleapp/config.yaml
- test/sampleconsistency/sampleconsistency_test.go
Update error message with detailed explanation so that developers know how to debug if unit test ever failed.
Fix a bug in unit test.
Update all READMEs so that they are valid
Part of: #1793
> Update Helloworld unit test error message to make it actionable

- docs/serving/installing-logging-metrics-traces.md
Removed extraneous period and double quotes.
> Fixed minor typos.

- docs/eventing/samples/kafka/source/README.md
> Fix KafkaSource URL

- docs/serving/samples/knative-routing-go/README.md
This patch fixes the format of code block.
Please refer to https://knative.dev/docs/serving/samples/knative-routing-go/#apply-custom-routing-rule under `* Send a request to the Search service:`. The markdown of the code block is broken.
> Fix format

- docs/eventing/getting-started.md
> Correct eventing getting started to look for imc-controller (not old name)

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/installing-istio.md
Fixes https://github.com/knative/docs/issues/1842
- Add a step to install cluster local gateway when setting up cluster
> Add a step to install cluster local gateway when setting up cluster

- docs/install/Knative-with-MicroK8s.md
> Fix typo in microk8s doc

- docs/serving/knative-kubernetes-services.md
> minor typo fix

- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
> Add CouchDB event source

- OWNERS_ALIASES
> Add vaikas to OWNERS via new account

- docs/eventing/samples/gcp-pubsub-source/README.md
- docs/eventing/samples/gcp-pubsub-source/event-display.yaml
- docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
- docs/eventing/samples/gcp-pubsub-source/trigger.yaml
- docs/eventing/sources/README.md
- docs/eventing/sources/sources.yaml
- Cherrypicking change from master to release-0.10. 
- In particular, this https://github.com/knative/docs/pull/1950
> Cherry-picking changes to release 0.10

- Gopkg.lock
- test/presubmit-link-check.sh
- vendor/knative.dev/test-infra/scripts/README.md
- vendor/knative.dev/test-infra/scripts/e2e-tests.sh
- vendor/knative.dev/test-infra/scripts/library.sh
- vendor/knative.dev/test-infra/scripts/performance-tests.sh
- vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
- vendor/knative.dev/test-infra/scripts/release.sh
Also update test-infra for the latest goodness.
/assign @RichieEscarez 
/cc @eallred-google
> Add a script to check for dead links in markdown files

- docs/samples.md
- Add external link to a collection of eventing samples
> add external code samples

- community/samples/README.md
- community/samples/serving/helloworld-clojure/README.md
- community/samples/serving/helloworld-dart/README.md
- community/samples/serving/helloworld-haskell/README.md
- community/samples/serving/helloworld-java-micronaut/README.md
- community/samples/serving/helloworld-r/README.md
- community/samples/serving/helloworld-rserver/README.md
- community/samples/serving/helloworld-rust/README.md
- community/samples/serving/helloworld-swift/README.md
- community/samples/serving/helloworld-vertx/README.md
- docs/README.md
- docs/eventing/event-registry.md
- docs/eventing/getting-started.md
- docs/eventing/samples/README.md
- docs/eventing/samples/_index.md
- docs/eventing/samples/helloworld/README.md
- docs/eventing/samples/iot-core/README.md
- docs/eventing/samples/kafka/channel/README.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gloo.md
- docs/install/README.md
- docs/install/installing-istio.md
- docs/serving/cluster-local-route.md
- docs/serving/samples/blue-green-deployment.md
contributes to fixing items in #1750
/cc @adrcunha  @eallred-google 
related (for v0.10): #1974
> fix broken links (from link checking report tool testing)

- docs/eventing/samples/apache-camel-source/source_http_poller.yaml
- docs/eventing/samples/apache-camel-source/source_mqtt.yaml
- docs/eventing/samples/apache-camel-source/source_telegram.yaml
- docs/eventing/samples/apache-camel-source/source_timer.yaml
- Update Camel Source examples to reflect usage of "Destination" introduced with https://github.com/knative/eventing-contrib/pull/700
> Update camel examples to reflect recent changes

- contributing/new-page-template.md
- Adds a template with some guide text for creating a new page.
- Uses comments to explain how to fill out frontmatter
> Template for new Docs pages

- docs/install/Knative-with-Gloo.md
- Update Gloo docs for knative 0.10.0
> fix gloo docs for 0.10.0 release

- docs/install/installing-istio.md
> Typo - WhiteSpace added

- OWNERS_ALIASES
Adding Ashleigh to the Docs Reviewers list. (Checking to see if this will give her any additional permissions, like editing projects and labels directly, which she needs.)
> Add abrennan89 to Docs Reviewers list

- docs/eventing/samples/cronjob-source/README.md
- docs/eventing/samples/kubernetes-event-source/README.md
doc updates for https://github.com/knative/eventing/pull/2259
/assign @nachocano
> reflecting 1.0 CE payload

- docs/client/README.md
- docs/client/_index.md
Fixes #2039
- Added 'client' folder with README and _index .md files
- Bare bones for now, will flesh out additional details as I have them
- Mentioned client in main docs README
> Initial commit for CLI section

- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Generated API reference docs for v0.11.0 using the fix from #2054
> v0.11.0 serving, eventing, eventing-contrib API reference docs

- docs/serving/samples/grpc-ping-go/proto/ping.pb.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
/assign samodell
/cc samodell
> golang format tools

- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
> v0.11.0 serving, eventing, eventing-contrib API reference docs (#2055)

- blog/steering/2019-12-updates.md
- blog/steering/_index.md
New blog post with an update from the Steering committee.
> Update from the steering committee

- blog/steering/2019-12-updates.md
Clarify sponsorship to indicate that all are welcome.
> Update 12/2019 blog post

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/installing-istio.md
add the instruction to install cluster local gateway
This PR just cherrypicks the change https://github.com/knative/docs/pull/1894 into master branch
> add the instruction to install cluster local gateway

- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-ICP.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/install/installing-istio.md
- docs/serving/deploying/private-registry.md
cherry-pick #1911 and #2027
* add the instruction to install cluster local gateway (#1911)
* How to use a private registry (#2027)
> cherry-pick #1911 and #2027

- docs/serving/getting-started-knative-app.md
Fixes https://github.com/knative/serving/issues/6101
This page is the entry point for someone looking to deploy their first knative app and best place to put this info.
As you can see in this issue https://github.com/knative/serving/issues/6101 some people try using locally built images for ease of use and fail to get it to work since knative resolves images a little bit differently.
> Add instruction on how to use local docker registry

- docs/eventing/getting-started.md
- docs/install/Knative-custom-install.md
- docs/install/Knative-with-AKS.md
- docs/install/Knative-with-Ambassador.md
- docs/install/Knative-with-Docker-for-Mac.md
- docs/install/Knative-with-GKE.md
- docs/install/Knative-with-Gardener.md
- docs/install/Knative-with-Gloo.md
- docs/install/Knative-with-IKS.md
- docs/install/Knative-with-Minikube.md
- docs/install/Knative-with-PKS.md
- docs/install/Knative-with-any-k8s.md
- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
- hack/reference-docs-gen-config.json
Bump the min k8s version to 1.15 in doc as we have already bumped the k8s version to 1.15 in other knative repo.
/cc @mattmoor
> Bump the min k8s version to 1.15

- docs/eventing/samples/github-source/README.md
- docs/eventing/samples/github-source/github-source.yaml
- docs/eventing/samples/github-source/service.yaml
- Update the github source example to use the new destination shape.
- Use eventing-contrib's release of event-display
> update minor api updates for github source.

- docs/eventing/samples/apache-camel-source/README.md
- Fix link to yaml file in MQTT CamelSource sample.
> Fix link to yaml file in MQTT CamelSource sample

- docs/install/check-install-version.md
- The previous one will meet error if user copy the cmd and run directly.
This one is more convenient for user to test the cmd.
> Update check version cmd

- docs/reference/client/README.md
- docs/reference/client/_index.md
Removing this stub directory since we need to release the docs today.
> Removing directory temporarily

- docs/install/README.md
> Remove superfluous conjunction

- docs/eventing/event-registry.md
> fix english

- community/samples/README.md
- docs/eventing/samples/kafka/source/event-display.yaml
> Cherry-pick batch on 1/31 into release-0.12

- blog/steering/2020-01-annual-report-2019.md
- community/annual_reports/README.md
- community/annual_reports/_index.md
Fixes https://github.com/knative/community/issues/72
Adds doc an blog post about the 2019 Annual Report from the Steering Committee. Also apologies if I didn't get my docs-foo right!
> Adds doc and blog post for 2019 report

- blog/steering/2020-01-annual-report-2019.md
- Fixes year for blog post date
> Fixes year for blog post date

- blog/steering/2020-01-annual-report-2019.md
* Adds alias to point to the 2019 link
> Adds alias for 2019 link

- docs/serving/using-auto-tls.md
* Fix auto tls typo: `namespace` -> `Knative Service`
> Fix auto tls typo

- docs/eventing/samples/kafka/README.md
- docs/eventing/samples/kafka/kafka.yaml
- docs/eventing/samples/kafka/kafka_setup.sh
As per @vaikas request on the Channels WG, here is a simple script for installing Apache Kafka.
This is much easier to follow, instead of sending folks to different websites and have them execute commands from there
/assing @vaikas
> Adding better Kafka install doc

- docs/install/knative-with-any-k8s.md
... now that we have nightly releases that do this!
/hold
Wait for: https://github.com/knative/serving/pull/6758
> Separate the Contour and KIngress installs.

- docs/install/knative-with-any-k8s.md
This reverts commit b59a3d97f00de8dc6c627790d44261c6d56ef53a.
Want to give this more time for community feedback.
> Revert "Reflect the separation of the Channel-based Broker. (#2182)"

- docs/install/Knative-with-Gloo.md
```
$ glooctl --version
Error: unknown flag: --version
Usage:
glooctl [command]
Available Commands:
add         Adds configuration to a top-level Gloo resource
check       Checks Gloo resources for errors (requires Gloo running on Kubernetes)
completion  generate auto completion for your shell
create      Create a Gloo resource
dashboard   Open Gloo dashboard
debug       Debug a Gloo resource (requires Gloo running on Kubernetes)
delete      Delete a Gloo resource
edit        Edit a Gloo resource
get         Display one or a list of Gloo resources
help        Help about any command
install     install gloo on different platforms
proxy       interact with proxy instances managed by Gloo
remove      remove configuration items from a top-level Gloo resource
route       subcommands for …
```
> Update the glooctl version command

- docs/serving/configuring-autoscaling.md
- docs/serving/using-auto-tls.md
> Cherry-pick 2.10.20

- smoketest.md
https://github.com/knative/website/pull/124 must be merged first.
> Add tabs to smoketest page

- docs/serving/samples/hello-world/helloworld-java-spring/Dockerfile
- docs/serving/samples/hello-world/helloworld-java-spring/README.md
- docs/serving/samples/hello-world/helloworld-java-spring/src/main/java/com/example/helloworld/HelloworldApplication.java
- docs/serving/samples/hello-world/helloworld-java-spring/src/main/resources/application.properties
- Instead of a using a flag to set port, set port in code
> Update Java Spring boot sample to programmatically get PORT

- docs/install/knative-with-any-k8s.md
> Revert "Revert "Reflect the separation of the Channel-based Broker. (#2182)""

- docs/install/knative-with-any-k8s.md
BASED on: #2194
Changes:
* Adding content for NATSS Channel install
/assign @Abd4llA  please review
> Natss install

- docs/install/knative-with-any-k8s.md
DO NOT merge this until https://github.com/knative/serving/pull/6663
is merged
> Add pointer to monitoring-core.yaml

- docs/install/knative-with-any-k8s.md
I should have caught these in code review, but I'll blame github for showing such tight code blocks ;-)
1. Couple missed artifact shortcodes,
2. Alphabetize Channels,
3. Fix some wording around Broker installation that is inaccurate.
> A couple little cleanups.

- docs/install/knative-with-any-k8s.md
Needs: https://github.com/knative/website/pull/136
cc @rgregg (see the linked PR for screenshot)
> Use the feature-state shortcode in install docs.

- docs/serving/samples/gitwebhook-go/README.md
- Fixed the webhook sample path to match the new /docs/ path.
> Fixed webhook sample path

- docs/install/upgrade-installation.md
Adds information on upgrading Knative.
Fixes #130
> Add upgrading your install file

- docs/eventing/samples/helloworld/helloworld-go/README.md
This commit updates the helloworld-go README.md, step 4
("Recreating the sample code" section), and adds {username}
to the example yaml which is mentioned in the description.
> Add {username} to helloworld-go service definition

- docs/install/upgrade-installation.md
> Fix typo in "upgrading your install"

- docs/eventing/samples/writing-receive-adapter-source/01-theory.md
- docs/eventing/samples/writing-receive-adapter-source/02-lifecycle-and-types.md
- docs/eventing/samples/writing-receive-adapter-source/03-controller.md
- docs/eventing/samples/writing-receive-adapter-source/04-reconciler.md
- docs/eventing/samples/writing-receive-adapter-source/05-receive-adapter.md
Fixes #2213 2213
- updating doc, to capture changes from https://github.com/knative/sample-source/pull/11 in the tutorial
/assign @n3wscott
> Updating sample doc for some changes for +genreconciler

- docs/install/knative-with-any-k8s.md
Reflect the changes to the namespace/service to use for IP/CNAME.
> Update contour install.

- docs/serving/using-auto-tls.md
Fixes #https://github.com/knative/serving/issues/6980
> Fix version typo in using-auto-tls.md

- docs/knative-offerings.md
- Adds triggermesh cloud to the list of knative-offerigns
> add triggermesh to the list of knative offerings

- docs/install/installing-istio.md
Fixes #2228 
- Changed capitalized SDS to lowercase sds so the link will work
> Fix istio sds link in installing istio

- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
Updates to Eventing API docs for v0.13.0 
* eventing-contrib.md
* eventing.md
-
-
-
> Eventing API docs for v0.13.0

- docs/install/README.md
- docs/install/any-kubernetes-cluster.md
Related: https://github.com/knative/docs/issues/2265
> Rename knative-with-any-k8s for better SEO

- docs/reference/eventing/eventing-contrib.md
- docs/reference/eventing/eventing.md
- docs/reference/serving.md
Adds Serving API 0.13.0 docs
-
-
-
> Updated Serving API docs for 0.13.0

- docs/install/any-kubernetes-cluster.md
Fixes: https://github.com/knative/serving/issues/7043
> Adopt the builds from knative.dev/net-istio

- Gopkg.lock
- vendor/knative.dev/test-infra/scripts/README.md
- vendor/knative.dev/test-infra/scripts/e2e-tests.sh
- vendor/knative.dev/test-infra/scripts/library.sh
- vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
- vendor/knative.dev/test-infra/scripts/performance-tests.sh
- vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
- vendor/knative.dev/test-infra/scripts/release.sh
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign dprotaso grantr samodell
/cc dprotaso grantr samodell
> Auto-update dependencies

- docs/install/any-kubernetes-cluster.md
I must have missed this because the MD link checked is dying here: https://github.com/knative/serving/pull/7167
This is a cherrypick of #2286
> [RELEASE 0.13] Add a minishift redirect

- docs/eventing/accessing-traces.md
- docs/eventing/event-delivery.md
- docs/eventing/event-registry.md
- docs/eventing/getting-started.md
- use lowercase title to be consistent with the rest of the doc
-
-
> use lowercase title to be consistent with the rest of the doc

- docs/eventing/channel-based-broker.md
- With https://github.com/knative/eventing/pull/2034 we can now also create a broker, using an annotation on the Trigger. Added documentation for that
-
/assign @grac3gao
> Documenting the Trigger annotation case for the Broker creation

- docs/eventing/samples/sinkbinding/README.md
- updating the log to the latest of the actual source 
/assign @mattmoor 
/assign @samodell
> CloudEvent version 1.0 and latest log details

- docs/eventing/migration/README.md
- docs/eventing/migration/_index.md
- docs/eventing/migration/ping.md
- docs/eventing/migration/sinkbinding.md
Fixes #2275 
- Cherry pick #2275 and #2297
> Cherry-pick 0.13 migration docs to 0.13 release branch

- docs/eventing/samples/ping-source/README.md
- docs/eventing/samples/ping-source/ping-source.yaml
- docs/eventing/samples/ping-source/service.yaml
Cherry pick of: #2126
Fixes: #2294
Document ping source.
-
-
-
> [RELEASE 0.13] Cherrypick 2126

- docs/eventing/channel-based-broker.md
#2282 was the original one but for some reason it can't be updated.
- The instruction to create RBACs for reading configmaps from the system namespace is removed since we now copy configmaps into user namespace.
- Added instruction to propagate the required configmaps to user namespace.
> Update broker installation doc to include ConfigMapPropagation.

- docs/eventing/channels/channels-crds.md
- docs/eventing/channels/channels.yaml
- link to each channel documentation instead of the code. 
-
-
> link to each channel documentation instead of the code

- docs/install/any-kubernetes-cluster.md
- add couchdb source as optional install
-
> add couchdb source as optional install

- docs/install/README.md
Fixes #2245
- Change the description about the relation of serving and Istio.
> Fix doc error about eventing requiring Istio

- docs/eventing/samples/container-source/README.md
Fixes #2179 
- Update the image so that the container has the correct logs instead of errors.
> Updated image location for container-source

- docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
Fixes broken `steps.yaml` file for Sequence with Broker and Trigger sample.
> Fix third function image definition

- Gopkg.lock
- vendor/knative.dev/test-infra/scripts/README.md
- vendor/knative.dev/test-infra/scripts/library.sh
- vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign dprotaso grantr samodell
/cc dprotaso grantr samodell
> [master] Auto-update dependencies

- docs/install/any-kubernetes-cluster.md
/hold
A lot of stuff needs to land before this is usable, and I need to run through them once we are actually producing nightly builds to make sure I got everything right.
cc @ZhiminXiang
> Document how to install net-http01

- docs/serving/deploying/private-registry.md
- Change the section for adding image pull secrets to use patch instead of editing the resource.
> edit -> patch

- docs/install/any-kubernetes-cluster.md
/assign @mdemirhan @evankanderson 
/hold
Holding to see that things look properly via stagedocs-bot.
> Deprecate the observability plugin

- docs/serving/samples/hello-world/helloworld-php/README.md
> replace go with PHP in PHP sample

- docs/serving/samples/gitwebhook-go/README.md
> Fix typo secert => secret

- Gopkg.lock
- vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Picking up fix to `presubmit-tests.sh` from test-infra.
> Update deps for https://github.com/knative/docs/pull/2377

- docs/install/upgrade-installation.md
Documentation for https://github.com/knative/serving/issues/6726
- Include documentation that users may be required to migrate resources to the latest storage
> Upgrade documentation includes notes about storage version migration

- docs/serving/installing-cert-manager.md
- Current cert manager installation steps were old
- Updated the steps to look for steps in the cert manager website to install
> cert manager installation steps changes

- docs/serving/samples/autoscale-go/README.md
Fixes #2293 
- Updated the link to master so that it has the correct config. (not sure if we are avoiding this to not break links later on?)
> Updated link to autoscale default

- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/heartbeats-source.yaml
- docs/eventing/samples/sinkbinding/sinkbinding.yaml
> Fix sink/binding sample

- docs/serving/installing-cert-manager.md
- Bump supported cert-manager version to 0.12
> Bump supported cert-manager version to 0.12

- docs/eventing/samples/kafka/source/event-source.yaml
in knative/eventing-contrib#1156 we've updated the format for the
topics and bootstrapServer to be lists, update example accordingly
----
#
> Update KafkaSource example with updated bootstrapServer, Topics format

- OWNERS_ALIASES
Adding myself to reviewers to help out with reviews
- add mpetason to reviewers for docs under OWNER_ALIASES
-
-
> Adding myself to reviewers to start reviewing

- docs/eventing/broker-trigger.md
> Subscriber image should not be in a sub array.

- docs/samples.md
> Adding Knative Eventing Example

- docs/serving/configuring-autoscaling.md
We're working on a new version of the autoscaling docs in the Autoscaling WG. This is the first part of it to get a preview.
**Note for reviewers:** The diff is meaningless, this is all written from scratch.
> Redo the autoscaling configuration documentation.

- OWNERS_ALIASES
- Add myself as a doc reviewer ✨
> Add jonatasbaldin in docs-reviewers

- docs/install/knative-with-operators.md
- This PR updates the docs of operators by adding the links to the integrated operator in knative-sandbox.
> [release-0.14] Update the docs on operator for release 0.14

- docs/eventing/sources/README.md
- docs/eventing/sources/generator/ReadmeTemplate.gomd
- docs/eventing/sources/generator/main.go
- docs/eventing/sources/sources.yaml
- Adding a new section into Eventing > Source Samples for `SinkBindings`. I think this is a good idea, but would love any feedback :)
- Add Konnek in the `SinkBinding` section
> Add Konnek event source and SinkBinding

- docs/eventing/channel-based-broker.md
- docs/eventing/channels/default-channels.md
- docs/eventing/event-delivery.md
- docs/eventing/mt-channel-based-broker.md
updates to recent API on the docs for eventing
> Some updates on usage of v1alpha1 to beta

- docs/serving/configuring-autoscaling.md
As pointed out by Shash Reddy, these docs lack the annotation key.
> Add annotations to autoscaling settings.

- docs/install/knative-with-operators.md
- Added instruction on how to install All-In-One operator
> Change the document to install Knative Operator

- docs/serving/configuring-autoscaling.md
CC can be set globally via config-defaults CM.
/assign @markusthoemmes @abrennan89
> Update the docs to include CC global setting

- community/samples/serving/helloworld-deno/.dockerignore
- community/samples/serving/helloworld-deno/Dockerfile
- community/samples/serving/helloworld-deno/README.md
- community/samples/serving/helloworld-deno/deps.ts
- community/samples/serving/helloworld-deno/main.ts
> feat: add helloworld-deno

- docs/install/any-kubernetes-cluster.md
Fixes #2462 
- Make install instructions consisntent
-
-
> make eventing install instructions consistent

- docs/eventing/samples/kafka/source/README.md
> Correcting CloudEvent formatting

- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-source.yaml
knative/eventing-contrib#902 updated the apigroup, update the docs to match
this was reported in knative/eventing-contrib#1087
> Update kafkasource apigroup to match eventing-contrib

- README.md
> Link instructions to run website locally

- docs/install/any-kubernetes-cluster.md
> cp issue-2462

- docs/eventing/channels/channels.yaml
Add knative-sandbox/eventing-kafka to list of Knative channel implementations
/cc @Harwayne  @vaikas @lionelvillard @grantr
-
-
-
> Add knative-sandbox/eventing-kafka to list of channels

- docs/eventing/README.md
…enting#3186
Motivated by https://github.com/knative/eventing/issues/3186, where it wasn't clear that one of the roles of Broker was to be a target for user-generated events.
- Updates the eventing main document.
> Rewrite eventing/README.md to reference different usage cases

- docs/eventing/samples/kafka/source/README.md
- Add a an example to show KafkaSource TLS authentication
- Correct some formatting issues.
> Example for Kafka TLS Authentication

- docs/install/installing-istio.md
Fixes https://github.com/knative/docs/issues/2357 https://github.com/knative/serving/issues/7568
- Use `istioctl` instead of `helm` to install istio.
- Remove SDS related section as Istio 1.5 enables SDS by default. See https://github.com/istio/istio/issues/22306#issuecomment-605641786
NOTE: By this change, Istio 1.5.2 becomes the minimal version. Istio 1.4.x will be [EOL](https://istio.io/news/support/announcing-1.4-eol/) so it should be alright to remove it.
> Use istioctl instead of helm to install istio

- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kafka/source/README.md
-since Source/Channel are covered in the install guide, we just link to them
> Remove the duplicated install section for Kafka

- docs/eventing/accessing-traces.md
From #2459
- List the new components that supports tracing in 0.15
> List new components supporting tracing

- docs/samples.md
> Added 2 more external samples to samples.md

- docs/eventing/samples/kafka/source/README.md
Fixes https://github.com/knative/docs/issues/2520
- Updating the log captures since they have changed in recent releases, also adding some steps to see these logs.
> fixing Apache Kafka Event Source and Verify Sections

- docs/serving/samples/cloudevents/cloudevents-nodejs/index.js
- docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json
- docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
Signed-off-by: Carlos Santana <csantana@us.ibm.com>
Fixes #2524
Update serving cloudeventjs sample to use latest version of the nodejs sdk 2.0.1
> [fix] update serving nodejs cloudevent sample 2.0.1

- docs/eventing/samples/kafka/source/README.md
Fixes - follow up for https://github.com/knative/docs/pull/2530
- typo fix for my initial PR
> fixing typo in kafkasource README

- docs/serving/configuring-autoscaling.md
> Ellenevans patch 1

- docs/serving/getting-started-knative-app.md
> Ellenevans patch 1 3

- docs/serving/using-a-tls-cert.md
> Ellenevans patch 1 5

- docs/serving/configuring-autoscaling.md
> Ellenevans patch 1 1

- docs/serving/getting-started-knative-app.md
> Ellenevans patch 1 2

- docs/eventing/broker/README.md
- docs/eventing/broker/mt-channel-based-broker.md
Fixes #2345 
Tech writer review of docs created by @vaikas [WIP]
> Updates to MT broker docs

- OWNERS_ALIASES
> Add new TOC members to OWNERS_ALIAS

- docs/install/any-kubernetes-cluster.md
- This is a cherry pick request of 119f463487912fff4a8d4247515bdb2ac01f9e9e commit from the master branch
> add Kong Ingress Controller as a supported network layer

- docs/serving/using-cert-manager-on-gcp.md
Fixes https://github.com/knative/docs/issues/2555
Fix the format of applying certmanager related yaml
> Fix the format of applying certmanager related yaml

- OWNERS_ALIASES
From [requirements](https://knative.dev/community/contributing/roles/#approver)
~~Nominated by WG lead (no WG lead currently)~~
> Add abrennan89 to doc-approvers

- docs/knative-offerings.md
Signed-off-by: RyderXia <ryder.xia@sap.com>
Fix broken link
> fix gardener broken link

- docs/eventing/samples/writing-event-source/05-receive-adapter.md
> fix title typo

- docs/serving/feature-flags.md
Add documentation about the Feature/Extension Flags introduced in https://github.com/knative/serving/pull/7897.
* Document each feature/extension (what it does, stage (Alpha, Beta, GA), etc...).
/assign @whaught
> Add Feature/Extension Flags page.

- test/sampleapp/config.go
Fixes missing double-quote in yaml tag.
> Fixes yaml typo

- blog/README.md
Fixes issue #2522 
- An editorial team
- A process for the Knative blog
- Guidelines on how to contribute to the Knative blog
> Blogging guidelines for Knative - Ready to publish

- blog/articles/get-started-knative-eventing.md
> Adding author line to the header

- blog/articles/get-started-knative-eventing.md
> fixing typo in the title

- docs/install/README.md
- docs/install/any-kubernetes-cluster.md
- Add a note that if upgrading there's a different procedure. I've heard from few folks it's causing havoc.
-
-
> add a blurp about install vs. upgrade

- docs/install/any-kubernetes-cluster.md
- Update Knative install instructions
- Remove ChannelBasedBroker
- Update feature states for eventing to stable for .16
> update install instructions remove channel based broker

- blog/articles/get-started-knative-eventing.md
Fixes a previous commit (27917726f06035b72c63edcec18589a48c627b3f).
- Quote the author field so it parses
> Quote the author so it parses correctly.

- docs/eventing/event-registry.md
- docs/eventing/samples/kafka/binding/README.md
- docs/eventing/samples/kafka/binding/event-binding.yaml
- docs/eventing/samples/kafka/binding/event-source.yaml
- docs/eventing/samples/kafka/source/README.md
- docs/eventing/samples/kafka/source/event-source.yaml
- updating new API shape, see: https://github.com/knative/eventing-contrib/pull/1359 
-
-
> Updates to reflect the v1beta shape of the KafkaSource

- docs/install/any-kubernetes-cluster.md
- Fix a copy&paste error. Change repo from serving->eventing.
-
-
> serving->eventing

- docs/eventing/broker/README.md
- docs/eventing/getting-started.md
- docs/eventing/samples/iot-core/trigger.yaml
- docs/eventing/samples/kafka/channel/030-trigger.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/trigger.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- Ensure that all examples using trigger specify the Broker since in v1 this is no longer defaulted.
-
-
> make sure all triggers have spec.broker

- docs/serving/using-a-tls-cert.md
Fixes https://github.com/knative/docs/issues/2616
- Delete `---` as I suspect it causes the incorrect yaml rendering.
> Correct the format for yaml rendering

- docs/install/upgrade-installation.md
Address #2624 
- Update upgrade instructions by having both pre/post install steps.
- Update example upgrade versions to current releases.
-
> update upgrade instructions for pre/post install.

- docs/eventing/getting-started.md
- docs/install/any-kubernetes-cluster.md
- Document the install of the Eventing Sugar Controller
- Update the annotation for `Knative Eventing Injection` for namespaces in the mainline get started docs.
> Document installing Eventing Sugar Controller

- docs/install/installing-istio.md
> [release-0.15] Add the missing section of "Installing Istio without sidecar injection"

- docs/eventing/getting-started.md
- docs/install/any-kubernetes-cluster.md
Change few examples from v1alpha1/v1beta to v1.
-
-
-
> update few usages of v1alpha1/v1beta1 to v1

- docs/eventing/samples/helloworld/helloworld-go/README.md
- docs/eventing/samples/helloworld/helloworld-go/sample-app.yaml
- docs/eventing/samples/iot-core/README.md
- docs/eventing/samples/kafka/channel/README.md
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
It is simpler to just make a Broker directly for samples.
> Removing sugar annotation from samples.

- docs/eventing/README.md
- docs/eventing/samples/parallel/multiple-branches/README.md
- docs/eventing/samples/parallel/multiple-branches/parallel.yaml
- docs/eventing/samples/parallel/multiple-branches/ping-source.yaml
- docs/eventing/samples/parallel/mutual-exclusivity/README.md
- docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
- docs/eventing/samples/sequence/sequence-reply-to-event-display/ping-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
- docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
- docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
- docs/eventing/samples/sequence/sequence-terminal/README.md
- docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
- docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
- docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
- docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
- update flows samples to use v1 API
-
-
> update flows samples to use v1 API

- docs/eventing/README.md
- Remove Eventing requires Serving
- Slack discussion: https://knative.slack.com/archives/C9JP909F0/p1594292940378800
> Remove Eventing requires Serving

- docs/eventing/getting-started.md
Doesn't fix any one particular issue; general clean up / rewrite of eventing doc sections.
- Clean up of eventing getting started doc
> Clean up eventing docs

- docs/install/upgrade-installation.md
> [release-0.16] update doc to reflect migration job changes

- docs/install/upgrade-installation.md
> update doc to reflect migration job changes

- docs/install/installing-istio.md
Fixes #2608 
- This PR added the missing section of `Installing Istio without sidecar injection`.
> Add the missing section of "Installing Istio without sidecar injection"

- blog/articles/set-up-a-local-knative-environment-with-kind.md
- docs/install/any-kubernetes-cluster.md
- docs/serving/using-auto-tls.md
Part of github.com/knative/community/issues/153
/hold
> Update last of knative/net-* references to use knative-sandbox

- docs/serving/feature-flags.md
Issue #2684
- Cherrypick https://github.com/knative/docs/pull/2685 into release-0.16
> Cherrypick dryrun docs change

- docs/eventing/broker/README.md
Clarify that if you use out of the box config, you get IMC channels, and clarify that if you want to use some other channel, you have to modify the configmap.
- Clarify that if you use out of the box config, you get IMC channels, and clarify that if you want to use some other channel, you have to modify the configmap.
-
-
> fix cm name + talk about using different channel

- .github/workflows/stale.yaml
> Use github actions/stale for managing stale issues/PRs

- docs/install/any-kubernetes-cluster.md
- Change the CM name from imc-channel (does not exist) to config-br-default-channel
- Change ChannelBasedBroker -> MTChannelBasedBroker
-
> Update the cm name, ChannelBasedBroker -> MTChannelBasedBroker

- docs/install/any-kubernetes-cluster.md
Fixes https://github.com/knative/serving/issues/8584
> Update Ambassador install instructions

- docs/eventing/sources/pingsource.md
> fix link to ref doc

- docs/install/any-kubernetes-cluster.md
according to release notes https://github.com/knative/serving/releases
> move to k8s v1.16

- docs/install/operator/configuring-eventing-cr.md
- docs/install/operator/configuring-serving-cr.md
- This PR added the explanation of the field spec.version for operator CR's.
> Add the section to describe the field spec.version

- docs/serving/autoscaling/scale-bounds.md
Fixes https://github.com/knative/serving/issues/8826
- Add docs for initial scale
/cc @julz @vagababov @markusthoemmes
> Add docs for initial scale

- docs/install/any-kubernetes-cluster.md
> Move net-contour to beta

- docs/install/any-kubernetes-cluster.md
/assign @markusthoemmes @jmprusi @davidor
> Move net-kourier to beta

- docs/serving/webhook-customizations.md
Documents how to exclude a specific namespace from the Knative Webhook
https://github.com/knative/pkg/commit/086ff43956418f32abedde99deb4fab952de69f5
- adds webhook-customizations page
- documents the label to use to exclude Knative namespaces from the webhook
> Added Docs related to excluding namespaces from the Knative Webhook

- docs/eventing/samples/helloworld/helloworld-go/README.md
Fixes https://github.com/knative/docs/issues/2734
This patch adds extra indents to the code blockl with `---`.
I am not 100% sure if it fixes the issue on website, but helloworld-python has 
the same block and it renders perfectly. So it seems the indent issue.
https://knative.dev/development/eventing/samples/helloworld/helloworld-go/ (wrong rendering)
https://knative.dev/development/eventing/samples/helloworld/helloworld-python/ (correct rendering)
> Fix rendering issue in helloworld-go eventing

- docs/serving/using-a-tls-cert.md
Documents this feature https://github.com/knative-sandbox/net-contour/pull/193
> include doc on how to bring your own certificate with net-contour

- docs/serving/feature-flags.md
Fixes https://github.com/knative/docs/issues/2782
> Document the feature/extension flags.

- docs/install/knative-with-operators.md
Fixes #2768 
- This PR added the explanation on how to install future Knative releases and customized knative manifests with the operator.
> Add the instruction on how to use spec.version and spec.manifests

- blog/releases/announcing-knative-v0-17-release.md
Reviving release notes on the website
Related to #1880
> Add release notes for knative 0.17

- docs/install/knative-with-operators.md
Updates the minimum version of kubernetes on the operator page
> operator install prereq kubernetes 1.16 minimum version

- docs/serving/samples/cloudevents/cloudevents-vertx/pom.xml
- docs/serving/samples/cloudevents/cloudevents-vertx/src/main/java/org/knative/examples/cloudevents/vertx/CloudEventSampleVerticle.java
- Updates our cloudevents-vertx sample to latest sdk-java 2.0.0-milestone2
> Updated cloudevents-vertx sample to latest sdk-java 2.0.0-milestone2

- docs/install/operator/configuring-serving-cr.md
- docs/serving/debugging-performance-issues.md
- test/e2e/sampleapp_test.go
- test/flag.go
- test/sampleconsistency/sampleconsistency_test.go
> Remove unnecessary occurrences of whitelist and master.

- docs/eventing/samples/helloworld/helloworld-python/README.md
- docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
- doc change to reflect removal of deprecated code: https://github.com/knative/eventing/pull/3880
-
-
> Remove deprecated  and have only the fqn for injection

- docs/serving/getting-started-knative-app.md
Just fixing a selling typo: knatice -> knative
> fixing typo

- docs/serving/services/creating-services.md
> Fix the mismatch process for creating ksvc based on hello-go

- docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock
- docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
- docs/serving/samples/cloudevents/cloudevents-rust/src/main.rs
- Updated cloudevents-rust sample to sdk-rust 0.2, using the new apis
> Updated cloudevents-rust sample to sdk-rust 0.2

- docs/eventing/samples/writing-event-source/01-theory.md
- docs/eventing/samples/writing-event-source/04-reconciler.md
- docs/eventing/samples/writing-event-source/README.md
- correcting actual REPO urls, and not rely on http redirects...
> Updating references to the real REPO url

- docs/eventing/samples/helloworld/helloworld-python/README.md
- docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
Fixes #2817 
- Change trigger from v1alpha1 -> v1
- grepped for v1alpha1 in other samples, only sources are coming up with v1alpha1 now.
-
> v1alpha1 -> v1 for Trigger

- test/e2e-tests.sh
> fix istio install

- docs/install/operator/configuring-serving-cr.md
> Fix broken hash link in documentation

- docs/serving/samples/cloudevents/cloudevents-vertx/index.md
Like https://github.com/knative/docs/pull/2805 but for the cloudevents-vertx sample
> CloudEvents Vert.x tabbed doc with kn 

- go.mod
- go.sum
- vendor/knative.dev/test-infra/scripts/infra-library.sh
- vendor/modules.txt
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc abrennan89 dprotaso vaikas
/assign abrennan89 dprotaso vaikas
> [Automated] Upgrade to latest dependencies

- docs/eventing/sources/_index.md
- Add RedisSource to the list of eventing sources.
-
-
> Add Redis Source

- .github/workflows/knative-boilerplate.yaml
- .github/workflows/knative-donotsubmit.yaml
- .github/workflows/knative-go-build.yaml
- .github/workflows/knative-go-test.yaml
- .github/workflows/knative-stale.yaml
- .github/workflows/knative-style.yaml
- .github/workflows/knative-verify.yaml
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc abrennan89 dprotaso vaikas
/assign abrennan89 dprotaso vaikas
> [Automated] Update actions

- docs/serving/using-auto-tls.md
Fixes #2792 
- Add documentation for disabling AutoTLS per service/route via annotation
> Add documentation for disabling AutoTLS per service/route via annotation

- docs/eventing/broker/kafka-broker.md
See: https://knative.dev/development/eventing/broker/kafka-broker/#installation
- Align example output
> Fix alignment in example output

- OWNERS_ALIASES
Since she no longer works on the project.
FYI: How Prow chooses reviewers: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers#blunderbuss-selection-mechanism
> remove Sams permissions

- docs/eventing/debugging/README.md
- docs/eventing/samples/kafka/channel/020-k8s-events.yaml
- docs/eventing/samples/kubernetes-event-source/README.md
- docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
- docs/eventing/sources/apiserversource.md
Fixes #2879 
Helps with knative/eventing#4166
- Updating ApiServerSource example to use v1
-
-
> updating ApiServerSource example to use v1

- docs/install/operator/configuring-eventing-cr.md
- docs/install/operator/configuring-serving-cr.md
- Anchor links expect lowercase letters only. This PR converts the uppercase letters into lowercase letters.
> Fix the broken links for serving and eventing configuration by configmap

- .github/workflows/knative-style.yaml
pulls down https://github.com/knative-sandbox/.github/pull/54
> do not lint .ai files.

- blog/steering/governance-changes.md
Adds a blog post about the recent governance changes within the project.
> Add blog post on project governance changes

- docs/serving/autoscaling/scale-bounds.md
Part of https://github.com/knative/serving/issues/8628
/hold for https://github.com/knative/serving/pull/9496 and https://github.com/knative/serving/pull/9577
Add documentation for max-scale-limit
/assign @markusthoemmes @vagababov @julz @abrennan89
> Add documentation for max-scale-limit

- blog/steering/governance-changes.md
> fix typo in blog post frontmatter

- docs/serving/autoscaling/autoscale-go/test/test.go
We want them to look like good code :-)
So brush the autoscale example
/assign @markusthoemmes mattmoor @abrennan89
> Our docs represent how we write code

- docs/install/installing-istio.md
This is a cherry-pick for https://github.com/knative/docs/commit/bd6307f3c3440e69a836c52effc6be9c653d991f against master branch.
/cc @ZhiminXiang @JRBANCEL @guillaumeblaquiere
> [master] Fix default installation without sidecar injection (#2775)

- docs/eventing/sources/_index.md
> Add ZenDesk and Slack to the list of sources

- docs/eventing/samples/sinkbinding/README.md
- docs/eventing/samples/sinkbinding/sinkbinding.yaml
- docs/eventing/samples/writing-event-source-easy-way/README.md
- docs/eventing/sources/sinkbinding.md
Fixes #2917  
Helps with knative/eventing#4176
- Updating SinkBinding example to use v1
-
-
> Update SinkBinding docs to use v1

- blog/articles/orchestrating-cloud-events-with.md
> fix yaml error

- docs/eventing/broker/README.md
- docs/eventing/event-delivery.md
Fixes #2043 
- Document Broker Delivery Options
> Document Broker Delivery Options

- test/e2e-tests.sh
- Should fix integration tests by pinning the Istio release to a branch
> [release-0.18] fix integration tests

- test/e2e-tests.sh
- Should fix integration tests by pinning the Istio release to a branch
> [release-0.17] fix integration

- docs/install/any-kubernetes-cluster.md
Fixes #2966 
- Updates the locations for the github.yaml and mt-github.yaml files.
> Issue 2966

- docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock
- docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
- docs/serving/samples/cloudevents/cloudevents-rust/src/main.rs
- Update cloudevents-sdk to 0.3
> CloudEvents Rust example: update to sdk 0.3

- docs/install/any-kubernetes-cluster.md
#2949 
- Updated Apache Camel-K Source to knative-sandbox
- Updated Apache CouchDB Source to knative-sandbox
> Fixed broken links in any-kubernetes-cluster related to eventing

- docs/install/operator/configuring-eventing-cr.md
- adding doc on how to configure the system resources for knative eventing components, using the operator
> Documenting how to configure system resources for eventing

- docs/eventing/channels/channels-crds.md
- docs/eventing/channels/channels.yaml
- docs/install/any-kubernetes-cluster.md
Fixes #2949 and additional broken links not reported
Related issues:
#2970
> Fix broken links from sandbox moved files

- docs/serving/samples/hello-world/helloworld-kotlin/README.md
- docs/serving/samples/hello-world/helloworld-kotlin/src/main/kotlin/com/example/hello/Main.kt
- docs/serving/samples/hello-world/helloworld-nodejs/README.md
- docs/serving/samples/hello-world/helloworld-nodejs/index.js
- docs/serving/samples/hello-world/helloworld-php/README.md
- docs/serving/samples/hello-world/helloworld-php/index.php
I noticed this deploying and curling them all.
> Make newlines consistent across samples
