docs/eventing/migration/sinkbinding.md, docs/eventing/samples/container-source/README.md, docs/eventing/samples/container-source/heartbeats-source.yaml
Part of https://github.com/knative/eventing/issues/3426
- Update ContainerSource example to use v1beta1
=> Update ContainerSource example to use v1beta1

docs/eventing/samples/kafka/source/README.md
Addresses some typos in the Kafka Source tutorial.
- change `native-source` to `knative-source`
- change `redploy` to `redeploy`
=> typos in kafka source

docs/serving/knative-kubernetes-services.md
The page "Knative Kubernetes Services" linked to a page that doesn't exist anymore. This PR updates the link.
=> Update docs to fix broken link

docs/serving/autoscaling/concurrency.md
It is possible to default the hard limit (containerConcurrency), just not via config-autoscaler.yaml.
/assign @markusthoemmes
=> Document how to set default for containerConcurrency

docs/install/installing-istio.md, docs/serving/setting-up-custom-ingress-gateway.md
Fixes #1402
- This PR adds the instruction of updating the configmap `config-istio` under the namespace `knative-serving`, if the service name for the local gateway is not `cluster-local-gateway`.
=> Update the instruction on how to use cluster local gateway

docs/eventing/samples/helloworld/helloworld-python/README.md, docs/eventing/samples/kubernetes-event-source/README.md
- Update the doc of APIServerSource that the CloudEvents now has name, kind and namespace as attributes in Extension.
- Fix helloworld-python with some invalid broker and trigger path which block the pull-knative-docs-markdown-link-check.
-
=> Update APIServerSource docs to include the new attributes in CloudEvents

docs/serving/cluster-local-route.md
Fixes https://github.com/knative/docs/issues/2702
- This patch fixes wrong resource name to label. It should be `service` instead of `route` under the `To label a Kubernetes service:`.
/cc @abrennan89 @ajtomato
=> Label to k8s service instead of route

docs/eventing/getting-started.md
The recent clean up https://github.com/knative/docs/pull/2662/files#diff-09662e63bc9f84d2728157a440719f4cR66 removed the `-` and started failing to the command.
This patch adds it.
/cc @abrennan89 @vaikas @lionelvillard
=> Fix missing hyphen in eventing getting started guide

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
Cherry-pick of e8f35156bb1c31330cb77292b60bcf70ae25bac6 
* Add the section to describe the field spec.version
* Change the description on the included releases
* Add the limitation about upgrade and downgrade
* Resolved the comments
* Update the `spec.version` docs
=> [release-0.16] Add the section to describe the field spec.version (#2697)

docs/serving/autoscaling/scale-bounds.md
- Add documentation for new max-scale global config addressed by issue knative/serving#8627 and introduced in knative/serving#8951.
=> Add documentation for max-scale global setting

docs/install/upgrade-installation.md
Fixes #2669 
- It looks like we moved from serving.yaml to serving-core.yaml so I modified the upgrade file path
=> Changed filename from serving.yaml to serving-core.yaml in upgrade docs

test/e2e-tests.sh
Currently integration test is failing like https://github.com/knative/docs/pull/2735 / [log](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_docs/2735/pull-knative-docs-integration-tests/1293718156736466944).
It is because https://github.com/knative/serving/commit/0a29c97556466ebf1a99566b66732796d0c3f7a4 deleted istio manifests in serving repo.
This patch fixes the URL for Istio manifest.
=> Fix URL to net-istio for istio manifest

docs/eventing/samples/parallel/multiple-branches/README.md, docs/eventing/samples/parallel/multiple-branches/ping-source.yaml, docs/eventing/samples/parallel/mutual-exclusivity/README.md, docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml, docs/eventing/samples/ping-source/README.md, docs/eventing/samples/ping-source/ping-source.yaml, docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md, docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md, docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml, docs/eventing/samples/sequence/sequence-terminal/README.md, docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml, docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md, docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml, docs/eventing/sources/pingsource.md
- Update PingSource code/sample to use v1beta1
-
-
=> update pingsource doc to use v1beta1 API

docs/eventing/samples/helloworld/helloworld-go/README.md
This is same fix with https://github.com/knative/docs/pull/2739 but for 0.16 branch.
https://github.com/knative/docs/pull/2739 proved that rendering works with the
extra indents.
https://knative.dev/development/eventing/samples/helloworld/helloworld-go/ (Fixed by pull/2739)
https://knative.dev/v0.15-docs/eventing/samples/helloworld/helloworld-go/ (Will be fixed by this PR)
=> Fix rendering issue in helloworld-go eventing for 0.16 branch

docs/serving/debugging-application-issues.md
Fixes
In fact, each knative ingress corresponds to multiple vsvc, so we should use selector to query.
=> fix get vsvc in debug app issues

docs/eventing/broker/alternate/README.md, docs/eventing/broker/kafka-broker.md, docs/install/any-kubernetes-cluster.md
- Add Apache Kafka Broker
/cc @abrennan89 @slinkydeveloper
=> Add Apache Kafka Broker

docs/eventing/event-delivery.md
We have more event delivery parameters that aren't documented.
This PR adds them all and document supported parameters by 
`InMemoryChannel` and `KafkaChannel` 
Fixes #2712 
- Document all event delivery parameters (`retries`, `backoffDelay`, `backoffPolicy`)
=> Document all event delivery parameters

docs/eventing/broker/README.md
Fixes #2753
- Remove spec / annotations broker.class so `config-br-defaults` values will actually be used.
-
-
=> remove spec / annotations so broker uses defaults

docs/eventing/broker/README.md
Add an example that does not rely on defaults for creating a Broker.
- Add an example that does not rely on defaults for creating a Broker.
-
-
=> add an explicit Broker creation not relying on defaults

docs/eventing/getting-started.md
Fixes #2757
- Update broker url in docs/eventing/getting-started.md, as the default url is now `http://broker-ingress.knative-eventing.svc.cluster.local/event-example/default`.
=> fix broker url in eventing getting-started.md

docs/eventing/triggers/README.md
Fixes #2759
- Document trigger.spec.subscriber type and usage with a particular path
=> Deliver events to a particular path of a Trigger subscriber

docs/eventing/samples/github-source/README.md, docs/install/any-kubernetes-cluster.md
Fixes #2544
- Add multi-tenant GitHub source installation documentation
- Update sample
-
=> Add multi-tenant GitHub source installation doc

docs/reference/eventing/eventing-contrib.md, docs/reference/eventing/eventing.md, docs/reference/serving.md
Update API ref docs using new 0.17 knative components
https://github.com/knative/docs/tree/master/docs/reference#updating-api-reference-docs-for-knative-maintainers
```
cd hack
KNATIVE_SERVING_COMMIT=v0.17.0 KNATIVE_EVENTING_COMMIT=v0.17.0 KNATIVE_EVENTING_CONTRIB_COMMIT=v0.17.0 ./gen-api-reference-docs.sh
```
=> build API docs for 0.17

CONTRIBUTING.md
The first paragraph appears twice. This is my first pull request to the knative/docs project.
<!-- General PR guidelines:
Most PRs should be opened against the master branch.
If the change should also be in the most recent release, add the
corresponding "cherrypick-0.X" label; for example, "cherrypick-0.12", to the
original PR. Best practice is to open a PR for the cherry-pick yourself after
your original PR has been merged into the master branch. Once the cherry-pick PR
has merged, remove the cherry-pick label from the original PR.
=> Remove redundant paragraph in CONTRIBUTING.md

docs/serving/using-a-tls-cert.md
https://github.com/knative/docs/issues/1210
- Use the latest way in Istio for manually configuring TLS of Istio Gateway
=> Update the stale content of configuring TLS of Istio Gateway

docs/install/any-kubernetes-cluster.md
- Fix the min k8s version. It should be 1.16
=> fix the min k8s version

docs/install/knative-with-operators.md
Cherry-pick: 5bcea2b532fed4cbfcb8c0f8793ccc1991403562
* Add the instruction on how to use spec.version and spec.manifests
* Fixes the patch based on comments
* Change ma.mi.pa into {{spec.version}}
* Replace missed ma.mi.pa
=> [release-0.17] Add the instruction on how to use spec.version and spec.manifests

docs/serving/deploying/private-registry.md
Fixes #2570 
- Updates the dockerhub url. The previous URL was broken.
=> Updates a broken docker link to docker.io

docs/eventing/samples/writing-receive-adapter-source/06-yaml.md, docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
All Kubernetes version is set to 1.16+ on 0.15.
https://github.com/knative/serving/releases/tag/v0.15.0
This includes backport of #2784 for master (or #2711 for v0.16).
=> Move Kubernetes to 1.16+ (v0.15)

docs/eventing/samples/writing-event-source/06-yaml.md, docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
All Kubernetes version is set to 1.16+ on 0.17.
https://github.com/knative/serving/releases/tag/v0.15.0
This includes backport of #2784 for master (or #2711 for v0.16).
=> Move Kubernetes to 1.16+ (v0.17)

docs/eventing/getting-started.md, docs/eventing/samples/writing-event-source/06-yaml.md, docs/install/knative-with-operators.md
All Kubernetes version is set to 1.16+ on v0.16.
https://github.com/knative/serving/releases/tag/v0.15.0
This complements #2711 and includes backport of #2784 for master.
/label proposal/0.16
=> Move Kubernetes to 1.16+ (v0.16)

docs/install/any-kubernetes-cluster.md
All of the known remaining issues with our Contour integration have been resolved, and I've been carefully monitoring testgrid and digging into any 503s (or other dataplane related failures).
As of me writing this:
1. The only failure in the net-contour [testgrid](https://testgrid.knative.dev/net-contour#continuous&exclude-non-failed-tests=50&sort-by-flakiness=50&width=20) is due to its workaround for https://github.com/knative-sandbox/net-certmanager/issues/44 (tracking: https://github.com/knative-sandbox/net-contour/issues/252), which shouldn't practically manifest in the context of Serving
2. The only failures in the contour leg on Serving [testgrid](https://testgrid.knative.dev/serving#contour-latest&width=20&exclude-non-failed-tests=50&sort-by-flakiness=50) are due to infrastructure …
=> Promote net-contour to stable.

docs/eventing/broker/kafka-broker.md, docs/install/any-kubernetes-cluster.md
The control plane is now a separate artifact, so we need to
add another step to the installation and rename the control plane
and the logging config artifacts.
Fixes #2813 
Fixes #2812
- Renamed `kafka-broker-config-logging` -> `kafka-config-logging`
- Renamed `kafka-broker-controller` -> `kafka-controller`
- Document the new installation steps.
=> [Kafka Broker] Change installation steps and artifact names

docs/serving/autoscaling/concurrency.md
Now it's cut after hard limit
As discovered in https://github.com/knative/serving/issues/9446
/assign @abrennan89 @mattmoor
=> Fix the doc layout so it actually renders the whole file

docs/install/installing-istio.md
The default installation doesn't work as described in the documentation.
I fixed it like this
* manifest apply no longer exists in istioctl CLI.
* Add runAsRoot to allow targetPort creation bellow 1024.
=> Fix default installation without sidecar injection

docs/serving/services/deployment.md
And document the progressDeadline setting which seems to be the most often used there and is not documented in any way.
This needs more love but I want to document this initial state
/assign mattmoor @mpetason @abrennan89
=> Add initial docs for config-deployment CM

docs/eventing/flows/sequence.md, docs/eventing/samples/apache-camel-source/README.md
Produced via:
```shell
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```
/cc abrennan89 dprotaso vaikas
/assign abrennan89 dprotaso vaikas
=> [Automated] Fix misspellings

blog/README.md
Fixes #1880  or description of the problem the PR solves
- Added a section to the blogging guidelines that addresses blogs about releases and new features
-
-
=> Adding a section about new releases blog 

docs/serving/tag-resolution.md
Fixes #2565 
- Adds a note about the configmap saying that it is a snippet. Should keep users from copy/pasting as a complete configmap.
=> Added note about the configmap not being complete

docs/serving/autoscaling/target-burst-capacity.md
As per title really. This setting has a global setting too and some of the info in this doc was outdated so gave it a scrub while at it.
=> Add global configuration for target-burst-capacity and some corrections

docs/serving/autoscaling/scale-bounds.md
Part of knative/serving#9092.
- Documents the new Scale Down Delay feature
/hold till we finish landing the feature
/assign @markusthoemmes @vagababov @abrennan89
=> Document Scale Down Delay

docs/install/installing-istio.md
We've been asked for "which version of Istio is actually supported" multiple times so I feel like we should clarify this in our docs and update accordingly once new versions stabilize for us.
=> Add tested Istio version for clarity

docs/reference/api/README.md, docs/reference/api/_index.md, docs/reference/api/eventing/eventing-contrib.md, docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md, docs/reference/relnotes/_index.md
https://github.com/knative/docs/tree/master/docs/reference/api
KNATIVE_SERVING_COMMIT=v0.18.0 \
KNATIVE_EVENTING_COMMIT=v0.18.0 \
KNATIVE_EVENTING_CONTRIB_COMMIT=v0.18.0 \
./gen-api-reference-docs.sh
Fixes: #1883
=> API docs for 0.18 docs release

docs/serving/feature-flags.md
While it's technically true that we pick the first container with a port, this is because we only allow exactly one container to _have_ a port (if there is more than one container with a port, or no containers with a port, we throw a validation error).
=> Make feature flag doc less misleading

docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
If the event's type isn't changed by the last step in the
sequence the event will be resent to the Trigger that targets
the sequence creating an unwanted loop.
Fixes #2851
- Change event type in Sequence with Broker example
/label cherrypick-0.18
/label cherrypick-0.17
/label cherrypick-0.16
=> Change event type in Sequence with Broker example

docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
If the type of the event isn't changed by the last step in the
sequence the event will be resent to the Trigger that targets
the sequence creating an unwanted loop.
Fixes #2851
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
- Backport change event type in Sequence with Broker example (#2897)
=> [release-0.18] Change event type in Sequence with Broker example (#2897)

docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
If the type of the event isn't changed by the last step in the
sequence the event will be resent to the Trigger that targets
the sequence creating an unwanted loop.
Fixes #2851
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
- Backport change event type in Sequence with Broker example (#2897)
=> [release-0.17] Change event type in Sequence with Broker example (#2897)

docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
If the type of the event isn't changed by the last step in the
sequence the event will be resent to the Trigger that targets
the sequence creating an unwanted loop.
Fixes #2851
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
- Backport change event type in Sequence with Broker example (#2897)
=> [release-0.16] Change event type in Sequence with Broker example (#2897)

docs/serving/autoscaling/autoscale-go/README.md
The filepath was changed since https://github.com/knative/docs/commit/b3ffdbfcb47ba2c51b42b9340da0fd93cc82aa2e.
This patch fixes it.
/cc @abrennan89
=> Fix autoscale-go sample's yaml file path

docs/serving/samples/hello-world/helloworld-java-spring/Dockerfile, docs/serving/samples/hello-world/helloworld-java-spring/README.md, docs/serving/samples/hello-world/helloworld-kotlin/Dockerfile, docs/serving/samples/hello-world/helloworld-kotlin/README.md
I'm biasing here towards "works most places".
With this, I can build and run all of our helloworld samples (except dotnet) on an arm64 cluster.
Note that this image was already in use by the spark image, so this also improves our consistency.
cc @saturnism for thoughts.
=> Switch the base JRE to one that supports multiple architectures.

blog/releases/announcing-knative-v0-17-release.md, blog/releases/announcing-knative-v0-18-release.md
=> Release notes for Knative 0.18

docs/install/installing-istio.md
This patch updates the stable istio version to 1.7.1 in Istio
installation guide.
Current serving repo and net-istio uses 1.7.1.
Fixes https://github.com/knative/docs/issues/2894
/cc @ZhiminXiang @JRBANCEL @arturenault @tcnghia
=> Bump to Istio 1.7.1 for tested version

docs/serving/cluster-local-route.md
Although https://knative.dev/docs/serving/cluster-local-route/
explains to add the visibility label to `Route`, the label on `Route` is
removed because Route takes over Ksvc's label.
Please see:
```
$ kubectl label route hello-example serving.knative.dev/visibility=cluster-local
route.serving.knative.dev/hello-example labeled
$ kubectl get rt --show-labels
NAME            URL                                        READY   REASON   LABELS
hello-example   http://hello-example.default.example.com   True             serving.knative.dev/service=hello-example
```
If users deployed the app by Route + Configuration instead of Ksvc
this makes sense but it is very rare (I think) and we should remove
this instruction.
/cc @ZhiminXiang @tcnghia
=> Do not add visibility label to Route

docs/serving/samples/hello-world/helloworld-go/go.mod, docs/serving/samples/hello-world/helloworld-shell/go.mod
The eventing sample uses go 1.14 already and we're using it everywhere, across the board. This is mostly for consistency.
=> Bump golang versions to align all samples

CONTRIBUTING.md
Fixes https://github.com/knative/docs/issues/2845
- As described in the issue, It seems that links on the CONTRIBUTING.md do not work. It seems that if we add `./` it works as it does on docs/README.md.
=> Fix liks on CONTRIBUTING.md

docs/serving/samples/tag-header-based-routing/README.md
Since the configuration was moved by https://github.com/knative/serving/commit/b564cda38a6468703e85c3f544eacb12baecd1fc,
this patch updates the doc.
/cc @ZhiminXiang @tcnghia @JRBANCEL
=> Change tag header based routing config to config-features

docs/serving/accessing-traces.md
Fixes #2987 
dead link in https://knative.dev/docs/serving/accessing-traces/#configuring-traces
=> fix dead link in config-trace

docs/install/knative-with-operators.md, docs/install/operator/configuring-serving-cr.md, docs/serving/feature-flags.md
- The internal links for operator docs should connect to the local MD files instead of public links.
=> Update the links for operator docs

docs/eventing/event-registry.md
Fixes #2943 
- Broke up the single Broker/Trigger link into two links for Broker and Trigger
=> Updated links for broker and trigger. Broke up the single link into two.

docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
Adds tabbed instructions for deploying and deleting the Node.js cloudevents
sample using the `kn` CLI.
=> docs(cloudevents): try cloudevents-nodejs with kn

docs/eventing/README.md
The link previously went to Broker, which does have basic information about triggers. Might need a review to see which is more relevant:
https://knative.dev/docs/eventing/broker/index.html#trigger
or
https://knative.dev/docs/eventing/triggers/
Fixes #2941 
- Updated trigger link from the broker page to the triggers page
- Need a review on whether we should link to the triggers page or the trigger section in broker
=> Updated trigger link in eventing docs

docs/serving/samples/hello-world/helloworld-csharp/Dockerfile, docs/serving/samples/hello-world/helloworld-csharp/README.md
This is serving from a Graviton EKS cluster built with this sample: https://helloworld-csharp.default.mink.dev
/assign @csantanapr @abrennan89
=> Drop the `-alpine` for dotnet, it isn't multi-arch.

docs/serving/samples/cloudevents/cloudevents-nodejs/index.js, docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json, docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
A few changes to the API were made in the recent release of the SDK. This commit updates the dependency and modifies the source to work with the new API.
- Update the Node.js example to use the `cloudevents` module version 3.1.0
- Modify the example code to work with the changed API
- Return the actual `CloudEvent` instance in the response body in `receiveAndReply()`
=> examples(nodejs): bump to the latest 3.x version of cloudevents SDK

docs/install/operator/configuring-eventing-cr.md
Adding a little bit more context for the different "default" channel configs.
The `current` text on master is incorrectly saying that the `` CM will configure the default channel. However it is only setting the deefault for what the configured broker uses (if we use a channel based broker).
Adding text that shows howto set the default channel via the `default-ch-webhook` configmap
=> Better doc for channel config via operator

docs/install/knative-with-operators.md
- Knative operator is also able to configure multiple ingresses other than istio. The guide is based on the existing guide in knative. The only change is that Knative operator leverage the serving CR instead of directly working on configMaps.
=> Add description on how to configure each ingress for knative serving

blog/releases/announcing-knative-v0-19-release.md
Closes #3024 
[Rendered version](https://github.com/csantanapr/knative-docs/blob/release-notes-0.19/blog/releases/announcing-knative-v0-19-release.md)
=> Release notes 0.19

docs/install/any-kubernetes-cluster.md
Adds tab with install instructions for the new optional/alpha [DomainMapping feature](https://github.com/knative/serving/issues/9713).
See also https://github.com/knative/docs/pull/3017.
/assign @mpetason @abrennan89
=> Add install instructions for DomainMapping CRD

docs/serving/installing-cert-manager.md, docs/serving/using-auto-tls.md
- Bump the min version of cert-manager to 1.0.0
- Remove the stale content used for installing cert-manager
- Move the part of configuring DNS challenge into auto TLS docs.
=> Polish the auto TLS related docs

docs/serving/autoscaling/autoscale-go/README.md
corrected the path to `docs/serving/autoscaling/autoscale-go/service.yaml` in the sample command invocation
=> doc: fix path to autoscale-go sample

docs/install/any-kubernetes-cluster.md
Cherry-pick of #3030 for 1.19.
/assign @abrennan89 @csantanapr
=> [Release-0.19] Add install instructions for DomainMapping CRD

docs/eventing/getting-started.md
Fix small typo - pluralize consumers
=> Small typo in docs/eventing/getting-started.md

docs/eventing/samples/writing-event-source/README.md
Fixes #2936
- Removes broken links from `eventing/writing-event-source`
- Adds reference to eventing-sources-page
=> fix: add a reference to eventing sources page instead of having a list

docs/eventing/README.md
Remove relative link which links to the section directly above. 
The link doesn't go to the specific Eventing Install docs.
The subsequent link in the list goes to the same general install destination as the section above.
I didn't remove the install section completely as it is used to populate the breadcrumbs on the right.
=> Update Eventing Readme

docs/eventing/samples/kafka/binding/README.md
- Drop namespace of the Job resource used in the Kafka example as none of the other resources use a namespace.
- Add job verification step
=> Fix Kafka Binding example

docs/eventing/samples/writing-event-source/07-knative-sandbox.md
- set weight to 70 so it shows as the last link in the list. This would
then match the intended order in the [README.md file](https://github.com/knative/docs/blob/master/docs/eventing/samples/writing-event-source/README.md#steps)
=> Update writing-event-source/07-knative-sandbox.md weight

docs/install/installing-istio.md
Fixes knative/serving#10221
- This addon is no longer supported in Istio 1.8. Remove it since it was disabled anyways.
=> Remove prometheus addon from Istio installation instructions

docs/install/operator/configuring-eventing-cr.md
Easy navigation and easy reading for others
=> fix broken url in docs

blog/articles/event-drive-app-knative-eventing-kogito.md
Sorry for opening these too many PRs. I believe that we have all set now.
See: https://knative.dev/blog/articles/images/kogito-example-patientonboarding.png
=> Adding absolute path for Kogito article images

docs/eventing/sources/sinkbinding.md
- Document the sinkbinding modes and their side effects in relation to namespaces and labels
=> Add documentation to sinkbinding modes

docs/install/knative-with-operators.md
The operator has introduced a new field called `spec.additionalManifests` to specify the customized manifests, based on the default manifests. We need instructions on how to leverage this field.
- The PR adds the instruction on how to install the customized manifests in the append mode.
=> Add the description on how to to append customized the manifests

docs/serving/istio-authorization.md
Forgot to add the knative-serving namespace, which is mentioned in the previous paragraph.
=> Fix typo in istio authorization docs

docs/eventing/samples/container-source/README.md, docs/eventing/sources/containersource.md
=> Fixed a typo.

docs/serving/samples/cloudevents/cloudevents-nodejs/README.md, docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json, docs/serving/samples/cloudevents/cloudevents-nodejs/package.json, docs/serving/samples/cloudevents/cloudevents-nodejs/service.yaml
- Fix #3135 that was using an out of date package.
- Little cleanup of wording.
-
After this change:
```
vaikas@vaikas-a01 cloudevents-nodejs % npm audit fix
up to date, audited 377 packages in 2s
found 0 vulnerabilities
```
=> update package, fix issue 3135

CONTRIBUTING.md, community/calendar/_index.md, community/meetup/README.md, docs/eventing/samples/writing-event-source/01-theory.md, docs/reference/api/serving.md, docs/serving/tag-resolution.md
Updates doc and calendar links to point to the `knative.team` drive and calendar, rather than the `google.com` hosted one.
- Switch slides to web-published versions, visible without auth, to reduce the amount of access requests needed.
- Switch CONTRIBUTING.md to point to new Google doc, since that link is most useful to people already in `knative-dev`.
- Switch community/calendar to point to new Knative.Team calendar for now; we may want to have an additional calendar for non-official events of interest to the community at some future point.
/assign @macruzbar
=> Update calendar and drive links

docs/eventing/event-registry.md
- adding note that the sources need to emit to the broker, otherwise they don't show up in the "eventtypes list"
- we no longer have a `generatedName`, but we have a label of the source name
=> Adding updates to the Event registry doc

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md, hack/gen-api-reference-docs.sh
New v0.20.0 API docs.
Command:
```
KNATIVE_SERVING_COMMIT=v0.20.0 KNATIVE_EVENTING_COMMIT=v0.20.0 ./gen-api-reference-docs.sh
```
Also investigated and resolved new API build errors (due to constant types) ([details](https://github.com/ahmetb/gen-crd-api-reference-docs/pull/29))
Netlify preview: https://5ffe5166b7462545d9c8fc4d--knative.netlify.app/docs/reference/api/
=> Knative API docs for v0.20.0

OWNERS_ALIASES, docs/serving/OWNERS
Also add `eng-approvers` as approvers to the serving docs.
Since that seems the reason for this group in the first place.
/assign mattmoor @abrennan89
=> Add vagababov to eng-approvers and sort and trim people not longer in Knative project

docs/install/any-kubernetes-cluster.md
As [testgrid](https://testgrid.knative.dev/net-kourier#continuous&exclude-non-failed-tests=50&sort-by-flakiness=50&width=20) shows, kourier does not have any non-flaky test failure and all features including alpha are implemented.
Hence this patch promotes net-kourier to stable.
/assign @tcnghia @ZhiminXiang 
/cc @mattmoor @davidor @jmprusi @markusthoemmes
=> Promote net-kourier to stable

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md, hack/gen-api-reference-docs.sh
Updating the tool version to v0.3.0 tag.
Ran locally against v0.20.0 tag for serving/eventing repos, seems to be
working fine.
cc: @RichieEscarez
=> update gen-api-reference-docs script

docs/serving/creating-domain-mappings.md
Documents the [DomainMapping feature](https://github.com/knative/serving/issues/9713) which will be added in alpha in v0.19.
This probably needs lots of work @abrennan89 @mpetason, but opening as a first version, anyway.
In particular looking for guidance on how best to call out that this is an Alpha feature etc.
=> Add DomainMapping docs

docs/serving/config-ha.md
- autoscaler can also be scaled now
- activator cannot be scaled by patching deployment, since there's an
HPA that will snap it back to the HPA desired values
- thus, provide the correct commands to change the activator scale.
/assign @abrennan89 @yanweiguo 
Fixes #2472
=> Autoscaler can be scaled too now. Add correct docs for activator

docs/eventing/channels/channels-crds.md, docs/eventing/event-delivery.md
This PR is associated with the [knative-eventing PR 4760](https://github.com/knative/eventing/pull/4760) which is adding an extension attribute to CloudEvents prior to sending them to the dead letter sink.
- Cleanup KafkaChannel descriptions to reflect the latest implementations.
- Add brief description of new CloudEvent extension attribute `ce-knativedispatcherr` to event-delivery documentation.
=> Describe new ce-knativedispatcherr cloudevent extension attribute

docs/install/installing-istio.md
Istioctl version:
```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (2 proxies)
```
I get this error:
```
Error: failed to install manifests: errors occurred during operation: failed to create Istio control plane with spec: 
hub:"docker.io/istio" tag:1.8.2 mesh_config:<key:"defaultConfig" value:map[proxyMetadata:map[]] > mesh_config:<key:"enablePrometheusMerge" value:true > components:<base:<enabled:<BoolValue:<value:true > > > pilot:<enabled:<BoolValue:<value:true > > tag:<nil> spec:<nil> k8s:<env:<name:"POD_NAME" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.name" > > > env:<name:"POD_NAMESPACE" valueFrom:<fieldRef:<apiVersion:"v1" fieldPath:"metadata.namespace" > > > readiness_probe:<httpGet:<path:"/ready" port:<IntOrString:<type:0 intVal:8080 …
```
=> remove prometheus component

docs/serving/config-ha.md
Fixes #3175 
- Update the docs for that the HA is enabled by default for autoscaler as well
- Add documents for downsides when scaling down autoscaler components.
/assign @abrennan89 @vagababov
=> HA is enabled for Autoscaler too

.gitattributes
Cleanup to indicate git attributes so that we can make lint checks depend on Git attributes rather than ad-hoc patterns.
- Set `git` attributes, mark certain graphics files as `binary`.
=> Add .gitattributes for docs

docs/serving/samples/multi-container/index.md
This patch adds `{{% readfile file="README.md" %}}` to `index.md` for multi-container.
Current page is blank as https://github.com/knative/docs/issues/3195 reported.
Fix https://github.com/knative/docs/issues/3195
/cc @savitaashture @abrennan89
=> Add readfile to Knative multi-container samples

docs/eventing/sources/pingsource.md
- change PingSource api version badge to v1beta2
-
-
=> fix: change PingSource api version badge to v1beta2

docs/eventing/getting-started.md
No SSH was ever harmed when starting a shell via kubectl attach to execute shell commands.
So correct that from the documentation.
-
-
-
=> Replace wrong description of kubectl attach

docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
Fixes #2781 
Removing all the labels and some other minor general cleanup.
IMHO we should remove whatever we can from the install docs ahead of reorganizing them to take out all the optional stuff like networking layers (just keep the default, everything else goes to its own section). It'll make cleaning this up easier later.
=> [#2781] Removing unnecessary version labels

docs/eventing/sources/sinkbinding.md
Change-Id: Iad1e74b9e58a9a194a4e6ef71fcfbd82d9b3fb57
Fixes #3218
-
-
-
=> fix: cronjob.yaml indent two spaces

docs/install/installing-istio.md
Update supported Istio versions.
This should be cherry-picked into release-0.20. How do I add the label?
=> Update supported istio versions

docs/serving/samples/cloudevents/cloudevents-nodejs/index.js, docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json, docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
Closes #3247
The following PR #3136 updated the cloudevent SDK from version 3.x to 4.x and this is a major semantic version, which caused code brakes as the code was not compatible with the new major version of the SDK.
https://github.com/knative/docs/pull/3136/files#diff-8d77ef3aae2dea7cc68b9f32a40ac8f43a211f8f6e7f673d12723ed596eca805R16
This PR updates the sample code to be compatible with the new major version of the SDK
=> Fix cloudevent-nodejs sample to support SDK 4.0

docs/serving/spec/knative-api-specification-1.0.md
I kept Dan since he's still the author of the latest version. And fixed
Evan't email to be a routable one.
/assign @evankanderson mattmoor
=> Update the email to be relevant

docs/eventing/sources/pingsource.md
=> Fix typo in pingsource docs

docs/eventing/debugging/example.yaml, docs/eventing/samples/helloworld/helloworld-python/README.md, docs/eventing/samples/iot-core/trigger.yaml
=> Fix example.yaml file

docs/serving/using-a-custom-domain.md
Fixes https://github.com/knative/docs/issues/3222
`config-domain.yaml` has a symlink before https://github.com/knative/serving/blob/release-0.17/config/config-domain.yaml, but the symlink was removed.
So this patch fixes the yaml path to the original file https://github.com/knative/serving/blob/master/config/core/configmaps/domain.yaml.
=> Update path for config-domain configmap

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md
Proposed Changes 
New v0.21.0 API docs.
Command:
```bash
cd ./hack/
KNATIVE_SERVING_COMMIT=v0.21.0 KNATIVE_EVENTING_COMMIT=v0.21.0 ./gen-api-reference-docs.sh
```
Related to #3275 
/assign @RichieEscarez
=> Knative API docs for v0.21.0

docs/install/installing-istio.md, docs/serving/setting-up-custom-ingress-gateway.md
https://github.com/knative-sandbox/net-istio/pull/411 replaced cluster-local-gateway with knative-local-gateway.
Hence this patch updates the docs.
Part of https://github.com/knative/docs/issues/3271.
/cc @JRBANCEL @ZhiminXiang @arturenault
=> Clean up cluster-local-gateway

docs/install/operator/configuring-serving-cr.md
Since https://github.com/knative/operator/commit/c45584402fda314a615cc0d23e1044b08f7d44f9,
Ingress configuration is moved in `spec.ingress.istio`.
Hence this patch updates the docs to use
`spec.ingres.istio.knative-ingress-gateway` and `spec.ingres.istio.knative-local-gateway`.
Part of https://github.com/knative/docs/issues/3271
/cc @houshengbo @maximilien
=> Move istio gateway's override setting into spec.ingress.istio

docs/install/operator/configuring-serving-cr.md
This patch adds the instruction of `spec.deployments` for knativeserving CR.
Fixes https://github.com/knative/docs/issues/3266
/cc @houshengbo @maximilien
=> Add new operator config spec.deployments to override configuration of system deployment

docs/install/_index.md, docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
Following up some comments from #3297 
- Removed some fluff (links should go in context docs not procedures, distracting)
- Updated kube min version
- `--filename` -> `-f` for consistency
- Removed install from source, belongs in dev docs
=> Follow up install doc improvements

docs/install/any-kubernetes-cluster.md
`istio-knative-extras.yaml` does not exist since long time ago.
And `cluster-local-gateway` was removed and `knative-local-gateway` is always deployed when `net-istio` is used.
This patch removes the note.
Fixes https://github.com/knative/docs/issues/3271
=> Remove note about cluster-local-gateway and istio-knative-extras.yaml

docs/install/knative-with-operators.md
- Knative operator supported Kourier, contour and istio. The doc needs to change accordingly.
=> Modify the instructions of the ingress configuration

docs/serving/debugging-application-issues.md
This patch fixes obsolete links in debugging guide.
- `Check application logs` is removed by 15153b3e469931b7dcf79aa56fcc0fcf23a42f13 so remove link as well.
- `Check Istio routing` is updated to `Check Ingress/Istio routing` by bbda7cf64b2859ef6fd68d90e82ef05fa458fdcd so rename the link as well.
Fix https://github.com/knative/docs/issues/3337
=> Fix obsolete links in debugging guide

docs/install/any-kubernetes-cluster.md
Fixes #3336 
- Fixed comments so they're not exposed
- Instead of having monitoring step squashed in under the tabs, I have moved this out under a verification heading, since that's really what it is.
- Removed a few lines of fluff, having verification steps now should make it self explanatory that this is the basic install and everything else is optional, also there's an overhaul of the install docs happening anyway.
=> Fixed comments and moved verification step

community/samples/serving/helloworld-rust/Dockerfile
Fixes helloworld-rust example to be buildable. 
Updates installation command based on reported error when building
```
warning: To build the current package use `cargo build`, to install the current package run `cargo install --path .`
```
Updates Rust version from 1.27 to current latest 1.50, which makes the sample build successfully without any other package version changes. 
Successfully builds with these changes.
=> Update Rust version and installation commands

docs/eventing/broker/kafka-broker.md
We've got a bug [1] report for a misconfiguration of 
`default.topic.replication.factor`.
This PR adds a note that could alert users on the
value of this configuration.
[1] https://github.com/knative-sandbox/eventing-kafka-broker/issues/720
- Add a note on replication factor value
=> Add a note on replication factor value

docs/eventing/event-delivery.md
Fixes #3309 - Remove links to Go code
- Removed the Go path link for Delivery Spec
- Removed the Go path link for Destination
=> Removed the Go path link from the ./eventing/event-delivery.md

docs/eventing/README.md
Fixes #3309 - Remove links to Go code
-  Removed the Go path link for Channel and added path https://github.com/knative/docs/tree/master/docs/eventing/channels
-  Removed the Go path link for Subscriptions
=> Removed the Go path link from the ./eventing/README.md

docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
Adds a sentence to installing topics to clarify that you don't have to install both Serving and Eventing components. 
Fixes #3355
=> Add clarifying info about what to install

CONTRIBUTING.md
- Add Hugo 0.76+ front-matter to prevent CONTRIBUTING.md from appearing on the site:
https://gohugo.io/content-management/build-options/#render
=> Hide CONTRIBUTING.md from the website

DEVELOPMENT.md
documentation
- Added a link to run the website locally in our development docs - it is currently in the README but also makes sense in the Dev docs in case a user references them
=> Added the link to run website locally from our README to our DEVELOPMENT

docs/serving/autoscaling/scale-to-zero.md
The tabs of the retention period are currently broken because they actually point at the tabs from the grace period. This fixes that.
=> Use a unique name for the scale-to-zero-retention tabs

docs/install/any-kubernetes-cluster.md, docs/install/installation-files.md
- Fixed a broken link
- Tweaked the serving and eventing extensions headings so that they are more consistent with the other headings on the page
- Changed the wording in optional extension opening sentences
=> Fix broken link and tweak wording

docs/serving/autoscaling/autoscaling-metrics.md
- Updates the listed metrics used with HPA (according to current code [only cpu](https://github.com/knative/serving/blob/0e8410a81e9609b979d5bc3cb9e602c3a4f4af02/pkg/apis/autoscaling/annotation_validation.go#L217) is allowed)
- Currently if you set any other metric you get a validation error: `invalid value: rps: spec.template.metadata.annotations.autoscaling.knative.dev/metric`
=> Fix HPA allowed metrics

docs/eventing/sources/pingsource.md
correct commands and outputs, this needs to be cherry-picked to 0.21 and 0.20 branches
- add missing namespace param in PingSource creation command
- fix the binary data output 
-
=> fix(PingSource): correct commands and outputs

docs/install/any-kubernetes-cluster.md
Want to separate the system requirements out and add "for prototyping purposes" bit so folks don't think you need to run this only in the cloud.
=> Separate prototyping and production concerns in any-kubernetes-cluster.md

docs/client/install-kn.md
Adding brew install kn command directly to page and making it the first option
Actually kind of crazy that we don't already do this
=> Make Homebrew installation the first option for `kn`, pull command to install out of Github and into knative.dev site

docs/install/install-serving-with-yaml.md
=> PRing my own PR :( 

docs/client/install-kn.md, docs/install/_index.md, docs/install/install-eventing-with-yaml.md, docs/install/install-extensions.md, docs/install/install-serving-with-yaml.md, docs/install/prerequisites.md
I figured out how to group commits
its over for you foes
=> Fixing the kn cli references

OWNERS, OWNERS_ALIASES, blog/OWNERS, docs/eventing/OWNERS, docs/eventing/channels/OWNERS, docs/eventing/sink/OWNERS, docs/eventing/sources/OWNERS, docs/install/OWNERS, docs/serving/OWNERS, test/OWNERS
See https://github.com/knative/community/pull/552 for the addition of groups/full OWNERS_ALIASES that will be synced.
This is a preparatory PR for landing OWNERS_ALIASES automation across the Knative org (alternative to the CODEOWNERS changes in knative-sandbox).
If this seems to be expanding permissions or otherwise likely to cause a problem, `/hold` this PR and comment here or on https://github.com/knative/community/pull/552.
=> Update OWNERS_ALIASES to match autogen in community

docs/eventing/broker/kafka-broker.md
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/589
- Add doc for new feature https://github.com/knative-sandbox/eventing-kafka-broker/issues/589
=> Kafka broker ordered delivery

docs/install/operator/configuring-eventing-cr.md
- adding a explicit section for setting some specific channel implementation for the default broker (the one that's there OOTB in eventing)
- and changing the section for the default channel to be more explict about options
=> Adding a bit more of clarfication on default channel configs

docs/client/install-kn.md, docs/install/_index.md, docs/install/install-eventing-with-yaml.md, docs/install/install-extensions.md, docs/install/install-serving-with-yaml.md, docs/install/prerequisites.md
Changes: 
1. Moved Kn CLI to pre-requisite 
2. Added homebrew `brew install kn` command to pre-reqs
2. Changed flow of install from install -> Serving or Eventing to Install -> Pre-Reqs -> Serving or Eventing
3. Added reference to the Install files in each of the Serving and Eventing Installs 
4. Fix broken link
5. Aligned any reference to "Serving" or "Eventing" to [Knative Word and Phrase List](https://docs.google.com/spreadsheets/d/1p1_kBUd6ZvonxHkMcEJPayf6QIpExuFf5cFq0ptar7I/edit#gid=0)
=> Updating install flow with minor changes to reflect desired prototype in UX/11

docs/eventing/sink/kafka-sink.md
The YAML key for the secret reference is wrong.
- Fix auth secret reference
=> [KafkaSink] Fix auth secret reference

docs/install/install-serving-with-yaml.md
=> Add context to network layer install section

blog/steering/[BLOG]-toc-2021-election-announcement.md
This is a blog post to kick off the TOC election for 2021. The target is to announce the election tomorrow (April 13), but we are still working on a few details, so it's important that this does not get published until:
- We merge [this PR](https://github.com/knative/community/pull/562) from @jberkus.
- And the voters.yaml (community/elections/2021-TOC/voters.yaml) file is populated with GH ids for voters.
The safest bet is probably to make sure we get the OK from @jberkus before it goes live.
@bsnchan and @thisisnotapril - since the 2 of you suggested making this a blog post - is there anything you'd like to add? Right now, this is mostly the text that will go out via email with a few tweaks to make it read better as a blog post.
=> Blog post announcing the TOC election kick-off for 2021.

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md, hack/reference-docs-gen-config.json
The api reference doc generator's config.json was a bit out of date. It was referencing the duck package as `github.com/knative/pkg` rather than as `knative.dev/pkg` where it now lives (see updated `hack/reference-docs-gen-config.json` in this PR). It also didn't know about the `knative.dev/networking` package since (I suspect) that was created after the config was last updated. There were also a couple other packages that the tool was printing warnings about that I added.
The result is these packages now properly link to the relevant external docs in the output, which appears to have been the original intention here (also ./hack/gen-api-reference-docs.sh no longer complains about "not found external link source for type" \o/).
/assign @evankanderson @abrennan89
=> Fix API doc generator to properly link to duck, networking

DEVELOPMENT.md, README.md, blog/README.md, test/README.md
Similar to the change we made to `CONTRIBUTING.md`, ask hugo not to render other "how to do docs" files.
- Avoid building files that aren't intended for the website.
=> Add frontmatter to avoid rendering infrastructure description files

docs/serving/_index.md
Fix https://github.com/knative/docs/issues/3484
As 4d6d81fbb719f94e1fdd246a9d2b37623d93a84c moved `README.md` to `_index.md`, this patch updates the link.
/cc @evankanderson @abrennan89 @hongshaoyang
=> Fix invalid link for autoscaling README

docs/_index.md, docs/eventing/_index.md, docs/eventing/metrics.md, docs/serving/_index.md, docs/serving/metrics.md
Fixes #1792 
- Adds serving, eventing metrics api documentation
- Each metric has a lifecycle status following the [k8s approach](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metric-lifecycle)
- Adds some guidelines on how to use the metrics.
Screenshots bellow:
Note: tables can be improved with some custom table shortcode etc (goes beyond of this PR). Also in the future info could
be extracted from a cvs file (common practice with hugo).
/cc @matzew @markusthoemmes  @evankanderson
=> Add metrics api docs

blog/releases/announcing-knative-v0-22-release.md
blog post for knative release 0.22
Closes #3485
=> blog post for knative release 0.22

docs/eventing/sink/_index.md
Adding documentation on how to set up a Custom Resource in order to be used as a sink.
- Adds a section [here](https://knative.dev/docs/eventing/sink) to explain the steps necessary to use a custom resource as a sink
=> setting a custom resource as sink doc

help/contributor/publishing.md
I was not able to find the instructions on how to preview the website locally.
The contributor docs are now on the website, but the menu item was not clear
Change "Website help"
=> change name for menu item for preview

docs/eventing/channels/_index.md
=> Added detail per issue #3425

docs/eventing/accessing-traces.md
Noticed that the key `enable` is not even in the structure of tracing config: 
```
type Config struct {
Backend              BackendType
ZipkinEndpoint       string
StackdriverProjectID string
Debug                bool
SampleRate           float64
}
```
also noticed here: https://github.com/knative/eventing/issues/1889#issuecomment-753998185
also its not mentioned in the `configuration options` in the doc, so I figured it might be something left over from previous versions. Let me know if it really is required? 
- just replaced `enable` key with `backend`
-
-
=> config-tracing configmap fix

help/maintainer/docs-release-process.md
- No need to have netlify admin access to cut a release
- No need to have Hugo installed to cut a release
=> remove unnecessary requrirements to do a release

.github/workflows/knative-mkdocs.yaml, hack/docker/Dockerfile, hack/docker/README.md, hack/docker/build.sh, hack/docker/clean.sh, hack/docker/mkdocs.sh, hack/docker/run.sh
Closes #3542 
- Add github action to publish mkdocs site to gh-pages branch
- Add hack script for local livereload for mkdocs under /hack/docker
After this gets merge, someone with admin access to the docs repo needs to go to settings GH Pages and enable the branch `gh-pages` with `/` root
This also allows contributors to publish their `mkdocs` branch in their forks to be published in their own github.io namespace
=> add gh-action to deploy mkdocs to gh-pages

.gitignore, docs/stylesheets/extra.css, hack/build-with-blog.sh, mkdocs.yml, package-lock.json, package.json
Fixes https://github.com/knative/docs/issues/3539.
Fixes https://github.com/knative/docs/issues/3541.
Builds the blog and community tabs with hugo.
Also added a little CSS to visually distinguish these links.
This works by cloning the website and community repos locally, copying blog and community in to the right places (same trick website uses in https://github.com/knative/website/blob/main/scripts/processsourcefiles.sh#L107), and then building those pieces using hugo in to the same site dir as mkdocs builds the docs.
Running:
- Same as today: `mkdocs serve` previews just the main site (with live reloading previews)
- New: `./hack/build-with-blog.sh` builds to `/site/` and is what we should run in the netlify build/github action.
- New: `./hack/build-with-blog.sh serve` builds to …
=> Build blog and community with hugo

.github/workflows/knative-mkdocs.yaml, hack/build-with-blog.sh, mkdocs.yml
- Update gh action to build with mkdocs and hugo
- Handle better redirects to be compatible with personal forks with different names than `docs`
- Handle the requirement of having postcss in the PATH
=> Update Github action to build with hugo and mkdocs

docs/serving/feature-flags.md
Since https://github.com/knative/serving/pull/10084 deleted old GC and
started using responsive GC by default, `responsive-revision-gc` in
`config-feature` is not used at all.
This patch removes the instruction for the configuration.
https://github.com/knative/serving/pull/11309 removes the configuration in serving repo.
=> Remove responsive-revision-gc config

docs/serving/_index.md, docs/serving/debugging-application-issues.md, docs/serving/deploying/private-registry.md, docs/serving/spec/knative-api-specification-1.0.md
Fixes #3117
Fixes broken / incorrect links
=> Fixes #3117 and broken links

docs/eventing/broker/kafka-broker/_index.md
- slightly changing the doc for _ordered delivery guarantees_
-
-
=> Slight change to ordered delivery guarantees

docs/stylesheets/extra.css, hack/build-with-blog.sh, mkdocs.yml, overrides/main.html
https://user-images.githubusercontent.com/354013/118398771-073ddb80-b652-11eb-90d9-24dcca25f255.mov
Builds previous versions of docs in to the site based on release branches.
**TL;dr:** `mkdocs serve` in any branch for live preview of just that version of docs, `./hack/build-with-blog.sh [serve]` to build/preview the whole thing, release by creating release branch as normal and updating RELEASES at top of build-with-blog.sh.
Fixes #3573.
/assign @omerbensaadon @csantanapr 
- `mkdocs serve --dirtyreload` - this will preview just the current version, very fast (immediate) update of changes to pages
- Run on a release branch (or on main, or wherever) to view docs for just that release.
- `./hack/build-with-blog.sh serve`
- We'll set netlify PR previews (and builds) up to run this, too.
- …
=> Add branch-based versioning

docs/serving/services/deployment.md
Looks like the default value in Kubernetes has changed to 600s: https://github.com/kubernetes/website/commit/ddfa877602152db51aeabb626d2e2d1cc168d065
=> Update the default progress deadline value

docs/serving/using-auto-tls.md
The doc uses ClusterIssuer `letsencrypt-http01-issuer` but the configuration uses
`letsencrypt-issuer` so it is confusable. Actual report is https://github.com/knative/docs/issues/3560.
So this patch changes the ClusterIssuer name to
`letsencrypt-http01-issuer` which is used in this doc section.
Fix https://github.com/knative/docs/issues/3560
=> Use correct ClusterIssue name

docs/eventing/accessing-traces.md, docs/eventing/channels/channel-types-defaults.md, docs/eventing/debugging/index.md, docs/eventing/flows/parallel.md, docs/eventing/samples/_index.md, docs/eventing/samples/gitlab-source/index.md, docs/eventing/samples/helloworld/_index.md, docs/eventing/samples/helloworld/helloworld-go/_index.md, docs/eventing/samples/helloworld/helloworld-python/_index.md, docs/eventing/samples/kafka/_index.md, docs/eventing/samples/kafka/binding/index.md, docs/eventing/samples/kafka/channel/index.md, docs/eventing/samples/kafka/source/index.md, docs/eventing/samples/parallel/_index.md, docs/eventing/samples/parallel/multiple-branches/_index.md, docs/eventing/samples/parallel/mutual-exclusivity/_index.md, docs/serving/samples/blue-green-deployment.md, docs/serving/samples/gitwebhook-go/index.md, docs/serving/samples/grpc-ping-go/index.md, docs/serving/samples/hello-world/helloworld-java-spring/README.md, docs/serving/samples/knative-routing-go/index.md, docs/serving/samples/multi-container/index.md, docs/serving/samples/rest-api-go/index.md, docs/serving/samples/secrets-go/index.md
Fixes #3568 #3577
I use the following command to scan in multiple threads
```shell
find . -type f -print0  | xargs -0 -P 6 grep -rni "/README.md)"|grep -v https
```
```shell
./docs/serving/samples/rest-api-go/index.md:15:1. A Kubernetes cluster with [Knative Serving](../../../install/README.md) installed
./docs/serving/samples/rest-api-go/index.md:205:The [traffic splitting example](../traffic-splitting/README.md) continues from
./docs/serving/samples/knative-routing-go/index.md:23:1. A Kubernetes cluster with [Knative Serving](../../../install/README.md)
./docs/serving/samples/multi-container/index.md:13:  [installation instructions](../../../install/README.md) if you need to
./docs/serving/samples/hello-world/helloworld-java-spring/README.md:17:  [installation …
```
=> Fix broken links

docs/eventing/samples/kafka/_index.md, docs/eventing/samples/kafka/kafka.yaml, docs/eventing/samples/kafka/source/index.md, docs/eventing/samples/kafka/source/kafka-topic.yaml
as per title, since v1beta1 is now gone :fire:
=> Updating to latest API version of Strimzi. 

docs/serving/samples/knative-routing-go/index.md, docs/serving/samples/knative-routing-go/routing-internal.yaml
Fixes #3562
I promised to write down how to support `"httpProtocol": "Redirected"` for the documentation found at https://knative.dev/docs/serving/samples/knative-routing-go/index.html
Thanks to @nak3 I found out how to do it, and wanted to make others lives easier by documenting it.
In case you think it would be better, I can also add graphics - but I did not have the sources of the already-present image, and did not want to make a bad copy of it.
=> docs about usage of internal services in an "api-gateway" access model

docs/serving/samples/knative-routing-go/routing.yaml
Fix typos in the sample yaml file.
=> Fix typos in the sample yaml file

docs/eventing/event-registry.md
I tried adding an EventType as proposed in the example - but `EventType` still is in `v1beta1`, although the example states it would be in `v1` already.
=> EventType is not yet part of the v1 eventing API

overrides/home.html
- drop the a since later on it uses plural for services.
-
-
=> Fix a mismatch in 'a' vs. plural

docs/check-install-version.md, mkdocs.yml
Fixes the search not showing up. We'd accidentally ended up with two `plugins` section in the yaml, which meant the search plugin wasn't in the list of plugins any more
=> One plugin section to rule them all (fixes search)

docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock, docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
`mkdocs` PR of this one: https://github.com/knative/docs/pull/3647
=> Updating to Version 0.3.1 of the CE SDK for Rust

overrides/assets/stylesheets/home.css
Just a liiiiittle bit of padding to make the logo not hug the browser's (and header's) edges as much.
=> Add a bit of padding around the logo in the header

docs/admin/install/install-extensions.md, docs/serving/using-auto-tls.md, docs/serving/using-cert-manager-on-gcp.md
`cert-manager` is deprecating all alpha and beta API versions in the next release (see [cert-manager#4021](https://github.com/jetstack/cert-manager/pull/4021)).
This PR changes `cert-manager` examples in docs to use `v1` API instead of `v1alpha2`.
It also bumps the minimum required version of `cert-manager` to be `v1.0.0`- this is the first stable version and also the first with `v1` API.
Please let me know if this is the wrong branch to PR against- I saw that most PRs were made against this branch rather than `main` so did the same.
Potentially related https://github.com/knative-sandbox/net-certmanager/issues/219
=> Bump cert manager API verson

docs/knative-offerings.md
The [original link to Gardener](https://gardener.cloud/documentation/050-tutorials/content/howto/knative-install/) is out of date. The PR updates it to the [correct one](https://gardener.cloud/documentation/tutorials/knative-install/).
=> fix out of date link to Gardener

docs/eventing/samples/kafka/channel/README.md
This updates the samples/kafka/channel README with information related to the configmap consolidation 
- Describe configmap updates (mainly SASL options and miscellaneous channel configuration) from https://github.com/knative-sandbox/eventing-kafka/pull/622
- Update links and call out areas where the difference between consolidated vs. distributed channel is important
=> Update kafka channel samples with configmap changes

docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json, package-lock.json, package.json
Runs `npm audit --fix` for the cloudevents nodejs sample and, while I was at it, the package.json used by the hugo build.
/assign @csantanapr @evankanderson
=> Bump node dependencies

docs/serving/samples/grpc-ping-go/Dockerfile
Fix compile error on golang 1.12 .  It doesn't define the method "errors.Is" yet. The error message is  as follows. 
#golang.org/x/net/http2  
src/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
golang 1.13+ defined the method "errors.Is", It will pass the compile when using golang 1.13+ instead.
-
-
-
=> Fix compile error for Dockerfile

docs/eventing/experimental-features.md, mkdocs.yml
- This adds a page to document eventing experimental features. For more details: https://docs.google.com/document/d/1AoH0FyLeuHIg5snrlCKzELQv-NEA6bbjTU2Qv3zlW5k/edit?usp=sharing and https://github.com/knative/eventing/blob/main/docs/experimental-features.md
=> Added the experimental features page

docs/eventing/experimental-features.md
Followup of https://github.com/knative/docs/pull/3676
- eventing experimental features page: removed double quotes
=> Remove double quotes on enabled and disabled

docs/serving/feature-flags.md
Documentation in support of [Serving PR #11410](https://github.com/knative/serving/pull/11410)
- Adds documentation for a feature gate that allows users to add Linux capabilities to a container
=> Adding docs for pod capabilities feature flat (see serving PR #11410)

overrides/assets/stylesheets/home.css
-Added margin for the list tag which solves issue #3665 
-Checked on Safari Version 14.1 (16611.1.21.161.6)
=> fixing icon displaying issue in safari  (#3665)

docs/admin/collecting-metrics/eventing-metrics/metrics.md, docs/admin/collecting-metrics/serving-metrics/metrics.md, mkdocs.yml
Another partial fix for #3710 - moving some metrics files into the admin guide metrics section
=> #3710: Moved serving and eventing metrics to admin guide

docs/eventing/samples/helloworld/helloworld-go/README.md, docs/eventing/samples/helloworld/helloworld-go/sample-app.yaml, docs/eventing/samples/helloworld/helloworld-python/README.md, docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
Fixes #3679
-  The sample to create a Broker also.
- Reformat YAML
=> fix eventing/samples/helloworld-python

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css
The `!important` specifier should [generally be avoided because it makes css hard to maintain](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception). Luckily, it doesn't look like we actually need it in any of these cases :).
=> Drop unneccesary important specifiers

docs/admin/install/knative-with-operators.md, docs/admin/install/serving/install-serving-with-yaml.md, docs/admin/install/uninstall.md, docs/serving/README.md
What the subject says, and as discussed at the recent TOC meeting -- the e2e tests haven't been passing for a little while and we want to ensure users will have a good time using the Ingresses that we list in the install guide with Knative.
Note: there are [plans to get this passing again](https://knative.slack.com/archives/C9CV04DNJ/p1623098357393000?thread_ts=1623092993.391700&cid=C9CV04DNJ) so this should hopefully be reverted sometime soonish.
/assign @dprotaso @ZhiminXiang 
cc @hbagdi
=> Temporarily remove kong from install guide

docs/stylesheets/extra.css
Removing the `100%` setting for code font sizing
=> Code font size bug fix

mkdocs.yml
Looks like the upgrade to mkdocs 1.2 breaks relative links that escape the base dir. Absolute links is a trivial fix (although it does break the blog and community links for github pages, but Im not sure we should care now we have PR previews, tbh).
=> Use absolute links for blog and community

community/_index.md, community/annual_reports/_index.md, community/calendar/_index.md, community/contributing/_index.md, community/meetup/_index.md, community/samples/_index.md, community/samples/serving/_index.md, community/samples/serving/helloworld-clojure/index.md, community/samples/serving/helloworld-dart/index.md, community/samples/serving/helloworld-deno/index.md, community/samples/serving/helloworld-elixir/index.md, community/samples/serving/helloworld-haskell/index.md, community/samples/serving/helloworld-java-micronaut/index.md, community/samples/serving/helloworld-java-quarkus/index.md, community/samples/serving/helloworld-r/index.md, community/samples/serving/helloworld-rserver/index.md, community/samples/serving/helloworld-rust/index.md, community/samples/serving/helloworld-swift/index.md, community/samples/serving/helloworld-vertx/index.md, community/samples/serving/machinelearning-python-bentoml/index.md
This commit reverts changes made to community which assumed it was being built by mkdocs (since it's still built with hugo) and caused formatting to break in the community tab.
/assign @omerbensaadon I did a straight `git checkout HEAD~10 community/` so please check I didn't revert something we actually wanted here, but it looks right to me
=> Revert changes to community

community/samples/serving/helloworld-clojure/index.md, community/samples/serving/helloworld-dart/index.md, community/samples/serving/helloworld-deno/index.md, community/samples/serving/helloworld-elixir/index.md, community/samples/serving/helloworld-haskell/index.md, community/samples/serving/helloworld-java-micronaut/index.md, community/samples/serving/helloworld-java-quarkus/index.md, community/samples/serving/helloworld-r/index.md, community/samples/serving/helloworld-rserver/index.md, community/samples/serving/helloworld-rust/index.md, community/samples/serving/helloworld-swift/index.md, community/samples/serving/helloworld-vertx/index.md, community/samples/serving/machinelearning-python-bentoml/index.md
See conversation in #3757.
/hold to make sure the preview looks good before merging this
=> Use bash rather than shell code blocks in community

docs/eventing/sources/sinkbinding/getting-started.md
Simply change API version for SinkBinding from _v1alpha1_ to _v1_ to align with the latest version of knative (v0.23)
=> Change Api version to sources.knative.dev/v1

docs/admin/install/knative-with-operators.md, docs/admin/install/serving/install-serving-with-yaml.md, docs/admin/install/uninstall.md
As discussed in the recent TOC meeting, we want to be sure the Ingresses
we list in the install instructions are ones we're confident will work
well with Knative, to avoid folks having a bad first experience.
Currently we don't have good (any) CI coverage for Gloo, so removing it
from the list for the moment until we do.
/assign @dprotaso @nak3 @ZhiminXiang
=> Drop install instructions for Gloo until we have better CI coverage

docs/admin/install/operator/configuring-serving-cr.md
This patch adds docs for https://github.com/knative/operator/pull/658.
It adds `nodeSelector` to override system deployments by operator.
/cc @houshengbo
=> Add `nodeSelector` to override system deployments by operator

docs/snippets/prerequisites.md
This patch bumps k8s min version to 1.19.
Please also refer to https://github.com/knative/pkg/pull/2157.
/cc @dprotaso
=> Bump k8s min version to 1.19

docs/eventing/experimental-features.md
Followup of #3676
- Adds a warning specifying that experimental features might break, and a link to the details
=> Add a warning about experimental features

docs/eventing/sources/sinkbinding/getting-started.md, docs/eventing/sources/sinkbinding/reference.md, mkdocs.yml
Fixes #3791
- Added context to code snippets on reference page
- Adjusted indentation in code snippet in Create a SinkBinding object section
Other tweaks
- Made the topic title a gerund
- Adjusted the app name in the kn command for creating a Knative Service to match the YAML
- Fixed the note at the end of the reference topic
- Removed API label from Creating a SinkBinding page because it is already on the README page
=> Code snippet tweaks

docs/eventing/experimental-features.md
- Documentation for the experimental feature https://github.com/knative/eventing/issues/5086
=> Documentation for KReference.Group feature

docs/eventing/sources/README.md
Please let me know if this should go against `main` or `release-0.23`.
Fixes #3815"
- Add VMware to maintainers of Tanzu Sources in the event sources docs.
=> docs: Add VMware to maintainers of Tanzu Sources

docs/developer/eventing/sinks/README.md, docs/eventing/sources/sinkbinding/reference.md
No related issue in /docs - this PR cleans up some of the sink docs so that they're grouped in one place in the developer guide, since sinks are not exclusive to SinkBinding objects
=> Cleaning up sink docs

docs/admin/install/knative-with-operators.md, docs/admin/install/serving/install-serving-with-yaml.md
Magic DNS does work locally on minikube, so long as `minikube tunnel` is
running. This caused confusion for a user in slack.
=> Clarify Magic DNS Caveat

docs/admin/install/installing-istio.md
This patch Bump istio version to 1.9.5 for supported Istio version.
https://github.com/knative-sandbox/net-istio/pull/648 started testing it as stable.
/cc @ZhiminXiang @arturenault
=> Bump Istio version to 1.9.5 for supported Istio version

mkdocs.yml
Looks like navigation.instant makes link anchors not work properly (disabled it on a hunch and it fixed the issue). I don't think the feature really buys us anything much, our search index isn't that big, so easiest to just disable it.
Fixes #3829.
/assign @csantanapr @omerbensaadon @dprotaso
=> Remove navigation.instant feature to fix anchors

docs/admin/install/operator/configuring-serving-cr.md
container name `webhook` is duplicated with serving and net-istio. But
the example does not have net-istio's webhook so users hit an issue
like https://github.com/knative/operator/issues/519 and https://github.com/knative-sandbox/net-istio/pull/560
when we followed the current doc.
This patch adds the net-istio webhook to the doc.
/cc @houshengbo
=> Add net-istio webhook to spec.registry.override

docs/stylesheets/extra.css
Ref #3837 
This is supposed to fix code sections breaking in the middle of the word rather than enlarging the table.
=> Fix wrapping behavior of code in tables

docs/admin/install/knative-with-operators.md, docs/admin/install/operator/configuring-serving-cr.md, docs/admin/upgrade/upgrade-installation-with-operator.md, docs/admin/upgrade/upgrade-installation.md, docs/serving/knative-kubernetes-services.md, docs/serving/using-auto-tls.md
- include a section about disabling autotls for a namespace
- handle rename of namespace certificate controller
- handle rename of other net-* controllers
=> docs updates

docs/stylesheets/extra.css
- Widen the center body content of pages from 61rem (620px) to 68rem (about 700px) per this thread: https://knative.slack.com/archives/C9CV04DNJ/p1624553384104500?thread_ts=1624464518.093800&cid=C9CV04DNJ
=> Widen center content area per slack discussion

overrides/assets/stylesheets/home.css
As per title, this fixes the breakpoints (and lacking paddings) on the main page. Also moves the rocket image breaking to even smaller screens as there's no point breaking that this early.
/assign @julz
=> Adjust breakpoint for new max-width

docs/admin/install/serving/install-serving-with-yaml.md
istio.yaml has CRDs and instances of those resources - thus for a successful install we should apply everything in two passes
=> install isstio.yaml in two passes

docs/developer/eventing/sources/containersource/README.md, docs/developer/eventing/sources/containersource/reference.md, mkdocs.yml
In PR #3774 I moved the ContainerSource docs to the developer guide in the navigation, but forgot to relocate the files in the directory structure. This PR fixes that.
=> Relocating ContainerSource docs to dev guide

docs/stylesheets/extra.css, hack/build.sh, overrides/home.html, overrides/main.html, overrides/partials/footer.html
Imports the cookie warning from the old site. For simplicity, this uses the cookie-consent.js script from the old site in both places, so it has to import jquery.
Note: this doesn't actually turn analytics on, but we'll now have the appropriate warnings in place when we do.
Fixes #3776.
=> Add cookie warning to site

hack/build.sh, mkdocs.yml
Sets the branch for code samples (i.e. the `{{ branch }}` variable) to either `mkdocs` (when building the dev docs), or to the version of docs being built (e.g. release-0.23 etc). This makes sure we create the correct links for the `git clones` in the samples.
Fixes https://github.com/knative/docs/issues/3715.
=> Use correct branch for samples

docs/eventing/channels/channel-types-defaults.md
link of "Create an InMemoryChannel" in https://knative.dev/docs/eventing/channels/channel-types-defaults/#next-steps return 404
Signed-off-by: jtcheng <jtcheng@alauda.io>
=> Fix broken links: create-default-channel in page of channel-types-defaults.md return 404

docs/eventing/experimental-features.md
- :bug: Fixed links
- :bug: Added new supported field for kreference-group
=> Little fixes for the experimental features page

docs/help/contributor/style-guide/documenting-code.md
Updating the style for documenting YAML to use two steps instead of one. This fixes the first part of issue #3813.
=> Update style for documenting YAML

hack/build.sh
Fixes #3885.
Totally goofed on which variable to use for the artefact URLs -- was using the version of _docs_ instead of the serving/eventing release version. Fixed, and added some comments. Thanks @nak3 for spotting this!
/assign @nak3 @omerbensaadon
=> Use correct version in artefact URLs

help/contributor/how-to/github.md
- While going through the GitHub workflow for Knative documentation, The very first section is ["Set up your local machine "](https://knative.dev/help/contributor/how-to/github/#clone), which contains the first point to create your fork of the knative/docs repo. 
- So for easy access, we can update the fork URL with the ["fork"](https://help.github.com/articles/fork-a-repo/) word and then can attach the knative/docs URL to the word ["knative/docs repo"](https://github.com/knative/docs) which can be easy for the new contributors to easily access the repo.
=> update fork and knative/docs repo url

mkdocs.yml
Spotted a couple warnings about redirects in the `mkdocs serve` output. This fixes them.
=> Fix up a couple redirects

mkdocs.yml
The docs are currently in mkdocs branch.
We'll want to revert this when we move things back to main.
Fixes #3733 
=> Edit edit link

mkdocs.yml
Fixes #3843 
Before:
After:
/assign @dprotaso @omerbensaadon
=> Add forward slash to search separators

docs/serving/load-balancing/README.md, docs/serving/load-balancing/activator-capacity.md, docs/serving/load-balancing/target-burst-capacity.md
As per title, this setting was missing in our documentation and completes the autoscaling docs again.
/assign @julz
=> Document missing activator-capacity

docs/stylesheets/extra.css
Originally the prev/next links looked like they were part of the header and were easy to miss. This makes it more obvious while at the same time making the header look more sleek.
-
-
-
=> Tame the footer and make the prev/next stand out

.github/workflows/linkcheck-daily.yaml, .github/workflows/linkcheck-pr.yaml
- Add a daily build that checks all the links and posts an alert to Slack if it fails (example run here: https://github.com/benmoss/docs/actions/runs/994372503)
- Add a PR build that just checks links that have changed in the PR
The daily build will only run when mkdocs is merged to main, since periodic actions only run on the default branch
We'll want to update the `base-branch` too when we merge it into main.
=> Add automated link checking

docs/index.md, overrides/assets/stylesheets/home.css, overrides/home.html
This has two advantages:
1. We get the privacy policy (etc) linked on the homepage, which seems Right (also more consistent).
2. We can drop the duplicated cookie popup code in home.html, since it's included via the footer on all non-homepage pages.
=> Add footer to homepage

docs/serving/setting-up-custom-ingress-gateway.md
This patch adds the instruction to use custom Istio Gateway.
Current doc has a similar instruction "customize Istio Gateway
Service". This doc is very similar but for "customize Istio Gateway".
Fix https://github.com/knative/docs/issues/3524
=> Add instruction for custom istio gateway

config/nav.yml, config/redirects.yml, docs/developer/serving/deploying-from-private-registry.md
Partial fix for https://github.com/knative/docs/issues/3935, related to https://github.com/knative/docs/issues/3710
- Move and clean up private container registry docs
- Direct preview link: https://deploy-preview-3965--dev-knative.netlify.app/development/developer/serving/deploying-from-private-registry/
=> #3935: Move private container registry docs to developer guide

docs/admin/install/serving/install-serving-with-yaml.md, docs/admin/install/serving/serving-installation-files.md, docs/admin/install/uninstall.md
The DomainMapping feature is now beta, and therefore built in to the
main yaml files. These links are therefore now 404s.
/assign @dprotaso @omerbensaadon
=> Remove reference to domainmapping yaml

docs/developer/serving/services/private-services.md
https://knative.dev/docs/developer/serving/services/private-services/ says:
> Knative provides three ways to enable private services which are only available inside the cluster:
> 3. Use custom domain mappings.
But DomainMapping for private service is not expected solution.
We can map domainmapping to the local domain (`svc.cluster.local`) but
it is accessible from public.
The option should be removed.
/cc @ZhiminXiang @julz
=> Remove one option to make private service by DomainMapping

docs/eventing/samples/kafka/resetoffset/README.md
This PR is related to the ResetOffset work in the eventing-kafka repository as described in [Issue 588](https://github.com/knative-sandbox/eventing-kafka/issues/588).  It contains a simple page with examples for using the new ResetOffset CRD with Distributed KafkaChannels.
- Adds a new page to the Eventing mkdocs/ branch under `Code Samples --> Apache Kafka --> ResetOffset Example`
I haven't done many docs PRs so please advise if this is in the wrong spot or not following standards - I tried to base it on existing content - thanks ; )
=> Kafka ResetOffset Examples

docs/snippets/install-kn.md
For Homebrew users, they may run into issues upgrading due to a branch
rename from `master` to `main`.
Fixes #3917 
Add section with instructions for Homebrew users that have issues updating kn cli due to a git branch re-name.
=> [#3917] add instructions to upgrade kn

docs/admin/install/knative-offerings.md, docs/knative-offerings.md
- Fix two broken links which are pointing Gardener documentation.
=> Fix broken Gardener links

DEVELOPMENT.md, blog/README.md, docs/serving/knative-kubernetes-services.md
Fixes #4013 
- Fixes broken links on docs/serving/knative-kubernetes-services.md page
(note that the first link here was circular... I assume it was meant to point to the readme)
- Fixes broken links in `DEVELOPMENT.md`
=> fixing broken links

docs/serving/feature-flags.md
- Adds doc under feature flags page for empty dir. This is part of [this work](https://github.com/knative/serving/issues/11664).
=> Add emptydir extension

docs/admin/eventing/broker-configuration.md, docs/admin/eventing/kafka-channel-configuration.md, docs/admin/install/installing-istio.md, docs/admin/install/knative-with-operators.md, docs/admin/upgrade/upgrade-installation-with-operator.md, docs/serving/istio-authorization.md, docs/serving/using-a-custom-domain.md, docs/serving/using-a-tls-cert.md, docs/serving/using-auto-tls.md
Update the commands from using `<<EOF` format to a two step procedure. 
Lots of files to change for the second part of #3813 so this PR will only change the files in the `/admin` and `/serving` directories.
=> Update command style in serving and admin directories

docs/client/README.md
Fixes: [#1251](https://github.com/knative/client/issues/1251)
- Adding information about `KUBECONFIG` env variable
- Adding information about `--config` option in `kn`
=> Updating knative client connection doc

docs/serving/feature-flags.md
This adds the doc for https://github.com/knative/serving/issues/3587 
- Add docs about the new kubernetes.podspec-priorityclassname feature flag for enabling priorityClassName in podSpec
=> Add docs about the new priority class name feature flag

docs/serving/using-auto-tls.md
- Fixes case of cloudDNS.  Refer this example yaml from cert-manager documentation: https://cert-manager.io/docs/configuration/acme/dns01/google/#create-an-issuer-that-uses-clouddns
=> Fixed case of cloudDNS

docs/eventing/event-registry.md
Fixes #4092 
- Fixes a broken link in the Event Registry documentation pointing to the installation of Knative.
=> Updates Broken Link in Event Registry Documentation

docs/eventing/broker/example-mtbroker.md
@matzew it's only "Kafka" without a broker suffix, right? (which is a bit confusing as the other class that I know (`MTChannelBasedBroker`) uses a different scheme (e.g. should then be `KafkaBasedBroker`). Btw would have preferred just an `MTChannel` as the broker class as the `BasedBroker` is really superfluous and redundant. (cc: @lionelvillard )
=> Fix the value of the Kafka broker class to `Kafka`

docs/help/contributor/style-guide/style-and-formatting.md
=> Added definition list formatting rule

docs/stylesheets/extra.css, overrides/main.html
We've been live for a full release now with the new site. Time to take the warnings about being new away!
Also fixed up the colours and text for the warning shown on old docs versions, and added an emoji because emojis are cool.
(Do let me know if you hate the diagonal stripes, I think they look good and emphasise the warning, but this is the sort of things where opinions differ in which case I'll happily drop them!)
Fixes #4150.
=> Update version warning banner for new release

docs/admin/eventing/broker-configuration.md
- Reflect the changes from https://github.com/knative/eventing/pull/5703 and https://github.com/knative/eventing/pull/5713 to the documentation examples.
(Context: it appears that this comment was copied from somewhere else, and the docs happily copied it although it didn't make sense)
This is a second take on #4179, but this time I refrained from trying to clarify the sentences I found confusing and only focused on copying the changes from https://github.com/knative/eventing/pull/5703.
/assign snneji
/assign abrennan89
=> Fix inaccurate description of `default-br-config`

docs/developer/eventing/sinks/README.md
Fixes the following exposed links in the table:
=> Fix exposed links

docs/getting-started/README.md, docs/snippets/install-kn.md, docs/snippets/quickstart-install.md
Fixes #4040 
- Updates the quickstart guide to make use of the `kn-quickstart` plugin instead of the KonK script.
=> Updating quickstart to use the plugin

docs/snippets/install-kn.md
- Fixes typo in homebrew link in install-kn.md snippet
=> Typo in quickstart markdown link

docs/admin/collecting-metrics/collector.yaml
The otel-collector-config configmap referenced in
https://knative.dev/docs/admin/collecting-metrics/#set-up-the-collector
has incorrect configuration which leads to a config loading issue causing
the otel-collector to go into a crashloop. This PR updates the config map
as per https://opentelemetry.io/docs/collector/configuration/
=> Update otel-collector-config configmap

docs/developer/serving/services/custom-domains.md
- Add a description of how to leverage `kn domain` for managing custom domains
- Extended YAML description for `CustomDomain` include the `tls:` section for enabling HTTPS
Note, that I'm not sure about the formatting as I add the `kn` usage in the middle of a numbered list and am not sure how it will be rendered. Any help for fixing the formatting is appreciated. 
Fixes #3496
=> Add how to create custom domains with kn domain

docs/eventing/samples/github-source/README.md
- add instruction to install GitHub event source (same as GitLab example)
=> docs: add github event source install instructions

docs/serving/README.md
Updates #63
- For the last two and half years, we haven't required Istio, but the opening serving sentence still suggests that Istio is a hard dependency.
Brought up by a prospective customer this week.
=> We haven't required Istio for 2 1/2 years

docs/admin/install/knative-with-operators.md
In the  "knative-with-operators" installation documents,  the knative operator is installed to the default namespace.
but this was not mentioned in the "verifiy the installation" section.
- add a step to make sure the user switches to the default namespace before the installation check.
=> set namespace to default before the installation verification

docs/developer/eventing/event-delivery.md
These changes are related to Eventing [Issue #5726](https://github.com/knative/eventing/issues/5726) ([PR #5727](https://github.com/knative/eventing/pull/5727)).
Simply attempting to add a new CloudEvent extension attribute to Dead Letter Sink events capturing the original destination URL.
- Enhancing the current documentation by describing the new `knativeerrordest` extension attribute in the same manner as existing attributes.
Holding until the actual Eventing PR is merged ; )
/hold
=> Enhance DLQ CloudEvents with destination

docs/admin/collecting-metrics/README.md, docs/admin/collecting-metrics/collector.yaml
Fixes #4233
Proposed Changes
Point the collector.yaml referenced in https://github.com/knative/docs/blob/main/docs/admin/collecting-metrics/README.md to the appropriate path. As the current one on the published documentation at step (2) of set up the collector section in https://knative.dev/docs/admin/collecting-metrics/ is still sourced from the master branch.
As a fix I am pointing ```collector.yaml``` to https://raw.githubusercontent.com/knative/docs/main/docs/admin/collecting-metrics/collector.yaml which also has a minor issue on the ```line 19``` where we have a missing : afer the key zpages.
=> fix for issue-4233: correctly sourced collector with a fix

CODE-OF-CONDUCT.md
- adding COC doc to repo (#4066 added a link but for GA we need the doc in the repo itself)
/assign @omerbensaadon @snneji
=> Adding COC doc

docs/snippets/prerequisites.md
Fixes https://github.com/knative/docs/issues/4269
Proposed Changes
The Getting started hyperlink should point to https://knative.dev/docs/getting-started/ and the Deploying images from a private container registry hyperlink to https://knative.dev/docs/developer/serving/deploying-from-private-registry/
Under the ```prerequisites.md``` the aforementioned links were being used relatively with respect to the path of ```docs/admin/install/eventing/install-eventing-with-yaml.md``` & ```docs/admin/install/serving/install-serving-with-yaml.md``` 
This was causing issues in the documentation when used from ```docs/admin/install/knative-with-operators.md``` leading it to miss out on the ```/doc``` path from the page's path. This PR should the problematic behavior.
=> fix for issue-4269: fixing deadlink in knative operator page

config/nav.yml, docs/developer/eventing/sources/apiserversource/README.md, docs/developer/eventing/sources/apiserversource/getting-started.md, docs/developer/eventing/sources/apiserversource/reference.md, docs/developer/eventing/sources/ping-source/README.md
Fixes https://github.com/knative/docs/issues/4287
- Fix `getting-started` page missing in the nabber
- Add event-display as an example for sink
- Document ServiceAccountName in the reference doc
- Various fixes
=> improve ApiServerSource doc

config/nav.yml, docs/admin/serving/config-defaults.md
Documents the `config-defaults` config map, following the same style as the existing `config-deployment` config map.
Part of the GA work.
**Note:** because I am lazy, and because it seems worth at least exploring the idea of fully automating these eventually to prevent things getting out of sync between code and docs, this was actually generated by the super-suuuuuper-hacky toy at http://github.com/julz/gen-configmap-docs. I'm happy to touch up the results, though, it just seemed like a easy (/more fun than doing it manually) way to get these done.
If we like the results of this, I can trivially repeat it to get us started on the other config maps that need documenting.
For API review:
/assign @dprotaso
For conformance and DUX review:
=> Document Defaults ConfigMap

mkdocs.yml
We were opting in to this without it actually being available outside Insiders before, now it's available to all so got silently enabled by the new version coming out and.. I think we need to change our nav a bit to properly use it, so the result is a regression right now.
=> Disable section index feature

docs/eventing/experimental-features.md
- Document `kreference-mapping` eventing experimental feature.
-
-
/hold
depends on https://github.com/knative/eventing/pull/5599
=> Add doc for kreference-mapping

.gitignore
- Updates `.gitignore` file to ignore `venv/` directory (python virtual environment, used for building mkdocs locally)
=> Ignore venv directory

docs/reference/relnotes/README.md
- Fix operator link on https://knative.dev/docs/reference/relnotes/: just changed link from archived knative/serving-operator to latest knative/operator release page.
=> Fix operator link on Knative release notes page

docs/admin/collecting-metrics/README.md
Fixing incorrect documentation for Prometheus setup.
- Change namespace in step 1 to `metrics`
=> Update metrics collector README.md

blog/config/nav.yml, config/nav.yml, docs/stylesheets/extra.css
Per [discussion on Slack](https://knative.slack.com/archives/C01JBD1LSF3/p1635796691053300), we want to make the link to the blog distinct again, by reverting it to the right of the header / putting it in the dark blue box. That's what this PR does.
=> Make blog distinct again

docs/help/contributor/style-guide/documenting-code.md
fixes #4077
Fixes #4077
- Add entry that describes the documentation style of flags that mentions using short flags rather than the extended version
=> Add entry for flag documentation

docs/getting-started/first-source.md
Fixes #4390 
Adds a tip box with instructions for using `curl` to send/receive cloud events to the Getting Started guide. 
Note: I put the tip box in what seemed like a logical place, but I'm totally open to placing it somewhere else on the page if others think there's a better location.
=> Adding command-line instructions for using cloudevents player

blog/config/nav.yml
Fix issue on current blog page where the code-samples nav page goes to code-samples.md instead of code-samples.
ref: https://knative.dev/blog/articles/knative-1.0/
ref: https://twitter.com/cra/status/1458593293458198528
=> Blog: fix code-samples nav link

config/nav.yml, mkdocs.yml
=> Renaming "Overview" pages to be more specific

config/nav.yml
Noticed that this file was on the site but could not be found in the navigation
=> Add Activator capacity to navigation

docs/install/operator/knative-with-operators.md
Fix deprecated sample output documentation
- Use domain-mapping and domainmapping-webhook insted of the net-istio in sample output
- Use new sample output for knative eventing installation
-
=> Fix sample output

docs/snippets/collecting-metrics.md
Fix link to the collector.yaml
=> Fix link to collector.yaml

docs/eventing/samples/kafka/channel/README.md
The proposed yaml to create a Kafka Channel leads to an error, because of the wrong indentation of the spec tag.
- Move the `spec` block one indentation to the left.
See the error here:
```
$ k apply -f harald                 
error: error validating "harald": error validating data: ValidationError(KafkaChannel.metadata): unknown field "spec" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2; if you choose to ignore these errors, turn validation off with --validate=false
$ cat harald                                 
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
name: my-kafka-channel
spec:
numPartitions: 3
replicationFactor: 1
$ vi harald …
```
=> Fix Kafka Channel yaml

mkdocs.yml
Removes `navigation.indexes` to fix `README.md` navigation issue.
See Slack thread: https://knative.slack.com/archives/C9CV04DNJ/p1637161269112900
=> Remove navigation.indexes

docs/serving/services/http-option.md
In [HTTPS redirection](https://knative.dev/docs/serving/services/http-option/) doc, the example uses `enabled` but it is a default value and so it doe not change anything actually.
The section is talking about `HTTPS redirection` so we should use
`redirected` in the example configuration.
/cc @abrennan89 @mgencur
=> Use `redirected` instead of `enabled` in the HTTPS redirection example

docs/eventing/custom-event-source/containersource/README.md
- Add resolved url to heartbeats example. I wasn't sure if there is automation for resolving `[gcloud-project]` to a value or this was just an oversight 🤔  
- Add missing env vars required for heartbeats example to work when using kn
=> Update ContainerSource README.md

config/nav.yml, docs/serving/autoscaling/README.md
Partial fix for  #4485 but doesn't close it
Preview: https://deploy-preview-4486--knative.netlify.app/development/serving/autoscaling/
- Move autoscaling into its own section in serving (not under admin or dev topics)
- Update overview content
- More PRs to follow
=> Move and cleanup autoscaling docs

config/nav.yml, config/redirects.yml, docs/getting-started/first-source.md, docs/install/operator/knative-with-operators.md, docs/serving/autoscaling/autoscale-go/README.md, docs/serving/autoscaling/concurrency.md, docs/serving/autoscaling/kpa-specific.md, docs/serving/autoscaling/scale-bounds.md, docs/serving/autoscaling/scale-to-zero.md, docs/serving/configuration/rolling-out-latest-revision-configmap.md, docs/serving/load-balancing/README.md, docs/serving/load-balancing/activator-capacity.md, docs/serving/load-balancing/target-burst-capacity.md, docs/serving/rolling-out-latest-revision.md, docs/serving/services/certificate-class.md, docs/serving/services/http-protocol.md, docs/serving/services/ingress-class.md, docs/serving/using-auto-tls.md
This makes the config maps and annotation keys consistent 
- update serving examples to use kebab-case for annotations
- update autoscaling examples to use kebab-case for annotations
- update examples to use kebab case networking annotations
- update operator config example to use kebab-case
Related:
- https://github.com/knative/serving/pull/12329
- https://github.com/knative/serving/issues/12103
=> update examples to use kebab case

docs/eventing/broker/rabbitmq-broker/README.md
This is what most users expect. Without it, the Messaging Topology Operator will not be able to manage objects from a different namespace. The implications are that all Brokers / Triggers / Sinks need to be created in the same namespace as the RabbitmqCluster. This annotation addresses that limitation.
More context:
- https://github.com/knative-sandbox/eventing-rabbitmq/issues/454
- https://github.com/rabbitmq/messaging-topology-operator/pull/201
=> Default to a single RabbitMQ cluster per Knative Eventing installation

docs/serving/autoscaling/autoscaling-metrics.md
This documents changes made in : https://github.com/knative/serving/pull/12277
- Add documentation for HPA autoscaling by custom metrics
=> adding documentation for hpa custom metrics

docs/serving/services/custom-domains.md
DomainMapping API uses `secretName`, not `secret`, see https://knative.dev/docs/reference/api/serving-api/#serving.knative.dev/v1alpha1.SecretTLS
=> Fixed wrong docs for DomainMapping API

blog/docs/articles/distributed-tracing.md
I was doing another pass at using tracing and going through my [blog post](https://knative.dev/blog/articles/distributed-tracing/). I noticed that some things no longer work because of upstream changes. This hard-codes the versions of the OTEL and Jaeger operator so that they continue to work with the examples as written.
=> Update details in the tracing blog post

blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
Update documents to reflect changes for knative v1.0.0.
=> Update links in document to Knative v1.0.0

docs/eventing/broker/kafka-broker/README.md
Fixes #4460
- Document Kafka Broker commit offset interval
=> Document Kafka Broker commit offset interval

blog/config/nav.yml, config/nav.yml, config/redirects.yml, docs/community/README.md, netlify.toml, overrides/home.html
Fixes #4576
- Update the contribute call to action on home page 
- Change "Join the Community" to "Community" in the menu
- Update Community overview page name
- Redirect away from old docs contributor guide.
=> Update contributing call to action and links

docs/eventing/sugar/README.md
Fixes #4543 
- fix docs to document that only a broker named "default" can be created using a Trigger with injection enabled.
=> Update Sugar Controller Instructions

hack/build.sh
Fixes #4562
- Add v1.1 drop v0.24 for docs
- Refactor build script to make simpler to release a new version of the docs
=> cut docs for knative v.1.1

docs/eventing/configuration/kafka-channel-configuration.md, docs/eventing/configuration/sources-configuration.md, docs/install/eventing/install-eventing-with-yaml.md, docs/install/operator/configuring-eventing-cr.md
- Update ConfigMap element names for eventing's channel and pingsource. They are [being renamed to keep consistent](https://github.com/knative/eventing/issues/5789) with other configuration elements.
Previous configuration element names are still processed the same but we want the new ones to be the only reference to users.
**MERGEABLE** since related PR at https://github.com/knative/eventing/pull/5875 got merged.
=> update config elements for eventing channel and pingsource

blog/README.md, contribute-to-docs/what-to-contribute/creating-blog-posts.md
Fixes #4340 
Updates the docs contributor guide to include instructions for updating the blog now that it's on mkdocs.
/assign @snneji 
One question: does the [leadership](https://github.com/knative/docs/blob/main/contribute-to-docs/what-to-contribute/creating-blog-posts.md#leadership) section need to be updated, or is this list still accurate?
=> update instructions on creating blog posts

overrides/main.html
Fixes #4593 
This fixes an issue where the warning message "You are viewing an archived snapshot of the documentation for Knative version 1.0" was not properly displaying. This fix creates an if-then-else announce block whereby the link to the 1.0 blog is shown on the current version, and past versions will show the you're looking at old docs" warning. 
It seems that the warning not being in the announce block was what was causing the problem with the 1.0 docs. It didn't show up as an issue prior to this because the link to the 1.0 blog was only added in the v1.0 docs.
Since this is a file change, I believe it will need to be cherry picked into the 1.0 release branch to take effect on https://knative.dev
/cherry-pick release-1.0
/assign @csantanapr
=> Fixes website banner for v1.0

.gitignore
When building the website locally, the `docs/images/case-studies` directory gets copied to `blog/docs/images/case-studies`, creating a local copy that isn't needed. This would prevent that directory from being merged (and make the local experience a bit nicer by not having an untracked git directory sitting around).
=> Ignore duplicate case-studies images

hack/build.sh, hack/macros.py
The 1.0 docs were displaying the "old version" incorrectly:
This fixes the issue by stripping `knative-` out of the version number and then adding it back to the artifact paths in macros.py.
=> Fix 1.0 banner again

docs/eventing/sources/apiserversource/getting-started.md
"Fixes #issue-number" or "Add description of the problem this PR solves":
Following the `Creating an ApiServerSource object` docs leads to a permission issue with the ApiServerSource.
Adds namespace to the Role and RoleBinding. They would be tied to the default namespace otherwise and the ApiServerSource wouldn't start
=> Adds namespace to Role and RoleBinding in ApiServerSource example

docs/getting-started/first-service.md
Updates URL of first service to use `sslip.io` domain
from [this](https://github.com/knative/docs/issues/4547#issuecomment-1002549336) comment
/cherry-pick release-1.1
(^^^ to bring into current version of docs)
=> Update getting started to sslip default domain

docs/install/serving/installing-istio.md
- [In the part of install istio](https://knative.dev/docs/install/serving/installing-istio/#choosing-an-istio-installation), unnecessary back quotes and string `sh` is shown (see the image below).
- This bug is caused by the rule of Markdown. If we indent 4 spaces or more, markdown makes a code block ([ref](https://dosenbachlab.wustl.edu/wiki/markdown-guide/#:~:text=To%20produce%20a%20code%20block,This%20is%20a%20code%20block.&text=A%20code%20block%20continues%20until,the%20end%20of%20the%20article)).
- To solve the bug, I just deleted indents.
- I already checked by my forked [github-pages](https://shunpoco.github.io/docs/install/serving/installing-istio/#choosing-an-istio-installation).
=> Fix bugs: delete indented code block in installing istio

golang/_redirects, tools/redir-gen/main.go, tools/redir-gen/redirtemplate.gohtml
Opening this to start a conversation, feel free to close if this has been proposed and rejected before.
Basically, I'd love to be able to browse to https://knative.dev/serving, https://knative.dev/pkg, etc., and not get a 404. With this change, these URLs should be processed by real browsers with a client-side redirect to https://pkg.go.dev/... where any available Go package docs will be served.
If the repo doesn't have Go packages, this will redirect to a 404 over there. But for knative.dev/pkg, etc., this would be more useful. We can talk about adding some configuration to only redirect if the package has Go code, maybe? 🤷 
The only real code change is in `tools/redir-gen/main.go` (at the bottom of the list of changed files in this PR), the rest is generated by running that script. I've …
=> Redirect to Go package docs from a real browser

docs/samples/README.md
Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>
This PR adds a link to an Iter8 tutorial, that demonstrates how  to load test a Knative service and validate SLOs, in a simple manner.
***
The last time I presented Iter8 in the Knative community meetup, I received a suggestion to create/add/link docs on how to effectively use Iter8 with Knative. This is the first of those docs. We hope to follow up with more docs on topics such as auto-rollouts, gitops, and A/B/n testing with Knative using Iter8.
=> Iter8 load testing tutorial

docs/eventing/sources/README.md
This PR adds clarification that event sources which import messages from technologies such as Kafka, don't create/set optional attributes such as the `datacontenttype`.  That's a responsibility on the event producer.
=> Mention optional attributes for CloudEvents in event sources overview

hack/macros.py
Fixes the macro that generates the link to the client reference docs.
/cherry-pick release-1.1
/assign @snneji
=> Fixes link to client reference

docs/install/operator/knative-with-operators.md, docs/install/serving/install-serving-with-yaml.md, docs/install/uninstall.md, docs/serving/README.md, docs/serving/using-auto-tls.md
Per this [Slack thread](https://knative.slack.com/archives/C0186KU7STW/p1637152982231400), we should probably remove Ambassador as a supported networking layer. 
See also #2050
=> Remove unsupported Ambassador networking layer from docs

config/nav.yml, docs/getting-started/README.md, docs/getting-started/first-broker.md, docs/getting-started/first-service.md, docs/getting-started/first-source.md, docs/getting-started/first-traffic-split.md, docs/getting-started/first-trigger.md, docs/getting-started/quickstart-install.md, docs/install/README.md, docs/install/client/install-kn.md, docs/install/serving/installing-istio.md, docs/snippets/install-kn.md, docs/snippets/prerequisites.md
Fixes #4197 
- Renamed getting started section to Tutorial
- Added an introductory page for the tutorial
- Made it clear that you must install using Quickstart to follow the tutorial
- Removed reference to getting started on Istio page because Istio is for an advanced install
=> Clarify purpose of getting started

docs/install/operator/configuring-serving-cr.md
There's a pitfall when following the doc to use Operator CR to override container registry. 
In the CR, when directly using `net-istio-controller` as the key, it somehow falls back to the knative serving `controller` image without any warning, thus we got `IngressNotConfigured` error when starting an ksvc.
There has been some discussions about it but the doc is still somewhat misleading.
- https://github.com/knative/operator/issues/519#issuecomment-827447017
- https://github.com/knative/serving/issues/12413#issuecomment-989966245
- https://github.com/knative/operator/issues/860
Therefore, it would be better to use explicit `net-istio-controller/controller` instead.
- Replace `net-istio-controller` with `net-istio-controller/controller`
=> More explicit net-istio-controller controller registry override in Operator CR

docs/getting-started/first-traffic-split.md
The "First Traffic Split" markdown has a trailing double quote on one of the expandable sections.
- remove extra trailing double quote
=> fix: first traffic split markdown has erroneous double quote

config/nav.yml, docs/getting-started/first-autoscale.md, docs/getting-started/first-broker.md, docs/getting-started/first-service.md, docs/getting-started/first-source.md, docs/getting-started/first-traffic-split.md, docs/getting-started/first-trigger.md, docs/getting-started/getting-started-eventing.md, docs/snippets/install-kn.md, docs/snippets/quickstart-install.md
Fixes #4554
Fixes #4736 
- Style edits to all pages in the tutorial
- Added a step for running `minikube tunnel` to the quickstart install page
- Changed the name of some of the Eventing tutorial pages to make it clearer that the tutorial covers sources and sinks
=> Clarifications and style edits for the tutorial

docs/getting-started/first-service.md
- This PR fixes a blockquote that erroneously specifies a `bash` as the language, when the content is `yaml`.
=> fix: first-service.md uses `bash` rather than `yaml` for YAML

overrides/home.html
- Removes one of the 'in's in "Knative is an open-source enterprise-level solution for leveraging Kubernetes in in serverless applications."
=> fix: remove duplicate 'in' on home page

docs/getting-started/first-service.md
- This PR adds a missing `bash` language to the `curl` code block.
=> fix: first-service.md curl command is missing `bash` language

docs/eventing/flows/sequence/sequence-reply-to-sequence/README.md
In the [Sequence wired to another Sequence](https://knative.dev/docs/eventing/flows/sequence/sequence-reply-to-sequence/) example the knative Service for event-display has a typo in the template spec.
- Fixed typo `containerers ` --> `containers`
=> Fx typo in event-display Service template spec

hack/build.sh
This allows us to pull in changes in the latest patches vs. it being fixed to the first release
=> Pull the API specs from the release branch vs a fixed tag

docs/install/client/configure-kn.md
As discussed in WG in Feb, updating the client configuration details to note that `path-lookup` is enabled by default. Also some minor syncing between the docs text and what's in https://github.com/knative/client/tree/main/docs#options
=> Updating client configuration details

blog/docs/steering/cncf.md
have easy way to find and link to vendor blog posts
=> add vendor blogs to cncf announcement

config/nav.yml, docs/reference/security/README.md
Adds security page to the website. Modeled after the [Kubernetes page on the same topic](https://kubernetes.io/docs/reference/issues-security/security/)
Fixes #4672 
/assign @evankanderson for WG review
/assign @csantanapr @snneji for DUX review
=> Adds security page to site

hack/macros.py
Note - the way the build script works now we'll need to cherry pick this change to older release branches
We should also confirm the netlify builds use a valid GITHUB_TOKEN so we don't hit any rate limiting
=> update macro to lookup point releases for artifacts

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/_template-announcing-knative-v1-X-release.txt, blog/docs/releases/announcing-knative-v1-2-release.md, blog/docs/releases/announcing-knative-v1-3-release.md
Adds the blog post for 1.3 release notes. I also made a some changes to the heading levels in the template.
I made a guess at which items from the release notes seemed like highlights because it seems like this release mainly consists of various small improvements and bug fixes.
Fixes #4790
=> Release note blog 1.3

netlify.toml
Sets `BUILD_VERSIONS="no"` for deploy previews to only build `main` branch and not the various release versions
Fixes #4525 
(see also [slack discussion](https://knative.slack.com/archives/C9CV04DNJ/p1647874975497899))
=> only build main branch for deploy preview

hack/docker/README.md
Fixes #4832 
Removes the references to using `npm` for running the Docker container and instead points to the "contributing to the docs" page with the same info. This will also allow us to have a single source of truth for future edits, etc.
=> Updates instructions on running mkdocs locally in docker

docs/serving/using-auto-tls.md
This patch fixes a tiny tpo `s/Provising/Provisioning`.
=> Fix typo in TLS doc

blog/docs/articles/set-up-a-local-knative-environment-with-kind.md, docs/install/yaml-install/serving/install-serving-with-yaml.md, tutorials/katacoda/1-serving-intro/step1.md, tutorials/katacoda/2-serving-intro-yaml/step1.md, tutorials/katacoda/3-eventing-intro-channels/scripts/install-dependencies.sh, tutorials/katacoda/4-eventing-intro-broker/scripts/install-dependencies.sh
As per title, this patch replace `ingress.class` with `ingress-class`.
The style was updated by https://github.com/knative/networking/pull/522. The old `ingress.class` is still available but it should be consistent in the docs.
Note, only Kong uses `ingress.class` in the code tree so I leave it as it is after opening https://github.com/Kong/kubernetes-ingress-controller/issues/2344.
Fix https://github.com/knative/docs/issues/4855
=> Replace `ingress.class` with `ingress-class`

.github/workflows/knative-dot-release-build.yaml, .github/workflows/knative-nightly-site-build.yaml, contribute-to-docs/docs-release-process.md
Fixes #4840 
This adds a github action to trigger a build of the website on any push to the `release-1.*` branch (the current version of the docs). 
It also adds an action to build the site nightly (so as to automatically pick up any dot releases for Knative components in a timely manner)
/assign @csantanapr (for branch strategy)
/assign @dprotaso (for a second pair of eyes on the GA syntax)
=> Adds Github Action for building on push to release branch

requirements.txt
Fixes an issue with jinja2 module that was breaking the build
Once this merges, we should close #4872  (which fixed the issue by pinning the jinja2 version, before I realized mkdocs-material already had a new release out with the fix)
/assign @csantanapr
=> update mkdocs to 8.2.7

blog/docs/releases/announcing-knative-v1-3-release.md
- Fixes the eventing-rabbitmq release notes to use the v1.3.1 release notes. It appears as though they were using v1.2 release notes.
=> Fix eventing-rabbitmq release notes for Release Blog v1.3

docs/getting-started/first-autoscale.md, docs/getting-started/first-service.md, docs/getting-started/first-traffic-split.md, docs/snippets/quickstart-install.md
This is part of the epic https://github.com/knative/docs/issues/4553
Fixes #4245 #4740 #4612
This PR addresses
- Minimum requirements (ie CPU and Memory) for `kn quickstart`
- https://github.com/knative/docs/issues/4245
- URL to work with minikube quickstart
- https://github.com/knative/docs/issues/4740
- Not hardcoding revision names
- https://github.com/knative/docs/issues/4612
=> Update serving tutorial

docs/getting-started/first-source.md
As part of #4815 we removed the IP address from links and commands because it did not work for minikube. 
This PR fixes a few locations that were missed out of that PR. Should hopefully make this page easier to use until we replace the Eventing tutorial as part of https://github.com/knative/docs/issues/4440.
=> Updated a few more Loadbalancer IPs

docs/eventing/sources/kafka-source/README.md
=> removed step 1 of creating service

docs/install/installing-istio.md, docs/install/uninstall.md, docs/install/upgrade/upgrade-installation-with-operator.md
=> Fix broken formatting in Installing guide

docs/eventing/channels/subscriptions.md
Fix typo in docs/eventing/channels/subscriptions.md
=> Fix typo in subscriptions.md

docs/eventing/broker/README.md, docs/eventing/sinks/README.md
- 3 link pointing to the spec docs fixed.
- There is a [slightly related PR at spec](https://github.com/knative/specs/pull/99) that should improve further navigation.
=> Fix eventing spec links

docs/install/upgrade/upgrade-installation-with-operator.md, docs/install/upgrade/upgrade-installation.md
Fixes https://github.com/knative/docs/issues/4863
- Updates versions to use 1.1+
- This change can maybe be cherrypicked back to older versions still supported (1.1, 1.2, 1.3, 1.4)
NOTE: A better long term solution would be either to make it part of the release process to update these docs for every version, or to find a way to make the docs not version specific.
Preview links:
- https://deploy-preview-4984--knative.netlify.app/docs/install/upgrade/upgrade-installation/#performing-the-upgrade
- https://deploy-preview-4984--knative.netlify.app/docs/install/upgrade/upgrade-installation-with-operator/
=> Update upgrading docs versions

blog/config/nav.yml, blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
As discussed in the WG today, the quickstart plugin has replaced the "setup knative on kind" blog post. This PR removes the link to said blog post and adds a warning at the beginning of the docs for users to use quickstart instead.
=> Removes blog link to old knative kind setup

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- This PR added the instruction on the feature to configure the env vars for the containers with Knative Operator.
=> Add the instruction on how to override/add env vars for containers

contribute-to-docs/docs-release-process.md, hack/build.sh
Fixes #4975 
- cut version 1.5
- simplify build script with only one variable now to touch
In a future we could remove this, and configure it automatically based on the last 4 release branches, and no need to edit the build script on every release
=> cut release 1.5, remove extra vars for build

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- This is a critical doc issue in 1.4 for knative operator. We need to drop the incorrect system resource configuration for knative operator.
=> [release-1.4] Correct the instruction on system resource settings

docs/eventing/sources/kafka-source/README.md
Fixes https://github.com/knative/docs/issues/3081
=> Fixes kafkasource bugs

hack/build.sh, hack/macros.py, hack/mkdocs.sh
Adds copyright info to hack scripts that didn't have this info. Dates are best estimates (for example, anything related to mkdocs I'm assuming is 2021)
=> Adds copyright info to some hack scripts

docs/eventing/broker/kafka-broker/README.md
- adding little note about the CE content mode that the broker uses and pointing to the notion of using kafka headser for "CE metadata"
/assign @pierDipi
=> Adding a little sentence on the CE mode of knative kafka broker

docs/eventing/sources/ping-source/README.md
"Fixed the problem in statement for  <sink-kind> supported objects by removing Deployment as It cannot be used as sink"
- wrong sentence here:
<sink-kind> is any supported [Addressable](https://knative.dev/docs/reference/concepts/duck-typing/#addressable) object that you want to use as a sink, for example, Service or Deployment.
*since Deployment cannot be used as sink*
- Correct Sentence here:
<sink-kind> is any supported [Addressable](https://knative.dev/docs/reference/concepts/duck-typing/#addressable) object that you want to use as a sink, for example, Service.
@abrennan89
=> fixed <sink-kind> supported object issue

docs/install/upgrade/upgrade-installation-with-operator.md
Fixes the ["Upgrading with the Knative Operator"](https://knative.dev/docs/install/upgrade/upgrade-installation-with-operator/) example which states the versions a knative operator release supports with an example.
Currently it states a knative operator version 1.5 would even support 1.1 which is different then the infos in the knative 1.5 release information.
- Fixing the example for supported changes
- Got supported versions from knative 1.5.1 release: https://github.com/knative/operator/releases/tag/knative-v1.5.1
=> fix: Update the knative-operator supported versions example

contribute-to-docs/getting-started/previewing-docs-locally.md, hack/docker/test.sh
Fixes #4930 
Updates the local full site build using Docker to include a required github token (provided by user)
/assign @csantanapr
=> Add github token to local docker build

docs/install/installing-istio.md
Link to the net-istio releases github page as the source of truth for supported versions per release instead of having a hard coded value.
**Description of problem the PR solves:**
Received messages on slack asking which versions of Istio we support and the docs page is out of date.
Linking to the net-istio releases page seems a better strategy in combination with [this issue](https://github.com/knative-sandbox/net-istio/issues/958) as opposed to updating the documentation every time. 
Worst case scenario the release notes can be updated manually instead of new documentation PRs.
- Link to the net-istio release page to show supported Istio version instead of hard coding.
=> Istio supported versions change

docs/serving/autoscaling/scale-bounds.md
Adds documentation for the `active-min-scale` annotation added in https://github.com/knative/serving/pull/13136
There's an ongoing discussion over the name of this annotation on [slack](https://knative.slack.com/archives/C9CV04DNJ/p1658938603476139), so this may need an update. But since the serving PR has already merged, may as well start getting the docs in for it.
=> Add documentation for active-min-scale

docs/eventing/broker/kafka-broker/README.md
This feature has been stable for quite some time, but we missed
the doc update so cherry-picks are necessary.
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>
- Remove unstable to Kafka broker ordered delivery feature
=> Remove unstable to Kafka broker ordered delivery feature

config/nav.yml, docs/eventing/broker/rabbitmq-broker/README.md, docs/eventing/sources/rabbitmq-source/README.md, docs/snippets/event-display.md
Right now, the RabbitMQ Source does not have an entry in the docs. This PR adds it to the Sources section and also updating the Broker docs to show that the RabbitMQ Cluster operator is no longer needed for Eventing RabbitMQ to work.
- Added RabbitMQ Source docs to Sources
- Fixed minor typos in Broker readme
- Specified that creating a Cluster with the RabbitMQ Cluster operator is now optional for the Eventing RabbitMQ CRDs
=> RabbitMQ Source docs

docs/eventing/broker/kafka-broker/README.md
- As per title: Trying to improve the wording that each kafka broker can have its own, independent configration, that basically overrides the global defaults
=> A try to change the wording for overriding the brokers config, on a per broker base

code-samples/community/serving/helloworld-dart/Dockerfile, code-samples/community/serving/helloworld-dart/README.md, code-samples/community/serving/helloworld-dart/analysis_options.yaml, code-samples/community/serving/helloworld-dart/bin/server.dart, code-samples/community/serving/helloworld-dart/pubspec.yaml
Update all Dart sample files to follow the latest Dart server template (`dart create -t server-shelf`).
=> Update Dart sample to latest Dart server template

docs/client/kn-plugins.md
Fixes https://github.com/knative/docs/issues/5065
=> Add list plugins command docs

docs/getting-started/first-traffic-split.md
Fix 'alwayss' to 'always' in traffic splitting.
- Fix type in Traffic Splitting (getting started) https://knative.dev/docs/getting-started/first-traffic-split/#verify-the-traffic-split :
alwayss -> always
=> Fix typo in Traffic Splitting getting started page

docs/serving/queue-extensions.md, docs/serving/services/using-queue-extensions.md
Hi, 
I noticed that the link we have for the readme file of security-guard is not working. 
Here is a fix
Best if we can fix v1.7 as well. 
Fixes https://github.com/knative/docs/issues/5197
=> [release-1.7] Fix guard readme link

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- Added the instruction on how to configure the podDisruptionBudget with the knative operator.
=> Add the configuration of podDisruptionBudget for knative operator

code-samples/serving/hello-world/helloworld-java-spring/README.md
This PR fixes the syntax of `code-samples/serving/hello-world/helloworld-java-spring/README.md`, which is mixing Markdown and Asciidoc syntaxes.
=> Fixed markdown syntax in helloworld-java-spring/README.md

docs/install/operator/configuring-serving-cr.md
When creating the CR by the yaml explained in the doc,  it fails due to the type mismatch of number vs string.
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
name: knative-serving
namespace: knative-serving
spec:
version: 1.5
```
Here is the error:
```shell
$ kubectl  apply -f a.yaml 
The KnativeServing "knative-serving" is invalid: spec.version: Invalid value: "number": spec.version in body must be of type string: "number"
```
To fix it, this patch adds the double quote in the version number.
=> Add double quote for version number in KnativeServing CR

docs/snippets/prerequisites.md
xref: https://github.com/knative/pkg/pull/2595
=> Bump minimum kubernetes version to 1.23

docs/getting-started/first-trigger.md
Fixes some wording in the Eventing [Getting started guide](https://knative.dev/docs/getting-started/first-trigger/#creating-your-first-trigger)
`The expand the next note to see how to use Filters` -> `Expand the next note to see how to use Filters`
=> Fix wording in eventing getting started guide

docs/serving/autoscaling/rps-target.md
Making it clear in the docs that when using RPS for autoscaling, users need to set the scaling metric annotation regardless of if the target is set per-revision or via the global configmap.
Issue surfaced in [slack discussion](https://knative.slack.com/archives/C93E33SN8/p1662019087164369)
=> Using RPS as scaling metric always requires an annotation

docs/eventing/custom-event-source/sinkbinding/create-a-sinkbinding.md, docs/eventing/custom-event-source/sinkbinding/reference.md
At two places in the docs the api version `batch/v1beta1` was still used. For `CronJob`s this was deprecated in kubernetes 1.21 and unavailable since v1.25 (see [deprecation-guide CronJob v1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)).
This PR addresses it and changes the api version for the examples to use `batch/v1`
=> Update docs to use batch/v1

docs/eventing/brokers/broker-developer-config-options.md, docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
PR fixes:
* some markdown syntax in the RabbitMQ Broker doc, so the code example is displayed properly (048ba6d8ae5beff5a01f6fc3ec84d223eca3224c)
* some broker spec indentation in the Broker configuration example (e9eb2d51d4a43f29d364ab419a2e13453884eebf)
* use correct target namespace for broker in broker configuration example, as the current namespace depends on the used kubeconfig context (6e41f0645d48cb2d4b381570c4b91d885c280e79)
* states support for RabbitMQ broker in configuration example (009f6d1bc8f06c8d45ee2e01a953eacbd7c3ac33)
=> Fix issues in broker docs

docs/eventing/troubleshooting/example.yaml
In the docs for debugging eventing (https://knative.dev/docs/eventing/troubleshooting/) the referenced example.yaml contains an deprecated/ now unavailable api version for the ApiServerSource:
https://github.com/knative/docs/blob/e9bb939b7e023b9d0dafcca882cfb05105fb0287/docs/eventing/troubleshooting/example.yaml#L14
This leads to an error on applying the yaml:
```
$ k apply -f example.yaml                                                                                                                                                                                                                                                                                                          
namespace/knative-debug created
inmemorychannel.messaging.knative.dev/chan created …
```
=> Update ApiServerSource apiVersion in example.yaml

docs/serving/configuration/feature-flags.md
This PR adds three missing feature flags to the Serving docs. This gets all of the active feature flags on the site.
(There's a fourth, `autodetect-http2`, that hasn't been implemented, and thus not adding it to the docs at this time)
=> Add missing serving feature flags to site

golang/_redirects, golang/func.html
Note that I did not change knative-sandbox/kn-plugin-func. These should be removed after the move.
See: https://github.com/knative/community/issues/1169
=> chore: add redirects for func

code-samples/serving/hello-world/helloworld-python/README.md
This PR fixes markdown syntax in the `serving/hello-world/helloworld-python/README.md` file. Making it easier to read for new starters.
- Update markdown syntax in `serving/hello-world/helloworld-python/README.md` file
=> Fixed markdown syntax in Python serving README.md

docs/serving/using-auto-tls.md
- Remove note about requirement to use http-protocol enabled with http01 challenge. 
It seems to imply that http-01 challenge will work only with http-protocol set to enabled, but it does work with "Redirected". This seems to be have been an issue in the past [#423](https://github.com/knative-sandbox/net-contour/issues/423) before  being solved by this PR #610: 
- Typo in cluster
_PS_: There is also a mention to a deprecated value (Disabled) for http-protocol, but it seems to be still valid to use. Not sure if it should be removed or not from line 252.
=> Remove note about requirement to use http-protocol enabled with http01 challenge

blog/config/nav.yml
The top level navigation in the blog section did not include headers for Functions and the Knative CLI.
=> Fix top-level nav in blog section

blog/docs/events/knative-at-kubecon-na-2022.md
Basically, make it easy for readers to see when an event is occurring.
/cc @evankanderson - thanks for your belated input on https://github.com/knative/docs/pull/5291. I have addressed your concerns in a follow up PR. I did not include information about vendor booths. If you want to help out with some wording on that, I'd be happy to include it. As far as Red Hat goes, we'll have Serverless demos at our booth, but those will be part of a larger set of demos that feature other tech and I don't really have a schedule for that. Not sure what IBM will be doing.
=> Improve overall structure of kubecon blog post

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-8-release.md
As per title, this patch adds the blog post for 1.8 release.
/cc @lionelvillard @snneji @abrennan89
/cc @davidhadas @upodroid (I added about security guard & image signing)
=> Add release blog post for 1.8 release

docs/snippets/temporary-dns.md
Fixes #5316 
We updated the default domain in knative/serving#13259 to `svc.cluster.local`, which is not reachable outside of the cluster. As a result, users who want to use the temporary DNS option will first need to patch in a domain (for example, `example.com`) before they'll be able to reach the service.
=> Update instructions for using temporary DNS in installation section

docs/reference/security/README.md
Fixed a typo and updated the email to be a `mailto` link.
=> chore: update security report detail

docs/eventing/channels/channels-crds.md, docs/eventing/channels/channels.yaml
Currently the different channel links in the [docs](https://knative.dev/docs/eventing/channels/channels-crds/), lead to a 404 (e.g. to `https://github.com/knative/eventing/tree/%7B'provider':%20'mike'%7D/config/channels/in-memory-channel/README.md`). This PR addresses it and fixes the links to resolve correctly.
What did I do?
* Fix the URLs in `docs/eventing/channels/channels.yaml`
* run `go run eventing/channels/generator/main.go`
=> Fix channel links

docs/functions/building-functions.md
"Fixes a broken link for the on cluster build documentation"
- Update the link
=> fix broken link for on cluster build

docs/snippets/functions-templates-intro.md
Fixes #5334 
- Update links to point to `function-templates` instead
=> Fix stale links in functions-templates-intro snippet

docs/eventing/experimental-features/new-trigger-filters.md
Fix some typos `expession` -> `expression`
=> chore: fix typos in new trigger filter docs

docs/snippets/proc-running-function.md
Indicate that when running a function, if it has not yet been built, the developer will need to provide the `--registry` flag.
Fixes: https://github.com/knative/docs/issues/5309
/kind fix
=> fix(functions): include --registry flag for `run`

blog/OWNERS
The top-level docs OWNERS file include the docs WG leads and the TOC, so post CNCF move we shouldn't need separate approvers for the blog.
=> Remove outdated blog OWNERS file

docs/snippets/functions-templates-intro.md
Signed-off-by: Thomas Risberg <risbergt@vmware.com>
Adds missing link to springboot template doc to "Function templates" section of the "Knative Functions overview" page 
- adds a line for "Spring Boot" to the list of function templates
=> Add link to springboot for function-templates

docs/serving/app-security/security-guard-install.md
Signed-off-by: David Hadas <david.hadas@gmail.com>
1. Found indentation issues with the example script for installing guard with TLS using operator
2. script worked only if one first installed guard without TLS... change the order of the script such that it can be installed on vanilla Knative.
=> Guard script fix - for 1.9

docs/snippets/quickstart-install.md
Signed-off-by: Vivek Kumar Sahu <vivekkumarsahu650@gmail.com>
This PR adds a NOTE before installation of Knative on kind. While Installing Knative on kind could lead to error something like: 
```
Error starting userland proxy: listen tcp4 127.0.0.1:80: bind: address already in use.
```
Basically knative will use Port 80. So, if Port 80 is already is use then you can get above errors.
Solution:
Check the Port is already is in use or not:
```
netstat -tnlp | grep 80
```
If it in use, stop that service using port 80. 
- Added NOTE to make sure Port 80 is free before installing knative on Kind.
=> added note for knative installation on kind

docs/install/operator/configuring-eventing-cr.md
Fixes #5277
- describing `affinity` on a different deployment, since there is no activator in Eventing
NOTE: this just fixing the problem w/ the `ACTIVATOR`, not trying to address https://github.com/knative/docs/issues/5276  (which is a separate issue)
=> We do not have an activator in Eventing

code-samples/serving/multi-container/README.md, code-samples/serving/multi-container/servingcontainer/servingcontainer.go, docs/eventing/channels/generator/main.go, test/sampleapp/config.go
Remove ioutil for new go version: https://go.dev/doc/go1.16#ioutil
=> Cleanup: remove ioutil for new go version

docs/eventing/observability/logging/fluent-bit-collector.yaml, docs/serving/observability/logging/fluent-bit-collector.yaml, docs/serving/stackdriver/Dockerfile
This PR is a part of https://github.com/kubernetes/k8s.io/issues/4780.
This PR does the following changes:
- modify all occurrences of k8s.gcr.io to registry.k8s.io.
=> Migrate from k8s.gcr.io to registry.k8s.io

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/kafka-broker/README.md, docs/eventing/configuration/kafka-channel-configuration.md, docs/eventing/event-registry.md, docs/eventing/sinks/kafka-sink.md, docs/eventing/sources/kafka-source/README.md
Manual cherry-pick (:cherries:) for https://github.com/knative/docs/pull/5461
- The PR underlines that we offer implementation/apis for Apache Kafka, not the other way around
=> [release-1.9] Update the usage of Apache Kafka term

docs/eventing/experimental-features/new-trigger-filters.md
`not` do not expect a list of filters, it only expects only one filter. [not_filter.go](https://github.com/knative/eventing/blob/f6ca59b33fb42ff981367b43dc0280841ac324b6/pkg/eventfilter/subscriptionsapi/not_filter.go#L27-L29)
The equality parameter in `cesql` should be `=` instead of `==` to work. [INFO](https://github.com/knative/eventing/discussions/6717#discussioncomment-4859920)
- change the code part with those fix
=> Update NOT and CESQL which are not working 

blog/config/nav.yml, docs/reference/relnotes/README.md
Clicking the "References" link in the top menu bar while within the "Blog" section of the site, produced a 404 error. This corrects the navigation link from that section and also adds Knative Functions to the releases page.
=> fix: correct bad link to reference page

docs/serving/services/private-services.md, docs/serving/using-a-custom-domain.md
Fixes #5509 
Updates the docs on creating private services with the detail that services are private by default.
/cc @dprotaso @ReToCode @nak3 
/cherrypick release-1.8
/cherrypick release-1.9
=> Knative services are private by default

docs/install/operator/knative-with-operators.md, docs/install/yaml-install/serving/install-serving-with-yaml.md, docs/snippets/dns.md, docs/snippets/no-dns.md
'Temporary DNS' is confusing since we are not actually setting up DNS in this instance
=> Relabel tab to 'No DNS'

config/nav.yml, docs/install/troubleshooting.md
- Add a page with common troubleshooting help
/cherrypick release-1.10
/cc @dprotaso, @psschwei, @skonto , @nak3 this should help us with the common issues we get asked in GH-issues and slack. The idea is that we can link to that page. In the future we can add common problems and their solutions as well. WDYT? Feedback from English native speaker also highly welcome :)
=> Add installation troubleshooting page

.github/workflows/knative-docs-image.yaml, docs/serving/autoscaling/autoscale-go/Dockerfile, docs/serving/autoscaling/autoscale-go/go.mod
This created an `autoscale-go` image to replace the one hosted on `gcr.io/knative-samples` (which was removed)
=> create autoscale-go image

blog/docs/articles/knative-serving-in-k0s.md, blog/docs/articles/quickstart-with-knative.md, blog/docs/articles/set-up-a-local-knative-environment-with-kind.md, docs/getting-started/first-service.md, docs/getting-started/first-traffic-split.md, docs/serving/app-security/security-guard-quickstart.md, docs/serving/autoscaling/autoscale-go/README.md, docs/serving/autoscaling/autoscaler-types.md, docs/serving/autoscaling/concurrency.md, docs/serving/autoscaling/kpa-specific.md, docs/serving/autoscaling/rps-target.md, docs/serving/autoscaling/scale-bounds.md, docs/serving/autoscaling/scale-to-zero.md, docs/serving/configuration/config-defaults.md, docs/serving/configuration/feature-flags.md, docs/serving/deploying-from-private-registry.md, docs/serving/services/creating-services.md, docs/serving/services/using-queue-extensions.md
We created new images since `gcr.io/knative-samples` no longer exists
helloworld-go - https://github.com/knative/docs/pull/5550
autoscale-go  https://github.com/knative/docs/pull/5554
=> point to the new ghcr.io images

docs/snippets/security-prereqs-binaries.md, docs/snippets/security-prereqs-images.md
Fixes: #5567, #5494
- update snippet for `cosign verify` with images
- update snippet for `cosign verify` with blobs
=> Update Knative cosign verify docs

docs/snippets/about-functions.md
Where used in the Functions text, "stateless" and "event-driven" link to techtarget.com and wikipedia respectively.
Fixes: https://github.com/knative/docs/issues/5403
=> docs: add links to stateless and event-driven

docs/serving/autoscaling/autoscale-go/service.yaml
- Fix image url of autoscale-go service
Fixes https://github.com/knative/serving/issues/14000
/cherry-pick release-1.10
=> Fix image url of autoscale-go service

docs/serving/autoscaling/autoscaling-metrics.md
Fixes #5566  
Have modified the autoscaling-metrics.md based on the changes mentioned in the issue
- Modified `"custom"` metrics are only supported to custom metrics are supported
- Removed `per-revision` prefix and `configuration` suffix in all tabs
=> Update autoscaling-metrics.md for modifications

overrides/main.html
Removes the TOC election banner from the website now that the election is over.
=> chore: remove TOC election banner

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- The operators do support `workload` field and we should not use `deployments` anymore. Workloads is a better name since we do support also statefulsets.
-
=> Using workloads instead of deployments on the documentation

blog/config/nav.yml, blog/docs/articles/improved-ha-configuration.md
- new blog post on `workloads` override, with the focus for HA config
=> Adding a little blog, explaining the workloads override for HA replicas

code-samples/eventing/gitlab-source/README.md
Add fix for eventing gitlab source readme
- Use project access token instead of personal access token for gitlab source (which is more secure from security perspective)
-  Use right breadcrumb for gitlab webhook (Settings >> Webhooks)
=> docs: fix eventing gitlab source readme

docs/serving/autoscaling/scale-bounds.md
The changes in this PR only reflect the existing behaviour of scale down operation by autoscaler when activation scale is set until the behaviour is changed in future.
Related Issue: https://github.com/knative/serving/issues/14017
=> Document current behaviour of scaling down with activation scale

docs/serving/services/configure-requests-limits-services.md
- Adds docs for https://github.com/knative/serving/pull/14038
- Adds content for the resource-percentage annotation, previously undocumented.
=> Describe how to set qp resources

config/nav.yml, docs/serving/services/storage.md
- Adds a section for storage integration with Knative Services. Could be expanded with more examples in the feature.
=> Add details for storage and knative services

docs/reference/security/README.md
the client binary is code-sign verified with cosign in keyless mode and cosign has changed the way it's keyless code signing works since the docs were made here
- updates the docs for code-sign verification for client binary
=> docs: update instructions on client code-sign verification

docs/eventing/experimental-features/eventtype-auto-creation.md
This adds mention of eventtype auto create supporting the channel as well as the broker.
- Mention the channel when discussing event type autocreate working with brokers
- Make the Broker section subsections of the example, so that it is clear that this is only an example, and you don't need to use a Broker
-
=> Added mention of channels to event type autocreate docs

docs/client/configure-kn.md
- Add 'channel-type-mappings' customisation option to Customizing kn docs.
This feature already existed and was documented as part of the [github docs for kn-client](https://github.com/knative/client/tree/11bc9779a7e3c9782132c2cd8be035a64b86febb/docs#eventing-configuration), but was missing from the official website. Please take a look at [this](https://github.com/knative/client/issues/1410#issuecomment-1498937341) comment.
- Also, replaced the config yaml with a better-commented version of the same, which already existed as part of the [github docs for kn-client](https://github.com/knative/client/tree/11bc9779a7e3c9782132c2cd8be035a64b86febb/docs#eventing-configuration).
=> update configure-kn.md to include channel-type-mappings and add comments to sample yaml

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-11-release.md
Changes 
- Add Knative v1.11.0 release blog
PTAL and please double check your names for spelling & copy paste error. Thanks!
/cc @knative/technical-oversight-committee 
/cc @knative/knative-release-leads
=> Add Knative v1.11.0 release blog

blog/config/nav.yml, blog/docs/articles/knative-eventing-vision.md
- adding a Knative Eventing Vision blog, showing what's coming in the next month(s)
=> Adding blog on Knative Vision

docs/snippets/proc-building-function.md, docs/snippets/proc-running-function.md
- Adding some context for the `FUNC_REGISTRY` env variable and highlighting the fact that the prompt asks for an image registry
=> Updates to func build/run documentation

docs/eventing/experimental-features/eventtype-auto-creation.md
"Fixes #5669 " or "Add description of the problem this PR solves"
-
-
-
=> correct Event Type AutoCreate flag name

docs/snippets/install-kn.md, docs/snippets/quickstart-install.md
This PR is a minor documentation enhancement for the Knative `Install Knative using quickstart` document. It ensures that wording for the installation steps between methods are consistent.
Update the PATH in step three of the `Install the Knative CLI` `Using a binary` section to be `PATH` to match the other `PATH` mentions in the installation steps.
Add a step explaining how to move the `kn` binary to your `PATH`. The `Using a binary` method of this installation follows this pattern so I felt like the `Using Go` method should match.
Add "by running the command" to the end of step three of the `Install the Knative quickstart plugin` `Using Go` section so that it matched structure of the other executable move instructions in the document.
=> update kn + quickstart installs for consistency

docs/getting-started/first-service.md
When going to the Quickstart `Deploying a Knative Service` section I noticed that the revision name in the expected output when deploying a service using the CLI has changed from `hello-world` to `hello-0001`.
Change
```{ .bash .no-copy }
Service hello created to latest revision 'hello-world' is available at URL:
http://hello.default.${LOADBALANCER_IP}.sslip.io
```
To
```{ .bash .no-copy }
Service hello created to latest revision 'hello-0001' is available at URL:
http://hello.default.${LOADBALANCER_IP}.sslip.io
```
=> update expected revision name for quickstart service

config/nav.yml, config/redirects.yml, docs/install/installing-cert-manager.md, docs/install/yaml-install/serving/install-serving-with-yaml.md, docs/serving/README.md, docs/serving/encryption/enabling-automatic-tls-certificate-provisioning.md, docs/serving/encryption/using-certificates-in-networking-layer.md, docs/serving/services/certificate-class.md, docs/serving/services/custom-tls-certificate-domain-mapping.md, docs/serving/services/http-protocol.md, docs/serving/services/service-metrics.md
Partially https://github.com/knative/serving/issues/14368
- Rename `auto-tls` to `external-domain-tls`
- Reword the existing pages to prepare for the future flags we introduce
- Make it more clear that the current feature is only for external domains
- Point to our existing work to bring HTTPS to cluster-local domains as well
- Remove duplications about installing cert-manager
- Reorder the navigation to have a new section for encryption. We'll add an overview page to that section to explain the three different parts of Serving Encryption in the future
- Rename pages to better reflect what they are trying to explain
Review links for changed pages:
- https://deploy-preview-5692--knative.netlify.app/docs/install/installing-cert-manager/
- …
=> Rename and reword `auto-tls` feature to `external-domain-tls`

docs/getting-started/first-source.md
When doing the `Creating your first source` section of the `Using a Knative Service as a source` tutorial I noticed that the service revision created was consistently labeled with `00001` rather than being randomly generated as the doc would imply. 
I updated the expected output to have a revision of `00001` rather than `vwybw-1`. I also removed the `Why is my Revision name something different!` notice since the generated revision is no longer variable.
=> Source cloudevents revision

docs/snippets/no-dns.md
This PR is a documentation enhancement. It adds the missing reference to the sample application.
The `helloworld-go application` here is a backward reference, as a newcomer, I have no idea where it is.
So I added a `tip` section, linking to the first service page - https://knative.dev/docs/getting-started/first-service/
=> Explain what `sample application` is, in `no-dns.md`

code-samples/community/serving/helloworld-rust/Cargo.lock, code-samples/community/serving/helloworld-rust/Cargo.toml, code-samples/community/serving/helloworld-rust/Dockerfile, code-samples/community/serving/helloworld-rust/README.md
This PR updates the dependencies and fixes the following error when trying to build the sample code:
```bash
package `socket2 v0.5.5` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.62.1
```
In addition, it updates the steps to recreate the sample code as it is outdated and following it, leads to the following errors:
```bash
error: edition 2021 is unstable and only available with -Z unstable-options.
error: could not compile `proc-macro2
```
- Bump the versions of all dependencies to the latest ones
- Bump Rust to version 1.73.0
- Update the README.md with up-to-date steps to reproduce sample code
=> Helloworld rust/bump dependencies

blog/mkdocs.yml, mkdocs.yml, requirements.txt
As per title, this patch fixes the deprecation warning.
As following docs mentions, this patch just changes:
* `python/name:materialx.emoji.twemoji` to `material.extensions.emoji.twemoji`.
* `python/name:materialx.emoji.to_svg` to `python/name:material.extensions.emoji.to_svg`.
https://pypi.org/project/mkdocs-material-extensions/
> NOTE: This project is now deprecated as MkDocs for Material now implements this logic directly. Users should migrate to using mkdocs-material's material.extensions.emoji.twemoji and material.extensions.emoji.to_svg in place of the respective materialx.emoji.twemoji and materialx.emoji.to_svg functions provided by this library.
=> Fix deprecation warning in Knative Verify

blog/mkdocs.yml, mkdocs.yml, requirements.txt
This reverts commit 7aed08da133242c26e036b486afd6fe6497475e4.
https://github.com/knative/docs/pull/5727 fixes the warning but brakes the format.
/cc @pmbanugo
=> Revert "Fix deprecation warning (#5727)"

blog/config/nav.yml
Update nav.yml for navigating blog post about kubecon na 23
-
-
-
=> Update nav.yml for navigating blog post about kubecon na 23

docs/eventing/sources/ping-source/README.md
PingSource docs updated to align with the code changes made in this PR: https://github.com/knative/eventing/pull/7394
- Documents how a PingSource's schedule now supports both the standard and Quartz Scheduler formats.
=> PingSource schedule seconds support documented

hack/build.sh
=> Bump to new release version

blog/config/nav.yml, blog/mkdocs.yml, config/nav.yml, docs/index.md, docs/stylesheets/extra.css, mkdocs.yml, requirements.txt
- As per title, this patch fixes the deprecation warning (including https://github.com/knative/docs/pull/5727)
- Re-order nav-items on the right, as this is now a `flexbox` instead of `display: block`
- Updates CSS and markdown settings to fix wrongly displayed home page, see https://github.com/knative/docs/pull/5727#issuecomment-1774835540
Fixes #5723
=> Fix deprecation warnings and update CSS

docs/serving/services/storage.md
Fixes https://github.com/knative/docs/issues/5083
- Continues the work in https://github.com/knative/docs/pull/5507
=> Finalize pvc support

config/nav.yml, docs/functions/subscribing-functions.md, docs/snippets/proc-subscribe-function.md
- Initial documentation for `func subscribe`
=> Adding initial doc for func subscribe

code-samples/eventing/helloworld/helloworld-go/README.md
The code sample in the README.md can not compile and work well and I spent some time to find the reason. I fix the code sample with the content in the helloworld.go and eventschemas.go  and it can compile and work well now.
- change the code sample in the README.md with the content in helloworld.go and eventschemas.go
=> Fix wrong code sample in helloworld-go README.md

blog/docs/releases/announcing-knative-v1-12-release.md, docs/install/uninstall.md, docs/install/yaml-install/serving/install-serving-with-yaml.md
Part of https://github.com/knative/serving/issues/14640
=> drop net-http01 from v1.13 release 

docs/serving/configuration/deployment.md
=> Documentation - progress deadline annotation on per revision basis

docs/install/yaml-install/eventing/eventing-installation-files.md, docs/install/yaml-install/serving/serving-installation-files.md
Use [artifact](https://github.com/knative/docs/blob/b7eadf9c492ee323505b714c54116e8c1e32c096/hack/macros.py#L104) macro to generate the link to the appropriate yaml files for the serving and eventing installation pages.
Fixes #4998
=> fix links to files on installation files page (#4998)

docs/install/upgrade/upgrade-installation.md
- Use `kubectl create` instead of `kubectl apply` because of https://github.com/kubernetes/kubernetes/issues/44501
- Follow-up for https://github.com/knative/docs/issues/5759#issuecomment-1838550871
/assign @skonto 
/cherry-pick release-1.12
=> Use create instead of apply

mkdocs.yml
Context: https://cloud-native.slack.com/archives/C04LY5G9ED7/p1704358780773299
- Enables copy buttons on code (shell) blocks
/assign @skonto
=> Enable copy for code blocks

docs/snippets/collecting-metrics.md
- Improve configuration steps for Grafana dashboards based on knative-extensions/monitoring#25
=> improve grafana configuration steps

docs/eventing/configuration/broker-configuration.md
Fixes #5810 
- Solved the bug.
=> Resolved the bug in the default styling of note

config/nav.yml, docs/serving/services/http-protocol.md
- Documents https://github.com/knative/serving/issues/12387. Some similar docs from another project [here](https://caddyserver.com/docs/json/apps/http/servers/enable_full_duplex/).
- Adds proper warning for cases where clients may not support the feature.
=> Document the use of HTTP/1 full duplex support

blog/docs/articles/new_event_discovery_features.md
=> Event types discovery - fix link to eventtype-auto-creation doc

docs/install/uninstall.md
Fixes #5835
- Use `artifact` function to retrieve release links on [Uninstalling Knative](https://knative.dev/docs/install/uninstall/) page, for the following files:
- _serving-core.yaml_
- _serving-crds.yaml_
- _eventing-core.yaml_
- _eventing-crds.yaml_
=> Use links to artifact on uninstall page

netlify.toml, overrides/partials/footer.html
- Add Linux Foundation trademark link
- Fix cookie-banner link (no need to route it to pre-release any more)
Fixes #5829
/assign @knative/steering-committee 
/assign @knative/technical-oversight-committee
=> Add linux foundation trademark

docs/eventing/brokers/broker-types/kafka-broker/README.md
This documents how to set Kafka topic config options on a broker.
- Add a paragraph explaining that we support all kafka topic config options, and how to set them
Note: this should not merge until after https://github.com/knative-extensions/eventing-kafka-broker/pull/3671
=> Document how to set Kafka Topic config options

docs/install/installing-istio.md, docs/install/operator/configuring-serving-cr.md, docs/install/operator/knative-with-operators.md, docs/serving/setting-up-custom-ingress-gateway.md
Following https://github.com/knative-extensions/net-istio/issues/1247
- Update net-istio configuration to reflect preferred format
=> Update net-istio configuration format

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/rabbitmq-broker/README.md, docs/eventing/sources/rabbitmq-source/README.md, docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Part of https://github.com/knative/eventing/issues/7670
/assign @gabo1208
=> [release-1.13] add deprecation notices for rabbitmq integration

docs/serving/configuration/config-defaults.md
This PR is related to https://github.com/knative/serving/pull/14969 .
Because TerminationGrace`Period`Seconds is more appropriate than terminationGrace`Time`Seconds.
The document probably explain about fallowing value.
https://github.com/knative/serving/blob/6dc7097b740f6b0e6ae744abad5e84338a1b8066/config/core/deployments/activator.yaml#L124
I believe this PR makes this document more understandable.
Thank you.
- Modified terminationGraceTimeSeconds in the document of Max revision timeout seconds to terminationGracePeriodSeconds.
=> Modify the description about Max revision timeout seconds

code-samples/eventing/bookstore-sample-app/db/README.md, code-samples/eventing/bookstore-sample-app/db/sample.sql
Fixes #5881 
* Added the SQL file for creating a table for BookReviews according to the schema described [here](https://docs.google.com/document/d/1dYvNdHFf4qoiIbWWOWMLAXDAFpEjjRsa9lP27tpqPTI/edit)
* Added dummy data into BookReviews table
* Wrote documentation for implemented schema and added dummy rows
=> Sample Bookstore App: DB setup for Book Review Comments

config/nav.yml, config/redirects.yml, docs/about/case-studies/README.md, hack/docker/run.sh, overrides/home.html
- The "Case Studies" text in the homepage at knative.dev is currently not clickable. You need to click one of the company logos to see the full list.
- Made the "Case Studies" text in the homepage at knative.dev clickable. It points to a new page that lists all case studies in a table
- Preview: 
- Check out the "Case Studies" header at https://deploy-preview-5869--knative.netlify.app/docs/
- Check out the new page: https://deploy-preview-5869--knative.netlify.app/docs/about/case-studies/
=> Case studies index page and link from homepage

blog/docs/articles/demystifying-activator-on-path.md
- Adjusting based on suggestions from @psschwei here: https://github.com/knative/docs/pull/5709#pullrequestreview-1948329204
=> Polish the article "Demysifying the activator on data path"

docs/serving/encryption/enabling-automatic-tls-certificate-provisioning.md
This PR proposes changes the docs on automatic TLS certificate provisioning. In the examples given under "Provisioning certificates per namespace (wildcard certificates)" objects are provided as values for `namespace-wildcard-cert-selector`, I think only strings can be values for ConfigMap data values. In the next section (Configure config-certmanager ConfigMap) a string is provided. 
- ConfigMap's data values can only be of type String
=> Docs: Change namespace-wildcard-cert-selector value type from object to string

code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/.funcignore, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/.gitignore, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/Procfile, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/app.sh, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.py, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.yaml, code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/requirements.txt
Fixes #5917
- Related #5917
- Implement inappropriate language filter Python script
- Currently, there is only a working Python script, but README.md has not been written yet.
=> Implement inappropriate language filter Python script

docs/eventing/experimental-features/sender-identity.md
Explain limitations for having `authentication-oidc` enabled and eventing-istio.
=> Add limitations for having OIDC and Istio enabled

code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/.funcignore, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/.gitignore, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/Procfile, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/README.md, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/app.sh, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/func.py, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/func.yaml, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/requirements.txt, code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/setup.py
Fixes #5889
- The code for the sentiment analysis service, which fits in knative function's python template
=> Sample App: Adding the knative function build for the sentiment analysis service

code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.py
- Fixed the input and output cloudevent format
=> Sample App: Fix the content in the bad word filter knative function code

docs/eventing/sources/kafka-source/README.md
- Adding Kafka Source details on delivery spec
=> Adding Kafka Source details on delivery spec

docs/serving/encryption/configure-certmanager-integration.md
Addressing https://github.com/knative/docs/pull/5804#discussion_r1584701059
=> Improve Serving encryption docs

config/nav.yml, docs/eventing/experimental-features/new-apiserversource-filters.md
This MR adds a page for the experimental feature that add `filters` to the APIServerSource kind.
Related to [#7799](https://github.com/knative/eventing/pull/7799) and [#7791](https://github.com/knative/eventing/issues/7791)
- Add a page for the experimental feature that adds `filters` to `APIServerSource`
=> Add SubscriptionsAPI filters to APIServerSource

OWNERS
Currently, there are many PRs which are being opened to the docs repo regarding design changes (which I should review). But, since the UX leads group are only approvers and not reviewers on this repository, I don't have my review requested.
This PR adds the UX leads as docs reviewers (on top of the already existing approver permissions) so that we can get our reviews requested
=> Add UX leads as docs reviewers

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css
- Fixes #5765 
- Changed the root website dark and light blue to the following hex codes:
-- Light Blue: 6593C8
-- Dark blue: 0D4984
=> fix: Website colour adjustments

blog/config/nav.yml, blog/docs/articles/enhancing-the-knative-experience.md, blog/docs/index.md
- Reflecting on My LFX Mentorship Project. ([Final Report](https://github.com/knative/ux/tree/main/user-research/contributor-research))
=> Added a Blog Post Detailing My LFX Mentorship Project

config/nav.yml, docs/eventing/brokers/broker-developer-config-options.md, docs/eventing/sinks/README.md, docs/eventing/sinks/job-sink.md
Fixes https://github.com/knative/eventing/issues/7732
- Add JobSink documentation
- Usage
- Examples
=> Add JobSink documentation

overrides/assets/stylesheets/home.css, overrides/home.html, overrides/partials/footer.html
Fixes #5972 
- Added Linkedln page link in Follow us section.
=> added Linkedln page link

blog/config/nav.yml, blog/docs/articles/consuming_s3_data_with_knative.md
=> Adding a new post on S3 events to Knative Functions

blog/docs/articles/consuming_s3_data_with_knative.md
=> Little fix on typo

docs/serving/encryption/external-domain-tls.md
- Remove old warning about istio and external-domain-tls
- Ref: https://cloud-native.slack.com/archives/C04LMU0AX60/p1718290650661339
=> Remove old warning about istio and external-domain-tls

docs/community/contributing.md
It was mentioned on the TOC call today that some folks were finding it difficult to find the different contributor roles, so this PR adds an explicit link to them from the "contributor" page.
=> Add link to community roles to contributor page

blog/mkdocs.yml
It should be defaulting to `False` anyway. Otherwise we have "expected string got bool error".
https://guts.github.io/mkdocs-rss-plugin/configuration/#categories_example
=> Remove as_updated field in rss plugin

blog/mkdocs.yml, docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css
Fixes #6028 
- swapped the main 2 primary light and primary dark colours
- changed the nav-item-color to #494848
- added consistent corner rounding and spacing between buttons.
=> Swap website colours of the Home page

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css, overrides/home.html, overrides/partials/footer.html
resolves #6035 
changes made :
1. replaced the footer background colour.
2. Move footer icons to the right.
3. Remove the pre-footer section of the previous design.
4. added space at the top of the cncf logo container.
proposed design :
Implementaion:
=> new design implementation for footer and removed the pre-footer section

code-samples/eventing/bookstore-sample-app/README.md, code-samples/eventing/bookstore-sample-app/solution/README.md, code-samples/eventing/bookstore-sample-app/start/README.md, docs/samples/README.md
- Add the readme files for the sample app code
- Update the [code-sample page](https://knative.dev/development/samples/) to include sample app code in it
Note: the link to the sample app tutorial pages will show as "Page note found" for now, it will be functional until Knative release 1.15 is out.
=> Add the readme for sample app codes, and update the code-sample page

docs/stylesheets/extra.css
Fixes #6064  
This PR updates the border radius of the "Get started" buttons on the Tutorial page to match the border radius used on the home page.
- Applied `border-radius: 0.7rem;` to the "Get started" buttons on the Tutorial page.
- The home page uses `border-radius: 0.7rem;` for its buttons, and this change ensures consistency in the button styles across the website.
=> Update the button border radius on Tutorial page #6064

config/nav.yml, docs/eventing/brokers/broker-types/kafka-broker/README.md, docs/eventing/brokers/broker-types/kafka-broker/configuring-kafka-features.md, docs/eventing/configuration/kafka-channel-configuration.md, docs/eventing/configuration/keda-configuration.md, docs/eventing/sources/kafka-source/README.md
We now have KEDA scaling of all Knative Kafka dispatcher components. This PR adds:
- docs mentioning that this exists
- docs explaining how to use this
=> feat: added documentation for keda scaling of Kafka dispatcher components

blog/config/nav.yml, blog/docs/articles/llm-agents-demo.md
This blog continues on our explanation of LLM Agents with knative, giving a concrete example of how to call new tools from an LLM without redeploying it.
=> feat: add blog post with demo of LLM Agents on Knative

docs/serving/services/configure-probing.md
- Improves the hint about progress deadline seconds in startup probe docs
=> Improve startup probe hint about progress deadline

code-samples/serving/websockets-go/README.md, code-samples/serving/websockets-go/config/service.yaml
Little updates to get the demo better aligned
=> Minor tweaks for WebSockets sample

blog/config/nav.yml, blog/docs/articles/Knative-Serving-WebSockets.md
As per title. Following up on https://github.com/knative/docs/pull/6109
=> Adding Websocket blog post

overrides/partials/footer.html
Currently, in the footer of our website's documentation section, the 'Next' and 'Previous' links are shown in front of the page's title, and they have different font sizes. I'm sure this wasn't done on purpose. The problem is because the title and the navigation links are in the same class, which messes up the styles.
To fix this, I moved the footer text outside of that class. This way, the existing styles won't get overridden by the class styles.
=> Fix footer styling issue

overrides/assets/stylesheets/home.css, overrides/home.html
I have made top three sections of home page responsive.
=> made top three sections of home page responsive

docs/serving/configuration/feature-flags.md
=> Document host* and shareProcessNamespace flags

blog/docs/articles/consuming_sqs_data_with_integrationsource.md
- correction after API changes
=> Update SQS Source blog

config/nav.yml, docs/eventing/sources/integration-source/README.md, docs/eventing/sources/integration-source/aws_ddbstreams.md, docs/eventing/sources/integration-source/aws_s3.md, docs/eventing/sources/integration-source/aws_sqs.md, docs/eventing/sources/integration-source/timer.md
Work in progress, do not yet merge.
/hold
(for now)
=> Adding first draft of IntegrationSource doc

config/nav.yml, docs/eventing/sinks/README.md, docs/eventing/sinks/integration-sink/README.md, docs/eventing/sinks/integration-sink/aws_s3.md, docs/eventing/sinks/integration-sink/aws_sqs.md, docs/eventing/sinks/integration-sink/logger.md
- first attempt for docs on integration sink CRD
=> Adding initial doc for IntegrationSink

docs/eventing/sinks/README.md
- Adding new integration sink options to sink index
=> Update Sink Index page

blog/config/nav.yml, blog/docs/articles/configurable-runtimeclassnames.md
adds a blog post for configuring Knative Serving to use RuntimeClasses
- talk about Knative Serving config-deployment setting for RuntimeClassName
=> blog: add runtimeclassnames post

docs/eventing/sinks/integration-sink/aws_s3.md, docs/eventing/sinks/integration-sink/aws_sns.md, docs/eventing/sinks/integration-sink/aws_sqs.md, docs/eventing/sources/integration-source/aws_ddbstreams.md, docs/eventing/sources/integration-source/aws_s3.md, docs/eventing/sources/integration-source/aws_sqs.md
- fixing SNS header for sink
- fixing `bash` rendering
=> Fixing minor doc issues

code-samples/community/serving/machinelearning-python-bentoml/README.md, code-samples/community/serving/machinelearning-python-bentoml/iris_classifier.py, code-samples/community/serving/machinelearning-python-bentoml/main.py
Fix machinelearning-python-bentoml to work in latest Python and bentoml.
=> fix ML example

docs/install/operator/knative-with-operators.md
Adds docs to go along with new helm chart repository
https://github.com/knative/operator/pull/1931
=> chore: add instructions for installing with Helm

config/nav.yml, docs/reference/security/verifying-images.md
Adds documentation on how to consume Knative supply chain attestations.  Captures discussion from [this comment](https://github.com/knative/docs/pull/5775#discussion_r1414296163), where they are unlikely otherwise to be found.
- Adds initial security documentation, focused on supply chain security.  Future security configuration documents should probably be added to the same location.
=> Add documentation on fetching Knative supply-chain security attestations

code-samples/eventing/kafka/binding/event-source.yaml, docs/eventing/event-registry/README.md, docs/eventing/sinks/job-sink.md, docs/eventing/sources/kafka-source/README.md, docs/eventing/sources/kafka-source/event-source.yaml
Fixes https://github.com/knative-extensions/eventing-kafka-broker/issues/3953
=> Document KafkaSource v1 API

code-samples/eventing/bookstore-sample-app/solution/db-service/200-create-postgre.yaml, code-samples/eventing/bookstore-sample-app/start/db-service/200-create-postgre.yaml
To fix this error:
`error: error validating "db-service/200-create-postgre.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false`
=> sample-app: Add serviceName to postgresql manifest

code-samples/eventing/bookstore-sample-app/start/setup.sh
- **fix broken link**
- **allow script to be run from any directory**
/assign @Leo6Leo
=> fix broken links + allow script to be run in any directory

code-samples/eventing/bookstore-sample-app/README.md, code-samples/eventing/bookstore-sample-app/solution/README.md, code-samples/eventing/bookstore-sample-app/solution/slack-sink/README.md, code-samples/eventing/bookstore-sample-app/start/README.md, code-samples/eventing/bookstore-sample-app/start/db-service/README.md, code-samples/eventing/bookstore-sample-app/start/slack-sink/README.md
fixes #6224 
Some of the links in Bookstore Sample App (https://github.com/knative/docs/tree/main/code-samples/eventing/bookstore-sample-app) were broken. Checked and fixed all the broken links. All the links now redirect user to the correct destination.
=> Updated the links in Bookstore Sample App

config/nav.yml, docs/eventing/transforms/README.md, docs/eventing/transforms/event-transform-jsonata.md
Fixes https://github.com/knative/eventing/issues/7704
Fixes https://github.com/knative/eventing/issues/8001
Fixes https://github.com/knative/eventing/issues/8274
- Add EventTransform documentation
- Add Event Transform for JSON with JSONata documentation
=> Add EventTransform documentation

docs/install/operator/knative-with-operators.md
- To make the equivalent between the manifests and helm installation. 
- Otherwise, following the steps on "_Verify your Knative Operator installation_" will fail.
=> Helm: create and use 'knative-operator' namespace

docs/community/governance.md
Fixes a few outdated items noticed during graduation governance review.
- Remove mentions of the TOC now that it has been merged with the steering committee.
- Remove a duplicate mention of the Knative audiences, which is also at the top of https://knative.dev/docs/community/
=> Update web community info to remove TOC and duplication of audience info

docs/eventing/triggers/README.md
I tried to create a  Trigger object by following the guideline at https://knative.dev/docs/eventing/triggers/#trigger-filtering .
```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
name: my-service-trigger
spec:
broker: default
filters:
exact:
type: dev.knative.foo.bar
suffix:
myextension: -value
subscriber:
ref:
apiVersion: serving.knative.dev/v1
kind: Service
name: my-service
```
However, I got the error due to a wrong syntax since `spec.filters` expects an array of filters.
```
strict decoding error: unknown field "spec.filters.exact", unknown field "spec.filters.suffix"
```
- Fix a wrong attribute in Trigger filtering's example manifest file
=> Fix: wrong filters attribute in trigger document

docs/snippets/proc-running-function.md
iRaindrop = Bruce Hamilton bhamilton@expertsupport.com
The top two content tab sections in the quickstart, https://knative.dev/docs/getting-started/build-run-deploy-func/, needed attention. In the first, a note interrupted the tab functionality and in the second I added the "kn func invoke" example and moved the existing REST response the "func invoke" tab.
Formatting fixes applied for content tabs with correct output examples for func invoke and kn func invoke.
-
-
-
=> Knative quickstart - content tab fixes, added success output for kn func

mkdocs.yml
Fixes at least the 404 page, which currently has asset links to `/docs/assets/...`.  Oddly, many of the other pages somehow continue to work (caches?)
- Fix the site base URL.
=> Fix site base URL, which should fix some asset links

docs/eventing/features/authorization.md
In the [Eventing / Features / Authorization / Example](https://knative.dev/docs/eventing/features/authorization/#example) docs is a "bug" in this sentence:
> When we remove now the EventPolicy again and keep OIDC _disabled_ , the Broker will fall back to the default authorization mode, which is `allow-same-namespace`:
The `allow-same-namespace` is only used when OIDC is kept **enabled** and no `EventPolicy` is active =>  _disabled_ should be **enabled**.
- :pencil2: Swap _disabled_ for **enabled**.
=> fix: change OIDC disabled to enabled

docs/.nav.yml, docs/client/install-kn.md, docs/install/README.md, docs/install/operator/knative-with-operator-cli.md, docs/install/operator/knative-with-operators.md, docs/install/quickstart-install.md, docs/install/yaml-install/eventing/install-eventing-with-yaml.md, docs/install/yaml-install/serving/install-serving-with-yaml.md, docs/snippets/install-kn.md
Improve installation guidance
iRaindrop = Bruce Hamilton bhamilton@expertsupport.com
Provide roadmap guidance for installing Knative, make improvements and consistencies.
- Roadmap for installations
- Improvements for accessing binaries (later push)
=> Installation Doc Updates

docs/snippets/proc-running-function.md
Fixes error made in PR 6367.
- The success output for `kn func invoke` should be the same for `func invoke`. This PR is just this fix and has no other changes.
=> Undo different example output for kn func invoke

docs/versioned/install/operator/configuring-serving-cr.md
Follow on to #6368 to include AWS docs.
- Add link to AWS Docs for pod identity
=> Added link to AWS Pod identity docs

docs/versioned/bookstore/page-7/slack-sink-learning-knative-eventing-and-apache-camel-K-integration.md
Overhauled the Camel K operator installation and configuration. Fixed issues with the overall setup, a few typos and wrong directory paths.
The Pipe CR had a typo in the Broker name "bad-word-broker". Now it is correctly "badword-broker". That was the reason for the "bad" comments not reaching the Slack sink.
Issue #6423.
/cherry-pick release-1.19
Update [7 - Connect Slack via Camel-K](https://knative.dev/docs/bookstore/page-7/slack-sink-learning-knative-eventing-and-apache-camel-k-integration/).
- Remove Camel-k CLI installation.
- Add installation via Kustomize and update link to installation docs.
- Fix secret path.
- Fix `bookstore-broker` name.
- Fix slack-sink manifests path.
- Fix typo in Pipe broker name.
- Change pipe name to align with manifest.
- Add `kubectl patch ...` command …
=> Fix section "7-Connect Slack via Camel-K" in e2e tutorial.
