knative/docs

docs/serving/using-a-tls-cert.md
=> add missing secret command for contour tls setup

docs/install/any-kubernetes-cluster.md
I noticed this running `./scripts/localbuild.sh` from website.
/assign @evankanderson @abrennan89 @RichieEscarez @vaikas
=> Fix website build

docs/serving/accessing-traces.md, docs/serving/autoscaling/rps-target.md
Fixes #2987 and  #2947 
- RE #2988 fix dead link in config-trace (#2988)
- RE #2948 Add annotation "autoscaling.knative.dev/metric: rps"
=> RE #2988 And  RE #2948 

docs/serving/autoscaling/rps-target.md
Fixes #2947 
RE #2948 Add annotation "autoscaling.knative.dev/metric: rps"
=> RE #2948 Add annotation "autoscaling.knative.dev/metric: rps"

OWNERS_ALIASES
Give @csantanapr docs eng approver
=> Add csantanapr as eng approver

blog/steering/2020-11-ksc-elections.md
Since blog posts go out thru RSS, I wanted to help publicize more the Knative Steering Committee elections.
And with the deadline for nominations and not that many candidates currently I think this might help.
Anyone see a problem publishing this today?
=> Blog ksc nominations

docs/install/installing-istio.md
This is a cherry-pick for https://github.com/knative/docs/commit/bd6307f3c3440e69a836c52effc6be9c653d991f against release-0.18 branch.
/cc @ZhiminXiang @JRBANCEL @guillaumeblaquiere
=> [release-0.18] Fix default installation without sidecar injection (#2775)

docs/serving/samples/hello-world/helloworld-scala/Dockerfile, docs/serving/samples/hello-world/helloworld-scala/README.md, docs/serving/samples/hello-world/helloworld-scala/build.sbt, docs/serving/samples/hello-world/helloworld-scala/helloworld-scala.yaml, docs/serving/samples/hello-world/helloworld-scala/project/build.properties, docs/serving/samples/hello-world/helloworld-scala/project/plugins.sbt
Fixes #2927
There's a few more things askew with the Scala sample but I'd like to line those up in a separate PR to keep concerns separate.
=> Transform Scala example to use a Dockerfile

docs/serving/samples/hello-world/helloworld-scala/Dockerfile, docs/serving/samples/hello-world/helloworld-scala/README.md, docs/serving/samples/hello-world/helloworld-scala/build.sbt, docs/serving/samples/hello-world/helloworld-scala/service.yaml, docs/serving/samples/hello-world/helloworld-scala/src/main/resources/application.conf, docs/serving/samples/hello-world/helloworld-scala/src/main/scala/example/HelloWorldScala.scala
This aligns the Scala sample with our other samples, behavior and layout-wise. Also bumps the Scala version and dependencies to something much more recent.
=> Align Scala sample with the rest of our samples

.wokeignore
=> Ignore false-positive divisive language flagging

community/calendar/_index.md
Closes #3036 
Adds the Community Calendar page.
=> [feat] Add community calendar

docs/serving/samples/hello-world/helloworld-kotlin/Dockerfile, docs/serving/samples/hello-world/helloworld-kotlin/README.md, docs/serving/samples/hello-world/helloworld-kotlin/build.gradle
As per title. I noticed some testfailures and thus decided to give this a shot.
/assign @mattmoor @grayside
=> Simplify Kotlin example and bump versions to be more recent

docs/eventing/sugar/README.md, docs/eventing/sugar/_index.md
- Document the sugar controller for Namespaces
- Document the sugar controller for Triggers
=> Adding docs for the sugar controller

docs/eventing/sink/OWNERS, docs/eventing/sink/_index.md, docs/eventing/sink/kafka-sink.md, docs/install/any-kubernetes-cluster.md
Backport #3031 
- Document Sink concept
- Document Apache Kafka Sink
=> [0.19] Document Apache Kafka Sink (#3031)

docs/serving/samples/hello-world/helloworld-go/index.md
Update file name with go extension to match file in docs repo and to work with the next steps in the file
=> Update docs/serving/samples/helloworld index

docs/install/any-kubernetes-cluster.md
Fixes: https://github.com/knative/docs/issues/3068
/assign @julz @abrennan89
=> Fix a rendering glitch that hides eventing.

docs/serving/samples/hello-world/helloworld-scala/README.md
Signed-off-by: 杨阳 10014842 <yangyang1@zte.com.cn>
- Local building tools are not necessary since the Dockerfile works
- Keep the Service consistent with the service.yaml
- Remove duplicate code
=> Fix scala sample of serving

docs/eventing/samples/writing-event-source/01-theory.md
=> Update 01-theory.md: nit

docs/eventing/samples/kafka/channel/README.md
- adding the doc for the new TLS/SASL auth feature of the `KafkaChannel`
=> Adding configuration description for TLS/SASL for the KafkaChannel

docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Remove duplicate statement in the wrong location
Reword incorrect statement
It makes sense to cherry-pick this to the release branch as well.
=> Update  ..sequence-with-broker-trigger/README.md

docs/serving/feature-flags.md
- adds documentation for https://github.com/knative/serving/pull/10301
=> add docs for hostAliases feature gate

docs/install/operator/configuring-eventing-cr.md
Easy navigation and easy reading for others
=> fix broken url in docs

docs/eventing/event-registry.md
- fixing incorrect format
-
-
/assign @abrennan89
=> Fixing yaml format

docs/eventing/broker/kafka-broker.md
Fixes #3145 Kafka installation should be added in Prerequisites in page "Apache Kafka Broker(docs/eventing/broker/kafka-broker.md)"
=> add kafka installation

docs/install/any-kubernetes-cluster.md
Fixes #2166.
In conjunction with https://github.com/knative-sandbox/net-istio/pull/479.
/assign @mattmoor @nak3
=> Use inline Istio installation.

docs/serving/cluster-local-route.md
Use same terms throughout and same capitalization.
/assign @abrennan89
=> Fix the cluster-local docs to be consistent

docs/install/any-kubernetes-cluster.md
Fixes #3169
Update Kubernetes minimum version from `v0.16` to `v0.17` in the install docs.
=> Update k8s minimum version in (docs/install/any-kubernetes-cluster.md)

CONTRIBUTING.md
This patch clarifies how to cherry-pick the PR as
`cherrypick-#.#` label does not work.
/cc @evankanderson @izabelacg
=> Clarify how to cherry-pick the PR

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md, hack/gen-api-reference-docs.sh, hack/patches/serving.patch
=> Rebase of 3147

docs/install/knative-with-operators.md
Fixes #3186
- using a proper version VAR...
=> Using proper VERSION var for istio example

docs/eventing/samples/ping-source/index.md
Fixes #3085
- use kn rather than `kubectl -f some-file.yaml` as thats a wasted
opportunity and doesn't add any value.
- show examples of kn side by side with the declarative form
=> [#3085] Enhance PingSource example with kn

docs/serving/spec/knative-api-specification-1.0.md
- Add text to allow for other types of routing, aside from percentage based
Related to: https://github.com/knative/serving/pull/5036
ping @dgerd
=> Allow for non-percent routing

community/annual_reports/README.md
- Add 2020 Annual Report to https://knative.dev/community/annual_reports/
=> Add link to 2020 Annual Report

docs/serving/using-auto-tls.md
=> Add Kourier to the list of net layers to support auto-tls

docs/serving/rolling-out-latest-revision.md
/assign @abrennan89 @tcnghia @mattmoor
=> Initial Gradual rollout docs

docs/_index.md, docs/serving/rolling-out-latest-revision.md
Fixes #3196 
- Follow up @evankanderson 's comments from #3197
=> [#3196] Follow up on Evan's comments

docs/eventing/samples/kafka/source/README.md
Signed-off-by: james426759 <james759426@gmail.com>
Fixes https://knative.dev/docs/eventing/samples/kafka/source/
- edit docs for topic [Apache Kafka Source Example](https://knative.dev/docs/eventing/samples/kafka/source/) for Knative v.0.20
=> update knative-v0.20 docs for topic Apache Kafka Source Example

docs/install/installing-istio.md
Signed-off-by: james759426 <james759426@gmail.com>
Fixes #
- update docs for topic Installing Istio for Knative v.0.20
old: Replace the `local-gateway.knative-serving.cluster-local-gateway` field with the custom service. As an example, if you name both
new: Replace the `local-gateway.knative-serving.knative-local-gateway` field with the custom service. As an example, if you name both
=> update docs for topic Installing Istio for Knative

docs/eventing/sources/sinkbinding.md
* use correct apiVersion
* fix schedule so it runs every minute like the comment suggests
* use busybox as default example image, following suit from [Kubernetes CronJob docs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
=> Improve CronJob yaml in SinkBinding example

docs/serving/creating-domain-mappings.md
=> [#3223] Fix dead link

docs/install/upgrade-installation-with-operator.md, docs/install/upgrade-installation.md
- This PR adds the instruction on how to upgrade Knative with the operator.
=> Add the instruction on how to upgrade Knative with the operator

docs/eventing/broker/kafka-broker.md
Part of #3202
- Document SASL and SSL support for Kafka Broker
/cc @abrennan89 @matzew @slinkydeveloper
=> Document SASL and SSL support for Kafka Broker

docs/eventing/sources/pingsource.md
=> fix kn example for pingsource

docs/eventing/sink/kafka-sink.md
Fixes #3202
Similar to https://github.com/knative/docs/pull/3239
- Document SASL and SSL support for KafkaSink
/cc @csantanapr @abrennan89 @matzew @slinkydeveloper
=> Document SASL and SSL support for KafkaSink

docs/install/installing-istio.md
Cherry-pick Istio version update from master
=> Update supported istio versions (#3243)

community/contributing/_index.md
See also https://github.com/knative/client/issues/1071
=> Add link to CLI good-first-issues in contribution guide.

docs/eventing/accessing-traces.md
Traces for pingsource will be added with PR: https://github.com/knative/eventing/pull/4877 
which further fixes: https://github.com/knative/eventing/issues/4757
=> PingSource tracing added

docs/install/upgrade-installation-with-operator.md
- Use a different title for the upgrading instruction with Knative operator.
=> Change the title for upgrading with the operator

docs/install/any-kubernetes-cluster.md
=> add default tabs for install dns and extensions

docs/knative-offerings.md
fixes #3220 
thanks @yangyunfeng007 for submitting this issue :)
=> Fix broken link on knative-offerings.md

docs/install/README.md, docs/install/_index.md, docs/install/any-kubernetes-cluster.md, docs/install/knative-with-operators.md
- removed README
- cleaned up list of deployment options and headings / structure
- Removed fluff, improved readability / findability
- Fixed TOC / nav headings
=> Cleanup install docs

docs/eventing/event-registry.md
=> Fix link and minor improvements to doc

docs/install/assets/serving.md
=> Add description table for install files for Knative Serving

docs/install/assets/eventing.md
=> Add table for eventing assets (#1896)

docs/install/knative-with-operators.md
Add spacing to align command with steps and fix broken numbering.
=> Put command under steps

docs/install/knative-with-operators.md
- cherry-pick 9486782e59a609c28b55e6b44f38cc3277adfffa
=> [release-0.21] Modify the instructions of the ingress configuration

docs/eventing/sink/OWNERS, docs/eventing/sink/_index.md, docs/eventing/sink/kafka-sink.md, docs/install/any-kubernetes-cluster.md
Backport #3031 
- Document Sink concept
- Document Apache Kafka Sink
=> [0.18] Document Apache Kafka Sink (#3031)

docs/eventing/event-registry.md
Fixes #3309 - Remove links to Go code
- Removed the Go code path as mentioned in the fixes.
=> Removed the Go code link

docs/serving/knative-kubernetes-services.md
=> Correct link for Knative Serving documentation

docs/install/_index.md
Fixes #3407
xref: https://github.com/knative/docs/pull/3302
/assign @abrennan89
=> Fix install-kn link from install landing page

docs/client/install-kn.md, docs/install/_index.md, docs/install/install-eventing-with-yaml.md, docs/install/install-extensions.md, docs/install/install-serving-with-yaml.md, docs/install/prerequisites.md
Reverts knative/docs#3422
Accidentally pushed to main...
=> Revert "Fixing the kn cli references"

OWNERS_ALIASES
It turns out when I write a large YAML document by hand, I don't produce valid YAML.
- Make OWNERS_ALIASES valid YAML.
=> Make OWNERS_ALIASES valid yaml

docs/install/knative-with-operators.md, docs/uninstall.md
Adds new Uninstalling topic to address https://github.com/knative/docs/issues/3300
=> [#3300] Added Uninstalling topic

docs/concepts/README.md, docs/concepts/_index.md
First pass on what a duck type is.
=> Adding duck type concept page

docs/serving/autoscaling/autoscaling-targets.md
=> Delete RPS Target tab

docs/client/install-kn.md
=> fix homebrew statement

docs/install/any-kubernetes-cluster.md
For 0.21 supported minimum version is 0.18 according to https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-eventing-version-table
Adding link to list of versions 
@lionelvillard
-
-
-
=> Update k8s version

docs/install/installing-istio.md
This patch changes Istio installation to use Istio's default profile.
Fix https://github.com/knative/docs/issues/3442
=> Simplify installation istio for Knative

docs/install/_index.md
Fixes #3481
- Fixes link at https://knative.dev/development/install/
=> Fix extraneous ".md" link

docs/eventing/broker/_index.md, docs/eventing/broker/broker-event-delivery.md, docs/eventing/broker/create-mtbroker.md
Follow up PR for @grantr 's comments on https://github.com/knative/docs/pull/3483
=> Follow up comments on broker docs

docs/eventing/samples/kafka/channel/index.md
- adding doc for the new `tls.enabled` flag for the `KafkaChannel`, when using SASL w/ public CA certs
=> Updating the docs for tls.enabled

community/samples/serving/helloworld-rust/Cargo.toml, community/samples/serving/helloworld-rust/Dockerfile, community/samples/serving/helloworld-rust/index.md, community/samples/serving/helloworld-rust/src/main.rs
Updates hyper to v0.14.7 and Rust to v1.51.0.
@slinkydeveloper
=> updated to hyper v0.14.7 and rust v1.51.0

docs/serving/samples/hello-world/helloworld-java-spring/index.md
Fixes #3168 
For some reason the command looked OK in the code but doesn't display properly in the website.
Made some updates to the title of the section and updated the tabs name which seems to have fixed the issue in my local build.
=> minor change to fix command

overrides/home.html
- Show an animated gradient with the colors of the Knative logo in the homepage banner as can be seen [here](https://shinigambit.github.io/docs/)
=> background gradient animation for homepage banner

docs/client/configure-kn.md, docs/client/install-kn.md, docs/client/kn-plugins.md
Manual CP of #3495 to 0.22 branch
=> Cherrypick #3495

docs/client/README.md, mkdocs.yml
Updates the client section nav (via [mknav](http://github.com/julz/mknav)). (Forgot to do this when I did #3551).
=> Regenerate the client nav

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css, overrides/home.html
Fixes #3561, #3548
- Better organization of the css (take them out of the templates html
- Removed all home content from the navs section to the content section
this re-enables some theme features like the back to top button, fixed header (with shadow)
and scrolling events detection on the landing (home) page
You can view the results of this PR [here](https://gabo1208.github.io/docs-1/)
=> feat: added home and navigation menu changes

.github/workflows/knative-boilerplate.yaml, .github/workflows/knative-donotsubmit.yaml, .github/workflows/knative-go-build.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-security.yaml, .github/workflows/knative-style.yaml, .github/workflows/knative-verify.yaml
=> Enable workflows for mkdocs branch

hack/build-with-blog.sh
fix build script.
Need to add gh-action later to verify build script
/assign @julz
=> add correct bin PATH for postcss

OWNERS
=> add approvers ux

docs/eventing/samples/kafka/source/index.md
- adding some notes/background info on usecase and potential limitations of the `KafkaSource`
=> Adding notes on KafkaSource usage

hack/docker/Dockerfile, requirements.txt
add python dependency mkdocs-awesome-pages plugin
=> add python dependency mkdocs-awesome-pages plugin

docs/reference/api/eventing/eventing.md, docs/reference/api/serving.md
Proposed Changes 
New v0.23.0 API docs.
Command:
```bash
cd ./hack/
KNATIVE_SERVING_COMMIT=v0.23.0 KNATIVE_EVENTING_COMMIT=v0.23.0 ./gen-api-reference-docs.sh
```
Related to #3618
=> api specs for Release v0.23

docs/serving/_index.md
=> Update serving/_index.md with network layer option

hack/build-with-blog.sh
Based on feedback
Closes #3622
=> make default version development for now

overrides/assets/stylesheets/home.css, overrides/home.html
The margins and paddings are a bit all over the place on the homepage. This aims at evening that out, while also reducing the amount of different font-styles used for a more "calm" picture.
=> Even out the margins and paddings on the homepage

help/maintainer/docs-release-process.md
=> fix the broken link

hack/build-with-blog.sh, netlify.toml
This will allow the drop down for versions to redirect user to old site
Related to #3617 
/assign @julz
=> handle old versions with redirects

docs/getting-started/README.md, docs/getting-started/first-service.md
Fix #3654 and add "Knative Sandbox" language based on user feedback
=> fixes #3654

docs/getting-started/first-traffic-split.md
=> fixes #3656

docs/getting-started/first-service.md
=> Fix 3654 bug fixes

overrides/assets/stylesheets/home.css
Mostly playing around a bit. This is totally a design bikeshed.
=> Be a bit more subtle with the gradient's colors

docs/stylesheets/extra.css
Title. This caused the announce bar to appear.
=> Fix syntax error that causes some CSS to not apply

docs/admin/install/install-eventing-with-yaml.md, docs/getting-started/first-broker.md, docs/getting-started/first-source.md
sorry really need this to be pushed through for interview in 1 minute
=> eventing getting started hotfixes

hack/build-with-blog.sh
Hopefully this will fix the netlify preview infinite redirects 🤞.
=> Fix redirect to cope with query strings

overrides/assets/stylesheets/home.css, overrides/home.html
- Added some lines in CSS file 
- Altered img tag by adding style attribute
-
=> changed in CSS file and added style in img tag for fixing glitchy logo appearence (#3672)

overrides/home.html
=> Randomise home page icon order

docs/eventing/sink/README.md
=> Fix sink markdown

docs/admin/install/install-eventing-with-yaml.md, docs/eventing/broker/README.md
- Add pointers to RabbitMQ broker to install and available broker.
-
-
=> add rabbitmq to list of brokers

docs/eventing/sources/sinkbinding/getting-started.md, docs/eventing/sources/sinkbinding/reference.md, mkdocs.yml
Fixes #3687.
1. Fixed bulleted lists in tabs
1. Fixed tab formatting in Create a SinkBinding object
1. Fixed note formatting on reference page
=> Formatting fixes for SinkBinding topic

docs/eventing/samples/helloworld/helloworld-go/README.md, docs/eventing/samples/helloworld/helloworld-python/README.md, docs/eventing/samples/parallel/README.md, docs/eventing/sink/kafka-sink.md, docs/eventing/sources/kafka-source/README.md, docs/serving/autoscaling/autoscaling-concepts.md, docs/serving/istio-authorization.md, docs/serving/samples/hello-world/helloworld-scala/index.md, docs/serving/samples/traffic-splitting/index.md, docs/serving/using-auto-tls.md, docs/serving/using-subroutes.md, mkdocs.yml
Part of the fix for #3643 and #3644 
Some general cleanup
This is by no means a PR to make things perfect, so I'd prefer not to block it on hardcore docs reviews or add too much scope, it's simply supposed to make some slight improvements until we have time to invest in properly improving / rewriting docs.
=> Fixing broken links and general cleanup

docs/stylesheets/extra.css
This should fix the CSS so the current page is highlighted in blue in the sidebar again.
=> Fix active page highlight

docs/stylesheets/extra.css
-Font size changes  for 
- table tag
- code tag
- admonition class
-Fixing issue #3694
=> Fontsizing for tables, code tags fixing issue (#3694)

docs/eventing/channels/subscriptions.md, docs/eventing/flows/sequence/sequence-reply-to-sequence/sequence1.yaml, docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
- :broom: Change few remaining v1beta1 to v1.
-
-
=> Fix v1beta1->v1 docs

docs/developer/serving/services/custom-domains.md
Add a note to indicate that private Knative Serivce could be accessed from public internet when using DomainMapping.
See discussion knative-sandbox/net-istio#566
=> Add a note about the visibility expansion of DomainMapping 

blog/releases/announcing-knative-v0-17-release.md, blog/releases/announcing-knative-v0-18-release.md, blog/releases/announcing-knative-v0-19-release.md, blog/releases/announcing-knative-v0-2-release.html, blog/releases/announcing-knative-v0-20-release.md, blog/releases/announcing-knative-v0-21-release.md, blog/releases/announcing-knative-v0-22-release.md, blog/releases/announcing-knative-v0-23-release.md, blog/releases/announcing-knative-v0-3-release.html, blog/releases/announcing-knative-v0-4-release.html, blog/releases/announcing-knative-v0-5-release.html
Blog release for v0.23
Fixes #3624
=> Issue 3624 blog v0.23

docs/eventing/broker/create-mtbroker.md, docs/eventing/broker/kafka-broker/README.md, docs/eventing/debugging/README.md, docs/eventing/samples/helloworld/helloworld-go/README.md, docs/eventing/samples/helloworld/helloworld-python/README.md, docs/eventing/samples/iot-core/README.md, docs/eventing/sink/kafka-sink.md, docs/eventing/sources/apiserversource/getting-started/README.md, docs/eventing/sources/creating-event-sources/writing-event-source/05-receive-adapter.md, docs/eventing/sources/ping-source/README.md, docs/eventing/sources/sinkbinding/getting-started.md, overrides/home.html
Part of the fix for #3643, #3644 and #3752
Some general bash no copy additions and small fixes
=> Eventing sanity pt2

docs/stylesheets/extra.css
=> fix nav links and item css colors

docs/stylesheets/extra.css
=> fix fixing nav item colors

docs/getting-started/first-trigger.md
Thank you to @keshto!! 
Fixes #3737
=> Fixes #3737, fix trigger in getting started guide

docs/serving/autoscaling/README.md
`HPA` is a Serving extensions and it is listed in serving extensions.
=> Fix typo for Serving extensions

overrides/assets/stylesheets/home.css
Fixes #3706 
/assign @markusthoemmes @omerbensaadon
=> Fix hero image aspect ratio on safari

docs/help/contributor/style-guide/README.md
=> Removed broken link and reference to other style guides

docs/serving/convert-deployment-to-knative-service.md, mkdocs.yml
Fixes https://github.com/knative/docs/issues/3841
/cc @evankanderson 
-
-
-
=> Added a new doc for covert from k8s deploy to knative service

overrides/home.html
Remove the "Try in your browser" for now.
Do we want to open a separate issue for re-adding it somewhere else or just keep #3880 open to track that?
=> Remove "Try in your browser"

docs/eventing/channels/channel-types-defaults.md, docs/eventing/channels/create-default-channel.md, docs/eventing/channels/subscriptions.md
=> changed notes for info admonition

overrides/assets/stylesheets/home.css, overrides/home.html
Fixes #3909
- Fix the Trusted by spacing problems on Homepage
=> Fix the Trusted by spacing problems on Homepage

.github/pull-request-template.md, README.md
=> Added new cont. guide link to places

docs/stylesheets/extra.css, overrides/partials/footer.html
Copied footer links from existing site over.
Fixes #3914 
=> Add footer links

overrides/assets/stylesheets/home.css, overrides/home.html
Fixes #3905
- Adding logos for social links on Homepage footer
=> Social logos on Homepage footer

docs/help/contributor/README.md
=> Fix snippets link

config/redirects.yml
Adding from Samia's PR to prevent her having to rebase
=> Add Samia's redirect to prevent painful rebase

overrides/main.html
=> show site feedback information

docs/help/contributor/style-guide/word-and-phrase-list.md
=> Added link to Merriam-Webster

docs/stylesheets/extra.css, overrides/main.html
Playing around with header text and colour (white on back seems a bit harsh).
=> Tweak pardon our progress header

docs/developer/serving/services/custom-domains.md, docs/stylesheets/extra.css, hack/macros.py
Fixes #3874 
Feedback, especially on colour and formatting choices, very welcome. Before merging you may want to try `feature(alpha="1.2")`,  `feature(stable="2.3")` and (in case we ever want to be this verbose)  `feature(alpha="2.3", beta="3.4")`
=> Add feature stable label macro and document that DomainMapping is beta

docs/serving/convert-deployment-to-knative-service.md
@markusthoemmes @evankanderson ^^
=> Added the benefit of deploy to knative service

docs/admin/install/knative-with-operators.md
- This PR adds the instruction on how to configure the eventing sources with the eventing CR.
=> Add the instruction on how to configure the eventing sources with the operator

docs/help/contributor/style-guide/documenting-code.md
=> Tweak style rule

config/nav.yml
=> Revert "capitalizing Guide"

config/nav.yml
=> Revert "[release-0.24] capitalizing Guide"

docs/serving/feature-flags.md
Updated documentation to capture this change: https://github.com/knative/serving/pull/11606
- This issue is fixed by the above PR: https://github.com/knative/serving/issues/10814
- And this PR documents this change.
=> RunAsNonRoot can be set to true without the feature flag

blog/releases/announcing-knative-v0-24-release.md
=> Add v0.24 blog release notes

docs/developer/serving/services/custom-domains.md
Fixes #3835
First pass, help with the wording of this would be great 🙏.
=> Document ClusterDomainClaims

docs/index.md
=> (Fixes #3982) Change homepage name

docs/admin/collecting-metrics/serving-metrics/metrics.md
=> Fixed a typo.

blog/releases/announcing-knative-v0-24-release.md
=> Tweak release notes

docs/admin/install/eventing/install-eventing-with-yaml.md
=> Heavy style edits

docs/snippets/install-kn.md
Cherry-pick of #4010 for 0.24 release branch
Original Issue: #3917
=> add kn homebrew instructions for 0.24 release

docs/help/contributor/style-guide/style-and-formatting.md, docs/help/contributor/style-guide/voice-and-language.md
=> Added rule and tidied up a bit

config/nav.yml, docs/serving/feature-flags.md
Fixes  #3971
FYI: This PR needs a follow up issue to decide whether to use `-` or `*` for bullet lists in docs @snneji @RichardJJG 
Both are accepted but we should probably just choose one to keep docs consistent; any preference?
=> Fix feature flag doc formatting

config/nav.yml, docs/eventing/samples/kafka/resetoffset/README.md
=> #4017: Editing for Kafka ResetOffset example

docs/admin/install/knative-with-operators.md
- Knative Operator is ready to call as in beta phase, as the CRs have been stabilized.
=> Describe the operator as in beta phase

docs/help/contributor/style-guide/documenting-code.md
Fixes #3811.
This fixes the second item in that issue.
=> Update style guide

docs/developer/eventing/sources/kafka-source/README.md
=> Fix yaml formatting

docs/serving/knative-kubernetes-services.md
Fixes #4013 and also improves link text.
=> Fix broken links

docs/admin/install/eventing/install-eventing-with-yaml.md, docs/admin/install/serving/install-serving-with-yaml.md
=> Add output for verification step

docs/admin/install/knative-offerings.md
Cherry-pick of #3994 for release-0.24
Add entry for VMware's Knative offering
=> Cherry-pick Update knative-offerings.md (#3994)

docs/serving/using-auto-tls.md
=> Fixed a minor typo.

docs/snippets/install-kn.md
Fixes #4078 
- Adds complete install instructions for the `kn` plugin
=> Complete instructions for installing kn binary

.github/pull-request-template.md, docs/help/contributor/structure.md
=> Add references to upating nav menu

docs/client/README.md
Fixes: [#1251](https://github.com/knative/client/issues/1251)
- Adding information about `--kubeconfig`, `context`, and `config` options in `kn`
=> Ways to connect to cluster using kn

archived/v0.23-docs/install/collecting-metrics/collector.yaml
bug fix according to https://github.com/open-telemetry/opentelemetry-collector/issues/3845.
fix error:
'service.extensions[0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[health_check: pprof: zpages:]'
Fixes #11810 
-
-
-
=> Fixes #11810 

config/nav.yml, docs/developer/serving/services/byo-certificate.md
=> add docs for byo certificate via domainmapping

docs/serving/samples/hello-world/helloworld-java-spring/README.md, docs/serving/samples/hello-world/helloworld-java-spring/service.yaml, docs/serving/setting-up-custom-ingress-gateway.md
This is the final PR for cleaning up `EOF` format `kubectl` commands. 
Fixes #3813.
=> Updating the last few commands to remove EOF

docs/getting-started/first-broker.md
=> #4124: fix link

docs/serving/deploying-from-private-registry.md
Fixes #4128 
- fixed a example of imagePullSecrets
=> Fixed an example of imagePullSecrets

docs/help/contributor/style-guide/style-and-formatting.md
=> Add link styling rules

docs/admin/collecting-metrics/README.md
=> Fix broken formatting

docs/client/README.md, docs/client/configure-kn.md, docs/getting-started/README.md, docs/getting-started/first-autoscale.md, docs/getting-started/first-broker.md, docs/getting-started/first-traffic-split.md, docs/getting-started/next-steps.md
=> Add .md to links in getting-started and client folders

docs/admin/install/eventing/install-eventing-with-yaml.md, docs/admin/install/uninstall.md
- Fix link of release asset for the NATSS channel
This was reported in the \#eventing-questions channel on Slack.
=> eventing-natss: Fix name of release manifest

docs/developer/eventing/sources/kafka-source/README.md
Fixes #4140 ; additional minor cleanup
=> Fix broken link, some minor cleanup

docs/admin/collecting-logs/README.md, docs/admin/collecting-metrics/eventing-metrics/metrics.md, docs/admin/eventing/broker-configuration.md, docs/admin/install/README.md, docs/admin/install/eventing/eventing-installation-files.md, docs/admin/install/installing-istio.md, docs/admin/install/operator/configuring-serving-cr.md, docs/admin/install/serving/install-serving-with-yaml.md, docs/admin/install/serving/serving-installation-files.md, docs/admin/serving/feature-flags.md
=> Added .md extension where missing

docs/getting-started/first-service.md
The service in the tutorial could not be resolved. It is not immediately apparent why this is the case (VPN, FritzBox DNS Server, etc). The tips in the comments solved the problem for me.
- Add a pointer to a possible solution.
=> Add pointer in case the service cannot be resolved

docs/developer/serving/services/custom-domains.md
=> Style changes

docs/client/README.md, docs/client/install-kn.md, docs/eventing/broker/README.md, docs/eventing/channels/README.md, docs/getting-started/first-autoscale.md, docs/getting-started/first-broker.md, docs/getting-started/first-source.md, docs/getting-started/first-traffic-split.md, docs/getting-started/first-trigger.md, docs/snippets/dns.md, docs/snippets/install-kn.md
=> Changed HTML links to Markdown

docs/developer/concepts/duck-typing.md
=> Style edits to Duck Typing topic

docs/help/contributor/README.md
=> Add link to code of conduct

docs/getting-started/README.md, docs/snippets/install-kn.md, docs/snippets/quickstart-install.md
add `kn quickstart` to getting started guide for version 0.25
=> add kn quickstart 0.25

docs/snippets/prerequisites.md
per 0.24 release notes https://github.com/knative/serving/releases/tag/v0.24.0 v1.19 is now the minimum k8s version
fixes: https://github.com/knative/docs/issues/4177
-
-
-
=> set v1.19 as minimum k8s version

docs/help/contributor/github.md, docs/help/contributor/structure.md, docs/help/contributor/templates/template-procedure.md
=> Add .md extension to internal links

CONTRIBUTING.md
Fixes an issue mentioned in: https://github.com/knative/docs/issues/4197
- Updates some broken links. Please note, I could not find the appropriate links for `website help` and `maintainer help` I removed them... if these pages do exist somewhere else I would prefer to re-link them
=> Updates links in `CONTRIBUTING.md`

config/redirects.yml, docs/_index.md, docs/admin/install/installing-istio.md, docs/samples.md
=> Add missing .md to links in Docs folder (top level)

docs/getting-started/first-traffic-split.md
Going through getting started guide...
=> Correct kubectl expected output

.github/workflows/knative-boilerplate.yaml, .github/workflows/knative-donotsubmit.yaml, .github/workflows/knative-go-build.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-security.yaml, .github/workflows/knative-style.yaml, .github/workflows/knative-verify.yaml, .github/workflows/mkdocs-strict-verify.yaml, docs/help/contributor/README.md, docs/snippets/links/main-docs-branch-link.md, golang/docs.html, mkdocs.yml
Fixes #3862
/assign @omerbensaadon 
/assign @julz 
/hold
hold it until we rename the branch
=> rename mkdocs branch to main

config/redirects.yml
=> Add redirect for a moved file to prevent user 404s

docs/developer/serving/services/custom-domains.md
Fixes #4225
Fixed the formatting issues and made a few other tweaks.
=> Fix formatting for create custom domains with kn domain

golang/_redirects, golang/container-freezer.html
- adding aliases for container-freezer
Part of https://github.com/knative/community/issues/742
(hopefully in the right place this time ;) )
/assign @julz @evankanderson
=> Adding container-freezer aliases

docs/help/contributor/style-guide/documenting-code.md
Fixes https://github.com/knative/docs/issues/3794
=> Add code excerpt docs guidelines

config/nav.yml, docs/admin/collecting-metrics/serving-metrics/metrics.md, docs/developer/serving/services/service-metrics.md
Fixes https://github.com/knative/docs/issues/3865
Direct preview link: https://deploy-preview-4259--knative.netlify.app/development/developer/serving/services/service-metrics/
=> Moved metrics to dev guide

config/nav.yml, docs/developer/eventing/sources/ping-source/README.md, docs/developer/eventing/sources/ping-source/reference.md
=> Edit PingSource docs

config/nav.yml, docs/developer/serving/services/http-option.md
Part of: https://github.com/knative/serving/issues/11547
=> include documentation about the httpOption annotation

docs/developer/eventing/sources/kafka-source/README.md
=> Style edits to Apache Kafka Source Example topic

help/maintainer/docs-release-process.md
Fixes #3978
- Update the release docs. Since the new docs build is more automated and I expect the build script to change, I explained the high-level process, but not a line-by-line update.
=> Update release docs

docs/developer/eventing/sources/ping-source/ping-source-binary.yaml, docs/developer/eventing/sources/ping-source/ping-source.yaml, docs/eventing/flows/sequence/sequence-reply-to-event-display/README.md, docs/eventing/flows/sequence/sequence-reply-to-event-display/ping-source.yaml, docs/eventing/flows/sequence/sequence-reply-to-sequence/README.md, docs/eventing/flows/sequence/sequence-reply-to-sequence/ping-source.yaml, docs/eventing/flows/sequence/sequence-terminal/README.md, docs/eventing/flows/sequence/sequence-terminal/ping-source.yaml, docs/eventing/flows/sequence/sequence-with-broker-trigger/README.md, docs/eventing/flows/sequence/sequence-with-broker-trigger/ping-source.yaml, docs/eventing/samples/parallel/multiple-branches/README.md, docs/eventing/samples/parallel/multiple-branches/ping-source.yaml, docs/eventing/samples/parallel/mutual-exclusivity/README.md, docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml, tutorials/katacoda/3-eventing-intro-channels/step2.md, tutorials/katacoda/3-eventing-intro-channels/step3.md, tutorials/katacoda/3-eventing-intro-channels/step4.md
- Fix examples still using PingSource v1beta2
-
-
=> PingSource is v1

docs/developer/eventing/sources/apiserversource/README.md, docs/developer/eventing/sources/apiserversource/getting-started.md, docs/developer/eventing/sources/apiserversource/reference.md, docs/developer/eventing/sources/containersource/README.md, docs/developer/eventing/sources/containersource/reference.md, docs/developer/eventing/sources/ping-source/README.md, docs/developer/eventing/sources/ping-source/reference.md, docs/developer/eventing/sources/sinkbinding/README.md, docs/developer/eventing/sources/sinkbinding/getting-started.md, docs/developer/eventing/sources/sinkbinding/reference.md
Fixes formatting in ApiServerSource docs and includes tweaks to other sources docs to make them more consistent.
Fixes #4303
=> Clean up sources docs

config/nav.yml, docs/developer/serving/services/certificate-class.md
Part of https://github.com/knative/serving/issues/11547
=> include documentation about certificate class annotation

docs/eventing/getting-started.md
Fixes #https://github.com/knative/docs/issues/4276
- Propagate event-example ns everywhere
-
-
=> fix eventing getting started doc

docs/eventing/channels/create-default-channel.md, docs/eventing/channels/subscriptions.md
=> [eventing] fix broken link to ref doc

docs/admin/install/knative-offerings.md
Fixes broken link. Got the corrected link from Google search.
=> Update broken VMware link

config/nav.yml, docs/eventing/broker/README.md, docs/eventing/broker/rabbitmq-broker/README.md
- Adds a document describing how users can get started with eventing-rabbitmq
=> Add doc for rabbitmq broker

blog/docs/articles/steering-elections-2021.md
- Add a blog post for Steering Elections 2021.
-
-
=> sc 2021 blogpost

config/nav.yml
Removes duplicate "blog" tab in naviagation
=> Removing duplicate blog tab

config/nav.yml, docs/stylesheets/extra.css
Brings the changes to the website tabs made in #4409 to the release-0.26 branch [as discussed in Slack](https://knative.slack.com/archives/C01JBD1LSF3/p1635800491071300?thread_ts=1635796691.053300&cid=C01JBD1LSF3)
/assign @omerbensaadon @julz
=> Updating website tabs in 0.26 release

docs/about/case-studies/deepc.md, docs/about/case-studies/outfit7.md, docs/about/case-studies/puppet.md
=> Fix rendering glitch

hack/build.sh
=> cut docs for Knative 1.0 GA

config/redirects.yml
Fixes redirect issue for several pages identified in [Slack](https://knative.slack.com/archives/C9CV04DNJ/p1635978610050600)
=> removes redundant redirects

docs/eventing/sinks/kafka-sink.md
Fixes #4400 
- Document contentMode for KafkaSink
=> Document contentMode for KafkaSink

docs/eventing/sources/README.md
Signed-off-by: Jens Gerke <jens.gerke@direktiv.io>
- Added SNMP and Direktiv source to the sources list
=> Added SNMP and Direktiv source

docs/about/case-studies/puppet.md
=> Update puppet.md - fix wording

docs/about/case-studies/puppet.md
=> Update puppet.md - fix grammar

blog/mkdocs.yml
I am 99.99% sure this fixes #4419 
but I cannot run the blog locally due to #4427
=> update mkdocs.yml in blog

config/redirects.yml
I checked all pages for broken redirects and found one more. Hopefully this should be the last one.
=> fix redirect loop

config/nav.yml, docs/eventing/event-registry.md
=> Edit event registry docs

blog/config/nav.yml, blog/docs/articles/highlighting-value-knative-c-suite.md, blog/docs/index.md
Adds the "Highlighting the Value of Knative for the C-Suite" blog post, as requested by @omerbensaadon 
Note: I had to fiddle with the formatting for the quotes on the left side, but it is very possible that I did not do so in the optimal way. This is a roundabout way of me saying that someone should definitely take a look at the HTML because there's a very real chance I did something ~stupid~ non-optimal when rendering it.
=> Adding c-suite blog post

overrides/home.html
Fixes #4386 
Quick PR to update the link for the button on the home page.
=> Update administrator button on homepage

docs/install/operator/knative-with-operators.md
- This PR changed the format of the section installing eventing with different eventing sources.
=> Change the format of the section of installing eventing sources

blog/config/nav.yml, blog/docs/releases/announcing-knative-v1-0-release.md
=> add release notes for v1.0

hack/docker/README.md
=> Grammar fix

archived/v0.23-docs/eventing/broker/index.xml, archived/v0.23-docs/eventing/broker/kafka-broker/index.html, archived/v0.23-docs/eventing/event-registry/index.html, archived/v0.23-docs/eventing/index.html, archived/v0.23-docs/eventing/index.xml, archived/v0.23-docs/eventing/samples/container-source/index.html, archived/v0.23-docs/eventing/samples/index.xml, archived/v0.23-docs/eventing/samples/writing-event-source/index.xml, archived/v0.23-docs/eventing/sources/creating-event-sources/writing-event-source/01-theory/index.html, archived/v0.23-docs/eventing/sources/creating-event-sources/writing-event-source/index.xml, docs/eventing/broker/kafka-broker/README.md, docs/eventing/event-registry.md, docs/eventing/sinks/kafka-sink.md, docs/getting-started/first-broker.md, vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go, vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go, vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go, vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
Fixed few broken CloudEvents docs links in the documentation
Copy of PR #444. This time with CLA and proper contributor email
=> Fixed few broken cloudevents links in the documentation

docs/install/serving/install-serving-with-yaml.md, docs/serving/configuration/deployment.md, docs/serving/configuration/rolling-out-latest-revision-configmap.md, docs/serving/samples/knative-routing-go/README.md, docs/serving/samples/kong-routing-go/README.md, docs/serving/services/certificate-class.md, docs/serving/services/custom-domains.md, docs/serving/services/http-option.md, docs/serving/services/ingress-class.md, docs/serving/using-a-tls-cert.md, docs/serving/using-auto-tls.md
- update casing for serving's config-deployment
- update casing for serving's config-network
Part of https://github.com/knative/serving/issues/7300
=> Switch to snake-casing for config map properties

blog/docs/articles/highlighting-value-knative-c-suite.md
- `Triggermesh` -> `TriggerMesh`
=> Fix capitalization of TriggerMesh in blog post

docs/eventing/channels/channel-types-defaults.md, docs/eventing/sources/kafka-source/README.md
- Adding a note on messaging ordering for Kafka channel and source
-
-
=> Adding a note on messaging ordering for Kafkas

docs/snippets/collecting-logs.md
- Use the correct link to fluent-bit-collector.yaml.
=> Correct the link of fluent-bit-collector.yaml

.github/workflows/knative-mkdocs-dockerimage.yaml
Fixes https://github.com/knative/docs/issues/4449
- Github action to build and push latest commit to dockerhub
=> Github Action to build docker image of knative mkdocs

docs/getting-started/README.md, docs/snippets/quickstart-install.md
Fixes #4473
- Remove buggy behavior of `kind`installation
- Add section for minikube installation
-
=> Add documentation about minikube quickstart

docs/eventing/broker/create-mtbroker.md, docs/eventing/broker/kafka-broker/README.md, docs/eventing/channels/channels-crds.md, docs/eventing/configuration/channel-configuration.md, docs/eventing/flows/sequence/sequence-with-broker-trigger/README.md, docs/eventing/sources/apache-camel-source/README.md, docs/eventing/sugar/README.md, docs/install/client/README.md, docs/install/operator/configuring-eventing-cr.md, docs/install/serving/installing-istio.md, docs/serving/autoscaling/scale-bounds.md, docs/serving/configuration/config-defaults.md, docs/serving/load-balancing/README.md, docs/serving/troubleshooting/debugging-application-issues.md, docs/serving/using-auto-tls.md, docs/snippets/install-kn.md
Fixes https://github.com/knative/docs/issues/4476
Some additional other misc. fixes for spacing etc
I didn't check the samples files since they're moving into github.
=> Update notes formatting

docs/install/serving/installing-istio.md
This is same fix with https://github.com/knative/docs/pull/3466.
It seems https://github.com/knative/docs/pull/4388 reverted the fix accidentally.
/cc @snneji
=> Fix istio installation doc

hack/macros.py
Fixes knative/eventing#5930
Nightly (a.k.a. development) releases are published to knative-nightly, and do not use the org name. This has not changed since 2019-05-17: https://github.com/knative/test-infra/blob/09f2b26361c825a1a110ce96a3c2657e3d5a23a9/scripts/release.sh#L96
Thank you @andersonsoares-tomtom for reporting this via https://github.com/knative/eventing/issues/5930
=> Fix all links to nightly releases

blog/README.md
Adds a README for the blog that details how the blog works, how to make updates, etc.
=> Adding instructions on how to update blog

docs/serving/README.md
Fixes https://github.com/knative/docs/issues/2108 
Remove fluff content
=> Add note about HTTPS

docs/eventing/custom-event-source/containersource/README.md, docs/eventing/custom-event-source/containersource/reference.md, docs/eventing/custom-event-source/sinkbinding/create-a-sinkbinding.md
Fixes https://github.com/knative/docs/issues/4188
=> Update heartbeats image

docs/serving/using-a-custom-domain.md
Fixes https://github.com/knative/docs/issues/4359
- Remove Google Cloud (vendor specific) note
- Remove additional fluff and general cleanup
=> Updated custom domain docs

README.md, blog/docs/releases/announcing-knative-v0-17-release.md, blog/docs/releases/announcing-knative-v0-18-release.md, blog/docs/releases/announcing-knative-v0-19-release.md, blog/docs/releases/announcing-knative-v0-20-release.md, blog/docs/releases/announcing-knative-v0-21-release.md, blog/docs/releases/announcing-knative-v0-22-release.md, blog/docs/releases/announcing-knative-v0-23-release.md, blog/docs/releases/announcing-knative-v0-24-release.md, blog/docs/releases/announcing-knative-v0-25-release.md, blog/docs/releases/announcing-knative-v0-26-release.md, blog/docs/releases/announcing-knative-v0-5-release.md, blog/docs/releases/announcing-knative-v1-0-release.md, blog/docs/steering/2020-05-toc_election_results.md, blog/docs/steering/2020-11-ksc-elections.md, docs/eventing/custom-event-source/custom-event-source/README.md
Found a few more links that needed updating after moving the community docs.
=> Fix links community docs

netlify.toml
=> Redirect to new community section

.gitpod.yml
add gitpod for drive-by users making quick changes
This supersedes PR  https://github.com/knative/docs/pull/4507
You can see how it works in this video https://user-images.githubusercontent.com/1094878/145515788-d0d3cf50-1f12-46b4-9bb0-2074829239fe.mp4
=> add gitpod for drive-by users making quick changes

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- Add the additional info regarding configuring the resources for a specific container name.
=> Add description on configuring resources for a specific container

docs/install/operator/knative-with-operators.md
- No need to state it is beta, since it is already GA.
=> Remove the beta info for operator, since it is GA

blog/config/nav.yml, config/nav.yml, config/redirects.yml, docs/community/README.md, netlify.toml, overrides/home.html
Cherry pick of #4578 
* Update contributing links
* Redirect from old docs contributor guide
* Remove redirect from redirects.yml
* Fix redirect
* Remove arrow
=> [release-1.0] Update contributing call to action and links

blog/config/nav.yml, config/nav.yml, config/redirects.yml, docs/community/README.md, netlify.toml, overrides/home.html
Cherry pick #4578
* Update contributing links
* Redirect from old docs contributor guide
* Remove redirect from redirects.yml
* Fix redirect
* Remove arrow
=> [release-0.26] Update contributing call to action and links

blog/config/nav.yml, config/nav.yml, config/redirects.yml, docs/community/README.md, netlify.toml, overrides/home.html
Cherry pick of #4578 
* Update contributing links
* Redirect from old docs contributor guide
* Remove redirect from redirects.yml
* Fix redirect
* Remove arrow
=> [release-0.25] Update contributing call to action and links

overrides/main.html
Removes the banner.
Fixes #4596
=> Remove 1.0 banner

config/nav.yml, docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md, docs/install/operator/configuring-with-operator.md
- Clean up docs about config using Operators
- Remove duplicate content and fluff
Preview link: https://deploy-preview-4618--knative.netlify.app/development/install/operator/configuring-with-operator/
=> Clean up operator configmap docs

docs/serving/configuration/deployment.md
Documents: https://github.com/knative-sandbox/container-freezer/issues/20
Document "freezer service"  knative serving config-deployment page.
=> Add documentation for freezer to knative docs

docs/install/knative-offerings.md
Fixes #4621 
- Change Gardener link in "Knative Offerings" page to point to Github repository
The Gardener website has been restructured, so that only tutorials for Gardener components are shown. We can't find a component to attach this tutorial to, but we can link to the original Github page, which has the same content.
=> Updated link

config/nav.yml, docs/install/operator/knative-with-operators.md, docs/install/upgrade/upgrade-installation-with-operator.md, docs/snippets/dns.md, docs/snippets/real-dns-operator.md, docs/snippets/real-dns-yaml.md
Fixes #3890 
- Extensive edits on `knative-with-operators.md`
- Fix some formatting issues with snippets
The preview for the page I edited is here: https://deploy-preview-4634--knative.netlify.app/development/install/operator/knative-with-operators/.
=> Edit Operator docs

hack/macros.py
I manually cherry picked #4638 because the automatic one didn't work.
/assign @psschwei
=> [release-1.1] Fixes link to client reference

blog/mkdocs.yml
=> fix rss feed xml with correct url links

docs/serving/configuration/revision-gc.md
Fixes #4652
- Update example to immediately collect any inactive revision
=> Fix example to immediately collect any inactive revision (#4652)

docs/install/knative-offerings.md
Signed-off-by: Matt Ray <github@mattray.dev>
=> TriggerMesh provides both on-premises and hosted Knative support.

docs/getting-started/first-autoscale.md, docs/getting-started/first-source.md, docs/getting-started/first-traffic-split.md, docs/snippets/quickstart-install.md
=> Change DNS to sslip in code examples

docs/install/operator/knative-with-operators.md
Fixes #4651 
Swapped istio and kourier.
=> Make kourier first network layer

docs/snippets/prerequisites.md
Since it has been bumped here https://github.com/knative/pkg/pull/2397
Fixes #4654
=> Update min version requirement

blog/config/nav.yml, blog/docs/releases/_template-announcing-knative-v1-X-release.txt, blog/docs/releases/announcing-knative-v1-1-release.md
=> Release notes 1.1

docs/serving/configuration/feature-flags.md
As per title. Part of the work in https://github.com/knative/serving/issues/12438
=> Add pvc extension

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- This PRs added the description on how to configure the resources for a container within a specific deployment.
=> Update the docs regarding using `spec.deployment` to override the resources

docs/eventing/channels/channel-types-defaults.md
-Just a quick typo fix: guaranty -> guarantee
=> chore(eventing): fix typo in channel docs

hack/build.sh
=> Update release to 1.2 in build script

config/redirects.yml
Must have missed this one when adding redirects.
=> Add redirect for operator install page

.github/workflows/knative-release-notes.yaml, .github/workflows/knative-security.yaml, code-samples/serving/cloudevents/cloudevents-dotnet/Properties/launchSettings.json, code-samples/serving/hello-world/helloworld-csharp/Program.cs
As per title + fix security workflow
Replaces https://github.com/knative/docs/pull/4686
Fixes https://github.com/knative/docs/pull/4686
=> [main] update actions main

blog/docs/index.md
- Blog `Featured section` references latest Knative release
=> Update Knative.dev Blog index.md

blog/docs/releases/announcing-knative-v1-2-release.md
add pvc support to release notes 1.2
=> add pvc support to release notes 1.2

config/nav.yml, docs/getting-started/clean-up.md, docs/getting-started/first-traffic-split.md, docs/getting-started/next-steps.md
=> Edit Clean up page in tutorial

.github/pull-request-template.md
- Update cherrypick instructions based on Prow docs
- https://knative.slack.com/archives/C9CV04DNJ/p1643912783626809
- Sample usage: https://github.com/knative/docs/pull/4684#issuecomment-1029267693
=> Update pull-request-template.md cherrypick instructions

config/nav.yml, docs/eventing/broker/kafka-broker/README.md
- The term "Apache Kafka Broker" is very misleading as servers inside of a "Kafka cluster" are called brokers. Instead I change the header to "Knative Kafka Broker" to indicate a bit of differentiation between the actual Apache Kafka project and the Knative based implementation here  
-
-
=> Rewording the bits for the knative Kafka broker

docs/getting-started/quickstart-install.md, docs/snippets/install-kn.md
=> Add upgrade commands for homebrew

docs/stylesheets/extra.css, mkdocs.yml, requirements.txt
=> update to mkdocs 8

docs/stylesheets/extra.css, mkdocs.yml, requirements.txt
=> test mkdocs8

blog/mkdocs.yml, docs/stylesheets/extra.css, hack/build.sh, mkdocs.yml, requirements.txt
Fixes #4491
Upgrade guide is here https://squidfunk.github.io/mkdocs-material/upgrade/#whats-new
=> Upgrade material-mkdocs to major version 8 

docs/snippets/collecting-metrics.md
- Added a warning to the docs about a recent [query](https://knative.slack.com/archives/C964EFQAW/p1644776122603229). 
/cc @skonto
=> Add a note about otel and prometheus being mutually exclusive

docs/eventing/sources/kafka-source/README.md
We're moving the KafkaSource implementation
to a new repository.
This PR changes the installation instructions and 
changes the text to verify that the KafkaSource
is ready/running.
- Update KafkaSource documentation with the new installation instructions
=> Update KafkaSource documentation with the new installation instructions

blog/mkdocs.yml, mkdocs.yml
=> Update copyright to 2022

contribute-to-docs/getting-started/previewing-docs-locally.md
Tell users to run preview script from root directory.
=> Small change to live preview instructions

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css, overrides/home.html
=> fixed button color now in home + rephrased headline

.github/pull-request-template.md, .github/workflows/knative-release-notes.yaml, .github/workflows/knative-security.yaml, .github/workflows/knative-style.yaml
sync github actions for release-1.2
=> sync github action directory

docs/stylesheets/extra.css
=> Fix home design details

docs/serving/services/creating-services.md
Updated the numbered list and moved the tabs to be side by side tabs instead of one after the other.
Fixes: #4703
=> fix numbered list and tabs formatting

docs/serving/autoscaling/concurrency.md, docs/serving/using-auto-tls.md
=> Moved the "Important" note to "Warning" note format

blog/docs/steering/cncf.md
Links were showing in one paragraph, this spaces them out into a list
=> Fixes formatting on external blog links

config/nav.yml, docs/reference/security/README.md
=> Adds security page to site

docs/eventing/experimental-features/new-trigger-filters.md
Updates the docs to match the change introduced here knative/eventing#6148
- Update the new trigger filters docs to rename the `sql` field to `cesql`.
=> Rename sql to cesql

docs/install/client/kn-plugins.md
Adds list of kn plugins and some details around installing them. Any suggestions welcome :) 
Fixes #4719
=> Adds list of kn plugins to docs

docs/eventing/flows/sequence/README.md
Fixes #3853 
- added an info stamp for the need of hairpin traffic in eventing sequence.
=> info stamp added regarding hairpin mode in sequence

hack/build.sh
=> Update build script for 1.3 release

blog/docs/articles/_index.md, blog/docs/events/_index.md, blog/docs/releases/_index.md, blog/docs/steering/_index.md
=> Removed every _index.md file.

hack/docker/Dockerfile, hack/docker/build-image.sh, requirements.txt
This PR sets up the correct dependencies for the upcoming mkdocs macro updates
=> update docker image with extra python dependencies

hack/macros.py
cherry-pick of https://github.com/knative/docs/pull/4831
=> [release-1.0] update macro to lookup point releases for artifacts

hack/macros.py
Fixes: https://github.com/knative/docs/issues/4842
=> drop removeprefix as it's only available in python3.9

golang/_redirects, golang/infra.html
- Adds infra repo redirect
-
-
=> add infra to golang redirect

docs/eventing/README.md, docs/serving/README.md
Per issue #4848
https://github.com/knative/docs/issues/4848
=> Adding install links to overview pages

code-samples/community/serving/helloworld-rust/README.md, docs/serving/services/creating-services.md
Fixes #4894 
Edited indentation in two code snippets
=> Fix indentation

docs/snippets/quickstart-install.md
=> Add steps to quickstart binary install

docs/snippets/prerequisites.md
Done here: https://github.com/knative/pkg/pull/2485
=> bump our min k8s version to 1.22

docs/serving/autoscaling/scale-bounds.md
- Fixes https://github.com/knative/docs/issues/4897
=> Update scale bounds with global min-scale

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md, docs/install/operator/configuring-with-operator.md, docs/install/operator/knative-with-operators.md
- Upgrade the instruction on upgrading the v1alpha1 custom resources to v1beta1.
=> Upgrade the docs for Knative Operators

blog/config/nav.yml, blog/docs/steering/2022-04-14-annual-report-2021.md
Add blog for 2021 annual report
cc @vaikas  @pmorie
=> add blog for 2021 annual report

docs/about/testimonials.md
=> Fix small typos in testimonials.md

blog/config/nav.yml, blog/docs/events/install-fest-04-2022.md
Add blog post about install fest, it supersedes PR #4926
=> Install fest blog

config/nav.yml, docs/eventing/configuration/sugar-configuration.md, docs/eventing/sugar/README.md
Fixes #4896 
- Update existing Sugar Controller page to reference LabelSelector Changes
- Add Configuration page for "config-sugar" ConfigMap
=> Update Sugar Controller docs

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md, docs/install/operator/knative-with-operators.md
=>  Clean up broken formatting in Operator install docs

hack/build.sh
=> changes to add Knative 1.4 docs

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-4-release.md
Fixes #4902
- blog post for release 1.4
=> add blog post for release 1.4

blog/config/nav.yml, blog/docs/steering/toc-2022-election-announcement.md
@vaikas please approve Tuesday morning.  Thanks!
=> Blog post for 2022 TOC elections

docs/getting-started/first-autoscale.md
Small PR to change a warning to a note because I don't think this is important enough to be a warning. 
See this comment thread: https://github.com/knative/docs/pull/4893#discussion_r845964217
=> Change warning to note

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- Add the instruction on how to configure the service labels and annotations with Knative operator.
=> Instruction on how to override the labels and annotations for services

docs/install/operator/configuring-serving-cr.md
- Leverage the KnativeServing CR to configure the servers stanza for istio gateways.
=> Configure the servers for istio gateways

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
- This PR removed the deprecated configuration of system resources, only keeping the configuration for a specific deployment.
=> Remove the deprecated configuration of system resources

docs/eventing/configuration/broker-configuration.md
Fixes #2944 
- Add example and description of Broker delivery spec YAML
- https://deploy-preview-4965--knative.netlify.app/docs/eventing/configuration/broker-configuration/#configuring-delivery-spec-defaults
=> Add delivery spec Broker docs

docs/snippets/install-kn.md, docs/snippets/quickstart-install.md
=> kn CLI install should use tap instead of compile for brew install

docs/eventing/broker/README.md
Fixes #4969
- Fix dead link to Broker spec at `Eventing` / `Brokers` / `About Brokers`
=> Fix dead link to Broker spec

config/nav.yml, docs/serving/using-a-custom-domain.md, docs/serving/using-auto-tls.md
Fixes #4352 and general cleanup of sections
Preview links:
- https://deploy-preview-4980--knative.netlify.app/docs/serving/using-auto-tls/
- https://deploy-preview-4980--knative.netlify.app/docs/serving/using-a-custom-domain/
=> Fix values and general cleanup

docs/snippets/prerequisites.md
Update minimum CPU recommendation
Fix #4944 
-
-
-
=> Bumped the CPU requirements

docs/serving/traffic-management.md
Fixes https://github.com/knative/docs/issues/4860
=> Fix minor tag bug

blog/config/nav.yml, blog/docs/releases/announcing-knative-v1-5-release.md, blog/docs/releases/announcing-knative-v1-5-release.txt
Fixes: https://github.com/knative/docs/issues/4976#issuecomment-1146856965
=> Include blog post for release-1.5

docs/serving/configuration/feature-flags.md
Fixes [#12999](https://github.com/knative/serving/issues/12999)
- Just a typo
=> Fix docs typo regarding runtimeClassName Extension

docs/serving/configuration/config-defaults.md
Fixes #4732 
- Add per-revision config settings where they exist, or explain that they are N/A
- Clean up formatting
=> Add per-revision examples to serving config

blog/docs/releases/announcing-knative-v1-5-release.md
Fixes https://github.com/knative/docs/issues/5016
Remove unused heading
=> Remove unused heading from TOC

overrides/home.html
Fixes #4905
This is a change that we discussed in the WG back on March 22; see #4905 for more details
=> Rename home page buttons

blog/config/nav.yml, blog/docs/articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.md, blog/docs/articles/distributed-tracing.md, blog/docs/articles/event-drive-app-knative-eventing-kogito.md, blog/docs/articles/event-driven-image-bigquery-processing-pipelines.md, blog/docs/articles/get-started-knative-eventing.md, blog/docs/articles/highlighting-value-knative-c-suite.md, blog/docs/articles/knative-v0-3-autoscaling-a-love-story.md, blog/docs/articles/ko-fast-kubernetes-microservice-development-in-go.md, blog/docs/articles/orchestrating-cloud-events-with.md, blog/docs/articles/quickstart-with-knative.md, blog/docs/articles/set-up-a-local-knative-environment-with-kind.md, blog/docs/articles/workflow-as-function-flow.md, blog/docs/events/google-summer-of-code-2022.md, blog/docs/releases/announcing-knative-1.0.md, blog/docs/releases/knative-1.0.md
Fixes: https://github.com/knative/docs/issues/4363
Also moved some blog posts from Articles to Releases as appropriate
=> Update blog post frontmatter format

blog/docs/articles/highlighting-value-knative-c-suite.md, blog/docs/articles/knative-v0-3-autoscaling-a-love-story.md, blog/docs/events/google-summer-of-code-2022.md
=> Adding more blog authors

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md
Fixes https://github.com/knative/docs/issues/4329
Also, some additional cleanup and removed the list at the top because this page already has a TOC in the right nav.
=> Cleanup for KnativeServing CR config docs

docs/serving/deploying-from-private-registry.md
Fixes https://github.com/knative/docs/issues/4420
=> Add per-Service imagePullSecrets config

contribute-to-docs/getting-started/becoming-a-contributor.md, docs/contributing/contributing.md
Fixes https://github.com/knative/docs/issues/5047
Additional minor clean up
=> Update CLA information in docs

docs/eventing/broker/kafka-broker/README.md, docs/eventing/custom-event-source/containersource/README.md, docs/eventing/custom-event-source/containersource/reference.md, docs/eventing/custom-event-source/sinkbinding/reference.md, docs/eventing/event-registry.md, docs/eventing/sinks/kafka-sink.md, docs/eventing/sources/README.md, docs/eventing/sources/apiserversource/reference.md, docs/eventing/sources/ping-source/reference.md
- updating link to the latest 1.0.x version
=> Updating to point to CE 1.0.2

docs/eventing/sinks/kafka-sink.md
- Reflect the change of the CE content mode based on https://github.com/knative-sandbox/eventing-kafka-broker/pull/2391
=> KafkaSink: Swap the default

docs/eventing/broker/rabbitmq-broker/README.md
- Rabbitmq broker docs changed to reference the new config object that will be introduced in v1.6
=> Updated RabbitMQ docs with RabbitMQ broker config reference

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-6-release.md
Add blog / release notes for Knative 1.6 release
- Adds summarized changes collected here: https://hackmd.io/k5bKq_cmSKKP0S2xwaPB-A?both
/assign @abrennan89 @psschwei
=> Add Knative 1.6 blog entry

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/configuring-serving-cr.md, docs/install/operator/knative-with-operator-cli.md, docs/install/operator/knative-with-operators.md
- This PR added the instruction on how to install and use the operator CLI plugin to install operator, serving and eventing.
=> Add the instruction on how to install and configure with the operator CLI plugin

config/nav.yml
- Add the link into the navigation for Knative Operator CLI plugin.
=> Add the link to the Knative Operator CLI plugin

docs/serving/tag-resolution.md
Fixes https://github.com/knative/docs/issues/4881
@dprotaso I took a stab at including the info about secrets but wasn't sure about it so please feel free to add comments or corrections. Thanks.
=> Update custom certs docs

docs/install/operator/configuring-eventing-cr.md, docs/install/operator/knative-with-operators.md
- Move eventing Operator install config options to eventing Operator install docs
- Some editing, cleanup and minor issue fix for eventing CR docs
Direct preview links:
- https://deploy-preview-5152--knative.netlify.app/docs/install/operator/knative-with-operators/#install-knative-eventing
- https://deploy-preview-5152--knative.netlify.app/docs/install/operator/configuring-eventing-cr/
=> Cleanup eventing CR docs

docs/serving/autoscaling/kpa-specific.md
=> Fix typo in kpa-specific.md

docs/eventing/experimental-features/delivery-timeout.md, docs/eventing/experimental-features/strict-subscriber.md
Promote strict subscriber and delivery timeout features to beta
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>
- Promote delivery timeout to beta: https://github.com/knative/eventing/pull/6472
- Promote strict subscriber to beta: https://github.com/knative/eventing/pull/6473
=> Document Eventing features promoted to beta

docs/eventing/channels/subscriptions.md
Fixes https://github.com/knative/docs/issues/4937
=> Add reply feature to subscription docs

config/nav.yml, docs/concepts/resources/revisions.md, docs/serving/README.md, docs/serving/revisions/README.md, docs/serving/revisions/revision-admin-config-options.md, docs/serving/revisions/revision-developer-config-options.md, docs/snippets/about-revisions.md, docs/snippets/about-serving.md
- Created Resources > Revisions topic under Concepts
- Created Revisions topic under Serving
Additional PRs will follow to clean up / move revision config options
- https://deploy-preview-5156--knative.netlify.app/docs/concepts/resources/revisions/
- https://deploy-preview-5156--knative.netlify.app/docs/serving/revisions/
=> Updating docs for Revisions

docs/serving/configuration/config-defaults.md
timeout key doesn't exist on the serving.knative.dev/v1 api spec https://knative.dev/docs/reference/api/serving-api/#serving.knative.dev/v1.Revision
=> Fix Revision timeout seconds key

hack/build.sh
=> Publish Knative 1.7 docs

hack/build.sh
fix build bc command not found on 1.7 release
=> fix build bc command not found on 1.7 release

docs/install/operator/knative-with-operator-cli.md
Signed-off-by: Vincent Hou <shou@us.ibm.com>
- Update the docs regarding kn operator plugin.
=> Update the latest version from 1.6 to 1.7 for kn operator

docs/client/kn-plugins.md
Fixes https://github.com/knative/docs/issues/5067
=> explain kn source plugins

docs/install/operator/knative-with-operators.md
Signed-off-by: Vincent Hou <shou@us.ibm.com>
- Updated the document for operator 1.7.
=> Update the docs for operator 1.7.0

contribute-to-docs/what-to-contribute/creating-blog-posts.md
Part of knative/community#1096
- :broom: Quarterly release cadence
=> :broom: Quarterly release cadence

code-samples/serving/hello-world/helloworld-go/README.md
While I was going through the docs - found this could be better reformatted for readability and syntax highlighting.
- `dockerfile` syntax highlighting
- multiple minor snippets syntax highlights
- reformatted indents and added sub-headings
=> fix: docs indents and code highlights

docs/eventing/sources/ping-source/README.md
Fixes #5058
- Added an example of using kn to create a ping source with base64 binary data
=> updated ping source with kn base64 example

docs/eventing/sources/kafka-source/README.md
Fixes https://github.com/knative/docs/issues/3583
- Added SASL docs
- Moved "clean up" to end of section (source deletion should be after all the other options)
=> Add SASL for KafkaSource docs

docs/eventing/sources/kafka-source/README.md
xref #5230 
/assign @abrennan89
=> Fix markdown rendering issue with brackets

docs/eventing/channels/channels-crds.md, docs/eventing/channels/channels.yaml, docs/eventing/channels/generator/ReadmeTemplate.gomd, docs/eventing/channels/generator/main.go
- Remove deprecated channels from the list to avoid confusion
- Change Support to Maintainer to better reflect Knative (or third-party) role.
- InMemory channel is "Stable" in a sense that it's compliant, maintained and does what it's supposed to do. 
/cc @pierDipi
=> Cleanup channel list

docs/eventing/sources/apiserversource/README.md, docs/eventing/sources/kafka-source/README.md, docs/eventing/sources/ping-source/README.md, docs/eventing/sources/rabbitmq-source/README.md
- Add new "stage" badge to better communicate the source current status
- Minor KafkaSource editing, trying to highlight that KafkaSources connect to existing topics
-
=> Add badges to sources and minor editing

docs/install/README.md
Suggesting very minor style improvements. 😄
- Compound adjectives (add hyphen)
- s/bash/Bash
=> [DOCS] Minor style updates

docs/snippets/quickstart-install.md
It would be nice to have the example command that the user could copy, similar to how it's done in the previous procedure for installing the `kn` CLI in step 3 (https://knative.dev/docs/install/quickstart-install/#install-the-knative-cli)
=>  Provide explicit example of bash command, similar to `kn` quickstart

docs/serving/autoscaling/kpa-specific.md
Came from [slack discussion](https://knative.slack.com/archives/C0186KU7STW/p1665383969207639)
=> Add info on relation between KPA mode and window

config/nav.yml, docs/eventing/sources/apiserversource/README.md, docs/eventing/sources/redis/README.md, docs/eventing/sources/redis/getting-started.md
- Add minimal RedisStreamSource documentation. 
-
-
=> Minimal redis stream source doc

config/nav.yml, docs/client/README.md, docs/client/kn-plugins.md, docs/contributing/contributing.md, docs/functions/README.md, docs/functions/build-run-deploy-func.md, docs/functions/creating-functions.md, docs/functions/install-func.md, docs/getting-started/about-knative-functions.md, docs/getting-started/build-run-deploy-func.md, docs/getting-started/create-a-function.md, docs/getting-started/getting-started-eventing.md, docs/getting-started/install-func.md, docs/snippets/about-functions.md, docs/snippets/build-func-intro.md, docs/snippets/create-a-function.md, docs/snippets/deploy-func-intro.md, docs/snippets/functions-templates-intro.md, docs/snippets/install-func-CLI.md, docs/snippets/install-functions-intro.md, docs/snippets/install-kn-func-plugin.md, docs/snippets/proc-building-function.md, docs/snippets/proc-deploying-function.md, docs/snippets/proc-running-function.md, docs/snippets/run-func-intro.md, hack/macros.py
Fixes https://github.com/knative/docs/issues/5265
Fixes https://github.com/knative/docs/issues/5205
Fixes https://github.com/knative/func/issues/903
Direct preview links:
- Tutorial: https://deploy-preview-5271--knative.netlify.app/docs/getting-started/about-knative-functions/
- Core docs: https://deploy-preview-5271--knative.netlify.app/docs/functions/
Related to https://github.com/knative/docs/pull/5243/files
=> Add functions section to docs

blog/config/nav.yml, blog/docs/events/knative-at-kubecon-na-2022.md, blog/docs/index.md
A hastily written blog post so that we can do a little promotion of the upcoming talks. Please let me know if I have missed anything, and apologies for the boilerplate language!
=> Add blog post for KnativeCon/KubeCon NA 2022

docs/about/case-studies/deepc.md, docs/about/case-studies/outfit7.md, docs/about/case-studies/puppet.md, docs/about/testimonials.md
I have fixed a couple of spelling mistakes and improved some grammar in these testimonial files
=> Spell check

blog/docs/events/knative-at-kubecon-na-2022.md
=> fix typo for kubecon 2022 blog

docs/install/operator/knative-with-operators.md
- Update the operands' versions for knative operator 1.8.
=> Update the operands' version for Knative Operator 1.8

hack/build.sh
Fix https://github.com/knative/docs/issues/5289
/cc @snneji @abrennan89 @lionelvillard 
Created based on https://github.com/knative/docs/pull/5190
=> Publish Knative 1.8 docs

docs/serving/accessing-traces.md, docs/serving/autoscaling/autoscale-go/README.md, docs/serving/configuration/feature-flags.md, docs/serving/knative-kubernetes-services.md, docs/serving/services/README.md, docs/serving/troubleshooting/debugging-application-issues.md, docs/serving/using-auto-tls.md
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> Fixed typos and outdated content

hack/build.sh
This is similar fix with https://github.com/knative/docs/pull/5191 but another place.
/cc @psschwei
=> Fix build bc command not found

docs/eventing/brokers/broker-types/kafka-broker/README.md
- Adding a note for why the Kafka Broker is using `binary` CE mode
=> Adding a note or two on why binary is better

golang/_redirects, golang/scaling-group.html
Signed-off-by: jwcesign <jiangwei115@huawei.com>
Part of https://github.com/knative/community/issues/1195
- Add scaling-group golang redirect
=> add scaling-group golang redirect

docs/functions/language-packs.md
Fix the documentation URL for the language pack
- Fix 404 Not found exception by altering the URL which has been changed
=> Fix the documentation URL for the language pack

hack/build.sh
=> drop release 1.5 as it's no longer supported

blog/config/nav.yml, blog/docs/articles/single-node-kafka-development.md
- Adding a blog post for simpler kafka development
/cc @aliok @creydr @pierDipi
=> Adding a blog post for simpler kafka development

docs/serving/app-security/security-guard-install.md
Fixes and additions to `guard` documentation related to set and unset TLS
Include also how to install `guard` with the operator
Include also how to install `guard` that uses TLS with the operator
=> guard doc fixes

docs/serving/autoscaling/autoscale-go/README.md
- use `go install` instead of `go get`, as this seems to be the new way of doing things.
=> Use `go install` to install binary

docs/snippets/quickstart-install.md
noted in https://github.com/knative-sandbox/kn-plugin-quickstart/issues/382
=> Fixes minikube quickstart default memory value

code-samples/serving/hello-world/helloworld-nodejs/README.md
Needed for the sample consistency test / unit tests
=> update hello world node app dependencies in readme

docs/eventing/brokers/broker-types/kafka-broker/README.md
- Adding a little bit more on the subject of consumer delivery guarantees
=> Adding a little bit more on the subject of consumer delivery guarantees

README.md, _index.html, blog/docs/articles/highlighting-value-knative-c-suite.md, blog/docs/releases/_template-announcing-knative-v1-X-release.txt, blog/mkdocs.yml, contribute-to-docs/README.md, contribute-to-docs/getting-started/README.md, contribute-to-docs/getting-started/becoming-a-contributor.md, contribute-to-docs/getting-started/github-workflow.md, contribute-to-docs/style-guide/README.md, contribute-to-docs/what-to-contribute/creating-blog-posts.md, docs/community/README.md, docs/community/contributing.md, docs/community/governance.md, docs/eventing/custom-event-source/custom-event-source/README.md, docs/getting-started/next-steps.md, docs/serving/app-security/security-guard-about.md, mkdocs.yml
Updates to the website, docs repo, and the blog. I skipped the old release notices, but we can add them if someone really, really wants them.
=> Updates slack URLs to CNCF instance

docs/community/README.md
=> Add missing slack channels, fix formatting

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/kafka-broker/README.md
- Added the "Shared data plane mode" docs for Kafka Broker
-
-
=> Docs for KafkaNamespaced broker

blog/config/nav.yml, blog/docs/releases/announcing-knative-v1-9-release.md
- Add blog announcing Knative 1.9 release.
=> Add Knative 1.9 announcement

docs/eventing/sources/apiserversource/reference.md
- A new feature was added to ApiServerSource in https://github.com/knative/eventing/pull/6665. This PR updates the reference and adds examples
=> Adds namespace selector reference to ApiServerSource docs [1.9 feature]

blog/config/nav.yml, blog/docs/events/google-summer-of-code-2023.md
=> GSoC23@Knative blogpost

hack/build.sh
- Release the krak^W^WKnative version 1.9 docs
- Retire version 1.6 docs
=> Release docs version 1.9

docs/serving/observability/metrics/serving-metrics.md
=> Fixes a typo in docs

blog/config/nav.yml, blog/docs/articles/kafka-broker-with-isolated-data-plane.md
- Blog post about Knative Kafka Broker with isolated data plane
-
-
=> Blog post about Knative Kafka Broker with isolated data plane

docs/snippets/prerequisites.md
- Bump min required kubernetes version
/cherry-pick release-1.9
=> Update min required kubernetes version

docs/functions/building-functions.md
Fixes #5305
- Add CLI func if Git URL already specified
=> Add CLI func if Git URL already specified

docs/community/README.md
There is an incomplete sentence in the community documentation in https://knative.dev/docs/community/.
- Corrected the documentation fixing the error in the incomplete sentence.
=> Fixed error in incomplete sentence.

docs/eventing/sinks/kafka-sink.md
- Adding a little extra sentence on what the `KafkaSink` is, before directly showing the installation and configuration
=> Adding a little description to the Kafka Sink doc

docs/functions/README.md
Fixes #5427 
Fixed the link to the github markdown file https://github.com/knative/func/blob/main/docs/language-packs/language-pack-contract.md
=> fix language-packs link

docs/eventing/sources/kafka-source/README.md
chore: adds scaling section
- Adds Scaling section to KafkaSource page
=> Document scaling KafkaSource

docs/serving/app-security/security-guard-quickstart.md
Fixes #5438 
- Document how to create a guard protected function
=> Documenting guard support for functions

docs/install/upgrade/check-install-version.md
Replace dropped label ```serving.knative.dev/release``` with ```app.kuberentes.io/version``` in version query command.
"Fixes [knative/serving/#13722](https://github.com/knative/serving/issues/13722)"
See https://github.com/knative/serving/pull/12754 
- Updated version query command for knative serving and eventing
=> Update version label in query command

docs/serving/app-security/security-guard-install.md, docs/serving/app-security/security-guard-quickstart.md
1. Add documentation for protecting Guard with functions
2. do a small fix in guard documentation - highlighting the per namespace config, and making sure it is there for knative operator
=> Guard functions

code-samples/eventing/helloworld/helloworld-go/README.md
Fixes #5442
- move the indentation for proper code highlighting.
Now it is looking fine
=> Fix Code Block Formatting

blog/config/nav.yml, blog/docs/articles/from-cloudevent-to-apach-kafka-records-part-one.md
- a new blog post describing how to send cloud events to knative and persist them in a kafka topic
=> Proxy kafka records blog post

docs/snippets/proc-running-function.md
Fixes #5308
- Adds a `cd hello` step to instructions
=> Missing step in knative functions tutorial

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/kafka-broker/README.md, docs/eventing/configuration/kafka-channel-configuration.md, docs/eventing/event-registry.md, docs/eventing/sinks/kafka-sink.md, docs/eventing/sources/kafka-source/README.md
- The PR underlines that we offer implementation/apis for Apache Kafka, not the other way around
=> Update the usage of Apache Kafka term 

config/nav.yml
- one more change regarding apache kafka term usage
=> Little more updates on Apache Kafka term usage

docs/eventing/event-mesh.md
=> Spelling correction of Python

blog/config/nav.yml, blog/docs/events/knative-projectmeeting-kubecon-eu-2023.md, blog/docs/index.md
"Fixes #1297" or "Add description of the problem this PR solves"
-
-
-
=> knativeproject kiosk annoucement KubeconEU23

docs/eventing/brokers/broker-admin-config-options.md
=> Fix typo in broker admin config options

code-samples/serving/hello-world/helloworld-php/README.md
Fixes  #5506
- Change target sample Ruby Sample V1 to PHP Sample V1.
=> [FIX]: Target sample.

blog/config/nav.yml, blog/docs/releases/announcing-knative-v1-10-release.md
- Add blog announcing Knative 1.10 release.
=> Add Knative 1.10 announcement

.github/workflows/knative-docs-image.yaml
- push the autoscale image
- only run workfolw if certain paths change
Fixes: https://github.com/knative/docs/issues/5555
=> Fix build image workflow

blog/docs/articles/knative-serving-in-k0s.md, blog/docs/articles/quickstart-with-knative.md, blog/docs/articles/set-up-a-local-knative-environment-with-kind.md, docs/getting-started/first-service.md, docs/getting-started/first-traffic-split.md, docs/serving/app-security/security-guard-quickstart.md, docs/serving/autoscaling/autoscale-go/README.md, docs/serving/autoscaling/autoscaler-types.md, docs/serving/autoscaling/concurrency.md, docs/serving/autoscaling/kpa-specific.md, docs/serving/autoscaling/rps-target.md, docs/serving/autoscaling/scale-bounds.md, docs/serving/autoscaling/scale-to-zero.md, docs/serving/configuration/config-defaults.md, docs/serving/configuration/feature-flags.md, docs/serving/deploying-from-private-registry.md, docs/serving/services/creating-services.md, docs/serving/services/using-queue-extensions.md
- Update image references to ghcr.io/knative/*
=> [release-1.10] Update image references to ghcr.io/knative/*

blog/docs/articles/quickstart-with-knative.md, blog/docs/articles/set-up-a-local-knative-environment-with-kind.md, docs/getting-started/first-service.md, docs/getting-started/first-traffic-split.md, docs/serving/app-security/security-guard-quickstart.md, docs/serving/autoscaling/autoscale-go/README.md, docs/serving/autoscaling/autoscaler-types.md, docs/serving/autoscaling/concurrency.md, docs/serving/autoscaling/container-freezer.md, docs/serving/autoscaling/kpa-specific.md, docs/serving/autoscaling/rps-target.md, docs/serving/autoscaling/scale-bounds.md, docs/serving/autoscaling/scale-to-zero.md, docs/serving/configuration/config-defaults.md, docs/serving/configuration/feature-flags.md, docs/serving/deploying-from-private-registry.md, docs/serving/services/creating-services.md, docs/serving/services/using-queue-extensions.md
- gcr.io/knative-samples was deleted
=> [release-1.9] Update image references to ghcr.io

docs/getting-started/next-steps.md
Knative.tips is history (not reachable anymore).
Thanks, @ahmetb, for all your support at that time!
=> Update next-steps.md, remove knative.tips link

docs/serving/services/service-metrics.md
- More details here https://github.com/knative/serving/issues/13946.
=> Add details about revision_queue_depth metric

overrides/main.html
Adds a banner about TOC elections to the current release branch
=> TOC election banner on release branch

docs/serving/services/service-metrics.md
- Part of the work for https://github.com/knative/serving/pull/14019
=> Document QP reporting period

docs/getting-started/first-source.md
"Fixes #5608 " or "Removes the little mistake in the sentance"
- I removed an extra "you" from the sentance
=> Removed grammatical mistake

docs/eventing/event-registry.md
Fixes #5611
- Adding some updates for the V1B2 EventType API, present in 1.11 release
=> Adding some updates for the V1B2 EventType API, present in 1.11 release

overrides/home.html
Fixes https://github.com/knative/docs/issues/5407
- Remove the subtitle in the homepage
Preview: https://deploy-preview-5633--knative.netlify.app/docs/
=> Remove subtitle in homepage

docs/concepts/README.md, docs/eventing/README.md, docs/snippets/about-eventing.md
- Updating the eventing message. Based on the iterations via this PR: https://github.com/knative/eventing/pull/7045
=> Aligning the Eventing message w/ the README from its repo

docs/install/operator/configuring-serving-cr.md
This path documentation about the new field introduce by https://github.com/knative/operator/pull/1227
/cherrypick release-1.10
/cherrypick release-1.9
/cc @houshengbo
=> Add doc about cutomize kourier-bootstrap for Kourier gateways

hack/build.sh
- Similar to https://github.com/knative/docs/pull/5538
=> Add version 1.11 to generate docs

blog/docs/articles/new_event_discovery_features.md
- as per title, improving the blog post
=> Adding note on channel api support for this as well

blog/docs/articles/knative-eventing-vision.md
=> Fixing the actual date of publication

docs/serving/services/byo-certificate.md, docs/serving/services/custom-domains.md
"Fixes #5672 " or "Add description of the problem this PR solves"
- Update DomainMapping to v1beta1 from v1alpha1
=> Update DomainMapping to v1beta1 from v1alpha1

golang/_redirects, golang/serving-progressive-rollout.html
- Added the golang redirect for serving-progressive-rollout.
=> Added the golang redirect for serving-progressive-rollout

docs/snippets/prerequisites.md
Partially https://github.com/knative/pkg/issues/2821
- Bump min-required k8s version to 1.26
/assign @dprotaso
=> Bump min-k8s version to 1.26

docs/eventing/experimental-features/transport-encryption.md
=> Document how to trust specific CA certs for event senders

golang/_redirects, tools/redir-gen/main.go
Unblocks - https://github.com/knative/pkg/pull/2862
=> control-protocol is still used in Knative 1.10

blog/docs/events/knative-at-kubecon-na-2024.md
Blog post about knative presence in KubeCon NA 2023
-
-
-
=> Blog post about knative presence in KubeCon NA 2023

docs/install/yaml-install/serving/install-serving-with-yaml.md
Part of https://github.com/knative/serving/issues/14640
=> [release-1.12] add deprecation notices for net-http01

docs/snippets/prerequisites.md
- Bump min-k8s version to 1.27
/assign @dprotaso
=> Bump min-k8s version to 1.27

.github/workflows/knative-docs-image.yaml
- Trigger docker image build when python requirements change
Fixes #5750
=> Trigger image build when requirements change

golang/_redirects, golang/backstage-plugins.html
Similar to https://github.com/knative/docs/pull/4160
For https://github.com/knative/community/issues/1450
=> Add backstage-plugins redirect

blog/docs/events/security-audit-2023.md
=> security audit blogpost: fix broken link to report

blog/mkdocs.yml, mkdocs.yml
Fixes #5802 
- Update the Year 2022 to 2024 (latest)
=> Updated Copywrite Information

mkdocs.yml
"Fixes #5811"
- Implemented a Hugo shortcode for a reusable "Edit this page" button.
- Ensured the button dynamically links to the raw markdown file associated with the documentation page.
=> Add edit Button to Documentation Pages

hack/build.sh
=> Update Knative docs to 1.13

docs/eventing/event-registry.md
- adding hint about `auto create` on event registry doc
=> Mention auto-create on event registry doc

docs/eventing/sources/kafka-source/README.md
Fixes #5849 
- Explain that we have experimental support for automatic Kafka source scaling
- Provide configmap required to enable the feature
-
/cc @Leo6Leo @pierDipi @matzew @creydr
=> added docs for kafka scaling to kafka source docs

.github/workflows/knative-docs-image.yaml
"Fixes #5718 " or "Add support s390x and ppc64le archs"
-
-
-
=> Add support s390x and ppc64le archs

docs/install/operator/knative-with-operators.md, docs/install/yaml-install/eventing/install-eventing-with-yaml.md, docs/install/yaml-install/serving/install-serving-with-yaml.md, docs/snippets/security-prereqs-images.md
- fixing hard-coded old version in [security-prereqs-images.md](https://github.com/knative/docs/blob/main/docs/snippets/security-prereqs-images.md)
- change --8<-- to {% include %} for calling define_env
=> Fix hard-coded version

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/rabbitmq-broker/README.md, docs/eventing/sources/rabbitmq-source/README.md, docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Reverts knative/docs#5862
cc @dprotaso
=> Revert "[release-1.13] add deprecation notices for rabbitmq integration"

docs/eventing/brokers/broker-types/README.md, docs/eventing/brokers/broker-types/rabbitmq-broker/README.md, docs/eventing/sources/rabbitmq-source/README.md, docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Reverts knative/docs#5863
cc @dprotaso
=> Revert "[release-1.12] add deprecation notices for rabbitmq integration"

config/nav.yml, docs/eventing/faq/README.md
The UX WG did an evaluation of the documentation structure for eventing. This PR makes changes to the navigation to improve the usability of the docs
=> Restructure eventing docs navigation

docs/snippets/prerequisites.md
Bump min-k8s version to 1.28
As it is shown here:
https://github.com/knative/pkg/blob/fd7cc2153e6a06f9cbb7a8401d5d1bcdf8edac96/version/version.go#L36
/cc @dprotaso
=> Bump min-k8s version to 1.28

docs/eventing/sources/kafka-source/README.md
"kafka-source-dispatcher" is a statefulset app, not a deployment app, so it needs to be modified. #
=> fix correct display

docs/eventing/experimental-features/sender-identity.md
=> Add list with OIDC authn supporting eventing components

docs/serving/configuration/config-defaults.md
- Follow up of https://github.com/knative/serving/pull/14600. See also the request here: https://github.com/knative/serving/pull/14600#issuecomment-1947717848.
=> Document the remaining timeout settings

hack/build.sh
- Update Knative docs to 1.14
/cc @knative/knative-release-leads
=> Update Knative docs to 1.14

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-14-release.md
- Add release blog Knative 1.14
/cc @knative/knative-release-leads
=> Add release blog Knative 1.14

blog/docs/articles/consuming_s3_data_with_knative.md
=> Correct link to first article

blog/config/nav.yml, blog/docs/articles/aws_to_func_migration.md
- new post on migrating to Knative Functions
=> Blog on migrating to Knative Functions

docs/serving/configuration/deployment.md
adds docs for configuring runtime-class-name
- related: https://github.com/knative/serving/issues/12729
=> feat: add docs for runtime-class-name feature

overrides/home.html
Fixes #6037 
- Added the getting-started/tutorial
=> fix: tutorial button in the home page

docs/stylesheets/extra.css
I have resolved the border radius issue of the tabs in the Navbar.
=> Navbar tabs border radius issue resolved

.github/workflows/knative-docs-image.yaml, .github/workflows/mkdocs-strict-verify.yaml
- Update docker/setup-buildx-action, docker/login-action, docker/build-push-action, and actions/checkout
=> Update the github action versions, as reviewdog is complaining

.github/workflows/knative-docs-image.yaml
Fixes #6047
- Add the github workflow 
- Modify the corresponding documentation to use the correctly built images
=> Use the knative's release image registry for the pre-build image

.github/workflows/knative-docs-image.yaml
- Only have the pre-built image for the linux platforms. If users need to run the sample app on other architecture, they will need to build the image themselves.
- Watch the changes on the whole `bookstore-sample-app` directory. 
Apologies for this extra PR, as there is no way for me to test the GitHub action without having the PR merged.
/cc @dprotaso @Cali0707
=> Fix the failed image build workflow

code-samples/eventing/bookstore-sample-app/solution/frontend/config/100-front-end-deployment.yaml, code-samples/eventing/bookstore-sample-app/solution/node-server/config/100-deployment.yaml, code-samples/eventing/bookstore-sample-app/start/frontend/config/100-front-end-deployment.yaml, code-samples/eventing/bookstore-sample-app/start/node-server/config/100-deployment.yaml
- Update all the pre-built image usage from quay to use knative's ghir.
/cc @Cali0707 @matzew
=> Use Knative release build image for the sample app

blog/docs/articles/llm-agents-overview.md
Since we are publishing a part 2, I decided it would be better to update the title for this blog post
=> update the LLM Overview article title

hack/build.sh
=> Release v1.15

docs/eventing/features/transport-encryption.md
- Fix CI error in https://app.netlify.com/sites/knative/deploys/66a78012eb26e6000782bf3a#L334
=> Fix wrong artifact url

docs/serving/services/http-protocol.md
- We missed it in https://github.com/knative/docs/pull/5839.
- For discussion see [here]( https://cloud-native.slack.com/archives/C04LMU0AX60/p1722351206223989).
=> Fix full duplex example yaml

overrides/assets/stylesheets/home.css
=> alignment issued resolved on home page

blog/config/nav.yml, blog/docs/articles/Building-Stateful-applications-with-Knative-and-Restate.md, blog/docs/index.md
- Add a blog post about Knative and Restate!
=> [Blog post] Building Stateful applications with Knative and Restate

code-samples/eventing/bookstore-sample-app/solution/node-server/package-lock.json, code-samples/eventing/bookstore-sample-app/solution/node-server/package.json, code-samples/eventing/bookstore-sample-app/start/node-server/package-lock.json, code-samples/eventing/bookstore-sample-app/start/node-server/package.json, code-samples/serving/cloudevents/cloudevents-nodejs/package-lock.json, code-samples/serving/cloudevents/cloudevents-nodejs/package.json, code-samples/serving/hello-world/helloworld-nodejs/package-lock.json, code-samples/serving/hello-world/helloworld-nodejs/package.json
fixes https://issues.redhat.com/browse/SRVCOM-3317 . serve-static vulnerability
cc: @matzew
=> fix: update express to the latest(4.20.0).

docs/serving/configuration/deployment.md
This configuration element was removed as part of
https://github.com/knative/serving/pull/13830
-
-
-
=> Remove cocurrenty-state-endpoint from docs

code-samples/serving/hello-world/helloworld-nodejs/README.md
- Broken here https://github.com/knative/docs/pull/6115
=> Fix sampleconsistency test

hack/build.sh
- As per title. Similar to https://github.com/knative/docs/pull/6077.
=> Release v1.16

blog/config/nav.yml, blog/docs/index.md, blog/docs/releases/announcing-knative-v1-16-release.md
- As per title. Similar to https://github.com/knative/docs/pull/6080 (minus the images). Asked @Cali0707 to add the images for consistency.
- Part of https://github.com/knative/release/issues/329
=> Add release blog Knative 1.16

overrides/assets/stylesheets/home.css
"Fixes #6161 
- Changed button radius from 0.7rem to 8px
- The roundness of the button does not looks much harsh
=> fixed border radius on  home page button

code-samples/eventing/parallel/multiple-branches/README.md
Remove redundant dot in the ksvc yaml
-
-
-
=> chore: fix typo in sample parallel README

docs/reference/security/verifying-images.md, docs/snippets/security-prereqs-images.md
Followup to https://github.com/knative/docs/pull/6193
- Reduces the text on the YAML/operator install pages, and makes clear that signature verification is an _optional_ step, and not a required prerequisite
=> Link to supply-chain details rather than including inline.

docs/eventing/event-registry/README.md
- Update the documentation. Since [knative/eventing#2412](https://github.com/knative/eventing/issues/2412) updated the resource name from CronJobSource to PingSource, the documentation is misleading;
=> docs: update README to reflect CronJobSource renamed to PingSource

hack/build.sh
- Update version switch with latest 1.17
/cc @knative/knative-release-leads
=> Update version switch with latest 1.17

overrides/home.html
"meaning that companies only use what they pay for" -> "meaning that companies only pay for what they use".
=> Fix pay-per-use description in homepage

docs/install/operator/configuring-serving-cr.md
=> fix: fix typo in configuring serving cr

mkdocs.yml
…thub.com>
update for 2025 year mkdocs.md
-
-
-
=> Update mkdocs.md for 2025 year

hack/build.sh
update `hack/build.sh` for new release 1.18
=> new release 1.18

hack/build.sh
update versions in build.sh for new release
=> Update for release 1.19 in build.sh

docs/stylesheets/extra.css, overrides/assets/stylesheets/home.css
=> chore: fix version picker overflowing into top nav

docs/install/uninstall.md, docs/serving/knative-kubernetes-services.md
=> drop references to old net-cert-manager controller

docs/eventing/observability/accessing-traces.md, docs/serving/observability/accessing-traces.md
Fixes: https://github.com/knative/docs/issues/6347
=> tracing-sampling should be tracing-sampling-rate

docs/serving/observability/metrics/serving-metrics.md, docs/snippets/observability-shared-metrics.md
- **include UCUM link**
- **address Evan's OTel Docs feedback**
- **include autoscaler attributes**
/assign @evankanderson @Cali0707
=> OTel docs follow up

docs/versioned/eventing/sinks/integration-sink/aws_s3.md, docs/versioned/eventing/sinks/integration-sink/aws_sns.md, docs/versioned/eventing/sinks/integration-sink/aws_sqs.md
- fixed auth indentation in examples
- fixed wrong service reference in examples
=> minor fixes for integrationsink doc
